In [23]:
from recbole.quick_start import run_recbole

from itertools import product
from pathlib import Path

import pandas as pd
import json

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path.cwd()

CONFIG_ROOT = PROJECT_ROOT / "recbole" / "config"

RESULTS_DIR = PROJECT_ROOT / "tuning_results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

In [25]:
from recbole.config import Config
from recbole.data import create_dataset, data_preparation
from recbole.utils import get_model, get_trainer, init_seed


def evaluate_traditional_model(model_name, config_path, params):
    """Fit a traditional RecBole model and evaluate on validation data."""

    config = Config(
        model=model_name,
        dataset="ml-100k",
        config_file_list=[str(config_path)],
        config_dict={
            "seed": 2020,
            "reproducibility": True,
            "use_gpu": False,
            "data_path": str(PROJECT_ROOT / "dataset"),
            **params,
        },
    )

    init_seed(config["seed"], config["reproducibility"])

    dataset = create_dataset(config)
    train_data, valid_data, _ = data_preparation(config, dataset)

    # EASE and SLIMElastic fit their parameters during initialization
    model = get_model(model_name)(
        config,
        train_data.dataset
    ).to(config["device"])

    trainer = get_trainer(
        config["MODEL_TYPE"],
        config["model"]
    )(config, model)

    valid_result = trainer.evaluate(
        valid_data,
        load_best_model=False
    )

    return {
        "best_valid_score": valid_result["mrr@10"],
        "best_valid_result": valid_result,
    }

In [22]:
def tune_model(
    name,
    model,
    config_path,
    search_space,
    fixed_params=None,
    save=True
):
    """
    Exhaustively tune a RecBole model.

    Parameters
    ----------
    name : str
        Name used for displaying/saving results.

    model : str
        RecBole model name.

    config_path : str or Path
        Path to the model's YAML configuration.

    search_space : dict
        Hyperparameters and values to test.

        Example:
        {
            "k": [20, 50, 100],
            "shrink": [0, 10, 50]
        }

    fixed_params : dict, optional
        Parameters that should remain fixed.
        Useful for things such as knn_method.

    save : bool
        Save tuning results to CSV.

    Returns
    -------
    DataFrame
        All tuning experiments.
    """

    if fixed_params is None:
        fixed_params = {}

    # Parameter names
    param_names = list(search_space.keys())

    # All combinations
    combinations = list(
        product(*search_space.values())
    )

    results = []

    print(f"Tuning {name}")
    print(f"Number of experiments: {len(combinations)}")
    print("=" * 60)

    for i, values in enumerate(combinations, start=1):

        params = dict(zip(param_names, values))

        config_dict = {
            "model": model,
            "dataset": "ml-100k",
            **fixed_params,
            **params,
        }

        print(
            f"[{i}/{len(combinations)}] "
            f"{name}: {params}"
        )

        if model in {"EASE", "SLIMElastic"}:
            result = evaluate_traditional_model(
                model_name=model,
                config_path=config_path,
                params=params,
            )
        else:
            result = run_recbole(
                model=model,
                dataset="ml-100k",
                config_dict=config_dict,
                config_file_list=[str(config_path)],
                saved=False,
            )

        valid = result["best_valid_result"]

        row = {
            **params,
            "valid_score": result["best_valid_score"],
            **valid,
        }

        valid = result["best_valid_result"]

        row = {
            **params,
            "valid_score": result["best_valid_score"],
            **valid
        }

        results.append(row)

    df = pd.DataFrame(results)

    # Best first
    df = df.sort_values(
        "valid_score",
        ascending=False
    ).reset_index(drop=True)

    if save:
        output_path = RESULTS_DIR / f"{name}_tuning.csv"
        df.to_csv(output_path, index=False)

        print(f"\nSaved to:")
        print(output_path)

    print("\nBest configuration:")
    display(df.head(1))

    return df

In [11]:
itemcf_space = {
    "k": [20, 50, 100, 200],
    "shrink": [0, 10, 50, 100]
}

In [26]:
itemcf_results = tune_model(
    name="ItemCF",
    model="ItemKNN",
    config_path=CONFIG_ROOT / "ItemKNN" / "ml-100k.yaml",
    search_space=itemcf_space,
    fixed_params={
        "knn_method": "item"
    }
)

Tuning ItemCF
Number of experiments: 16
============================================================
[1/16] ItemCF: {'k': 20, 'shrink': 0}

13 Oct 22:09    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
13 Oct 22:09    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 0
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


13 Oct 22:09    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
13 Oct 22:09    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 22:09    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
13 Oct 22:09    INFO  ItemKNN()
Trainable parameters: 1
13 Oct 22:09    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  46%|██████████████████████▎                          | 36/79 [00:00<00:00, 356.87it/s]:  96%|███████████████████████████████████████████████▏ | 76/79 [00:00<00:00, 380.65it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 330.28it/s]
13 Oct 22:09    INFO  epoch 0 training [time: 0.32s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  36%|████████████████▋                             | 171/472 [00:00<00:00, 1697.91it/s]:  72%|█████████████████████████████████▏            | 341/472 [00:00<00:00, 1398.89it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1319.38it/s]
13 Oct 22:09    INFO  epoch 0 evaluating [time: 0.43s, valid_score: 0.355300]
13 Oct 22:09    INFO  valid result:
recall@10 : 0.1884    mrr@10 : 0.3553    ndcg@10 : 0.2063    hit@10 : 0.7041    precision@10 : 0.1471
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  25%|███████████▋                                  | 120/472 [00:00<00:00, 1195.04it/s]:  51%|███████████████████████▍                      | 240/472 [00:00<00:00, 1063.23it/s]:  74%|█████████████████████████████████▉            | 348/472 [00:00<00:00, 1040.07it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1113.95it/s]
13 Oct 22:09    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    23.00 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.54 G/16.00 G |
+-------------+----------------+
13 Oct 22:09    INFO  best valid : OrderedDict([('recall@10', 0.1884), ('mrr@10', 0.3553), ('ndcg@10', 0.2063), ('hit@10', 0.7041), ('precision@10', 0.1471)])
13 Oct 22:09    INFO  test result: OrderedDict([('recall@10', 0.2328), ('mrr@10', 0.4364), ('ndcg@10', 0.2637), ('hit@10', 0.7762), ('precision@10', 0.1852)])

[2/16] ItemCF: {'k': 20, 'shrink': 10}

13 Oct 22:10    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
13 Oct 22:10    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 10
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


13 Oct 22:10    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
13 Oct 22:10    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 22:10    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
13 Oct 22:10    INFO  ItemKNN()
Trainable parameters: 1
13 Oct 22:10    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  82%|████████████████████████████████████████▎        | 65/79 [00:00<00:00, 643.30it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 523.39it/s]
13 Oct 22:10    INFO  epoch 0 training [time: 0.21s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  36%|████████████████▎                             | 168/472 [00:00<00:00, 1675.23it/s]:  71%|████████████████████████████████▋             | 336/472 [00:00<00:00, 1437.32it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1442.61it/s]
13 Oct 22:10    INFO  epoch 0 evaluating [time: 0.39s, valid_score: 0.356500]
13 Oct 22:10    INFO  valid result:
recall@10 : 0.1925    mrr@10 : 0.3565    ndcg@10 : 0.2077    hit@10 : 0.7179    precision@10 : 0.1478
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  39%|█████████████████▉                            | 184/472 [00:00<00:00, 1831.85it/s]:  78%|███████████████████████████████████▊          | 368/472 [00:00<00:00, 1579.72it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1522.67it/s]
13 Oct 22:10    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    18.80 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.56 G/16.00 G |
+-------------+----------------+
13 Oct 22:10    INFO  best valid : OrderedDict([('recall@10', 0.1925), ('mrr@10', 0.3565), ('ndcg@10', 0.2077), ('hit@10', 0.7179), ('precision@10', 0.1478)])
13 Oct 22:10    INFO  test result: OrderedDict([('recall@10', 0.2339), ('mrr@10', 0.4326), ('ndcg@10', 0.2609), ('hit@10', 0.772), ('precision@10', 0.181)])

[3/16] ItemCF: {'k': 20, 'shrink': 50}

13 Oct 22:10    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
13 Oct 22:10    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 50
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


13 Oct 22:10    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
13 Oct 22:10    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 22:10    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
13 Oct 22:10    INFO  ItemKNN()
Trainable parameters: 1
13 Oct 22:10    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  68%|█████████████████████████████████▍               | 54/79 [00:00<00:00, 536.42it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 443.09it/s]
13 Oct 22:10    INFO  epoch 0 training [time: 0.25s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  34%|███████████████▍                              | 159/472 [00:00<00:00, 1587.28it/s]:  67%|██████████████████████████████▉               | 318/472 [00:00<00:00, 1395.18it/s]:  97%|████████████████████████████████████████████▊ | 460/472 [00:00<00:00, 1345.23it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1289.11it/s]
13 Oct 22:10    INFO  epoch 0 evaluating [time: 0.43s, valid_score: 0.348400]
13 Oct 22:10    INFO  valid result:
recall@10 : 0.1908    mrr@10 : 0.3484    ndcg@10 : 0.2051    hit@10 : 0.7073    precision@10 : 0.1459
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  34%|███████████████▍                              | 159/472 [00:00<00:00, 1582.31it/s]:  67%|██████████████████████████████▉               | 318/472 [00:00<00:00, 1419.01it/s]:  98%|█████████████████████████████████████████████ | 462/472 [00:00<00:00, 1370.53it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1305.23it/s]
13 Oct 22:10    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    14.60 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.57 G/16.00 G |
+-------------+----------------+
13 Oct 22:10    INFO  best valid : OrderedDict([('recall@10', 0.1908), ('mrr@10', 0.3484), ('ndcg@10', 0.2051), ('hit@10', 0.7073), ('precision@10', 0.1459)])
13 Oct 22:10    INFO  test result: OrderedDict([('recall@10', 0.2341), ('mrr@10', 0.4393), ('ndcg@10', 0.2627), ('hit@10', 0.7784), ('precision@10', 0.1803)])

[4/16] ItemCF: {'k': 20, 'shrink': 100}

13 Oct 22:10    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
13 Oct 22:10    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 100
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


13 Oct 22:10    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
13 Oct 22:10    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 22:10    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
13 Oct 22:10    INFO  ItemKNN()
Trainable parameters: 1
13 Oct 22:10    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  85%|█████████████████████████████████████████▌       | 67/79 [00:00<00:00, 662.36it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 539.43it/s]
13 Oct 22:10    INFO  epoch 0 training [time: 0.21s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  35%|███████████████▉                              | 163/472 [00:00<00:00, 1627.12it/s]:  69%|███████████████████████████████▊              | 326/472 [00:00<00:00, 1447.25it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1407.96it/s]
13 Oct 22:10    INFO  epoch 0 evaluating [time: 0.42s, valid_score: 0.350100]
13 Oct 22:10    INFO  valid result:
recall@10 : 0.1965    mrr@10 : 0.3501    ndcg@10 : 0.2081    hit@10 : 0.7137    precision@10 : 0.1474
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  35%|████████████████                              | 165/472 [00:00<00:00, 1641.24it/s]:  70%|████████████████████████████████▏             | 330/472 [00:00<00:00, 1428.50it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1381.29it/s]
13 Oct 22:10    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    15.80 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.58 G/16.00 G |
+-------------+----------------+
13 Oct 22:10    INFO  best valid : OrderedDict([('recall@10', 0.1965), ('mrr@10', 0.3501), ('ndcg@10', 0.2081), ('hit@10', 0.7137), ('precision@10', 0.1474)])
13 Oct 22:10    INFO  test result: OrderedDict([('recall@10', 0.234), ('mrr@10', 0.4396), ('ndcg@10', 0.2633), ('hit@10', 0.7699), ('precision@10', 0.1811)])

[5/16] ItemCF: {'k': 50, 'shrink': 0}

13 Oct 22:10    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
13 Oct 22:10    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 0
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


13 Oct 22:10    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
13 Oct 22:10    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 22:10    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
13 Oct 22:10    INFO  ItemKNN()
Trainable parameters: 1
13 Oct 22:10    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  82%|████████████████████████████████████████▎        | 65/79 [00:00<00:00, 646.81it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 533.40it/s]
13 Oct 22:10    INFO  epoch 0 training [time: 0.22s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  41%|███████████████████                           | 195/472 [00:00<00:00, 1948.61it/s]:  83%|██████████████████████████████████████        | 390/472 [00:00<00:00, 1584.34it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1538.73it/s]
13 Oct 22:10    INFO  epoch 0 evaluating [time: 0.39s, valid_score: 0.368000]
13 Oct 22:10    INFO  valid result:
recall@10 : 0.1992    mrr@10 : 0.368    ndcg@10 : 0.2163    hit@10 : 0.7296    precision@10 : 0.1531
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  41%|██████████████████▉                           | 194/472 [00:00<00:00, 1931.18it/s]:  82%|█████████████████████████████████████▊        | 388/472 [00:00<00:00, 1371.08it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1390.47it/s]
13 Oct 22:10    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    14.10 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.57 G/16.00 G |
+-------------+----------------+
13 Oct 22:10    INFO  best valid : OrderedDict([('recall@10', 0.1992), ('mrr@10', 0.368), ('ndcg@10', 0.2163), ('hit@10', 0.7296), ('precision@10', 0.1531)])
13 Oct 22:10    INFO  test result: OrderedDict([('recall@10', 0.2425), ('mrr@10', 0.4646), ('ndcg@10', 0.2794), ('hit@10', 0.79), ('precision@10', 0.1916)])

[6/16] ItemCF: {'k': 50, 'shrink': 10}

13 Oct 22:10    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
13 Oct 22:10    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 10
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


13 Oct 22:10    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
13 Oct 22:10    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 22:10    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
13 Oct 22:10    INFO  ItemKNN()
Trainable parameters: 1
13 Oct 22:10    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  84%|████████████████████████████████████████▉        | 66/79 [00:00<00:00, 659.33it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 538.19it/s]
13 Oct 22:10    INFO  epoch 0 training [time: 0.21s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  35%|████████████████▏                             | 166/472 [00:00<00:00, 1652.33it/s]:  70%|████████████████████████████████▎             | 332/472 [00:00<00:00, 1446.39it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1416.03it/s]
13 Oct 22:10    INFO  epoch 0 evaluating [time: 0.42s, valid_score: 0.374300]
13 Oct 22:10    INFO  valid result:
recall@10 : 0.2017    mrr@10 : 0.3743    ndcg@10 : 0.2197    hit@10 : 0.7243    precision@10 : 0.1549
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  36%|████████████████▍                             | 169/472 [00:00<00:00, 1684.81it/s]:  72%|████████████████████████████████▉             | 338/472 [00:00<00:00, 1461.87it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1430.14it/s]
13 Oct 22:10    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    14.50 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.61 G/16.00 G |
+-------------+----------------+
13 Oct 22:10    INFO  best valid : OrderedDict([('recall@10', 0.2017), ('mrr@10', 0.3743), ('ndcg@10', 0.2197), ('hit@10', 0.7243), ('precision@10', 0.1549)])
13 Oct 22:10    INFO  test result: OrderedDict([('recall@10', 0.2406), ('mrr@10', 0.4623), ('ndcg@10', 0.2782), ('hit@10', 0.7858), ('precision@10', 0.1906)])

[7/16] ItemCF: {'k': 50, 'shrink': 50}

13 Oct 22:10    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
13 Oct 22:10    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 50
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


13 Oct 22:10    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
13 Oct 22:10    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 22:10    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
13 Oct 22:10    INFO  ItemKNN()
Trainable parameters: 1
13 Oct 22:10    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  86%|██████████████████████████████████████████▏      | 68/79 [00:00<00:00, 672.84it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 538.58it/s]
13 Oct 22:10    INFO  epoch 0 training [time: 0.21s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  29%|█████████████▌                                | 139/472 [00:00<00:00, 1388.80it/s]:  59%|███████████████████████████                   | 278/472 [00:00<00:00, 1271.14it/s]:  86%|███████████████████████████████████████▌      | 406/472 [00:00<00:00, 1249.88it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1206.18it/s]
13 Oct 22:10    INFO  epoch 0 evaluating [time: 0.48s, valid_score: 0.378500]
13 Oct 22:10    INFO  valid result:
recall@10 : 0.2019    mrr@10 : 0.3785    ndcg@10 : 0.2194    hit@10 : 0.7338    precision@10 : 0.1516
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  33%|███████████████                               | 154/472 [00:00<00:00, 1533.92it/s]:  65%|██████████████████████████████                | 308/472 [00:00<00:00, 1325.24it/s]:  94%|███████████████████████████████████████████▏  | 443/472 [00:00<00:00, 1269.75it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1224.73it/s]
13 Oct 22:10    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    28.10 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.62 G/16.00 G |
+-------------+----------------+
13 Oct 22:10    INFO  best valid : OrderedDict([('recall@10', 0.2019), ('mrr@10', 0.3785), ('ndcg@10', 0.2194), ('hit@10', 0.7338), ('precision@10', 0.1516)])
13 Oct 22:10    INFO  test result: OrderedDict([('recall@10', 0.2346), ('mrr@10', 0.4641), ('ndcg@10', 0.2767), ('hit@10', 0.7741), ('precision@10', 0.1872)])

[8/16] ItemCF: {'k': 50, 'shrink': 100}

13 Oct 22:10    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
13 Oct 22:10    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 100
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


13 Oct 22:10    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
13 Oct 22:10    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 22:10    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
13 Oct 22:10    INFO  ItemKNN()
Trainable parameters: 1
13 Oct 22:10    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  85%|█████████████████████████████████████████▌       | 67/79 [00:00<00:00, 664.70it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 536.36it/s]
13 Oct 22:10    INFO  epoch 0 training [time: 0.22s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  27%|████████████▎                                 | 126/472 [00:00<00:00, 1254.92it/s]:  53%|████████████████████████▌                     | 252/472 [00:00<00:00, 1232.85it/s]:  80%|████████████████████████████████████▋         | 376/472 [00:00<00:00, 1214.95it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1186.86it/s]
13 Oct 22:10    INFO  epoch 0 evaluating [time: 0.47s, valid_score: 0.374200]
13 Oct 22:10    INFO  valid result:
recall@10 : 0.204    mrr@10 : 0.3742    ndcg@10 : 0.2194    hit@10 : 0.7285    precision@10 : 0.1532
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  33%|███████████████                               | 154/472 [00:00<00:00, 1536.85it/s]:  65%|██████████████████████████████                | 308/472 [00:00<00:00, 1325.14it/s]:  94%|███████████████████████████████████████████▏  | 443/472 [00:00<00:00, 1272.33it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1224.96it/s]
13 Oct 22:10    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    16.00 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.59 G/16.00 G |
+-------------+----------------+
13 Oct 22:10    INFO  best valid : OrderedDict([('recall@10', 0.204), ('mrr@10', 0.3742), ('ndcg@10', 0.2194), ('hit@10', 0.7285), ('precision@10', 0.1532)])
13 Oct 22:10    INFO  test result: OrderedDict([('recall@10', 0.233), ('mrr@10', 0.4669), ('ndcg@10', 0.2746), ('hit@10', 0.7709), ('precision@10', 0.1829)])

[9/16] ItemCF: {'k': 100, 'shrink': 0}

13 Oct 22:10    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
13 Oct 22:10    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 0
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


13 Oct 22:11    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
13 Oct 22:11    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 22:11    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
13 Oct 22:11    INFO  ItemKNN()
Trainable parameters: 1
13 Oct 22:11    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  84%|████████████████████████████████████████▉        | 66/79 [00:00<00:00, 656.66it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 513.05it/s]
13 Oct 22:11    INFO  epoch 0 training [time: 0.23s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  34%|███████████████▊                              | 162/472 [00:00<00:00, 1617.09it/s]:  69%|███████████████████████████████▌              | 324/472 [00:00<00:00, 1429.04it/s]:  99%|█████████████████████████████████████████████▋| 469/472 [00:00<00:00, 1371.44it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1301.05it/s]
13 Oct 22:11    INFO  epoch 0 evaluating [time: 0.50s, valid_score: 0.377900]
13 Oct 22:11    INFO  valid result:
recall@10 : 0.2058    mrr@10 : 0.3779    ndcg@10 : 0.2213    hit@10 : 0.7328    precision@10 : 0.1554
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  28%|████████████▉                                 | 133/472 [00:00<00:00, 1327.26it/s]:  56%|█████████████████████████▉                    | 266/472 [00:00<00:00, 1308.81it/s]:  84%|██████████████████████████████████████▋       | 397/472 [00:00<00:00, 1298.75it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1259.45it/s]
13 Oct 22:11    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    16.70 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.59 G/16.00 G |
+-------------+----------------+
13 Oct 22:11    INFO  best valid : OrderedDict([('recall@10', 0.2058), ('mrr@10', 0.3779), ('ndcg@10', 0.2213), ('hit@10', 0.7328), ('precision@10', 0.1554)])
13 Oct 22:11    INFO  test result: OrderedDict([('recall@10', 0.247), ('mrr@10', 0.4623), ('ndcg@10', 0.2834), ('hit@10', 0.7847), ('precision@10', 0.1931)])

[10/16] ItemCF: {'k': 100, 'shrink': 10}

13 Oct 22:11    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
13 Oct 22:11    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 10
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


13 Oct 22:11    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
13 Oct 22:11    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 22:11    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
13 Oct 22:11    INFO  ItemKNN()
Trainable parameters: 1
13 Oct 22:11    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  52%|█████████████████████████▍                       | 41/79 [00:00<00:00, 405.75it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 367.82it/s]
13 Oct 22:11    INFO  epoch 0 training [time: 0.30s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  22%|██████████▎                                   | 106/472 [00:00<00:00, 1056.57it/s]:  45%|████████████████████▋                         | 212/472 [00:00<00:00, 1008.98it/s]:  68%|███████████████████████████████▏              | 320/472 [00:00<00:00, 1039.05it/s]:  90%|█████████████████████████████████████████▌    | 427/472 [00:00<00:00, 1050.29it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1006.31it/s]
13 Oct 22:11    INFO  epoch 0 evaluating [time: 0.58s, valid_score: 0.378000]
13 Oct 22:11    INFO  valid result:
recall@10 : 0.2027    mrr@10 : 0.378    ndcg@10 : 0.2215    hit@10 : 0.7296    precision@10 : 0.1555
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  24%|███████████▏                                  | 115/472 [00:00<00:00, 1145.98it/s]:  49%|██████████████████████▉                        | 230/472 [00:00<00:00, 982.93it/s]:  70%|████████████████████████████████▊              | 330/472 [00:00<00:00, 856.73it/s]:  89%|█████████████████████████████████████████▌     | 418/472 [00:00<00:00, 840.08it/s]: 100%|███████████████████████████████████████████████| 472/472 [00:00<00:00, 840.36it/s]
13 Oct 22:11    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    23.00 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.58 G/16.00 G |
+-------------+----------------+
13 Oct 22:11    INFO  best valid : OrderedDict([('recall@10', 0.2027), ('mrr@10', 0.378), ('ndcg@10', 0.2215), ('hit@10', 0.7296), ('precision@10', 0.1555)])
13 Oct 22:11    INFO  test result: OrderedDict([('recall@10', 0.244), ('mrr@10', 0.4705), ('ndcg@10', 0.2846), ('hit@10', 0.7805), ('precision@10', 0.1911)])

[11/16] ItemCF: {'k': 100, 'shrink': 50}

13 Oct 22:11    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
13 Oct 22:11    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 50
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


13 Oct 22:11    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
13 Oct 22:11    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 22:11    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
13 Oct 22:11    INFO  ItemKNN()
Trainable parameters: 1
13 Oct 22:11    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  41%|███████████████████▊                             | 32/79 [00:00<00:00, 318.49it/s]:  81%|███████████████████████████████████████▋         | 64/79 [00:00<00:00, 310.36it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 300.43it/s]
13 Oct 22:11    INFO  epoch 0 training [time: 0.34s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  21%|█████████▉                                      | 98/472 [00:00<00:00, 978.82it/s]:  42%|███████████████████▌                           | 196/472 [00:00<00:00, 898.10it/s]:  61%|████████████████████████████▌                  | 287/472 [00:00<00:00, 844.62it/s]:  79%|█████████████████████████████████████          | 372/472 [00:00<00:00, 836.72it/s]:  97%|█████████████████████████████████████████████▍ | 456/472 [00:00<00:00, 836.53it/s]: 100%|███████████████████████████████████████████████| 472/472 [00:00<00:00, 814.55it/s]
13 Oct 22:11    INFO  epoch 0 evaluating [time: 0.72s, valid_score: 0.381300]
13 Oct 22:11    INFO  valid result:
recall@10 : 0.2044    mrr@10 : 0.3813    ndcg@10 : 0.2216    hit@10 : 0.7243    precision@10 : 0.1524
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  26%|███████████▊                                  | 121/472 [00:00<00:00, 1207.28it/s]:  51%|████████████████████████                       | 242/472 [00:00<00:00, 955.75it/s]:  72%|█████████████████████████████████▉             | 341/472 [00:00<00:00, 802.48it/s]:  90%|██████████████████████████████████████████▎    | 425/472 [00:00<00:00, 711.36it/s]: 100%|███████████████████████████████████████████████| 472/472 [00:00<00:00, 727.56it/s]
13 Oct 22:11    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    25.00 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.59 G/16.00 G |
+-------------+----------------+
13 Oct 22:11    INFO  best valid : OrderedDict([('recall@10', 0.2044), ('mrr@10', 0.3813), ('ndcg@10', 0.2216), ('hit@10', 0.7243), ('precision@10', 0.1524)])
13 Oct 22:11    INFO  test result: OrderedDict([('recall@10', 0.2414), ('mrr@10', 0.4731), ('ndcg@10', 0.2816), ('hit@10', 0.7826), ('precision@10', 0.1859)])

[12/16] ItemCF: {'k': 100, 'shrink': 100}

13 Oct 22:11    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
13 Oct 22:11    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 100
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


13 Oct 22:11    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
13 Oct 22:11    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 22:11    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
13 Oct 22:11    INFO  ItemKNN()
Trainable parameters: 1
13 Oct 22:11    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  61%|█████████████████████████████▊                   | 48/79 [00:00<00:00, 470.55it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 398.79it/s]
13 Oct 22:11    INFO  epoch 0 training [time: 0.28s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  22%|██████████▎                                   | 106/472 [00:00<00:00, 1057.23it/s]:  45%|█████████████████████                          | 212/472 [00:00<00:00, 646.32it/s]:  61%|████████████████████████████▍                  | 286/472 [00:00<00:00, 648.65it/s]:  76%|███████████████████████████████████▌           | 357/472 [00:00<00:00, 667.00it/s]:  91%|██████████████████████████████████████████▌    | 428/472 [00:00<00:00, 673.10it/s]: 100%|███████████████████████████████████████████████| 472/472 [00:00<00:00, 669.09it/s]
13 Oct 22:11    INFO  epoch 0 evaluating [time: 0.81s, valid_score: 0.386900]
13 Oct 22:11    INFO  valid result:
recall@10 : 0.2007    mrr@10 : 0.3869    ndcg@10 : 0.2216    hit@10 : 0.7264    precision@10 : 0.1496
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  25%|███████████▌                                  | 118/472 [00:00<00:00, 1171.01it/s]:  50%|███████████████████████                       | 236/472 [00:00<00:00, 1011.80it/s]:  72%|█████████████████████████████████▊             | 339/472 [00:00<00:00, 950.86it/s]:  92%|███████████████████████████████████████████▎   | 435/472 [00:00<00:00, 940.51it/s]: 100%|███████████████████████████████████████████████| 472/472 [00:00<00:00, 918.13it/s]
13 Oct 22:11    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    25.20 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.58 G/16.00 G |
+-------------+----------------+
13 Oct 22:11    INFO  best valid : OrderedDict([('recall@10', 0.2007), ('mrr@10', 0.3869), ('ndcg@10', 0.2216), ('hit@10', 0.7264), ('precision@10', 0.1496)])
13 Oct 22:11    INFO  test result: OrderedDict([('recall@10', 0.2402), ('mrr@10', 0.4827), ('ndcg@10', 0.2819), ('hit@10', 0.7922), ('precision@10', 0.183)])

[13/16] ItemCF: {'k': 200, 'shrink': 0}

13 Oct 22:11    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
13 Oct 22:11    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 0
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


13 Oct 22:11    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
13 Oct 22:11    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 22:11    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
13 Oct 22:11    INFO  ItemKNN()
Trainable parameters: 1
13 Oct 22:11    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  49%|████████████████████████▏                        | 39/79 [00:00<00:00, 388.67it/s]:  99%|████████████████████████████████████████████████▍| 78/79 [00:00<00:00, 350.02it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 311.16it/s]
13 Oct 22:11    INFO  epoch 0 training [time: 0.33s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  25%|███████████▌                                  | 118/472 [00:00<00:00, 1179.98it/s]:  50%|███████████████████████▌                       | 236/472 [00:00<00:00, 824.65it/s]:  69%|████████████████████████████████▎              | 325/472 [00:00<00:00, 802.84it/s]:  90%|██████████████████████████████████████████▏    | 424/472 [00:00<00:00, 863.57it/s]: 100%|███████████████████████████████████████████████| 472/472 [00:00<00:00, 854.85it/s]
13 Oct 22:11    INFO  epoch 0 evaluating [time: 0.64s, valid_score: 0.370600]
13 Oct 22:11    INFO  valid result:
recall@10 : 0.2073    mrr@10 : 0.3706    ndcg@10 : 0.223    hit@10 : 0.7328    precision@10 : 0.155
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  29%|█████████████▍                                | 138/472 [00:00<00:00, 1377.82it/s]:  58%|██████████████████████████▉                   | 276/472 [00:00<00:00, 1173.01it/s]:  84%|██████████████████████████████████████▌       | 396/472 [00:00<00:00, 1121.72it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1109.29it/s]
13 Oct 22:11    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    23.70 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.60 G/16.00 G |
+-------------+----------------+
13 Oct 22:11    INFO  best valid : OrderedDict([('recall@10', 0.2073), ('mrr@10', 0.3706), ('ndcg@10', 0.223), ('hit@10', 0.7328), ('precision@10', 0.155)])
13 Oct 22:11    INFO  test result: OrderedDict([('recall@10', 0.2529), ('mrr@10', 0.4767), ('ndcg@10', 0.2894), ('hit@10', 0.7922), ('precision@10', 0.1935)])

[14/16] ItemCF: {'k': 200, 'shrink': 10}

13 Oct 22:11    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
13 Oct 22:11    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 10
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


13 Oct 22:11    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
13 Oct 22:11    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 22:11    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
13 Oct 22:11    INFO  ItemKNN()
Trainable parameters: 1
13 Oct 22:11    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  80%|███████████████████████████████████████          | 63/79 [00:00<00:00, 623.11it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 506.29it/s]
13 Oct 22:11    INFO  epoch 0 training [time: 0.24s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  30%|█████████████▋                                | 140/472 [00:00<00:00, 1393.62it/s]:  59%|███████████████████████████▎                  | 280/472 [00:00<00:00, 1199.13it/s]:  85%|███████████████████████████████████████▏      | 402/472 [00:00<00:00, 1038.29it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1045.87it/s]
13 Oct 22:11    INFO  epoch 0 evaluating [time: 0.55s, valid_score: 0.370500]
13 Oct 22:11    INFO  valid result:
recall@10 : 0.2064    mrr@10 : 0.3705    ndcg@10 : 0.2228    hit@10 : 0.7359    precision@10 : 0.1551
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  30%|█████████████▋                                | 140/472 [00:00<00:00, 1396.27it/s]:  59%|███████████████████████████▎                  | 280/472 [00:00<00:00, 1175.81it/s]:  85%|██████████████████████████████████████▉       | 400/472 [00:00<00:00, 1114.29it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1102.79it/s]
13 Oct 22:11    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    17.80 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.62 G/16.00 G |
+-------------+----------------+
13 Oct 22:11    INFO  best valid : OrderedDict([('recall@10', 0.2064), ('mrr@10', 0.3705), ('ndcg@10', 0.2228), ('hit@10', 0.7359), ('precision@10', 0.1551)])
13 Oct 22:11    INFO  test result: OrderedDict([('recall@10', 0.2526), ('mrr@10', 0.4791), ('ndcg@10', 0.29), ('hit@10', 0.79), ('precision@10', 0.1928)])

[15/16] ItemCF: {'k': 200, 'shrink': 50}

13 Oct 22:11    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
13 Oct 22:11    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 50
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


13 Oct 22:12    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
13 Oct 22:12    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 22:12    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
13 Oct 22:12    INFO  ItemKNN()
Trainable parameters: 1
13 Oct 22:12    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  82%|████████████████████████████████████████▎        | 65/79 [00:00<00:00, 649.65it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 524.68it/s]
13 Oct 22:12    INFO  epoch 0 training [time: 0.22s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  29%|█████████████▎                                | 136/472 [00:00<00:00, 1347.96it/s]:  57%|██████████████████████████▍                   | 271/472 [00:00<00:00, 1175.63it/s]:  83%|██████████████████████████████████████        | 390/472 [00:00<00:00, 1108.32it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1104.55it/s]
13 Oct 22:12    INFO  epoch 0 evaluating [time: 0.52s, valid_score: 0.374400]
13 Oct 22:12    INFO  valid result:
recall@10 : 0.2045    mrr@10 : 0.3744    ndcg@10 : 0.2215    hit@10 : 0.7243    precision@10 : 0.1519
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  30%|█████████████▋                                | 140/472 [00:00<00:00, 1393.05it/s]:  59%|███████████████████████████▎                  | 280/472 [00:00<00:00, 1168.35it/s]:  85%|██████████████████████████████████████▉       | 400/472 [00:00<00:00, 1117.71it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1103.04it/s]
13 Oct 22:12    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    15.30 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.64 G/16.00 G |
+-------------+----------------+
13 Oct 22:12    INFO  best valid : OrderedDict([('recall@10', 0.2045), ('mrr@10', 0.3744), ('ndcg@10', 0.2215), ('hit@10', 0.7243), ('precision@10', 0.1519)])
13 Oct 22:12    INFO  test result: OrderedDict([('recall@10', 0.2444), ('mrr@10', 0.4801), ('ndcg@10', 0.2861), ('hit@10', 0.7794), ('precision@10', 0.1864)])

[16/16] ItemCF: {'k': 200, 'shrink': 100}

13 Oct 22:12    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
13 Oct 22:12    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 100
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


13 Oct 22:12    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
13 Oct 22:12    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 22:12    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
13 Oct 22:12    INFO  ItemKNN()
Trainable parameters: 1
13 Oct 22:12    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  87%|██████████████████████████████████████████▊      | 69/79 [00:00<00:00, 682.92it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 536.96it/s]
13 Oct 22:12    INFO  epoch 0 training [time: 0.21s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  30%|█████████████▋                                | 141/472 [00:00<00:00, 1408.42it/s]:  60%|███████████████████████████▍                  | 282/472 [00:00<00:00, 1200.80it/s]:  86%|███████████████████████████████████████▍      | 405/472 [00:00<00:00, 1119.12it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1104.41it/s]
13 Oct 22:12    INFO  epoch 0 evaluating [time: 0.52s, valid_score: 0.377900]
13 Oct 22:12    INFO  valid result:
recall@10 : 0.1971    mrr@10 : 0.3779    ndcg@10 : 0.219    hit@10 : 0.719    precision@10 : 0.1486
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  29%|█████████████▎                                | 136/472 [00:00<00:00, 1353.25it/s]:  58%|██████████████████████████▌                   | 272/472 [00:00<00:00, 1168.34it/s]:  83%|██████████████████████████████████████        | 391/472 [00:00<00:00, 1091.33it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1081.95it/s]
13 Oct 22:12    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    15.50 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.65 G/16.00 G |
+-------------+----------------+
13 Oct 22:12    INFO  best valid : OrderedDict([('recall@10', 0.1971), ('mrr@10', 0.3779), ('ndcg@10', 0.219), ('hit@10', 0.719), ('precision@10', 0.1486)])
13 Oct 22:12    INFO  test result: OrderedDict([('recall@10', 0.2341), ('mrr@10', 0.4696), ('ndcg@10', 0.2765), ('hit@10', 0.7646), ('precision@10', 0.1801)])

Saved to:
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/tuning_results/ItemCF_tuning.csv

Best configuration:

     k  shrink  valid_score  recall@10  mrr@10  ndcg@10  hit@10  precision@10
0  100     100       0.3869     0.2007  0.3869   0.2216  0.7264        0.1496

In [13]:
usercf_results = tune_model(
    name="UserCF",
    model="ItemKNN",
    config_path=CONFIG_ROOT / "ItemKNN" / "ml-100k.yaml",
    search_space=itemcf_space,
    fixed_params={
        "knn_method": "user"
    }
)

Tuning UserCF
Number of experiments: 16
============================================================
[1/16] UserCF: {'k': 20, 'shrink': 0}

13 Oct 21:51    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:51    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
2026-10-13 21:51:35,265	WARNING session.py:91 -- Session not detected. You should not be calling `report` outside `tuner.fit()` or while using the class API.
2026-10-13 21:51:35,265	WARNING session.py:97 --   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/traitlets/config/application.py", line 1080, in launch_instance
    app.start()
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 807, in start
    self.io_loop.start()
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel/utils.py", line 71, in preserve_context
    return await f(*args, **kwargs)
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 460, in do_execute
    res = shell.run_cell(
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 665, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3077, in run_cell
    result = self._run_cell(
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3132, in _run_cell
    result = runner(coro)
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3336, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3519, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3579, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/nm/k1qk3hy11591tls809pdvs4m0000gn/T/ipykernel_58377/3224810412.py", line 1, in <module>
    usercf_results = tune_model(
  File "/var/folders/nm/k1qk3hy11591tls809pdvs4m0000gn/T/ipykernel_58377/2435821772.py", line 85, in tune_model
    result = objective_function(
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/quick_start/quick_start.py", line 223, in objective_function
    tune.report(**test_result)

[2/16] UserCF: {'k': 20, 'shrink': 10}

13 Oct 21:51    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:51    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[3/16] UserCF: {'k': 20, 'shrink': 50}

13 Oct 21:51    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:51    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[4/16] UserCF: {'k': 20, 'shrink': 100}

13 Oct 21:51    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:51    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[5/16] UserCF: {'k': 50, 'shrink': 0}

13 Oct 21:51    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:51    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[6/16] UserCF: {'k': 50, 'shrink': 10}

13 Oct 21:51    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:51    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[7/16] UserCF: {'k': 50, 'shrink': 50}

13 Oct 21:51    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:51    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[8/16] UserCF: {'k': 50, 'shrink': 100}

13 Oct 21:51    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:51    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[9/16] UserCF: {'k': 100, 'shrink': 0}

13 Oct 21:51    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:51    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[10/16] UserCF: {'k': 100, 'shrink': 10}

13 Oct 21:51    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:51    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[11/16] UserCF: {'k': 100, 'shrink': 50}

13 Oct 21:51    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:51    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[12/16] UserCF: {'k': 100, 'shrink': 100}

13 Oct 21:51    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:51    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[13/16] UserCF: {'k': 200, 'shrink': 0}

13 Oct 21:51    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:51    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[14/16] UserCF: {'k': 200, 'shrink': 10}

13 Oct 21:51    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:51    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[15/16] UserCF: {'k': 200, 'shrink': 50}

13 Oct 21:51    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:51    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[16/16] UserCF: {'k': 200, 'shrink': 100}

13 Oct 21:51    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:51    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

Saved to:
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/tuning_results/UserCF_tuning.csv

Best configuration:

    k  shrink  valid_score  recall@10  mrr@10  ndcg@10  hit@10  precision@10
0  50       0        0.401      0.216   0.401   0.2355   0.755        0.1562

In [ ]:
bpr_space = {
    "embedding_size": [16, 32, 64, 128],
    "learning_rate": [0.0001, 0.001, 0.01],
}

In [15]:
bpr_results = tune_model(
    name="BPR",
    model="BPR",
    config_path=CONFIG_ROOT / "BPR" / "ml-100k.yaml",
    search_space=bpr_space
)

Tuning BPR
Number of experiments: 36
============================================================
[1/36] BPR: {'embedding_size': 16, 'learning_rate': 0.0001, 'reg_weight': 0.0}

13 Oct 21:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
2026-10-13 21:52:14,158	WARNING session.py:91 -- Session not detected. You should not be calling `report` outside `tuner.fit()` or while using the class API.
2026-10-13 21:52:14,158	WARNING session.py:97 --   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/traitlets/config/application.py", line 1080, in launch_instance
    app.start()
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 807, in start
    self.io_loop.start()
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel/utils.py", line 71, in preserve_context
    return await f(*args, **kwargs)
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 460, in do_execute
    res = shell.run_cell(
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 665, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3077, in run_cell
    result = self._run_cell(
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3132, in _run_cell
    result = runner(coro)
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3336, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3519, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3579, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/nm/k1qk3hy11591tls809pdvs4m0000gn/T/ipykernel_58377/4201119444.py", line 1, in <module>
    bpr_results = tune_model(
  File "/var/folders/nm/k1qk3hy11591tls809pdvs4m0000gn/T/ipykernel_58377/2435821772.py", line 85, in tune_model
    result = objective_function(
  File "/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/quick_start/quick_start.py", line 223, in objective_function
    tune.report(**test_result)

[2/36] BPR: {'embedding_size': 16, 'learning_rate': 0.0001, 'reg_weight': 0.0001}

13 Oct 21:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[3/36] BPR: {'embedding_size': 16, 'learning_rate': 0.0001, 'reg_weight': 0.001}

13 Oct 21:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[4/36] BPR: {'embedding_size': 16, 'learning_rate': 0.001, 'reg_weight': 0.0}

13 Oct 21:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[5/36] BPR: {'embedding_size': 16, 'learning_rate': 0.001, 'reg_weight': 0.0001}

13 Oct 21:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[6/36] BPR: {'embedding_size': 16, 'learning_rate': 0.001, 'reg_weight': 0.001}

13 Oct 21:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[7/36] BPR: {'embedding_size': 16, 'learning_rate': 0.01, 'reg_weight': 0.0}

13 Oct 21:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[8/36] BPR: {'embedding_size': 16, 'learning_rate': 0.01, 'reg_weight': 0.0001}

13 Oct 21:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[9/36] BPR: {'embedding_size': 16, 'learning_rate': 0.01, 'reg_weight': 0.001}

13 Oct 21:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[10/36] BPR: {'embedding_size': 32, 'learning_rate': 0.0001, 'reg_weight': 0.0}

13 Oct 21:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[11/36] BPR: {'embedding_size': 32, 'learning_rate': 0.0001, 'reg_weight': 0.0001}

13 Oct 21:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[12/36] BPR: {'embedding_size': 32, 'learning_rate': 0.0001, 'reg_weight': 0.001}

13 Oct 21:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[13/36] BPR: {'embedding_size': 32, 'learning_rate': 0.001, 'reg_weight': 0.0}

13 Oct 21:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[14/36] BPR: {'embedding_size': 32, 'learning_rate': 0.001, 'reg_weight': 0.0001}

13 Oct 21:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[15/36] BPR: {'embedding_size': 32, 'learning_rate': 0.001, 'reg_weight': 0.001}

13 Oct 21:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[16/36] BPR: {'embedding_size': 32, 'learning_rate': 0.01, 'reg_weight': 0.0}

13 Oct 21:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[17/36] BPR: {'embedding_size': 32, 'learning_rate': 0.01, 'reg_weight': 0.0001}

13 Oct 21:53    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:53    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[18/36] BPR: {'embedding_size': 32, 'learning_rate': 0.01, 'reg_weight': 0.001}

13 Oct 21:53    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:53    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[19/36] BPR: {'embedding_size': 64, 'learning_rate': 0.0001, 'reg_weight': 0.0}

13 Oct 21:53    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:53    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[20/36] BPR: {'embedding_size': 64, 'learning_rate': 0.0001, 'reg_weight': 0.0001}

13 Oct 21:53    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:53    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[21/36] BPR: {'embedding_size': 64, 'learning_rate': 0.0001, 'reg_weight': 0.001}

13 Oct 21:53    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:53    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[22/36] BPR: {'embedding_size': 64, 'learning_rate': 0.001, 'reg_weight': 0.0}

13 Oct 21:53    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:53    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[23/36] BPR: {'embedding_size': 64, 'learning_rate': 0.001, 'reg_weight': 0.0001}

13 Oct 21:53    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:53    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[24/36] BPR: {'embedding_size': 64, 'learning_rate': 0.001, 'reg_weight': 0.001}

13 Oct 21:53    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:53    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[25/36] BPR: {'embedding_size': 64, 'learning_rate': 0.01, 'reg_weight': 0.0}

13 Oct 21:53    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:53    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[26/36] BPR: {'embedding_size': 64, 'learning_rate': 0.01, 'reg_weight': 0.0001}

13 Oct 21:53    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:53    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[27/36] BPR: {'embedding_size': 64, 'learning_rate': 0.01, 'reg_weight': 0.001}

13 Oct 21:53    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:53    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[28/36] BPR: {'embedding_size': 128, 'learning_rate': 0.0001, 'reg_weight': 0.0}

13 Oct 21:53    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:53    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[29/36] BPR: {'embedding_size': 128, 'learning_rate': 0.0001, 'reg_weight': 0.0001}

13 Oct 21:53    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:53    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[30/36] BPR: {'embedding_size': 128, 'learning_rate': 0.0001, 'reg_weight': 0.001}

13 Oct 21:53    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:53    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[31/36] BPR: {'embedding_size': 128, 'learning_rate': 0.001, 'reg_weight': 0.0}

13 Oct 21:53    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:53    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[32/36] BPR: {'embedding_size': 128, 'learning_rate': 0.001, 'reg_weight': 0.0001}

13 Oct 21:54    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:54    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[33/36] BPR: {'embedding_size': 128, 'learning_rate': 0.001, 'reg_weight': 0.001}

13 Oct 21:54    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:54    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[34/36] BPR: {'embedding_size': 128, 'learning_rate': 0.01, 'reg_weight': 0.0}

13 Oct 21:54    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:54    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[35/36] BPR: {'embedding_size': 128, 'learning_rate': 0.01, 'reg_weight': 0.0001}

13 Oct 21:54    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:54    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

[36/36] BPR: {'embedding_size': 128, 'learning_rate': 0.01, 'reg_weight': 0.001}

13 Oct 21:54    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:54    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)

Saved to:
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/tuning_results/BPR_tuning.csv

Best configuration:

,embedding_size,learning_rate,reg_weight,valid_score,recall@10,mrr@10,ndcg@10,hit@10,precision@10
0,32,0.01,0.0,0.3581,0.1904,0.3581,0.2038,0.7169,0.1393

In [16]:
slim_space = {
    "alpha": [0.0001, 0.001, 0.01, 0.1],
    "l1_ratio": [0.1, 0.5, 0.9]
}

slim_results = tune_model(
    name="SLIM",
    model="SLIMElastic",
    config_path=CONFIG_ROOT / "SLIMElastic" / "ml-100k.yaml",
    search_space=slim_space
)

Tuning SLIM
Number of experiments: 12
============================================================
[1/12] SLIM: {'alpha': 0.0001, 'l1_ratio': 0.1}

13 Oct 21:54    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:54    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[2/12] SLIM: {'alpha': 0.0001, 'l1_ratio': 0.5}

13 Oct 21:54    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:54    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[3/12] SLIM: {'alpha': 0.0001, 'l1_ratio': 0.9}

13 Oct 21:55    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:55    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[4/12] SLIM: {'alpha': 0.001, 'l1_ratio': 0.1}

13 Oct 21:55    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:55    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[5/12] SLIM: {'alpha': 0.001, 'l1_ratio': 0.5}

13 Oct 21:55    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:55    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[6/12] SLIM: {'alpha': 0.001, 'l1_ratio': 0.9}

13 Oct 21:55    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:55    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[7/12] SLIM: {'alpha': 0.01, 'l1_ratio': 0.1}

13 Oct 21:55    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:55    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[8/12] SLIM: {'alpha': 0.01, 'l1_ratio': 0.5}

13 Oct 21:56    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:56    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[9/12] SLIM: {'alpha': 0.01, 'l1_ratio': 0.9}

13 Oct 21:56    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:56    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[10/12] SLIM: {'alpha': 0.1, 'l1_ratio': 0.1}

13 Oct 21:56    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:56    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[11/12] SLIM: {'alpha': 0.1, 'l1_ratio': 0.5}

13 Oct 21:56    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:56    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[12/12] SLIM: {'alpha': 0.1, 'l1_ratio': 0.9}

13 Oct 21:56    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:56    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

Saved to:
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/tuning_results/SLIM_tuning.csv

Best configuration:

,alpha,l1_ratio,valid_score,recall@10,mrr@10,ndcg@10,hit@10,precision@10
0,0.1,0.1,0.4165,0.2271,0.4165,0.2495,0.7625,0.1709

In [17]:
ease_space = {
    "reg_weight": [10, 50, 100, 200, 500, 1000]
}

ease_results = tune_model(
    name="EASE",
    model="EASE",
    config_path=CONFIG_ROOT / "EASE" / "ml-100k.yaml",
    search_space=ease_space
)

Tuning EASE
Number of experiments: 6
============================================================
[1/6] EASE: {'reg_weight': 10}

13 Oct 21:57    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:57    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[2/6] EASE: {'reg_weight': 50}

13 Oct 21:57    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:57    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[3/6] EASE: {'reg_weight': 100}

13 Oct 21:57    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:57    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[4/6] EASE: {'reg_weight': 200}

13 Oct 21:57    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:57    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[5/6] EASE: {'reg_weight': 500}

13 Oct 21:57    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:57    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[6/6] EASE: {'reg_weight': 1000}

13 Oct 21:57    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
13 Oct 21:57    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

Saved to:
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/tuning_results/EASE_tuning.csv

Best configuration:

   reg_weight  valid_score  recall@10  mrr@10  ndcg@10  hit@10  precision@10
0         500       0.4189     0.2386  0.4189   0.2568  0.7815        0.1766

In [28]:
fism_space = {
    "embedding_size": [32, 64],
    "learning_rate": [0.001, 0.005],
    "alpha": [0.5],
    "reg_weights": [
        [0.0001, 0.0001],
        [0.001, 0.001],
    ],
}

fism_results = tune_model(
    name="FISM",
    model="FISM",
    config_path=CONFIG_ROOT / "FISM" / "ml-100k.yaml",
    search_space=fism_space,
)

Tuning FISM
Number of experiments: 8
============================================================
[1/8] FISM: {'embedding_size': 32, 'learning_rate': 0.001, 'alpha': 0.5, 'reg_weights': [0.0001, 0.0001]}

14 Oct 08:13    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
14 Oct 08:13    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
split_to = 0
reg_weights = [0.0001, 0.0001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


14 Oct 08:13    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
14 Oct 08:13    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
14 Oct 08:13    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
14 Oct 08:13    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
14 Oct 08:13    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
14 Oct 08:13    INFO  FISM(
  (item_src_embedding): Embedding(1683, 32, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 32, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 110339
14 Oct 08:13    INFO  FLOPs: 18944.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:   1%|▋                                                  | 1/79 [00:00<00:11,  7.06it/s]:   3%|█▎                                                 | 2/79 [00:00<00:09,  7.97it/s]:   4%|█▉                                                 | 3/79 [00:00<00:09,  8.21it/s]:   5%|██▌                                                | 4/79 [00:00<00:08,  8.37it/s]:   6%|███▏                                               | 5/79 [00:00<00:08,  8.44it/s]:   8%|███▊                                               | 6/79 [00:00<00:08,  8.29it/s]:   9%|████▌                                              | 7/79 [00:00<00:08,  8.39it/s]:  10%|█████▏                                             | 8/79 [00:00<00:08,  8.39it/s]:  11%|█████▊                                             | 9/79 [00:01<00:08,  8.55it/s]:  13%|██████▎                                           | 10/79 [00:01<00:08,  8.59it/s]:  14%|██████▉                                           | 11/79 [00:01<00:07,  8.52it/s]:  15%|███████▌                                          | 12/79 [00:01<00:08,  7.51it/s]:  16%|████████▏                                         | 13/79 [00:01<00:08,  7.72it/s]:  18%|████████▊                                         | 14/79 [00:01<00:08,  7.58it/s]:  19%|█████████▍                                        | 15/79 [00:01<00:08,  7.59it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:08,  7.40it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:08,  7.53it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:08,  7.62it/s]:  24%|████████████                                      | 19/79 [00:02<00:07,  7.85it/s]:  25%|████████████▋                                     | 20/79 [00:02<00:07,  7.91it/s]:  27%|█████████████▎                                    | 21/79 [00:02<00:07,  7.50it/s]:  28%|█████████████▉                                    | 22/79 [00:02<00:07,  7.40it/s]:  29%|██████████████▌                                   | 23/79 [00:02<00:08,  6.82it/s]:  30%|███████████████▏                                  | 24/79 [00:03<00:08,  6.44it/s]:  32%|███████████████▊                                  | 25/79 [00:03<00:08,  6.67it/s]:  33%|████████████████▍                                 | 26/79 [00:03<00:07,  6.83it/s]:  34%|█████████████████                                 | 27/79 [00:03<00:07,  6.60it/s]:  35%|█████████████████▋                                | 28/79 [00:03<00:07,  6.98it/s]:  37%|██████████████████▎                               | 29/79 [00:03<00:06,  7.21it/s]:  38%|██████████████████▉                               | 30/79 [00:03<00:06,  7.39it/s]:  39%|███████████████████▌                              | 31/79 [00:04<00:06,  7.61it/s]:  41%|████████████████████▎                             | 32/79 [00:04<00:06,  7.79it/s]:  42%|████████████████████▉                             | 33/79 [00:04<00:05,  7.85it/s]:  43%|█████████████████████▌                            | 34/79 [00:04<00:05,  7.98it/s]:  44%|██████████████████████▏                           | 35/79 [00:04<00:05,  8.05it/s]:  46%|██████████████████████▊                           | 36/79 [00:04<00:05,  8.11it/s]:  47%|███████████████████████▍                          | 37/79 [00:04<00:05,  7.95it/s]:  48%|████████████████████████                          | 38/79 [00:04<00:05,  7.93it/s]:  49%|████████████████████████▋                         | 39/79 [00:05<00:05,  6.97it/s]:  51%|█████████████████████████▎                        | 40/79 [00:05<00:05,  6.85it/s]:  52%|█████████████████████████▉                        | 41/79 [00:05<00:05,  6.98it/s]:  53%|██████████████████████████▌                       | 42/79 [00:05<00:05,  7.17it/s]:  54%|███████████████████████████▏                      | 43/79 [00:05<00:04,  7.40it/s]:  56%|███████████████████████████▊                      | 44/79 [00:05<00:04,  7.34it/s]:  57%|████████████████████████████▍                     | 45/79 [00:05<00:04,  7.44it/s]:  58%|█████████████████████████████                     | 46/79 [00:06<00:04,  7.17it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:06<00:04,  7.16it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:06<00:04,  7.40it/s]:  62%|███████████████████████████████                   | 49/79 [00:06<00:03,  7.56it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:06<00:03,  7.66it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:06<00:03,  7.73it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:06<00:03,  7.84it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:06<00:03,  7.90it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:07<00:03,  8.02it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:07<00:02,  8.10it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:07<00:02,  8.16it/s]:  72%|████████████████████████████████████              | 57/79 [00:07<00:02,  8.16it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:07<00:02,  8.10it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:07<00:02,  7.27it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:07<00:02,  7.00it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:08<00:02,  7.15it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:08<00:02,  7.37it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:08<00:02,  7.55it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:08<00:02,  7.48it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:08<00:01,  7.54it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:08<00:01,  7.44it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:08<00:01,  7.30it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:08<00:01,  7.45it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:09<00:01,  7.64it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:09<00:01,  7.79it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:09<00:01,  7.95it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:09<00:00,  7.93it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:09<00:00,  7.98it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:09<00:00,  7.99it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:09<00:00,  7.68it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:10<00:00,  7.58it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:10<00:00,  7.64it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:10<00:00,  7.68it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:10<00:00,  7.71it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:10<00:00,  7.56it/s]
14 Oct 08:13    INFO  epoch 0 training [time: 10.57s, train loss: 55.0431]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 12.74it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 11.06it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 10.68it/s]:  10%|█████▏                                             | 8/79 [00:00<00:06, 10.38it/s]:  13%|██████▎                                           | 10/79 [00:00<00:06,  9.97it/s]:  15%|███████▌                                          | 12/79 [00:01<00:06,  9.99it/s]:  18%|████████▊                                         | 14/79 [00:01<00:06, 10.01it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:06,  9.99it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:06,  9.99it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:05, 10.04it/s]:  28%|█████████████▉                                    | 22/79 [00:02<00:05, 10.01it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:05, 10.02it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:05,  9.99it/s]:  34%|█████████████████                                 | 27/79 [00:02<00:05,  9.58it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:05,  9.27it/s]:  37%|██████████████████▎                               | 29/79 [00:02<00:05,  8.94it/s]:  38%|██████████████████▉                               | 30/79 [00:03<00:05,  8.74it/s]:  39%|███████████████████▌                              | 31/79 [00:03<00:05,  8.59it/s]:  41%|████████████████████▎                             | 32/79 [00:03<00:05,  8.48it/s]:  42%|████████████████████▉                             | 33/79 [00:03<00:05,  8.43it/s]:  43%|█████████████████████▌                            | 34/79 [00:03<00:05,  8.33it/s]:  44%|██████████████████████▏                           | 35/79 [00:03<00:05,  8.26it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:05,  8.25it/s]:  47%|███████████████████████▍                          | 37/79 [00:03<00:05,  8.13it/s]:  48%|████████████████████████                          | 38/79 [00:04<00:05,  8.06it/s]:  49%|████████████████████████▋                         | 39/79 [00:04<00:04,  8.07it/s]:  51%|█████████████████████████▎                        | 40/79 [00:04<00:05,  7.76it/s]:  52%|█████████████████████████▉                        | 41/79 [00:04<00:04,  7.86it/s]:  53%|██████████████████████████▌                       | 42/79 [00:04<00:04,  7.95it/s]:  54%|███████████████████████████▏                      | 43/79 [00:04<00:04,  7.99it/s]:  56%|███████████████████████████▊                      | 44/79 [00:04<00:04,  7.19it/s]:  57%|████████████████████████████▍                     | 45/79 [00:04<00:04,  7.47it/s]:  58%|█████████████████████████████                     | 46/79 [00:05<00:04,  7.67it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:05<00:04,  7.81it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:05<00:03,  7.86it/s]:  62%|███████████████████████████████                   | 49/79 [00:05<00:03,  7.93it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:05<00:03,  7.97it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:05<00:03,  8.00it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:05<00:03,  8.04it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:05<00:03,  7.93it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:06<00:03,  7.80it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:06<00:03,  7.81it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:06<00:02,  7.81it/s]:  72%|████████████████████████████████████              | 57/79 [00:06<00:02,  7.68it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:06<00:02,  7.50it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:06<00:02,  6.75it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:06<00:02,  6.86it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:07<00:02,  6.11it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:07<00:02,  6.55it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:07<00:02,  6.94it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:07<00:02,  7.28it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:07<00:01,  7.53it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:07<00:01,  7.70it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:07<00:01,  7.86it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:08<00:01,  7.98it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:08<00:01,  7.94it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:08<00:01,  8.03it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:08<00:00,  8.09it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:08<00:00,  8.22it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:08<00:00,  8.16it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:08<00:00,  8.06it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:08<00:00,  7.98it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:09<00:00,  8.05it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:09<00:00,  5.57it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:09<00:00,  5.19it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:09<00:00,  5.87it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:09<00:00,  8.14it/s]
14 Oct 08:14    INFO  epoch 1 training [time: 9.88s, train loss: 50.1013]

[2/8] FISM: {'embedding_size': 32, 'learning_rate': 0.001, 'alpha': 0.5, 'reg_weights': [0.001, 0.001]}

14 Oct 08:17    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
14 Oct 08:17    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
split_to = 0
reg_weights = [0.001, 0.001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


14 Oct 08:17    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
14 Oct 08:17    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
14 Oct 08:17    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
14 Oct 08:17    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
14 Oct 08:17    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
14 Oct 08:17    INFO  FISM(
  (item_src_embedding): Embedding(1683, 32, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 32, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 110339
14 Oct 08:17    INFO  FLOPs: 18944.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:   1%|▋                                                  | 1/79 [00:00<00:10,  7.19it/s]:   3%|█▎                                                 | 2/79 [00:00<00:09,  7.81it/s]:   4%|█▉                                                 | 3/79 [00:00<00:09,  8.27it/s]:   5%|██▌                                                | 4/79 [00:00<00:08,  8.43it/s]:   6%|███▏                                               | 5/79 [00:00<00:08,  8.59it/s]:   8%|███▊                                               | 6/79 [00:00<00:08,  8.38it/s]:   9%|████▌                                              | 7/79 [00:00<00:08,  8.38it/s]:  10%|█████▏                                             | 8/79 [00:00<00:08,  8.39it/s]:  11%|█████▊                                             | 9/79 [00:01<00:08,  8.52it/s]:  13%|██████▎                                           | 10/79 [00:01<00:07,  8.64it/s]:  14%|██████▉                                           | 11/79 [00:01<00:07,  8.59it/s]:  15%|███████▌                                          | 12/79 [00:01<00:07,  8.53it/s]:  16%|████████▏                                         | 13/79 [00:01<00:07,  8.57it/s]:  18%|████████▊                                         | 14/79 [00:01<00:07,  8.50it/s]:  19%|█████████▍                                        | 15/79 [00:01<00:07,  8.57it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:07,  8.64it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:07,  8.66it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:07,  8.64it/s]:  24%|████████████                                      | 19/79 [00:02<00:06,  8.62it/s]:  25%|████████████▋                                     | 20/79 [00:02<00:06,  8.43it/s]:  27%|█████████████▎                                    | 21/79 [00:02<00:06,  8.39it/s]:  28%|█████████████▉                                    | 22/79 [00:02<00:06,  8.49it/s]:  29%|██████████████▌                                   | 23/79 [00:02<00:06,  8.42it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:06,  8.23it/s]:  32%|███████████████▊                                  | 25/79 [00:03<00:08,  6.64it/s]:  33%|████████████████▍                                 | 26/79 [00:03<00:07,  6.86it/s]:  34%|█████████████████                                 | 27/79 [00:03<00:07,  6.94it/s]:  35%|█████████████████▋                                | 28/79 [00:03<00:07,  7.19it/s]:  37%|██████████████████▎                               | 29/79 [00:03<00:06,  7.49it/s]:  38%|██████████████████▉                               | 30/79 [00:03<00:06,  7.77it/s]:  39%|███████████████████▌                              | 31/79 [00:03<00:06,  7.82it/s]:  41%|████████████████████▎                             | 32/79 [00:03<00:05,  7.97it/s]:  42%|████████████████████▉                             | 33/79 [00:04<00:05,  7.96it/s]:  43%|█████████████████████▌                            | 34/79 [00:04<00:05,  8.07it/s]:  44%|██████████████████████▏                           | 35/79 [00:04<00:05,  8.23it/s]:  46%|██████████████████████▊                           | 36/79 [00:04<00:05,  8.31it/s]:  47%|███████████████████████▍                          | 37/79 [00:04<00:05,  8.33it/s]:  48%|████████████████████████                          | 38/79 [00:04<00:04,  8.42it/s]:  49%|████████████████████████▋                         | 39/79 [00:04<00:04,  8.40it/s]:  51%|█████████████████████████▎                        | 40/79 [00:04<00:05,  7.35it/s]:  52%|█████████████████████████▉                        | 41/79 [00:05<00:05,  6.56it/s]:  53%|██████████████████████████▌                       | 42/79 [00:05<00:05,  6.98it/s]:  54%|███████████████████████████▏                      | 43/79 [00:05<00:05,  6.44it/s]:  56%|███████████████████████████▊                      | 44/79 [00:05<00:05,  6.85it/s]:  57%|████████████████████████████▍                     | 45/79 [00:05<00:04,  7.24it/s]:  58%|█████████████████████████████                     | 46/79 [00:05<00:04,  7.64it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:06<00:05,  6.15it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:06<00:05,  5.79it/s]:  62%|███████████████████████████████                   | 49/79 [00:06<00:04,  6.05it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:06<00:04,  6.32it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:06<00:04,  6.77it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:06<00:03,  7.19it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:06<00:03,  7.44it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:07<00:03,  7.55it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:07<00:03,  7.73it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:07<00:03,  7.62it/s]:  72%|████████████████████████████████████              | 57/79 [00:07<00:02,  7.42it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:07<00:02,  7.77it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:07<00:03,  5.48it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:08<00:04,  4.41it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:08<00:03,  4.80it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:08<00:03,  5.44it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:08<00:02,  5.41it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:08<00:02,  5.13it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:09<00:02,  5.75it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:09<00:02,  6.32it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:09<00:01,  6.90it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:09<00:01,  7.20it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:09<00:01,  7.36it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:09<00:01,  7.14it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:09<00:01,  7.37it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:09<00:00,  7.72it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:10<00:00,  7.92it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:10<00:00,  6.16it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:10<00:00,  6.67it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:10<00:00,  7.11it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:10<00:00,  7.43it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:10<00:00,  7.77it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:10<00:00,  8.07it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:10<00:00,  7.26it/s]
14 Oct 08:17    INFO  epoch 0 training [time: 11.00s, train loss: 57.0669]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 11.79it/s]:   5%|██▌                                                | 4/79 [00:00<00:07, 10.69it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 10.47it/s]:  10%|█████▏                                             | 8/79 [00:00<00:06, 10.46it/s]:  13%|██████▎                                           | 10/79 [00:00<00:06, 10.48it/s]:  15%|███████▌                                          | 12/79 [00:01<00:06, 10.40it/s]:  18%|████████▊                                         | 14/79 [00:01<00:06, 10.47it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:06, 10.11it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:06,  9.98it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:05, 10.06it/s]:  28%|█████████████▉                                    | 22/79 [00:02<00:05, 10.23it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:05, 10.21it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:05, 10.14it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:05, 10.15it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 10.12it/s]:  41%|████████████████████▎                             | 32/79 [00:03<00:04, 10.26it/s]:  43%|█████████████████████▌                            | 34/79 [00:03<00:04, 10.32it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:04, 10.40it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 10.39it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 10.46it/s]:  53%|██████████████████████████▌                       | 42/79 [00:04<00:03, 10.40it/s]:  56%|███████████████████████████▊                      | 44/79 [00:04<00:03, 10.40it/s]:  58%|█████████████████████████████                     | 46/79 [00:04<00:03, 10.42it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:03, 10.15it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 10.21it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:05<00:02, 10.12it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:05<00:02,  9.92it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:05<00:02,  9.55it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:05<00:02,  9.32it/s]:  72%|████████████████████████████████████              | 57/79 [00:05<00:02,  9.19it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:05<00:02,  9.05it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:05<00:02,  8.93it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:02,  8.74it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:06<00:02,  8.77it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:06<00:01,  8.85it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:06<00:02,  6.48it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:06<00:02,  6.81it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:06<00:01,  7.00it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:06<00:01,  7.39it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:06<00:01,  7.72it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:07<00:01,  7.50it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:07<00:01,  7.51it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:07<00:01,  7.59it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:07<00:01,  7.91it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:07<00:00,  8.12it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:07<00:00,  8.28it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:07<00:00,  8.32it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:07<00:00,  8.30it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:08<00:00,  8.13it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:08<00:00,  8.12it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:08<00:00,  8.20it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:08<00:00,  8.27it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:08<00:00,  9.32it/s]
14 Oct 08:17    INFO  epoch 1 training [time: 8.62s, train loss: 56.6402]

[3/8] FISM: {'embedding_size': 32, 'learning_rate': 0.005, 'alpha': 0.5, 'reg_weights': [0.0001, 0.0001]}

14 Oct 08:21    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
14 Oct 08:21    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.005
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
split_to = 0
reg_weights = [0.0001, 0.0001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


14 Oct 08:21    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
14 Oct 08:21    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
14 Oct 08:21    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
14 Oct 08:21    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
14 Oct 08:21    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
14 Oct 08:21    INFO  FISM(
  (item_src_embedding): Embedding(1683, 32, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 32, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 110339
14 Oct 08:21    INFO  FLOPs: 18944.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:   1%|▋                                                  | 1/79 [00:00<00:10,  7.51it/s]:   3%|█▎                                                 | 2/79 [00:00<00:09,  7.79it/s]:   4%|█▉                                                 | 3/79 [00:00<00:09,  7.93it/s]:   5%|██▌                                                | 4/79 [00:00<00:09,  7.89it/s]:   6%|███▏                                               | 5/79 [00:00<00:09,  8.01it/s]:   8%|███▊                                               | 6/79 [00:00<00:09,  8.03it/s]:   9%|████▌                                              | 7/79 [00:00<00:08,  8.05it/s]:  10%|█████▏                                             | 8/79 [00:01<00:09,  7.86it/s]:  11%|█████▊                                             | 9/79 [00:01<00:09,  7.53it/s]:  13%|██████▎                                           | 10/79 [00:01<00:08,  7.72it/s]:  14%|██████▉                                           | 11/79 [00:01<00:08,  7.82it/s]:  15%|███████▌                                          | 12/79 [00:01<00:08,  7.94it/s]:  16%|████████▏                                         | 13/79 [00:01<00:08,  7.94it/s]:  18%|████████▊                                         | 14/79 [00:01<00:08,  7.94it/s]:  19%|█████████▍                                        | 15/79 [00:01<00:08,  7.99it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:07,  7.99it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:07,  7.98it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:07,  8.02it/s]:  24%|████████████                                      | 19/79 [00:02<00:07,  8.09it/s]:  25%|████████████▋                                     | 20/79 [00:02<00:07,  8.12it/s]:  27%|█████████████▎                                    | 21/79 [00:02<00:07,  8.08it/s]:  28%|█████████████▉                                    | 22/79 [00:02<00:07,  8.06it/s]:  29%|██████████████▌                                   | 23/79 [00:02<00:06,  8.08it/s]:  30%|███████████████▏                                  | 24/79 [00:03<00:06,  8.04it/s]:  32%|███████████████▊                                  | 25/79 [00:03<00:06,  7.98it/s]:  33%|████████████████▍                                 | 26/79 [00:03<00:06,  8.07it/s]:  34%|█████████████████                                 | 27/79 [00:03<00:06,  8.10it/s]:  35%|█████████████████▋                                | 28/79 [00:03<00:06,  8.09it/s]:  37%|██████████████████▎                               | 29/79 [00:03<00:06,  8.10it/s]:  38%|██████████████████▉                               | 30/79 [00:03<00:06,  7.82it/s]:  39%|███████████████████▌                              | 31/79 [00:03<00:06,  7.03it/s]:  41%|████████████████████▎                             | 32/79 [00:04<00:06,  7.33it/s]:  42%|████████████████████▉                             | 33/79 [00:04<00:06,  7.54it/s]:  43%|█████████████████████▌                            | 34/79 [00:04<00:06,  7.19it/s]:  44%|██████████████████████▏                           | 35/79 [00:04<00:06,  7.21it/s]:  46%|██████████████████████▊                           | 36/79 [00:04<00:05,  7.45it/s]:  47%|███████████████████████▍                          | 37/79 [00:04<00:05,  7.65it/s]:  48%|████████████████████████                          | 38/79 [00:04<00:05,  7.79it/s]:  49%|████████████████████████▋                         | 39/79 [00:04<00:05,  7.88it/s]:  51%|█████████████████████████▎                        | 40/79 [00:05<00:04,  7.94it/s]:  52%|█████████████████████████▉                        | 41/79 [00:05<00:04,  7.86it/s]:  53%|██████████████████████████▌                       | 42/79 [00:05<00:04,  7.87it/s]:  54%|███████████████████████████▏                      | 43/79 [00:05<00:04,  7.92it/s]:  56%|███████████████████████████▊                      | 44/79 [00:05<00:04,  7.96it/s]:  57%|████████████████████████████▍                     | 45/79 [00:05<00:04,  8.00it/s]:  58%|█████████████████████████████                     | 46/79 [00:05<00:04,  8.03it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:05<00:04,  8.00it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:06<00:03,  8.02it/s]:  62%|███████████████████████████████                   | 49/79 [00:06<00:03,  7.74it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:06<00:03,  7.85it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:06<00:03,  7.96it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:06<00:03,  8.01it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:06<00:03,  8.01it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:06<00:03,  8.05it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:06<00:02,  8.03it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:07<00:02,  8.08it/s]:  72%|████████████████████████████████████              | 57/79 [00:07<00:02,  8.05it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:07<00:02,  7.87it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:07<00:02,  7.93it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:07<00:02,  7.96it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:07<00:02,  7.99it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:07<00:02,  8.05it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:07<00:01,  8.03it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:08<00:01,  8.04it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:08<00:01,  8.06it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:08<00:01,  8.12it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:08<00:01,  8.11it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:08<00:01,  8.06it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:08<00:01,  7.82it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:08<00:01,  7.90it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:08<00:01,  7.95it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:09<00:00,  7.96it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:09<00:00,  7.19it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:09<00:00,  7.39it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:09<00:00,  7.55it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:09<00:00,  7.74it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:09<00:00,  7.86it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:09<00:00,  7.95it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:10<00:00,  8.10it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:10<00:00,  7.85it/s]
14 Oct 08:21    INFO  epoch 0 training [time: 10.18s, train loss: 51.0733]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 12.81it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 11.02it/s]:   8%|███▊                                               | 6/79 [00:00<00:07, 10.10it/s]:  10%|█████▏                                             | 8/79 [00:00<00:07, 10.02it/s]:  13%|██████▎                                           | 10/79 [00:00<00:06, 10.05it/s]:  15%|███████▌                                          | 12/79 [00:01<00:06, 10.08it/s]:  18%|████████▊                                         | 14/79 [00:01<00:06,  9.90it/s]:  19%|█████████▍                                        | 15/79 [00:01<00:06,  9.46it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:06,  9.18it/s]:  22%|██████████▊                                       | 17/79 [00:01<00:06,  8.87it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:07,  8.66it/s]:  24%|████████████                                      | 19/79 [00:01<00:07,  8.51it/s]:  25%|████████████▋                                     | 20/79 [00:02<00:07,  8.38it/s]:  27%|█████████████▎                                    | 21/79 [00:02<00:07,  8.28it/s]:  28%|█████████████▉                                    | 22/79 [00:02<00:06,  8.28it/s]:  29%|██████████████▌                                   | 23/79 [00:02<00:06,  8.25it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:06,  8.23it/s]:  32%|███████████████▊                                  | 25/79 [00:02<00:06,  8.25it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:06,  7.95it/s]:  34%|█████████████████                                 | 27/79 [00:02<00:06,  8.02it/s]:  35%|█████████████████▋                                | 28/79 [00:03<00:06,  8.05it/s]:  37%|██████████████████▎                               | 29/79 [00:03<00:06,  8.11it/s]:  38%|██████████████████▉                               | 30/79 [00:03<00:06,  8.02it/s]:  39%|███████████████████▌                              | 31/79 [00:03<00:05,  8.01it/s]:  41%|████████████████████▎                             | 32/79 [00:03<00:05,  8.07it/s]:  42%|████████████████████▉                             | 33/79 [00:03<00:05,  8.13it/s]:  43%|█████████████████████▌                            | 34/79 [00:03<00:05,  8.10it/s]:  44%|██████████████████████▏                           | 35/79 [00:03<00:05,  8.12it/s]:  46%|██████████████████████▊                           | 36/79 [00:04<00:05,  8.13it/s]:  47%|███████████████████████▍                          | 37/79 [00:04<00:05,  7.23it/s]:  48%|████████████████████████                          | 38/79 [00:04<00:05,  7.45it/s]:  49%|████████████████████████▋                         | 39/79 [00:04<00:05,  7.69it/s]:  51%|█████████████████████████▎                        | 40/79 [00:04<00:04,  7.85it/s]:  52%|█████████████████████████▉                        | 41/79 [00:04<00:04,  7.94it/s]:  53%|██████████████████████████▌                       | 42/79 [00:04<00:04,  8.01it/s]:  54%|███████████████████████████▏                      | 43/79 [00:05<00:04,  8.10it/s]:  56%|███████████████████████████▊                      | 44/79 [00:05<00:04,  8.10it/s]:  57%|████████████████████████████▍                     | 45/79 [00:05<00:04,  8.19it/s]:  58%|█████████████████████████████                     | 46/79 [00:05<00:04,  7.95it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:05<00:04,  7.96it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:05<00:03,  7.99it/s]:  62%|███████████████████████████████                   | 49/79 [00:05<00:03,  8.09it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:05<00:03,  8.15it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:05<00:03,  8.11it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:06<00:03,  8.14it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:06<00:03,  8.16it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:06<00:03,  8.14it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:06<00:02,  8.19it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:06<00:02,  8.21it/s]:  72%|████████████████████████████████████              | 57/79 [00:06<00:02,  8.23it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:06<00:02,  8.05it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:07<00:02,  7.68it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:07<00:02,  7.78it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:07<00:02,  7.89it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:07<00:02,  8.00it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:07<00:01,  8.05it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:07<00:01,  7.83it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:07<00:01,  7.87it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:07<00:01,  7.73it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:08<00:01,  7.75it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:08<00:01,  7.89it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:08<00:01,  7.59it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:08<00:01,  7.77it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:08<00:01,  7.84it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:08<00:00,  7.93it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:08<00:00,  8.08it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:08<00:00,  7.86it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:09<00:00,  7.87it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:09<00:00,  7.24it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:09<00:00,  7.50it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:09<00:00,  7.67it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:09<00:00,  7.91it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:09<00:00,  8.22it/s]
14 Oct 08:21    INFO  epoch 1 training [time: 9.74s, train loss: 49.2472]

[4/8] FISM: {'embedding_size': 32, 'learning_rate': 0.005, 'alpha': 0.5, 'reg_weights': [0.001, 0.001]}

14 Oct 08:25    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
14 Oct 08:25    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.005
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
split_to = 0
reg_weights = [0.001, 0.001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


14 Oct 08:25    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
14 Oct 08:25    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
14 Oct 08:25    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
14 Oct 08:25    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
14 Oct 08:25    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
14 Oct 08:25    INFO  FISM(
  (item_src_embedding): Embedding(1683, 32, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 32, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 110339
14 Oct 08:25    INFO  FLOPs: 18944.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:   1%|▋                                                  | 1/79 [00:00<00:10,  7.78it/s]:   3%|█▎                                                 | 2/79 [00:00<00:09,  8.04it/s]:   4%|█▉                                                 | 3/79 [00:00<00:09,  8.12it/s]:   5%|██▌                                                | 4/79 [00:00<00:09,  8.25it/s]:   6%|███▏                                               | 5/79 [00:00<00:08,  8.26it/s]:   8%|███▊                                               | 6/79 [00:00<00:08,  8.26it/s]:   9%|████▌                                              | 7/79 [00:00<00:08,  8.34it/s]:  10%|█████▏                                             | 8/79 [00:00<00:08,  8.29it/s]:  11%|█████▊                                             | 9/79 [00:01<00:08,  8.26it/s]:  13%|██████▎                                           | 10/79 [00:01<00:08,  8.27it/s]:  14%|██████▉                                           | 11/79 [00:01<00:08,  8.24it/s]:  15%|███████▌                                          | 12/79 [00:01<00:09,  7.24it/s]:  16%|████████▏                                         | 13/79 [00:01<00:08,  7.52it/s]:  18%|████████▊                                         | 14/79 [00:01<00:08,  7.77it/s]:  19%|█████████▍                                        | 15/79 [00:01<00:08,  7.80it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:07,  7.89it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:07,  8.04it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:07,  8.08it/s]:  24%|████████████                                      | 19/79 [00:02<00:07,  8.06it/s]:  25%|████████████▋                                     | 20/79 [00:02<00:07,  8.11it/s]:  27%|█████████████▎                                    | 21/79 [00:02<00:07,  8.14it/s]:  28%|█████████████▉                                    | 22/79 [00:02<00:07,  8.09it/s]:  29%|██████████████▌                                   | 23/79 [00:02<00:06,  8.15it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:06,  8.22it/s]:  32%|███████████████▊                                  | 25/79 [00:03<00:06,  8.24it/s]:  33%|████████████████▍                                 | 26/79 [00:03<00:06,  8.27it/s]:  34%|█████████████████                                 | 27/79 [00:03<00:06,  8.23it/s]:  35%|█████████████████▋                                | 28/79 [00:03<00:06,  8.23it/s]:  37%|██████████████████▎                               | 29/79 [00:03<00:06,  8.22it/s]:  38%|██████████████████▉                               | 30/79 [00:03<00:05,  8.23it/s]:  39%|███████████████████▌                              | 31/79 [00:03<00:05,  8.23it/s]:  41%|████████████████████▎                             | 32/79 [00:03<00:05,  8.07it/s]:  42%|████████████████████▉                             | 33/79 [00:04<00:05,  7.99it/s]:  43%|█████████████████████▌                            | 34/79 [00:04<00:05,  8.08it/s]:  44%|██████████████████████▏                           | 35/79 [00:04<00:05,  8.14it/s]:  46%|██████████████████████▊                           | 36/79 [00:04<00:05,  8.17it/s]:  47%|███████████████████████▍                          | 37/79 [00:04<00:05,  8.23it/s]:  48%|████████████████████████                          | 38/79 [00:04<00:04,  8.28it/s]:  49%|████████████████████████▋                         | 39/79 [00:04<00:04,  8.28it/s]:  51%|█████████████████████████▎                        | 40/79 [00:04<00:04,  8.28it/s]:  52%|█████████████████████████▉                        | 41/79 [00:05<00:04,  8.26it/s]:  53%|██████████████████████████▌                       | 42/79 [00:05<00:04,  8.00it/s]:  54%|███████████████████████████▏                      | 43/79 [00:05<00:04,  7.65it/s]:  56%|███████████████████████████▊                      | 44/79 [00:05<00:04,  7.83it/s]:  57%|████████████████████████████▍                     | 45/79 [00:05<00:04,  7.91it/s]:  58%|█████████████████████████████                     | 46/79 [00:05<00:04,  8.02it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:05<00:03,  8.03it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:05<00:03,  8.07it/s]:  62%|███████████████████████████████                   | 49/79 [00:06<00:03,  8.12it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:06<00:03,  8.17it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:06<00:03,  8.21it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:06<00:03,  8.24it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:06<00:03,  8.26it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:06<00:03,  7.34it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:06<00:03,  7.60it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:06<00:02,  7.81it/s]:  72%|████████████████████████████████████              | 57/79 [00:07<00:02,  7.92it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:07<00:02,  8.06it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:07<00:02,  8.11it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:07<00:02,  8.13it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:07<00:02,  7.91it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:07<00:02,  7.95it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:07<00:02,  7.99it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:07<00:01,  8.02it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:08<00:01,  8.04it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:08<00:01,  7.88it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:08<00:01,  7.96it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:08<00:01,  7.97it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:08<00:01,  8.04it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:08<00:01,  8.12it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:08<00:00,  8.17it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:08<00:00,  8.25it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:09<00:00,  8.17it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:09<00:00,  8.14it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:09<00:00,  7.90it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:09<00:00,  7.99it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:09<00:00,  8.04it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:09<00:00,  8.08it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:09<00:00,  8.18it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:09<00:00,  8.03it/s]
14 Oct 08:25    INFO  epoch 0 training [time: 9.96s, train loss: 56.3302]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 12.20it/s]:   5%|██▌                                                | 4/79 [00:00<00:07, 10.33it/s]:   8%|███▊                                               | 6/79 [00:00<00:07, 10.13it/s]:  10%|█████▏                                             | 8/79 [00:00<00:07, 10.12it/s]:  13%|██████▎                                           | 10/79 [00:00<00:06, 10.16it/s]:  15%|███████▌                                          | 12/79 [00:01<00:06, 10.13it/s]:  18%|████████▊                                         | 14/79 [00:01<00:06, 10.13it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:06, 10.20it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 10.23it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:05, 10.23it/s]:  28%|█████████████▉                                    | 22/79 [00:02<00:05,  9.51it/s]:  29%|██████████████▌                                   | 23/79 [00:02<00:06,  9.24it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:06,  8.85it/s]:  32%|███████████████▊                                  | 25/79 [00:02<00:06,  8.73it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:06,  8.38it/s]:  34%|█████████████████                                 | 27/79 [00:02<00:06,  8.39it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:06,  8.39it/s]:  37%|██████████████████▎                               | 29/79 [00:03<00:05,  8.38it/s]:  38%|██████████████████▉                               | 30/79 [00:03<00:05,  8.34it/s]:  39%|███████████████████▌                              | 31/79 [00:03<00:05,  8.33it/s]:  41%|████████████████████▎                             | 32/79 [00:03<00:05,  8.33it/s]:  42%|████████████████████▉                             | 33/79 [00:03<00:05,  8.30it/s]:  43%|█████████████████████▌                            | 34/79 [00:03<00:05,  8.30it/s]:  44%|██████████████████████▏                           | 35/79 [00:03<00:05,  8.29it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:05,  8.32it/s]:  47%|███████████████████████▍                          | 37/79 [00:04<00:05,  8.30it/s]:  48%|████████████████████████                          | 38/79 [00:04<00:04,  8.30it/s]:  49%|████████████████████████▋                         | 39/79 [00:04<00:04,  8.19it/s]:  51%|█████████████████████████▎                        | 40/79 [00:04<00:04,  8.17it/s]:  52%|█████████████████████████▉                        | 41/79 [00:04<00:04,  8.04it/s]:  53%|██████████████████████████▌                       | 42/79 [00:04<00:04,  8.09it/s]:  54%|███████████████████████████▏                      | 43/79 [00:04<00:04,  8.10it/s]:  56%|███████████████████████████▊                      | 44/79 [00:04<00:04,  8.09it/s]:  57%|████████████████████████████▍                     | 45/79 [00:05<00:04,  8.17it/s]:  58%|█████████████████████████████                     | 46/79 [00:05<00:04,  7.86it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:05<00:04,  8.00it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:05<00:03,  8.07it/s]:  62%|███████████████████████████████                   | 49/79 [00:05<00:03,  8.09it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:05<00:03,  8.12it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:05<00:03,  8.19it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:05<00:03,  8.14it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:06<00:03,  8.16it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:06<00:03,  8.20it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:06<00:02,  8.24it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:06<00:02,  8.19it/s]:  72%|████████████████████████████████████              | 57/79 [00:06<00:02,  8.20it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:06<00:02,  8.01it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:06<00:02,  7.98it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:06<00:02,  8.00it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:06<00:02,  8.02it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:07<00:02,  8.05it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:07<00:02,  7.30it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:07<00:01,  7.57it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:07<00:01,  7.74it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:07<00:01,  7.85it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:07<00:01,  7.98it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:07<00:01,  8.03it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:08<00:01,  7.74it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:08<00:01,  7.84it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:08<00:01,  7.92it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:08<00:00,  8.02it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:08<00:00,  8.12it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:08<00:00,  8.13it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:08<00:00,  7.99it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:08<00:00,  8.04it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:09<00:00,  8.13it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:09<00:00,  8.16it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:09<00:00,  8.26it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:09<00:00,  8.49it/s]
14 Oct 08:25    INFO  epoch 1 training [time: 9.40s, train loss: 54.7612]

[5/8] FISM: {'embedding_size': 64, 'learning_rate': 0.001, 'alpha': 0.5, 'reg_weights': [0.0001, 0.0001]}

14 Oct 08:28    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
14 Oct 08:28    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
split_to = 0
reg_weights = [0.0001, 0.0001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


14 Oct 08:28    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
14 Oct 08:28    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
14 Oct 08:28    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
14 Oct 08:28    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
14 Oct 08:28    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
14 Oct 08:28    INFO  FISM(
  (item_src_embedding): Embedding(1683, 64, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 64, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 218051
14 Oct 08:28    INFO  FLOPs: 37888.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:   1%|▋                                                  | 1/79 [00:00<00:16,  4.66it/s]:   3%|█▎                                                 | 2/79 [00:00<00:14,  5.30it/s]:   4%|█▉                                                 | 3/79 [00:00<00:13,  5.56it/s]:   5%|██▌                                                | 4/79 [00:00<00:13,  5.58it/s]:   6%|███▏                                               | 5/79 [00:00<00:12,  5.69it/s]:   8%|███▊                                               | 6/79 [00:01<00:12,  5.66it/s]:   9%|████▌                                              | 7/79 [00:01<00:12,  5.79it/s]:  10%|█████▏                                             | 8/79 [00:01<00:12,  5.87it/s]:  11%|█████▊                                             | 9/79 [00:01<00:11,  5.95it/s]:  13%|██████▎                                           | 10/79 [00:01<00:11,  5.81it/s]:  14%|██████▉                                           | 11/79 [00:01<00:11,  5.89it/s]:  15%|███████▌                                          | 12/79 [00:02<00:11,  5.94it/s]:  16%|████████▏                                         | 13/79 [00:02<00:11,  5.97it/s]:  18%|████████▊                                         | 14/79 [00:02<00:10,  6.01it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:10,  6.02it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:10,  5.93it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:10,  5.91it/s]:  23%|███████████▍                                      | 18/79 [00:03<00:10,  5.96it/s]:  24%|████████████                                      | 19/79 [00:03<00:09,  6.00it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:09,  6.07it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:09,  6.12it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:09,  6.18it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:09,  6.20it/s]:  30%|███████████████▏                                  | 24/79 [00:04<00:08,  6.21it/s]:  32%|███████████████▊                                  | 25/79 [00:04<00:08,  6.04it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:08,  6.07it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:08,  6.10it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:08,  6.10it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:08,  6.02it/s]:  38%|██████████████████▉                               | 30/79 [00:05<00:08,  5.99it/s]:  39%|███████████████████▌                              | 31/79 [00:05<00:07,  6.00it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:07,  6.01it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:07,  6.00it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:07,  5.99it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:07,  5.99it/s]:  46%|██████████████████████▊                           | 36/79 [00:06<00:07,  6.00it/s]:  47%|███████████████████████▍                          | 37/79 [00:06<00:06,  6.02it/s]:  48%|████████████████████████                          | 38/79 [00:06<00:06,  6.01it/s]:  49%|████████████████████████▋                         | 39/79 [00:06<00:06,  6.02it/s]:  51%|█████████████████████████▎                        | 40/79 [00:06<00:06,  5.99it/s]:  52%|█████████████████████████▉                        | 41/79 [00:06<00:06,  5.97it/s]:  53%|██████████████████████████▌                       | 42/79 [00:07<00:06,  5.31it/s]:  54%|███████████████████████████▏                      | 43/79 [00:07<00:06,  5.50it/s]:  56%|███████████████████████████▊                      | 44/79 [00:07<00:06,  5.64it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:05,  5.75it/s]:  58%|█████████████████████████████                     | 46/79 [00:07<00:05,  5.79it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:07<00:05,  5.85it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:08<00:05,  5.86it/s]:  62%|███████████████████████████████                   | 49/79 [00:08<00:05,  5.88it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:08<00:04,  5.87it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:08<00:04,  5.91it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:08<00:04,  5.88it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:08<00:04,  5.88it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:09<00:04,  5.81it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:09<00:04,  5.84it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:09<00:03,  5.86it/s]:  72%|████████████████████████████████████              | 57/79 [00:09<00:03,  5.71it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:09<00:03,  5.74it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:10<00:03,  5.79it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:10<00:03,  5.84it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:10<00:03,  5.87it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:10<00:02,  5.88it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:10<00:02,  5.89it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:10<00:02,  5.90it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:11<00:02,  5.90it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:11<00:02,  5.87it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:11<00:02,  5.83it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:11<00:01,  5.85it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:11<00:01,  5.85it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:11<00:01,  5.88it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:12<00:01,  5.78it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:12<00:01,  5.81it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:12<00:01,  5.83it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:12<00:00,  5.77it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:12<00:00,  5.83it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:12<00:00,  5.86it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:13<00:00,  5.88it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:13<00:00,  5.89it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  5.97it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  5.86it/s]
14 Oct 08:29    INFO  epoch 0 training [time: 13.62s, train loss: 54.1027]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:10,  7.21it/s]:   3%|█▎                                                 | 2/79 [00:00<00:12,  6.17it/s]:   4%|█▉                                                 | 3/79 [00:00<00:12,  5.98it/s]:   5%|██▌                                                | 4/79 [00:00<00:13,  5.69it/s]:   6%|███▏                                               | 5/79 [00:00<00:12,  5.74it/s]:   8%|███▊                                               | 6/79 [00:01<00:12,  5.79it/s]:   9%|████▌                                              | 7/79 [00:01<00:12,  5.83it/s]:  10%|█████▏                                             | 8/79 [00:01<00:12,  5.87it/s]:  11%|█████▊                                             | 9/79 [00:01<00:11,  5.87it/s]:  13%|██████▎                                           | 10/79 [00:01<00:11,  5.88it/s]:  14%|██████▉                                           | 11/79 [00:01<00:11,  5.86it/s]:  15%|███████▌                                          | 12/79 [00:02<00:11,  5.84it/s]:  16%|████████▏                                         | 13/79 [00:02<00:11,  5.87it/s]:  18%|████████▊                                         | 14/79 [00:02<00:11,  5.90it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:10,  5.93it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:10,  5.92it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:10,  5.89it/s]:  23%|███████████▍                                      | 18/79 [00:03<00:10,  5.89it/s]:  24%|████████████                                      | 19/79 [00:03<00:10,  5.87it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:10,  5.90it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:09,  5.89it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:09,  5.73it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:09,  5.65it/s]:  30%|███████████████▏                                  | 24/79 [00:04<00:09,  5.64it/s]:  32%|███████████████▊                                  | 25/79 [00:04<00:09,  5.68it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:09,  5.73it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:08,  5.78it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:08,  5.82it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:08,  5.86it/s]:  38%|██████████████████▉                               | 30/79 [00:05<00:08,  5.87it/s]:  39%|███████████████████▌                              | 31/79 [00:05<00:08,  5.87it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:08,  5.85it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:07,  5.85it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:07,  5.91it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:07,  5.83it/s]:  46%|██████████████████████▊                           | 36/79 [00:06<00:07,  5.85it/s]:  47%|███████████████████████▍                          | 37/79 [00:06<00:07,  5.69it/s]:  48%|████████████████████████                          | 38/79 [00:06<00:07,  5.77it/s]:  49%|████████████████████████▋                         | 39/79 [00:06<00:06,  5.77it/s]:  51%|█████████████████████████▎                        | 40/79 [00:06<00:07,  5.36it/s]:  52%|█████████████████████████▉                        | 41/79 [00:07<00:06,  5.49it/s]:  53%|██████████████████████████▌                       | 42/79 [00:07<00:06,  5.47it/s]:  54%|███████████████████████████▏                      | 43/79 [00:07<00:06,  5.61it/s]:  56%|███████████████████████████▊                      | 44/79 [00:07<00:06,  5.71it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:05,  5.75it/s]:  58%|█████████████████████████████                     | 46/79 [00:07<00:05,  5.79it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:08<00:05,  5.81it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:08<00:05,  5.78it/s]:  62%|███████████████████████████████                   | 49/79 [00:08<00:05,  5.83it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:08<00:05,  5.69it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:08<00:04,  5.76it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:08<00:04,  5.80it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:09<00:04,  5.80it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:09<00:04,  5.82it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:09<00:04,  5.81it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:09<00:03,  5.88it/s]:  72%|████████████████████████████████████              | 57/79 [00:09<00:03,  5.84it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:09<00:03,  5.91it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:10<00:03,  5.92it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:10<00:03,  5.71it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:10<00:03,  5.78it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:10<00:02,  5.82it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:10<00:02,  5.85it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:11<00:02,  5.85it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:11<00:02,  5.89it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:11<00:02,  5.90it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:11<00:02,  5.90it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:11<00:01,  5.89it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:11<00:01,  5.78it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:12<00:01,  5.61it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:12<00:01,  5.68it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:12<00:01,  5.45it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:12<00:01,  5.61it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:12<00:00,  5.68it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:12<00:00,  5.70it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:13<00:00,  5.74it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:13<00:00,  5.81it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:13<00:00,  5.84it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  5.49it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  5.76it/s]
14 Oct 08:29    INFO  epoch 1 training [time: 13.82s, train loss: 49.6136]

[6/8] FISM: {'embedding_size': 64, 'learning_rate': 0.001, 'alpha': 0.5, 'reg_weights': [0.001, 0.001]}

14 Oct 08:33    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
14 Oct 08:33    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
split_to = 0
reg_weights = [0.001, 0.001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


14 Oct 08:33    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
14 Oct 08:33    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
14 Oct 08:33    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
14 Oct 08:33    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
14 Oct 08:33    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
14 Oct 08:33    INFO  FISM(
  (item_src_embedding): Embedding(1683, 64, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 64, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 218051
14 Oct 08:33    INFO  FLOPs: 37888.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:   1%|▋                                                  | 1/79 [00:00<00:18,  4.32it/s]:   3%|█▎                                                 | 2/79 [00:00<00:14,  5.15it/s]:   4%|█▉                                                 | 3/79 [00:00<00:16,  4.73it/s]:   5%|██▌                                                | 4/79 [00:00<00:14,  5.10it/s]:   6%|███▏                                               | 5/79 [00:00<00:14,  5.24it/s]:   8%|███▊                                               | 6/79 [00:01<00:13,  5.31it/s]:   9%|████▌                                              | 7/79 [00:01<00:13,  5.47it/s]:  10%|█████▏                                             | 8/79 [00:01<00:12,  5.58it/s]:  11%|█████▊                                             | 9/79 [00:01<00:12,  5.68it/s]:  13%|██████▎                                           | 10/79 [00:01<00:12,  5.71it/s]:  14%|██████▉                                           | 11/79 [00:02<00:11,  5.72it/s]:  15%|███████▌                                          | 12/79 [00:02<00:11,  5.78it/s]:  16%|████████▏                                         | 13/79 [00:02<00:11,  5.79it/s]:  18%|████████▊                                         | 14/79 [00:02<00:11,  5.79it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:11,  5.80it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:10,  5.78it/s]:  22%|██████████▊                                       | 17/79 [00:03<00:10,  5.78it/s]:  23%|███████████▍                                      | 18/79 [00:03<00:10,  5.75it/s]:  24%|████████████                                      | 19/79 [00:03<00:10,  5.78it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:10,  5.80it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:09,  5.81it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:09,  5.84it/s]:  29%|██████████████▌                                   | 23/79 [00:04<00:09,  5.71it/s]:  30%|███████████████▏                                  | 24/79 [00:04<00:09,  5.74it/s]:  32%|███████████████▊                                  | 25/79 [00:04<00:09,  5.79it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:09,  5.65it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:09,  5.73it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:08,  5.74it/s]:  37%|██████████████████▎                               | 29/79 [00:05<00:08,  5.75it/s]:  38%|██████████████████▉                               | 30/79 [00:05<00:08,  5.77it/s]:  39%|███████████████████▌                              | 31/79 [00:05<00:08,  5.77it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:08,  5.78it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:07,  5.78it/s]:  43%|█████████████████████▌                            | 34/79 [00:06<00:07,  5.79it/s]:  44%|██████████████████████▏                           | 35/79 [00:06<00:07,  5.73it/s]:  46%|██████████████████████▊                           | 36/79 [00:06<00:07,  5.75it/s]:  47%|███████████████████████▍                          | 37/79 [00:06<00:07,  5.78it/s]:  48%|████████████████████████                          | 38/79 [00:06<00:07,  5.77it/s]:  49%|████████████████████████▋                         | 39/79 [00:06<00:06,  5.79it/s]:  51%|█████████████████████████▎                        | 40/79 [00:07<00:06,  5.78it/s]:  52%|█████████████████████████▉                        | 41/79 [00:07<00:06,  5.80it/s]:  53%|██████████████████████████▌                       | 42/79 [00:07<00:06,  5.82it/s]:  54%|███████████████████████████▏                      | 43/79 [00:07<00:06,  5.83it/s]:  56%|███████████████████████████▊                      | 44/79 [00:07<00:05,  5.86it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:06,  5.38it/s]:  58%|█████████████████████████████                     | 46/79 [00:08<00:06,  5.50it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:08<00:05,  5.55it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:08<00:05,  5.62it/s]:  62%|███████████████████████████████                   | 49/79 [00:08<00:05,  5.67it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:08<00:05,  5.73it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:08<00:04,  5.76it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:09<00:04,  5.80it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:09<00:04,  5.73it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:09<00:04,  5.74it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:09<00:04,  5.80it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:09<00:03,  5.81it/s]:  72%|████████████████████████████████████              | 57/79 [00:10<00:03,  5.81it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:10<00:03,  5.83it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:10<00:03,  5.81it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:10<00:03,  5.79it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:10<00:03,  5.77it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:10<00:02,  5.81it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:11<00:02,  5.85it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:11<00:02,  5.83it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:11<00:02,  5.84it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:11<00:02,  5.82it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:11<00:02,  5.86it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:11<00:01,  5.85it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:12<00:01,  5.91it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:12<00:01,  5.89it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:12<00:01,  5.72it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:12<00:01,  5.74it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:12<00:01,  5.75it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:12<00:00,  5.76it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:13<00:00,  5.73it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:13<00:00,  5.67it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:13<00:00,  5.72it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:13<00:00,  5.69it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  5.81it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  5.70it/s]
14 Oct 08:34    INFO  epoch 0 training [time: 13.97s, train loss: 57.0899]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:10,  7.65it/s]:   3%|█▎                                                 | 2/79 [00:00<00:14,  5.47it/s]:   4%|█▉                                                 | 3/79 [00:00<00:13,  5.64it/s]:   5%|██▌                                                | 4/79 [00:00<00:13,  5.69it/s]:   6%|███▏                                               | 5/79 [00:00<00:12,  5.70it/s]:   8%|███▊                                               | 6/79 [00:01<00:12,  5.78it/s]:   9%|████▌                                              | 7/79 [00:01<00:12,  5.83it/s]:  10%|█████▏                                             | 8/79 [00:01<00:12,  5.86it/s]:  11%|█████▊                                             | 9/79 [00:01<00:12,  5.72it/s]:  13%|██████▎                                           | 10/79 [00:01<00:11,  5.77it/s]:  14%|██████▉                                           | 11/79 [00:01<00:11,  5.69it/s]:  15%|███████▌                                          | 12/79 [00:02<00:11,  5.74it/s]:  16%|████████▏                                         | 13/79 [00:02<00:11,  5.77it/s]:  18%|████████▊                                         | 14/79 [00:02<00:11,  5.82it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:10,  5.84it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:10,  5.82it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:10,  5.76it/s]:  23%|███████████▍                                      | 18/79 [00:03<00:10,  5.80it/s]:  24%|████████████                                      | 19/79 [00:03<00:10,  5.84it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:10,  5.86it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:09,  5.86it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:09,  5.88it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:09,  5.89it/s]:  30%|███████████████▏                                  | 24/79 [00:04<00:09,  5.88it/s]:  32%|███████████████▊                                  | 25/79 [00:04<00:09,  5.90it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:09,  5.68it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:09,  5.73it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:08,  5.68it/s]:  37%|██████████████████▎                               | 29/79 [00:05<00:08,  5.70it/s]:  38%|██████████████████▉                               | 30/79 [00:05<00:08,  5.78it/s]:  39%|███████████████████▌                              | 31/79 [00:05<00:08,  5.82it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:08,  5.86it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:07,  5.92it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:07,  5.90it/s]:  44%|██████████████████████▏                           | 35/79 [00:06<00:07,  5.88it/s]:  46%|██████████████████████▊                           | 36/79 [00:06<00:07,  5.88it/s]:  47%|███████████████████████▍                          | 37/79 [00:06<00:07,  5.87it/s]:  48%|████████████████████████                          | 38/79 [00:06<00:06,  5.89it/s]:  49%|████████████████████████▋                         | 39/79 [00:06<00:06,  5.92it/s]:  51%|█████████████████████████▎                        | 40/79 [00:06<00:06,  5.74it/s]:  52%|█████████████████████████▉                        | 41/79 [00:07<00:06,  5.77it/s]:  53%|██████████████████████████▌                       | 42/79 [00:07<00:06,  5.81it/s]:  54%|███████████████████████████▏                      | 43/79 [00:07<00:06,  5.36it/s]:  56%|███████████████████████████▊                      | 44/79 [00:07<00:06,  5.53it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:06,  5.62it/s]:  58%|█████████████████████████████                     | 46/79 [00:07<00:05,  5.74it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:08<00:05,  5.83it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:08<00:05,  5.86it/s]:  62%|███████████████████████████████                   | 49/79 [00:08<00:05,  5.88it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:08<00:04,  5.89it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:08<00:04,  5.92it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:08<00:04,  5.91it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:09<00:04,  5.87it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:09<00:04,  5.90it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:09<00:04,  5.90it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:09<00:03,  5.93it/s]:  72%|████████████████████████████████████              | 57/79 [00:09<00:03,  5.94it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:09<00:03,  5.94it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:10<00:03,  5.79it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:10<00:03,  5.81it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:10<00:03,  5.92it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:10<00:02,  5.89it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:10<00:02,  5.90it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:10<00:02,  5.89it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:11<00:02,  5.80it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:11<00:02,  5.82it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:11<00:02,  5.84it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:11<00:01,  5.85it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:11<00:01,  5.86it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:12<00:01,  5.88it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:12<00:01,  5.88it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:12<00:01,  5.89it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:12<00:01,  5.90it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:12<00:00,  5.87it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:12<00:00,  5.76it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:13<00:00,  5.79it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:13<00:00,  5.79it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:13<00:00,  5.83it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  5.91it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  5.81it/s]
14 Oct 08:34    INFO  epoch 1 training [time: 13.73s, train loss: 56.6408]

[7/8] FISM: {'embedding_size': 64, 'learning_rate': 0.005, 'alpha': 0.5, 'reg_weights': [0.0001, 0.0001]}

14 Oct 08:46    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
14 Oct 08:46    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.005
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
split_to = 0
reg_weights = [0.0001, 0.0001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


14 Oct 08:47    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
14 Oct 08:47    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
14 Oct 08:47    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
14 Oct 08:47    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
14 Oct 08:47    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
14 Oct 08:47    INFO  FISM(
  (item_src_embedding): Embedding(1683, 64, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 64, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 218051
14 Oct 08:47    INFO  FLOPs: 37888.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:   1%|▋                                                  | 1/79 [00:00<00:19,  3.91it/s]:   3%|█▎                                                 | 2/79 [00:00<00:16,  4.69it/s]:   4%|█▉                                                 | 3/79 [00:00<00:16,  4.60it/s]:   5%|██▌                                                | 4/79 [00:00<00:15,  4.97it/s]:   6%|███▏                                               | 5/79 [00:01<00:14,  5.26it/s]:   8%|███▊                                               | 6/79 [00:01<00:13,  5.47it/s]:   9%|████▌                                              | 7/79 [00:01<00:13,  5.53it/s]:  10%|█████▏                                             | 8/79 [00:01<00:12,  5.61it/s]:  11%|█████▊                                             | 9/79 [00:01<00:12,  5.69it/s]:  13%|██████▎                                           | 10/79 [00:01<00:12,  5.71it/s]:  14%|██████▉                                           | 11/79 [00:02<00:11,  5.74it/s]:  15%|███████▌                                          | 12/79 [00:02<00:11,  5.77it/s]:  16%|████████▏                                         | 13/79 [00:02<00:11,  5.70it/s]:  18%|████████▊                                         | 14/79 [00:02<00:11,  5.65it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:11,  5.66it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:11,  5.59it/s]:  22%|██████████▊                                       | 17/79 [00:03<00:11,  5.61it/s]:  23%|███████████▍                                      | 18/79 [00:03<00:10,  5.58it/s]:  24%|████████████                                      | 19/79 [00:03<00:11,  5.05it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:11,  5.19it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:11,  5.22it/s]:  28%|█████████████▉                                    | 22/79 [00:04<00:11,  5.10it/s]:  29%|██████████████▌                                   | 23/79 [00:04<00:11,  5.08it/s]:  30%|███████████████▏                                  | 24/79 [00:04<00:10,  5.15it/s]:  32%|███████████████▊                                  | 25/79 [00:04<00:10,  5.33it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:09,  5.43it/s]:  34%|█████████████████                                 | 27/79 [00:05<00:09,  5.57it/s]:  35%|█████████████████▋                                | 28/79 [00:05<00:09,  5.66it/s]:  37%|██████████████████▎                               | 29/79 [00:05<00:08,  5.63it/s]:  38%|██████████████████▉                               | 30/79 [00:05<00:08,  5.65it/s]:  39%|███████████████████▌                              | 31/79 [00:05<00:08,  5.74it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:08,  5.74it/s]:  42%|████████████████████▉                             | 33/79 [00:06<00:08,  5.74it/s]:  43%|█████████████████████▌                            | 34/79 [00:06<00:07,  5.79it/s]:  44%|██████████████████████▏                           | 35/79 [00:06<00:08,  5.31it/s]:  46%|██████████████████████▊                           | 36/79 [00:06<00:07,  5.44it/s]:  47%|███████████████████████▍                          | 37/79 [00:06<00:07,  5.58it/s]:  48%|████████████████████████                          | 38/79 [00:06<00:07,  5.55it/s]:  49%|████████████████████████▋                         | 39/79 [00:07<00:07,  5.59it/s]:  51%|█████████████████████████▎                        | 40/79 [00:07<00:06,  5.64it/s]:  52%|█████████████████████████▉                        | 41/79 [00:07<00:06,  5.55it/s]:  53%|██████████████████████████▌                       | 42/79 [00:07<00:06,  5.67it/s]:  54%|███████████████████████████▏                      | 43/79 [00:07<00:06,  5.73it/s]:  56%|███████████████████████████▊                      | 44/79 [00:08<00:06,  5.77it/s]:  57%|████████████████████████████▍                     | 45/79 [00:08<00:05,  5.79it/s]:  58%|█████████████████████████████                     | 46/79 [00:08<00:05,  5.80it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:08<00:05,  5.73it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:08<00:05,  5.77it/s]:  62%|███████████████████████████████                   | 49/79 [00:08<00:05,  5.81it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:09<00:05,  5.34it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:09<00:05,  5.49it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:09<00:04,  5.60it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:09<00:04,  5.62it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:09<00:04,  5.66it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:09<00:04,  5.72it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:10<00:03,  5.76it/s]:  72%|████████████████████████████████████              | 57/79 [00:10<00:03,  5.79it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:10<00:03,  5.62it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:10<00:03,  5.34it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:10<00:03,  5.48it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:11<00:03,  5.60it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:11<00:03,  5.65it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:11<00:02,  5.74it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:11<00:02,  5.76it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:11<00:02,  5.80it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:11<00:02,  5.38it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:12<00:02,  5.54it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:12<00:01,  5.61it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:12<00:01,  5.67it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:12<00:01,  5.74it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:12<00:01,  5.74it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:12<00:01,  5.79it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:13<00:01,  5.81it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:13<00:00,  5.79it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:13<00:00,  5.80it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:13<00:00,  5.80it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:13<00:00,  5.36it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:14<00:00,  5.49it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:14<00:00,  5.52it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:14<00:00,  5.53it/s]
14 Oct 08:47    INFO  epoch 0 training [time: 14.38s, train loss: 50.7567]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:09,  7.87it/s]:   3%|█▎                                                 | 2/79 [00:00<00:14,  5.47it/s]:   4%|█▉                                                 | 3/79 [00:00<00:13,  5.45it/s]:   5%|██▌                                                | 4/79 [00:00<00:13,  5.46it/s]:   6%|███▏                                               | 5/79 [00:00<00:13,  5.38it/s]:   8%|███▊                                               | 6/79 [00:01<00:16,  4.40it/s]:   9%|████▌                                              | 7/79 [00:01<00:15,  4.57it/s]:  10%|█████▏                                             | 8/79 [00:01<00:14,  4.81it/s]:  11%|█████▊                                             | 9/79 [00:01<00:13,  5.04it/s]:  13%|██████▎                                           | 10/79 [00:01<00:13,  5.17it/s]:  14%|██████▉                                           | 11/79 [00:02<00:13,  5.22it/s]:  15%|███████▌                                          | 12/79 [00:02<00:12,  5.37it/s]:  16%|████████▏                                         | 13/79 [00:02<00:12,  5.22it/s]:  18%|████████▊                                         | 14/79 [00:03<00:21,  3.07it/s]:  19%|█████████▍                                        | 15/79 [00:03<00:19,  3.32it/s]:  20%|██████████▏                                       | 16/79 [00:03<00:18,  3.36it/s]:  22%|██████████▊                                       | 17/79 [00:03<00:16,  3.77it/s]:  23%|███████████▍                                      | 18/79 [00:04<00:14,  4.14it/s]:  24%|████████████                                      | 19/79 [00:04<00:15,  3.86it/s]:  25%|████████████▋                                     | 20/79 [00:04<00:13,  4.23it/s]:  27%|█████████████▎                                    | 21/79 [00:04<00:12,  4.56it/s]:  28%|█████████████▉                                    | 22/79 [00:04<00:11,  4.80it/s]:  29%|██████████████▌                                   | 23/79 [00:05<00:12,  4.38it/s]:  30%|███████████████▏                                  | 24/79 [00:05<00:14,  3.89it/s]:  32%|███████████████▊                                  | 25/79 [00:05<00:13,  4.12it/s]:  33%|████████████████▍                                 | 26/79 [00:05<00:12,  4.41it/s]:  34%|█████████████████                                 | 27/79 [00:06<00:11,  4.72it/s]:  35%|█████████████████▋                                | 28/79 [00:06<00:10,  4.92it/s]:  37%|██████████████████▎                               | 29/79 [00:06<00:09,  5.16it/s]:  38%|██████████████████▉                               | 30/79 [00:06<00:09,  4.90it/s]:  39%|███████████████████▌                              | 31/79 [00:06<00:09,  5.09it/s]:  41%|████████████████████▎                             | 32/79 [00:07<00:08,  5.32it/s]:  42%|████████████████████▉                             | 33/79 [00:07<00:08,  5.47it/s]:  43%|█████████████████████▌                            | 34/79 [00:07<00:08,  5.51it/s]:  44%|██████████████████████▏                           | 35/79 [00:07<00:08,  5.30it/s]:  46%|██████████████████████▊                           | 36/79 [00:07<00:07,  5.47it/s]:  47%|███████████████████████▍                          | 37/79 [00:07<00:07,  5.45it/s]:  48%|████████████████████████                          | 38/79 [00:08<00:07,  5.13it/s]:  49%|████████████████████████▋                         | 39/79 [00:08<00:07,  5.21it/s]:  51%|█████████████████████████▎                        | 40/79 [00:08<00:07,  5.31it/s]:  52%|█████████████████████████▉                        | 41/79 [00:08<00:07,  5.39it/s]:  53%|██████████████████████████▌                       | 42/79 [00:08<00:06,  5.53it/s]:  54%|███████████████████████████▏                      | 43/79 [00:09<00:06,  5.63it/s]:  56%|███████████████████████████▊                      | 44/79 [00:09<00:06,  5.26it/s]:  57%|████████████████████████████▍                     | 45/79 [00:09<00:06,  5.44it/s]:  58%|█████████████████████████████                     | 46/79 [00:09<00:05,  5.53it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:09<00:05,  5.61it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:09<00:05,  5.68it/s]:  62%|███████████████████████████████                   | 49/79 [00:10<00:05,  5.72it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:10<00:05,  5.76it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:10<00:04,  5.62it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:10<00:04,  5.69it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:10<00:04,  5.72it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:11<00:04,  5.44it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:11<00:04,  5.25it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:11<00:04,  5.42it/s]:  72%|████████████████████████████████████              | 57/79 [00:11<00:03,  5.51it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:11<00:03,  5.54it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:11<00:03,  5.54it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:12<00:03,  5.19it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:12<00:03,  5.34it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:12<00:03,  5.47it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:12<00:02,  5.56it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:12<00:02,  5.63it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:13<00:02,  5.66it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:13<00:02,  5.68it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:13<00:02,  5.55it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:13<00:01,  5.61it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:13<00:01,  5.66it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:13<00:01,  5.69it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:14<00:01,  5.71it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:14<00:01,  5.74it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:14<00:01,  5.37it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:14<00:00,  5.50it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:14<00:00,  5.60it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:14<00:00,  5.66it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:15<00:00,  5.71it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:15<00:00,  5.72it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:15<00:00,  5.86it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:15<00:00,  5.09it/s]
14 Oct 08:47    INFO  epoch 1 training [time: 15.66s, train loss: 49.1130]

[8/8] FISM: {'embedding_size': 64, 'learning_rate': 0.005, 'alpha': 0.5, 'reg_weights': [0.001, 0.001]}

14 Oct 08:52    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v378a84a4e8ede30b35db7597ce0cc5982cb81449c.json']
14 Oct 08:52    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.005
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
split_to = 0
reg_weights = [0.001, 0.001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


14 Oct 08:52    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
14 Oct 08:52    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
14 Oct 08:52    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
14 Oct 08:52    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
14 Oct 08:52    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
14 Oct 08:52    INFO  FISM(
  (item_src_embedding): Embedding(1683, 64, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 64, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 218051
14 Oct 08:52    INFO  FLOPs: 37888.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:   1%|▋                                                  | 1/79 [00:00<00:22,  3.54it/s]:   3%|█▎                                                 | 2/79 [00:00<00:17,  4.51it/s]:   4%|█▉                                                 | 3/79 [00:00<00:15,  5.03it/s]:   5%|██▌                                                | 4/79 [00:00<00:14,  5.32it/s]:   6%|███▏                                               | 5/79 [00:00<00:13,  5.43it/s]:   8%|███▊                                               | 6/79 [00:01<00:13,  5.54it/s]:   9%|████▌                                              | 7/79 [00:01<00:12,  5.64it/s]:  10%|█████▏                                             | 8/79 [00:01<00:12,  5.71it/s]:  11%|█████▊                                             | 9/79 [00:01<00:12,  5.69it/s]:  13%|██████▎                                           | 10/79 [00:01<00:12,  5.69it/s]:  14%|██████▉                                           | 11/79 [00:02<00:14,  4.83it/s]:  15%|███████▌                                          | 12/79 [00:02<00:13,  5.01it/s]:  16%|████████▏                                         | 13/79 [00:02<00:12,  5.21it/s]:  18%|████████▊                                         | 14/79 [00:02<00:12,  5.29it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:11,  5.41it/s]:  20%|██████████▏                                       | 16/79 [00:03<00:11,  5.50it/s]:  22%|██████████▊                                       | 17/79 [00:03<00:11,  5.57it/s]:  23%|███████████▍                                      | 18/79 [00:03<00:11,  5.54it/s]:  24%|████████████                                      | 19/79 [00:03<00:10,  5.60it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:10,  5.64it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:10,  5.52it/s]:  28%|█████████████▉                                    | 22/79 [00:04<00:10,  5.61it/s]:  29%|██████████████▌                                   | 23/79 [00:04<00:09,  5.61it/s]:  30%|███████████████▏                                  | 24/79 [00:04<00:09,  5.61it/s]:  32%|███████████████▊                                  | 25/79 [00:04<00:09,  5.58it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:09,  5.35it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:09,  5.49it/s]:  35%|█████████████████▋                                | 28/79 [00:05<00:09,  5.57it/s]:  37%|██████████████████▎                               | 29/79 [00:05<00:08,  5.63it/s]:  38%|██████████████████▉                               | 30/79 [00:05<00:08,  5.61it/s]:  39%|███████████████████▌                              | 31/79 [00:05<00:08,  5.55it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:08,  5.68it/s]:  42%|████████████████████▉                             | 33/79 [00:06<00:08,  5.69it/s]:  43%|█████████████████████▌                            | 34/79 [00:06<00:07,  5.65it/s]:  44%|██████████████████████▏                           | 35/79 [00:06<00:07,  5.69it/s]:  46%|██████████████████████▊                           | 36/79 [00:06<00:07,  5.73it/s]:  47%|███████████████████████▍                          | 37/79 [00:06<00:07,  5.78it/s]:  48%|████████████████████████                          | 38/79 [00:06<00:07,  5.75it/s]:  49%|████████████████████████▋                         | 39/79 [00:07<00:06,  5.77it/s]:  51%|█████████████████████████▎                        | 40/79 [00:07<00:06,  5.76it/s]:  52%|█████████████████████████▉                        | 41/79 [00:07<00:06,  5.76it/s]:  53%|██████████████████████████▌                       | 42/79 [00:07<00:06,  5.81it/s]:  54%|███████████████████████████▏                      | 43/79 [00:07<00:06,  5.84it/s]:  56%|███████████████████████████▊                      | 44/79 [00:07<00:06,  5.82it/s]:  57%|████████████████████████████▍                     | 45/79 [00:08<00:05,  5.72it/s]:  58%|█████████████████████████████                     | 46/79 [00:08<00:05,  5.74it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:08<00:05,  5.74it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:08<00:05,  5.72it/s]:  62%|███████████████████████████████                   | 49/79 [00:08<00:05,  5.77it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:08<00:05,  5.77it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:09<00:04,  5.80it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:09<00:04,  5.86it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:09<00:04,  5.32it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:09<00:04,  5.49it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:09<00:04,  5.62it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:10<00:04,  5.70it/s]:  72%|████████████████████████████████████              | 57/79 [00:10<00:03,  5.72it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:10<00:03,  5.77it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:10<00:03,  5.79it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:10<00:03,  5.81it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:10<00:03,  5.85it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:11<00:02,  5.83it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:11<00:02,  5.81it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:11<00:02,  5.83it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:11<00:02,  5.85it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:11<00:02,  5.83it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:11<00:02,  5.83it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:12<00:01,  5.81it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:12<00:01,  5.73it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:12<00:01,  5.74it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:12<00:01,  5.75it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:12<00:01,  5.78it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:12<00:01,  5.78it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:13<00:00,  5.62it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:13<00:00,  5.70it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:13<00:00,  5.76it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:13<00:00,  5.75it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:13<00:00,  5.78it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:14<00:00,  5.86it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:14<00:00,  5.61it/s]
14 Oct 08:52    INFO  epoch 0 training [time: 14.20s, train loss: 56.3469]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:11,  6.81it/s]:   3%|█▎                                                 | 2/79 [00:00<00:12,  6.24it/s]:   4%|█▉                                                 | 3/79 [00:00<00:12,  5.92it/s]:   5%|██▌                                                | 4/79 [00:00<00:12,  5.91it/s]:   6%|███▏                                               | 5/79 [00:00<00:12,  5.93it/s]:   8%|███▊                                               | 6/79 [00:01<00:12,  5.89it/s]:   9%|████▌                                              | 7/79 [00:01<00:12,  5.85it/s]:  10%|█████▏                                             | 8/79 [00:01<00:12,  5.80it/s]:  11%|█████▊                                             | 9/79 [00:01<00:12,  5.56it/s]:  13%|██████▎                                           | 10/79 [00:01<00:13,  5.19it/s]:  14%|██████▉                                           | 11/79 [00:01<00:12,  5.38it/s]:  15%|███████▌                                          | 12/79 [00:02<00:12,  5.46it/s]:  16%|████████▏                                         | 13/79 [00:02<00:11,  5.50it/s]:  18%|████████▊                                         | 14/79 [00:02<00:11,  5.46it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:11,  5.58it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:11,  5.66it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:10,  5.74it/s]:  23%|███████████▍                                      | 18/79 [00:03<00:10,  5.76it/s]:  24%|████████████                                      | 19/79 [00:03<00:10,  5.80it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:10,  5.81it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:09,  5.81it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:10,  5.64it/s]:  29%|██████████████▌                                   | 23/79 [00:04<00:10,  5.48it/s]:  30%|███████████████▏                                  | 24/79 [00:04<00:09,  5.61it/s]:  32%|███████████████▊                                  | 25/79 [00:04<00:09,  5.61it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:09,  5.69it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:09,  5.73it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:08,  5.76it/s]:  37%|██████████████████▎                               | 29/79 [00:05<00:08,  5.83it/s]:  38%|██████████████████▉                               | 30/79 [00:05<00:08,  5.83it/s]:  39%|███████████████████▌                              | 31/79 [00:05<00:08,  5.77it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:08,  5.63it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:08,  5.66it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:07,  5.70it/s]:  44%|██████████████████████▏                           | 35/79 [00:06<00:07,  5.79it/s]:  46%|██████████████████████▊                           | 36/79 [00:06<00:07,  5.82it/s]:  47%|███████████████████████▍                          | 37/79 [00:06<00:07,  5.71it/s]:  48%|████████████████████████                          | 38/79 [00:06<00:07,  5.73it/s]:  49%|████████████████████████▋                         | 39/79 [00:06<00:06,  5.73it/s]:  51%|█████████████████████████▎                        | 40/79 [00:07<00:06,  5.74it/s]:  52%|█████████████████████████▉                        | 41/79 [00:07<00:06,  5.75it/s]:  53%|██████████████████████████▌                       | 42/79 [00:07<00:06,  5.75it/s]:  54%|███████████████████████████▏                      | 43/79 [00:07<00:06,  5.78it/s]:  56%|███████████████████████████▊                      | 44/79 [00:07<00:06,  5.81it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:05,  5.82it/s]:  58%|█████████████████████████████                     | 46/79 [00:08<00:05,  5.84it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:08<00:05,  5.69it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:08<00:05,  5.68it/s]:  62%|███████████████████████████████                   | 49/79 [00:08<00:05,  5.66it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:08<00:05,  5.69it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:08<00:05,  5.29it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:09<00:04,  5.42it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:09<00:04,  5.51it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:09<00:04,  5.56it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:09<00:04,  5.65it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:09<00:04,  5.68it/s]:  72%|████████████████████████████████████              | 57/79 [00:10<00:03,  5.71it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:10<00:03,  5.76it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:10<00:03,  5.78it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:10<00:03,  5.82it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:10<00:03,  5.82it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:10<00:03,  5.63it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:11<00:02,  5.70it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:11<00:02,  5.64it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:11<00:02,  5.70it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:11<00:02,  5.74it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:11<00:02,  5.70it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:11<00:01,  5.81it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:12<00:01,  5.82it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:12<00:01,  5.84it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:12<00:01,  5.82it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:12<00:01,  5.78it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:12<00:01,  5.80it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:12<00:00,  5.76it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:13<00:00,  5.77it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:13<00:00,  5.79it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:13<00:00,  5.65it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:13<00:00,  5.66it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  5.85it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  5.69it/s]
14 Oct 08:52    INFO  epoch 1 training [time: 13.98s, train loss: 54.7640]

Saved to:
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/tuning_results/FISM_tuning.csv

Best configuration:

,embedding_size,learning_rate,alpha,reg_weights,valid_score,recall@10,mrr@10,ndcg@10,hit@10,precision@10
0,64,0.005,0.5,"[0.0001, 0.0001]",0.3429,0.1821,0.3429,0.1976,0.7169,0.1417