In [8]:
from recbole.quick_start import run_recbole

from itertools import product
from pathlib import Path

import pandas as pd
import json

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

CONFIG_ROOT = PROJECT_ROOT / "recbole" / "config"

RESULTS_DIR = PROJECT_ROOT / "group_18" / "tuning_results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

In [10]:
from recbole.config import Config
from recbole.data import create_dataset, data_preparation
from recbole.utils import get_model, get_trainer, init_seed


def evaluate_traditional_model(model_name, config_path, params):
    """Fit a traditional RecBole model and evaluate on validation data."""

    config = Config(
        model=model_name,
        dataset="ml-100k",
        config_file_list=[str(config_path)],
        config_dict={
            "seed": 2020,
            "reproducibility": True,
            "use_gpu": False,
            "data_path": str(PROJECT_ROOT / "dataset"),
            **params,
        },
    )

    init_seed(config["seed"], config["reproducibility"])

    dataset = create_dataset(config)
    train_data, valid_data, _ = data_preparation(config, dataset)

    # EASE and SLIMElastic fit their parameters during initialization
    model = get_model(model_name)(
        config,
        train_data.dataset
    ).to(config["device"])

    trainer = get_trainer(
        config["MODEL_TYPE"],
        config["model"]
    )(config, model)

    valid_result = trainer.evaluate(
        valid_data,
        load_best_model=False
    )

    return {
        "best_valid_score": valid_result["mrr@10"],
        "best_valid_result": valid_result,
    }

In [11]:
def tune_model(
    name,
    model,
    config_path,
    search_space,
    fixed_params=None,
    save=True
):
    """
    Exhaustively tune a RecBole model.

    Parameters
    ----------
    name : str
        Name used for displaying/saving results.

    model : str
        RecBole model name.

    config_path : str or Path
        Path to the model's YAML configuration.

    search_space : dict
        Hyperparameters and values to test.

        Example:
        {
            "k": [20, 50, 100],
            "shrink": [0, 10, 50]
        }

    fixed_params : dict, optional
        Parameters that should remain fixed.
        Useful for things such as knn_method.

    save : bool
        Save tuning results to CSV.

    Returns
    -------
    DataFrame
        All tuning experiments.
    """

    if fixed_params is None:
        fixed_params = {}

    # Parameter names
    param_names = list(search_space.keys())

    # All combinations
    combinations = list(
        product(*search_space.values())
    )

    results = []

    print(f"Tuning {name}")
    print(f"Number of experiments: {len(combinations)}")
    print("=" * 60)

    for i, values in enumerate(combinations, start=1):

        params = dict(zip(param_names, values))

        config_dict = {
            "model": model,
            "dataset": "ml-100k",
            **fixed_params,
            **params,
        }

        print(
            f"[{i}/{len(combinations)}] "
            f"{name}: {params}"
        )

        if model in {"EASE", "SLIMElastic"}:
            result = evaluate_traditional_model(
                model_name=model,
                config_path=config_path,
                params=params,
            )
        else:
            result = run_recbole(
                model=model,
                dataset="ml-100k",
                config_dict=config_dict,
                config_file_list=[str(config_path)],
                saved=False,
            )

        valid = result["best_valid_result"]

        row = {
            **params,
            "valid_score": result["best_valid_score"],
            **valid,
        }

        valid = result["best_valid_result"]

        row = {
            **params,
            "valid_score": result["best_valid_score"],
            **valid
        }

        results.append(row)

    df = pd.DataFrame(results)

    # Best first
    df = df.sort_values(
        "valid_score",
        ascending=False
    ).reset_index(drop=True)

    if save:
        output_path = RESULTS_DIR / f"{name}_tuning.csv"
        df.to_csv(output_path, index=False)

        print(f"\nSaved to:")
        print(output_path)

    print("\nBest configuration:")
    display(df.head(1))

    return df

In [12]:
itemcf_space = {
    "k": [20, 50, 100, 200],
    "shrink": [0, 10, 50, 100]
}

In [13]:
itemcf_results = tune_model(
    name="ItemCF",
    model="ItemKNN",
    config_path=CONFIG_ROOT / "ItemKNN" / "ml-100k.yaml",
    search_space=itemcf_space,
    fixed_params={
        "knn_method": "item"
    }
)

15 Oct 14:35    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:35    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 0
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}

Tuning ItemCF
Number of experiments: 16
============================================================
[1/16] ItemCF: {'k': 20, 'shrink': 0}

15 Oct 14:35    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:35    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:35    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:35    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:35    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  89%|███████████████████████████████████████████▍     | 70/79 [00:00<00:00, 691.14it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 665.77it/s]
15 Oct 14:35    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  71%|████████████████████████████████▋             | 336/472 [00:00<00:00, 3351.80it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 3336.77it/s]
15 Oct 14:35    INFO  epoch 0 evaluating [time: 0.15s, valid_score: 0.355300]
15 Oct 14:35    INFO  valid result:
recall@10 : 0.1884    mrr@10 : 0.3553    ndcg@10 : 0.2063    hit@10 : 0.7041    precision@10 : 0.1471
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  68%|███████████████████████████████▍              | 323/472 [00:00<00:00, 3226.29it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 3281.62it/s]
15 Oct 14:35    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     8.30 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.65 G/30.64 G |
+-------------+----------------+
15 Oct 14:35    INFO  best valid : OrderedDict([('recall@10', 0.1884), ('mrr@10', 0.3553), ('ndcg@10', 0.2063), ('hit@10', 0.7041), ('precision@10', 0.1471)])
15 Oct 14:35    INFO  test result: OrderedDict([('recall@10', 0.2328), ('mrr@10', 0.4364), ('ndcg@10', 0.2637), ('hit@10', 0.7762), ('precision@10', 0.1852)])

[2/16] ItemCF: {'k': 20, 'shrink': 10}

15 Oct 14:35    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:35    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 10
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:35    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:35    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:35    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:35    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:35    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 779.94it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 769.81it/s]
15 Oct 14:35    INFO  epoch 0 training [time: 0.11s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  59%|███████████████████████████                   | 278/472 [00:00<00:00, 2769.29it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2783.98it/s]
15 Oct 14:35    INFO  epoch 0 evaluating [time: 0.18s, valid_score: 0.356500]
15 Oct 14:35    INFO  valid result:
recall@10 : 0.1925    mrr@10 : 0.3565    ndcg@10 : 0.2077    hit@10 : 0.7179    precision@10 : 0.1478
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  59%|███████████████████████████▏                  | 279/472 [00:00<00:00, 2788.49it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2791.27it/s]
15 Oct 14:35    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     6.40 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.67 G/30.64 G |
+-------------+----------------+
15 Oct 14:35    INFO  best valid : OrderedDict([('recall@10', 0.1925), ('mrr@10', 0.3565), ('ndcg@10', 0.2077), ('hit@10', 0.7179), ('precision@10', 0.1478)])
15 Oct 14:35    INFO  test result: OrderedDict([('recall@10', 0.2339), ('mrr@10', 0.4326), ('ndcg@10', 0.2609), ('hit@10', 0.772), ('precision@10', 0.181)])

[3/16] ItemCF: {'k': 20, 'shrink': 50}

15 Oct 14:35    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:35    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 50
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:35    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:35    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:35    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:35    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:35    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 781.53it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 769.75it/s]
15 Oct 14:35    INFO  epoch 0 training [time: 0.11s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  51%|███████████████████████▍                      | 241/472 [00:00<00:00, 2406.22it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2462.33it/s]
15 Oct 14:35    INFO  epoch 0 evaluating [time: 0.20s, valid_score: 0.348400]
15 Oct 14:35    INFO  valid result:
recall@10 : 0.1908    mrr@10 : 0.3484    ndcg@10 : 0.2051    hit@10 : 0.7073    precision@10 : 0.1459
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  53%|████████████████████████▏                     | 248/472 [00:00<00:00, 2479.75it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2500.35it/s]
15 Oct 14:35    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     5.00 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.69 G/30.64 G |
+-------------+----------------+
15 Oct 14:35    INFO  best valid : OrderedDict([('recall@10', 0.1908), ('mrr@10', 0.3484), ('ndcg@10', 0.2051), ('hit@10', 0.7073), ('precision@10', 0.1459)])
15 Oct 14:35    INFO  test result: OrderedDict([('recall@10', 0.2341), ('mrr@10', 0.4393), ('ndcg@10', 0.2627), ('hit@10', 0.7784), ('precision@10', 0.1803)])

[4/16] ItemCF: {'k': 20, 'shrink': 100}

15 Oct 14:35    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:35    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 100
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:35    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:35    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:35    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:35    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:35    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 804.61it/s]
15 Oct 14:35    INFO  epoch 0 training [time: 0.10s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  51%|███████████████████████▍                      | 240/472 [00:00<00:00, 2392.63it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2402.64it/s]
15 Oct 14:35    INFO  epoch 0 evaluating [time: 0.20s, valid_score: 0.350100]
15 Oct 14:35    INFO  valid result:
recall@10 : 0.1965    mrr@10 : 0.3501    ndcg@10 : 0.2081    hit@10 : 0.7137    precision@10 : 0.1474
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  50%|███████████████████████▏                      | 238/472 [00:00<00:00, 2375.54it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2385.87it/s]
15 Oct 14:35    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     4.20 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.70 G/30.64 G |
+-------------+----------------+
15 Oct 14:35    INFO  best valid : OrderedDict([('recall@10', 0.1965), ('mrr@10', 0.3501), ('ndcg@10', 0.2081), ('hit@10', 0.7137), ('precision@10', 0.1474)])
15 Oct 14:35    INFO  test result: OrderedDict([('recall@10', 0.234), ('mrr@10', 0.4396), ('ndcg@10', 0.2633), ('hit@10', 0.7699), ('precision@10', 0.1811)])

[5/16] ItemCF: {'k': 50, 'shrink': 0}

15 Oct 14:35    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:35    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 0
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:35    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:35    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:35    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:35    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:35    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  91%|████████████████████████████████████████████▋    | 72/79 [00:00<00:00, 714.38it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 678.82it/s]
15 Oct 14:35    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  59%|███████████████████████████                   | 278/472 [00:00<00:00, 2778.40it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2775.30it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.18s, valid_score: 0.368000]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.1992    mrr@10 : 0.368    ndcg@10 : 0.2163    hit@10 : 0.7296    precision@10 : 0.1531
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  59%|███████████████████████████▏                  | 279/472 [00:00<00:00, 2782.61it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2777.46it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     4.80 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.68 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.1992), ('mrr@10', 0.368), ('ndcg@10', 0.2163), ('hit@10', 0.7296), ('precision@10', 0.1531)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2425), ('mrr@10', 0.4646), ('ndcg@10', 0.2794), ('hit@10', 0.79), ('precision@10', 0.1916)])

[6/16] ItemCF: {'k': 50, 'shrink': 10}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 10
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 789.09it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 772.77it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.11s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  50%|███████████████████████                       | 236/472 [00:00<00:00, 2353.38it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2371.99it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.21s, valid_score: 0.374300]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.2017    mrr@10 : 0.3743    ndcg@10 : 0.2197    hit@10 : 0.7243    precision@10 : 0.1549
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  52%|███████████████████████▊                      | 244/472 [00:00<00:00, 2429.48it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2351.27it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     5.10 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.70 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.2017), ('mrr@10', 0.3743), ('ndcg@10', 0.2197), ('hit@10', 0.7243), ('precision@10', 0.1549)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2406), ('mrr@10', 0.4623), ('ndcg@10', 0.2782), ('hit@10', 0.7858), ('precision@10', 0.1906)])

[7/16] ItemCF: {'k': 50, 'shrink': 50}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 50
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 783.64it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 764.13it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.11s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  46%|█████████████████████▏                        | 218/472 [00:00<00:00, 2177.80it/s]:  93%|██████████████████████████████████████████▌   | 437/472 [00:00<00:00, 2180.09it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2149.82it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.23s, valid_score: 0.378500]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.2019    mrr@10 : 0.3785    ndcg@10 : 0.2194    hit@10 : 0.7338    precision@10 : 0.1516
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  45%|████████████████████▊                         | 213/472 [00:00<00:00, 2123.79it/s]:  90%|█████████████████████████████████████████▌    | 426/472 [00:00<00:00, 2126.92it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2102.28it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     3.80 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.70 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.2019), ('mrr@10', 0.3785), ('ndcg@10', 0.2194), ('hit@10', 0.7338), ('precision@10', 0.1516)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2346), ('mrr@10', 0.4641), ('ndcg@10', 0.2767), ('hit@10', 0.7741), ('precision@10', 0.1872)])

[8/16] ItemCF: {'k': 50, 'shrink': 100}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 100
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  99%|████████████████████████████████████████████████▍| 78/79 [00:00<00:00, 772.32it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 728.96it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.11s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  46%|████████████████████▉                         | 215/472 [00:00<00:00, 2143.44it/s]:  91%|█████████████████████████████████████████▉    | 430/472 [00:00<00:00, 2119.49it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2066.05it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.24s, valid_score: 0.374200]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.204    mrr@10 : 0.3742    ndcg@10 : 0.2194    hit@10 : 0.7285    precision@10 : 0.1532
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  45%|████████████████████▌                         | 211/472 [00:00<00:00, 2101.03it/s]:  89%|█████████████████████████████████████████▏    | 422/472 [00:00<00:00, 2095.34it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2061.77it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     5.90 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.71 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.204), ('mrr@10', 0.3742), ('ndcg@10', 0.2194), ('hit@10', 0.7285), ('precision@10', 0.1532)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.233), ('mrr@10', 0.4669), ('ndcg@10', 0.2746), ('hit@10', 0.7709), ('precision@10', 0.1829)])

[9/16] ItemCF: {'k': 100, 'shrink': 0}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 0
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 73/79 [00:00<00:00, 729.02it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 680.76it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  50%|██████████████████████▊                       | 234/472 [00:00<00:00, 2332.90it/s]:  99%|█████████████████████████████████████████████▌| 468/472 [00:00<00:00, 2318.72it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2279.43it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.22s, valid_score: 0.377900]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.2058    mrr@10 : 0.3779    ndcg@10 : 0.2213    hit@10 : 0.7328    precision@10 : 0.1554
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  50%|███████████████████████                       | 237/472 [00:00<00:00, 2368.51it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2348.45it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     5.00 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.70 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.2058), ('mrr@10', 0.3779), ('ndcg@10', 0.2213), ('hit@10', 0.7328), ('precision@10', 0.1554)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.247), ('mrr@10', 0.4623), ('ndcg@10', 0.2834), ('hit@10', 0.7847), ('precision@10', 0.1931)])

[10/16] ItemCF: {'k': 100, 'shrink': 10}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 10
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 769.46it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 747.23it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.11s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  44%|████████████████████▍                         | 210/472 [00:00<00:00, 2097.30it/s]:  89%|█████████████████████████████████████████     | 421/472 [00:00<00:00, 2104.25it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2071.19it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.24s, valid_score: 0.378000]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.2027    mrr@10 : 0.378    ndcg@10 : 0.2215    hit@10 : 0.7296    precision@10 : 0.1555
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  46%|█████████████████████                         | 216/472 [00:00<00:00, 2149.96it/s]:  91%|██████████████████████████████████████████    | 431/472 [00:00<00:00, 2120.32it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2084.92it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     4.80 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.72 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.2027), ('mrr@10', 0.378), ('ndcg@10', 0.2215), ('hit@10', 0.7296), ('precision@10', 0.1555)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.244), ('mrr@10', 0.4705), ('ndcg@10', 0.2846), ('hit@10', 0.7805), ('precision@10', 0.1911)])

[11/16] ItemCF: {'k': 100, 'shrink': 50}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 50
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 75/79 [00:00<00:00, 744.26it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 698.06it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  42%|███████████████████▍                          | 200/472 [00:00<00:00, 1996.45it/s]:  85%|██████████████████████████████████████▉       | 400/472 [00:00<00:00, 1961.80it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1948.69it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.25s, valid_score: 0.381300]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.2044    mrr@10 : 0.3813    ndcg@10 : 0.2216    hit@10 : 0.7243    precision@10 : 0.1524
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  42%|███████████████████▎                          | 198/472 [00:00<00:00, 1976.27it/s]:  84%|██████████████████████████████████████▌       | 396/472 [00:00<00:00, 1968.28it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1945.18it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     5.80 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.73 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.2044), ('mrr@10', 0.3813), ('ndcg@10', 0.2216), ('hit@10', 0.7243), ('precision@10', 0.1524)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2414), ('mrr@10', 0.4731), ('ndcg@10', 0.2816), ('hit@10', 0.7826), ('precision@10', 0.1859)])

[12/16] ItemCF: {'k': 100, 'shrink': 100}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 100
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  94%|█████████████████████████████████████████████▉   | 74/79 [00:00<00:00, 733.22it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 704.58it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  42%|███████████████████▏                          | 197/472 [00:00<00:00, 1963.64it/s]:  83%|██████████████████████████████████████▍       | 394/472 [00:00<00:00, 1920.39it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1909.96it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.26s, valid_score: 0.386900]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.2007    mrr@10 : 0.3869    ndcg@10 : 0.2216    hit@10 : 0.7264    precision@10 : 0.1496
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  41%|██████████████████▊                           | 193/472 [00:00<00:00, 1922.93it/s]:  82%|█████████████████████████████████████▌        | 386/472 [00:00<00:00, 1888.29it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1892.73it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     8.40 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.73 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.2007), ('mrr@10', 0.3869), ('ndcg@10', 0.2216), ('hit@10', 0.7264), ('precision@10', 0.1496)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2402), ('mrr@10', 0.4827), ('ndcg@10', 0.2819), ('hit@10', 0.7922), ('precision@10', 0.183)])

[13/16] ItemCF: {'k': 200, 'shrink': 0}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 0
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  97%|███████████████████████████████████████████████▊ | 77/79 [00:00<00:00, 764.11it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 715.40it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  44%|████████████████████▎                         | 209/472 [00:00<00:00, 2082.37it/s]:  89%|████████████████████████████████████████▋     | 418/472 [00:00<00:00, 2014.11it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2000.18it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.25s, valid_score: 0.370600]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.2073    mrr@10 : 0.3706    ndcg@10 : 0.223    hit@10 : 0.7328    precision@10 : 0.155
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  45%|████████████████████▊                         | 213/472 [00:00<00:00, 2124.58it/s]:  90%|█████████████████████████████████████████▌    | 426/472 [00:00<00:00, 2085.61it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2054.46it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     5.40 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.72 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.2073), ('mrr@10', 0.3706), ('ndcg@10', 0.223), ('hit@10', 0.7328), ('precision@10', 0.155)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2529), ('mrr@10', 0.4767), ('ndcg@10', 0.2894), ('hit@10', 0.7922), ('precision@10', 0.1935)])

[14/16] ItemCF: {'k': 200, 'shrink': 10}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 10
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  97%|███████████████████████████████████████████████▊ | 77/79 [00:00<00:00, 761.74it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 719.56it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  42%|███████████████████▍                          | 200/472 [00:00<00:00, 1993.74it/s]:  85%|██████████████████████████████████████▉       | 400/472 [00:00<00:00, 1938.67it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1926.11it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.26s, valid_score: 0.370500]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.2064    mrr@10 : 0.3705    ndcg@10 : 0.2228    hit@10 : 0.7359    precision@10 : 0.1551
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  42%|███████████████████                           | 196/472 [00:00<00:00, 1953.43it/s]:  83%|██████████████████████████████████████▏       | 392/472 [00:00<00:00, 1940.96it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1919.27it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     4.20 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.74 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.2064), ('mrr@10', 0.3705), ('ndcg@10', 0.2228), ('hit@10', 0.7359), ('precision@10', 0.1551)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2526), ('mrr@10', 0.4791), ('ndcg@10', 0.29), ('hit@10', 0.79), ('precision@10', 0.1928)])

[15/16] ItemCF: {'k': 200, 'shrink': 50}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 50
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  72%|███████████████████████████████████▎             | 57/79 [00:00<00:00, 566.13it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 584.07it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.14s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  40%|██████████████████▎                           | 188/472 [00:00<00:00, 1871.86it/s]:  80%|████████████████████████████████████▋         | 376/472 [00:00<00:00, 1794.33it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1794.31it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.27s, valid_score: 0.374400]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.2045    mrr@10 : 0.3744    ndcg@10 : 0.2215    hit@10 : 0.7243    precision@10 : 0.1519
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  40%|██████████████████▏                           | 187/472 [00:00<00:00, 1868.67it/s]:  79%|████████████████████████████████████▍         | 374/472 [00:00<00:00, 1795.77it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1776.53it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     5.40 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.74 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.2045), ('mrr@10', 0.3744), ('ndcg@10', 0.2215), ('hit@10', 0.7243), ('precision@10', 0.1519)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2444), ('mrr@10', 0.4801), ('ndcg@10', 0.2861), ('hit@10', 0.7794), ('precision@10', 0.1864)])

[16/16] ItemCF: {'k': 200, 'shrink': 100}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 100
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  91%|████████████████████████████████████████████▋    | 72/79 [00:00<00:00, 716.38it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 674.48it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.13s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  37%|█████████████████                             | 175/472 [00:00<00:00, 1747.26it/s]:  74%|██████████████████████████████████▏           | 351/472 [00:00<00:00, 1750.33it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1757.47it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.28s, valid_score: 0.377900]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.1971    mrr@10 : 0.3779    ndcg@10 : 0.219    hit@10 : 0.719    precision@10 : 0.1486
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  40%|██████████████████▌                           | 191/472 [00:00<00:00, 1902.90it/s]:  81%|█████████████████████████████████████▏        | 382/472 [00:00<00:00, 1834.93it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1828.83it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    25.10 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.75 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.1971), ('mrr@10', 0.3779), ('ndcg@10', 0.219), ('hit@10', 0.719), ('precision@10', 0.1486)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2341), ('mrr@10', 0.4696), ('ndcg@10', 0.2765), ('hit@10', 0.7646), ('precision@10', 0.1801)])

Saved to:
/home/kasparas/Desktop/MScCS/RecommenderSystems/RecBole_DSAIT4335_Group_18/tuning_results/ItemCF_tuning.csv

Best configuration:

     k  shrink  valid_score  recall@10  mrr@10  ndcg@10  hit@10  precision@10
0  100     100       0.3869     0.2007  0.3869   0.2216  0.7264        0.1496

In [14]:
usercf_results = tune_model(
    name="UserCF",
    model="ItemKNN",
    config_path=CONFIG_ROOT / "ItemKNN" / "ml-100k.yaml",
    search_space=itemcf_space,
    fixed_params={
        "knn_method": "user"
    }
)

Tuning UserCF
Number of experiments: 16
============================================================
[1/16] UserCF: {'k': 20, 'shrink': 0}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 0
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  99%|████████████████████████████████████████████████▍| 78/79 [00:00<00:00, 771.84it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 729.66it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  65%|█████████████████████████████▋                | 305/472 [00:00<00:00, 3047.55it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 3042.72it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.17s, valid_score: 0.370800]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.2125    mrr@10 : 0.3708    ndcg@10 : 0.2217    hit@10 : 0.7359    precision@10 : 0.1505
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  67%|██████████████████████████████▊               | 316/472 [00:00<00:00, 3154.48it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 3095.83it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     5.60 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.70 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.2125), ('mrr@10', 0.3708), ('ndcg@10', 0.2217), ('hit@10', 0.7359), ('precision@10', 0.1505)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2429), ('mrr@10', 0.4381), ('ndcg@10', 0.2669), ('hit@10', 0.7773), ('precision@10', 0.1782)])

[2/16] UserCF: {'k': 20, 'shrink': 10}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 10
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  84%|████████████████████████████████████████▉        | 66/79 [00:00<00:00, 657.76it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 635.08it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.14s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  65%|█████████████████████████████▊                | 306/472 [00:00<00:00, 3059.08it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2947.30it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.17s, valid_score: 0.367300]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.2092    mrr@10 : 0.3673    ndcg@10 : 0.2176    hit@10 : 0.7359    precision@10 : 0.1471
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  66%|██████████████████████████████▏               | 310/472 [00:00<00:00, 3093.12it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2982.56it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     5.80 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.70 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.2092), ('mrr@10', 0.3673), ('ndcg@10', 0.2176), ('hit@10', 0.7359), ('precision@10', 0.1471)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2404), ('mrr@10', 0.4168), ('ndcg@10', 0.2586), ('hit@10', 0.7741), ('precision@10', 0.1751)])

[3/16] UserCF: {'k': 20, 'shrink': 50}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 50
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 819.78it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.11s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  59%|███████████████████████████▎                  | 280/472 [00:00<00:00, 2797.71it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2775.99it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.18s, valid_score: 0.329600]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.186    mrr@10 : 0.3296    ndcg@10 : 0.1944    hit@10 : 0.6967    precision@10 : 0.134
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  60%|███████████████████████████▍                  | 281/472 [00:00<00:00, 2809.02it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2689.59it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     4.80 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.70 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.186), ('mrr@10', 0.3296), ('ndcg@10', 0.1944), ('hit@10', 0.6967), ('precision@10', 0.134)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2224), ('mrr@10', 0.3819), ('ndcg@10', 0.2352), ('hit@10', 0.7444), ('precision@10', 0.1618)])

[4/16] UserCF: {'k': 20, 'shrink': 100}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 100
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 827.13it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.11s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  55%|█████████████████████████▏                    | 259/472 [00:00<00:00, 2587.17it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2509.22it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.20s, valid_score: 0.313600]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.1784    mrr@10 : 0.3136    ndcg@10 : 0.1852    hit@10 : 0.6713    precision@10 : 0.1268
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  46%|█████████████████████                         | 216/472 [00:00<00:00, 2149.37it/s]:  91%|██████████████████████████████████████████    | 431/472 [00:00<00:00, 1887.57it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1839.63it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    10.10 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.71 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.1784), ('mrr@10', 0.3136), ('ndcg@10', 0.1852), ('hit@10', 0.6713), ('precision@10', 0.1268)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2068), ('mrr@10', 0.3641), ('ndcg@10', 0.2195), ('hit@10', 0.7158), ('precision@10', 0.1507)])

[5/16] UserCF: {'k': 50, 'shrink': 0}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 0
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 73/79 [00:00<00:00, 726.79it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 681.12it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.13s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  61%|████████████████████████████▎                 | 290/472 [00:00<00:00, 2889.58it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2811.84it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.18s, valid_score: 0.401000]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.216    mrr@10 : 0.401    ndcg@10 : 0.2355    hit@10 : 0.755    precision@10 : 0.1562
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  56%|█████████████████████████▋                    | 264/472 [00:00<00:00, 2638.57it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2639.73it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     7.30 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.70 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.216), ('mrr@10', 0.401), ('ndcg@10', 0.2355), ('hit@10', 0.755), ('precision@10', 0.1562)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2524), ('mrr@10', 0.477), ('ndcg@10', 0.2877), ('hit@10', 0.7932), ('precision@10', 0.1909)])

[6/16] UserCF: {'k': 50, 'shrink': 10}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 10
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  71%|██████████████████████████████████▋              | 56/79 [00:00<00:00, 553.36it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 534.81it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.16s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  49%|██████████████████████▌                       | 232/472 [00:00<00:00, 2310.20it/s]:  98%|█████████████████████████████████████████████▏| 464/472 [00:00<00:00, 2228.10it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2151.95it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.24s, valid_score: 0.380600]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.209    mrr@10 : 0.3806    ndcg@10 : 0.2266    hit@10 : 0.7359    precision@10 : 0.1526
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  40%|██████████████████▌                           | 190/472 [00:00<00:00, 1891.72it/s]:  85%|███████████████████████████████████████▏      | 402/472 [00:00<00:00, 2020.22it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1958.55it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    18.50 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.71 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.209), ('mrr@10', 0.3806), ('ndcg@10', 0.2266), ('hit@10', 0.7359), ('precision@10', 0.1526)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2456), ('mrr@10', 0.469), ('ndcg@10', 0.2816), ('hit@10', 0.7826), ('precision@10', 0.1853)])

[7/16] UserCF: {'k': 50, 'shrink': 50}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 50
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  77%|█████████████████████████████████████▊           | 61/79 [00:00<00:00, 601.10it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 564.57it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.15s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  43%|███████████████████▋                          | 202/472 [00:00<00:00, 2016.96it/s]:  86%|███████████████████████████████████████▎      | 404/472 [00:00<00:00, 1939.11it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1921.75it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.26s, valid_score: 0.361800]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.2018    mrr@10 : 0.3618    ndcg@10 : 0.2164    hit@10 : 0.7275    precision@10 : 0.1469
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  40%|██████████████████▌                           | 191/472 [00:00<00:00, 1903.11it/s]:  81%|█████████████████████████████████████▏        | 382/472 [00:00<00:00, 1776.50it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1768.30it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    25.00 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.72 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.2018), ('mrr@10', 0.3618), ('ndcg@10', 0.2164), ('hit@10', 0.7275), ('precision@10', 0.1469)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2384), ('mrr@10', 0.445), ('ndcg@10', 0.2695), ('hit@10', 0.7561), ('precision@10', 0.1793)])

[8/16] UserCF: {'k': 50, 'shrink': 100}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 100
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 816.87it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.11s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  43%|███████████████████▊                          | 203/472 [00:00<00:00, 2023.95it/s]:  86%|███████████████████████████████████████▌      | 406/472 [00:00<00:00, 1919.08it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1878.90it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.27s, valid_score: 0.350300]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.197    mrr@10 : 0.3503    ndcg@10 : 0.2086    hit@10 : 0.7179    precision@10 : 0.1434
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  36%|████████████████▍                             | 169/472 [00:00<00:00, 1685.31it/s]:  78%|███████████████████████████████████▊          | 368/472 [00:00<00:00, 1862.35it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1862.19it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     5.70 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.73 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.197), ('mrr@10', 0.3503), ('ndcg@10', 0.2086), ('hit@10', 0.7179), ('precision@10', 0.1434)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2286), ('mrr@10', 0.4245), ('ndcg@10', 0.2565), ('hit@10', 0.7497), ('precision@10', 0.173)])

[9/16] UserCF: {'k': 100, 'shrink': 0}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 0
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  33%|████████████████▏                                | 26/79 [00:00<00:00, 253.92it/s]:  80%|███████████████████████████████████████          | 63/79 [00:00<00:00, 317.33it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 315.08it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.27s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  40%|██████████████████▏                           | 187/472 [00:00<00:00, 1860.75it/s]:  82%|█████████████████████████████████████▌        | 385/472 [00:00<00:00, 1929.77it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1918.45it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.27s, valid_score: 0.399200]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.2102    mrr@10 : 0.3992    ndcg@10 : 0.2345    hit@10 : 0.7402    precision@10 : 0.1567
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  48%|██████████████████████                        | 227/472 [00:00<00:00, 2269.44it/s]:  96%|████████████████████████████████████████████▏ | 454/472 [00:00<00:00, 2142.74it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2091.54it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    15.00 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.71 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.2102), ('mrr@10', 0.3992), ('ndcg@10', 0.2345), ('hit@10', 0.7402), ('precision@10', 0.1567)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2442), ('mrr@10', 0.4834), ('ndcg@10', 0.2873), ('hit@10', 0.7805), ('precision@10', 0.1885)])

[10/16] UserCF: {'k': 100, 'shrink': 10}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 10
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:36    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 75/79 [00:00<00:00, 745.76it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 687.15it/s]
15 Oct 14:36    INFO  epoch 0 training [time: 0.13s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  47%|█████████████████████▊                        | 224/472 [00:00<00:00, 2232.73it/s]:  95%|███████████████████████████████████████████▋  | 448/472 [00:00<00:00, 2188.17it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2122.32it/s]
15 Oct 14:36    INFO  epoch 0 evaluating [time: 0.24s, valid_score: 0.388200]
15 Oct 14:36    INFO  valid result:
recall@10 : 0.2094    mrr@10 : 0.3882    ndcg@10 : 0.2303    hit@10 : 0.7402    precision@10 : 0.1554
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  47%|█████████████████████▌                        | 221/472 [00:00<00:00, 2206.79it/s]:  94%|███████████████████████████████████████████   | 442/472 [00:00<00:00, 2193.81it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2132.36it/s]
15 Oct 14:36    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     9.20 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.72 G/30.64 G |
+-------------+----------------+
15 Oct 14:36    INFO  best valid : OrderedDict([('recall@10', 0.2094), ('mrr@10', 0.3882), ('ndcg@10', 0.2303), ('hit@10', 0.7402), ('precision@10', 0.1554)])
15 Oct 14:36    INFO  test result: OrderedDict([('recall@10', 0.2402), ('mrr@10', 0.4725), ('ndcg@10', 0.2817), ('hit@10', 0.7752), ('precision@10', 0.1853)])

[11/16] UserCF: {'k': 100, 'shrink': 50}

15 Oct 14:36    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:36    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 50
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:36    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:36    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:36    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:36    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:37    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  97%|███████████████████████████████████████████████▊ | 77/79 [00:00<00:00, 763.05it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 702.66it/s]
15 Oct 14:37    INFO  epoch 0 training [time: 0.13s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  43%|███████████████████▊                          | 203/472 [00:00<00:00, 2025.87it/s]:  86%|███████████████████████████████████████▌      | 406/472 [00:00<00:00, 1951.39it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1935.76it/s]
15 Oct 14:37    INFO  epoch 0 evaluating [time: 0.26s, valid_score: 0.376900]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.2012    mrr@10 : 0.3769    ndcg@10 : 0.221    hit@10 : 0.7328    precision@10 : 0.1503
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  42%|███████████████████▍                          | 199/472 [00:00<00:00, 1985.30it/s]:  84%|██████████████████████████████████████▊       | 398/472 [00:00<00:00, 1832.88it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1834.41it/s]
15 Oct 14:37    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     7.30 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.72 G/30.64 G |
+-------------+----------------+
15 Oct 14:37    INFO  best valid : OrderedDict([('recall@10', 0.2012), ('mrr@10', 0.3769), ('ndcg@10', 0.221), ('hit@10', 0.7328), ('precision@10', 0.1503)])
15 Oct 14:37    INFO  test result: OrderedDict([('recall@10', 0.233), ('mrr@10', 0.4641), ('ndcg@10', 0.2745), ('hit@10', 0.7614), ('precision@10', 0.1803)])

[12/16] UserCF: {'k': 100, 'shrink': 100}

15 Oct 14:37    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:37    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 100
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:37    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:37    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:37    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:37    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:37    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 779.34it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 732.77it/s]
15 Oct 14:37    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  42%|███████████████████▏                          | 197/472 [00:00<00:00, 1966.01it/s]:  83%|██████████████████████████████████████▍       | 394/472 [00:00<00:00, 1861.58it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1818.47it/s]
15 Oct 14:37    INFO  epoch 0 evaluating [time: 0.28s, valid_score: 0.364700]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.198    mrr@10 : 0.3647    ndcg@10 : 0.215    hit@10 : 0.7243    precision@10 : 0.1483
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  38%|█████████████████▎                            | 178/472 [00:00<00:00, 1777.07it/s]:  75%|██████████████████████████████████▋           | 356/472 [00:00<00:00, 1667.29it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1691.39it/s]
15 Oct 14:37    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     9.60 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.72 G/30.64 G |
+-------------+----------------+
15 Oct 14:37    INFO  best valid : OrderedDict([('recall@10', 0.198), ('mrr@10', 0.3647), ('ndcg@10', 0.215), ('hit@10', 0.7243), ('precision@10', 0.1483)])
15 Oct 14:37    INFO  test result: OrderedDict([('recall@10', 0.228), ('mrr@10', 0.4568), ('ndcg@10', 0.2683), ('hit@10', 0.755), ('precision@10', 0.1751)])

[13/16] UserCF: {'k': 200, 'shrink': 0}

15 Oct 14:37    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:37    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 0
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:37    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:37    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:37    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:37    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:37    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  94%|█████████████████████████████████████████████▉   | 74/79 [00:00<00:00, 730.83it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 688.09it/s]
15 Oct 14:37    INFO  epoch 0 training [time: 0.13s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  43%|███████████████████▉                          | 205/472 [00:00<00:00, 2041.58it/s]:  87%|███████████████████████████████████████▉      | 410/472 [00:00<00:00, 1922.10it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1887.22it/s]
15 Oct 14:37    INFO  epoch 0 evaluating [time: 0.27s, valid_score: 0.387400]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.1996    mrr@10 : 0.3874    ndcg@10 : 0.2241    hit@10 : 0.7232    precision@10 : 0.1494
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  44%|████████████████████▍                         | 210/472 [00:00<00:00, 2092.18it/s]:  89%|████████████████████████████████████████▉     | 420/472 [00:00<00:00, 1848.22it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1781.38it/s]
15 Oct 14:37    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     7.00 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.73 G/30.64 G |
+-------------+----------------+
15 Oct 14:37    INFO  best valid : OrderedDict([('recall@10', 0.1996), ('mrr@10', 0.3874), ('ndcg@10', 0.2241), ('hit@10', 0.7232), ('precision@10', 0.1494)])
15 Oct 14:37    INFO  test result: OrderedDict([('recall@10', 0.2325), ('mrr@10', 0.4684), ('ndcg@10', 0.2734), ('hit@10', 0.7656), ('precision@10', 0.1776)])

[14/16] UserCF: {'k': 200, 'shrink': 10}

15 Oct 14:37    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:37    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 10
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:37    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:37    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:37    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:37    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:37    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:  94%|█████████████████████████████████████████████▉   | 74/79 [00:00<00:00, 736.75it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 668.67it/s]
15 Oct 14:37    INFO  epoch 0 training [time: 0.13s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  43%|███████████████████▋                          | 202/472 [00:00<00:00, 2013.13it/s]:  86%|███████████████████████████████████████▎      | 404/472 [00:00<00:00, 1937.04it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1919.91it/s]
15 Oct 14:37    INFO  epoch 0 evaluating [time: 0.26s, valid_score: 0.382300]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.1961    mrr@10 : 0.3823    ndcg@10 : 0.22    hit@10 : 0.7211    precision@10 : 0.1475
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  40%|██████████████████▎                           | 188/472 [00:00<00:00, 1874.16it/s]:  80%|████████████████████████████████████▋         | 376/472 [00:00<00:00, 1832.84it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1809.61it/s]
15 Oct 14:37    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     4.50 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.72 G/30.64 G |
+-------------+----------------+
15 Oct 14:37    INFO  best valid : OrderedDict([('recall@10', 0.1961), ('mrr@10', 0.3823), ('ndcg@10', 0.22), ('hit@10', 0.7211), ('precision@10', 0.1475)])
15 Oct 14:37    INFO  test result: OrderedDict([('recall@10', 0.2286), ('mrr@10', 0.4643), ('ndcg@10', 0.2702), ('hit@10', 0.7572), ('precision@10', 0.1752)])

[15/16] UserCF: {'k': 200, 'shrink': 50}

15 Oct 14:37    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:37    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 50
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:37    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:37    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:37    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:37    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:37    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 755.26it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 713.93it/s]
15 Oct 14:37    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  41%|███████████████████                           | 195/472 [00:00<00:00, 1939.52it/s]:  82%|█████████████████████████████████████▉        | 389/472 [00:00<00:00, 1890.88it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1825.19it/s]
15 Oct 14:37    INFO  epoch 0 evaluating [time: 0.28s, valid_score: 0.371800]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.1922    mrr@10 : 0.3718    ndcg@10 : 0.2143    hit@10 : 0.7031    precision@10 : 0.1448
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  40%|██████████████████▍                           | 189/472 [00:00<00:00, 1887.55it/s]:  80%|████████████████████████████████████▊         | 378/472 [00:00<00:00, 1804.73it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1785.40it/s]
15 Oct 14:37    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     4.10 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.73 G/30.64 G |
+-------------+----------------+
15 Oct 14:37    INFO  best valid : OrderedDict([('recall@10', 0.1922), ('mrr@10', 0.3718), ('ndcg@10', 0.2143), ('hit@10', 0.7031), ('precision@10', 0.1448)])
15 Oct 14:37    INFO  test result: OrderedDict([('recall@10', 0.2276), ('mrr@10', 0.4523), ('ndcg@10', 0.2655), ('hit@10', 0.7497), ('precision@10', 0.173)])

[16/16] UserCF: {'k': 200, 'shrink': 100}

15 Oct 14:37    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:37    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 100
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:37    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:37    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:37    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:37    INFO  ItemKNN()
Trainable parameters: 1
15 Oct 14:37    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 775.50it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 723.81it/s]
15 Oct 14:37    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  40%|██████████████████▍                           | 189/472 [00:00<00:00, 1886.90it/s]:  80%|████████████████████████████████████▊         | 378/472 [00:00<00:00, 1833.32it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1819.16it/s]
15 Oct 14:37    INFO  epoch 0 evaluating [time: 0.28s, valid_score: 0.368400]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.1889    mrr@10 : 0.3684    ndcg@10 : 0.2112    hit@10 : 0.701    precision@10 : 0.1431
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  39%|█████████████████▊                            | 183/472 [00:00<00:00, 1824.36it/s]:  78%|███████████████████████████████████▋          | 366/472 [00:00<00:00, 1753.95it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1745.12it/s]
15 Oct 14:37    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     5.90 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.74 G/30.64 G |
+-------------+----------------+
15 Oct 14:37    INFO  best valid : OrderedDict([('recall@10', 0.1889), ('mrr@10', 0.3684), ('ndcg@10', 0.2112), ('hit@10', 0.701), ('precision@10', 0.1431)])
15 Oct 14:37    INFO  test result: OrderedDict([('recall@10', 0.2207), ('mrr@10', 0.4412), ('ndcg@10', 0.2579), ('hit@10', 0.7359), ('precision@10', 0.1678)])

Saved to:
/home/kasparas/Desktop/MScCS/RecommenderSystems/RecBole_DSAIT4335_Group_18/tuning_results/UserCF_tuning.csv

Best configuration:

    k  shrink  valid_score  recall@10  mrr@10  ndcg@10  hit@10  precision@10
0  50       0        0.401      0.216   0.401   0.2355   0.755        0.1562

In [15]:
bpr_space = {
    "embedding_size": [16, 32, 64, 128],
    "learning_rate": [0.0001, 0.001, 0.01],
}

In [16]:
bpr_results = tune_model(
    name="BPR",
    model="BPR",
    config_path=CONFIG_ROOT / "BPR" / "ml-100k.yaml",
    search_space=bpr_space
)

Tuning BPR
Number of experiments: 12
============================================================
[1/12] BPR: {'embedding_size': 16, 'learning_rate': 0.0001}

15 Oct 14:37    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:37    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.0001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 16
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:37    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:37    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:37    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:37    INFO  BPR(
  (user_embedding): Embedding(944, 16)
  (item_embedding): Embedding(1683, 16)
  (loss): BPRLoss()
)
Trainable parameters: 42032
15 Oct 14:37    INFO  FLOPs: 32.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 387.23it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 356.79it/s]
15 Oct 14:37    INFO  epoch 0 training [time: 0.13s, train loss: 27.7264]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 37/40 [00:00<00:00, 368.53it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 339.69it/s]
15 Oct 14:37    INFO  epoch 1 training [time: 0.13s, train loss: 27.7244]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 331.34it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 290.24it/s]
15 Oct 14:37    INFO  epoch 2 training [time: 0.15s, train loss: 27.7230]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 349.96it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 319.01it/s]
15 Oct 14:37    INFO  epoch 3 training [time: 0.14s, train loss: 27.7213]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  88%|██████████████████████████████████████████▉      | 35/40 [00:00<00:00, 344.76it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 320.99it/s]
15 Oct 14:37    INFO  epoch 4 training [time: 0.14s, train loss: 27.7196]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 321.17it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 296.61it/s]
15 Oct 14:37    INFO  epoch 5 training [time: 0.15s, train loss: 27.7181]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 297.18it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 295.94it/s]
15 Oct 14:37    INFO  epoch 6 training [time: 0.15s, train loss: 27.7166]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 415.60it/s]
15 Oct 14:37    INFO  epoch 7 training [time: 0.11s, train loss: 27.7146]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 396.91it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 370.71it/s]
15 Oct 14:37    INFO  epoch 8 training [time: 0.12s, train loss: 27.7128]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 377.08it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 352.42it/s]
15 Oct 14:37    INFO  epoch 9 training [time: 0.13s, train loss: 27.7095]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6222.28it/s]
15 Oct 14:37    INFO  epoch 9 evaluating [time: 0.09s, valid_score: 0.023600]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.008    mrr@10 : 0.0236    ndcg@10 : 0.0101    hit@10 : 0.0795    precision@10 : 0.009
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 426.12it/s]
15 Oct 14:37    INFO  epoch 10 training [time: 0.11s, train loss: 27.7070]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 389.23it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 359.35it/s]
15 Oct 14:37    INFO  epoch 11 training [time: 0.13s, train loss: 27.7041]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 378.99it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 355.81it/s]
15 Oct 14:37    INFO  epoch 12 training [time: 0.13s, train loss: 27.6996]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 371.45it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 338.40it/s]
15 Oct 14:37    INFO  epoch 13 training [time: 0.13s, train loss: 27.6958]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 356.69it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 335.04it/s]
15 Oct 14:37    INFO  epoch 14 training [time: 0.14s, train loss: 27.6905]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 359.84it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 329.75it/s]
15 Oct 14:37    INFO  epoch 15 training [time: 0.14s, train loss: 27.6829]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 373.17it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 346.89it/s]
15 Oct 14:37    INFO  epoch 16 training [time: 0.13s, train loss: 27.6751]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 319.99it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 313.85it/s]
15 Oct 14:37    INFO  epoch 17 training [time: 0.14s, train loss: 27.6659]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 389.02it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 363.24it/s]
15 Oct 14:37    INFO  epoch 18 training [time: 0.13s, train loss: 27.6538]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 374.62it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 346.66it/s]
15 Oct 14:37    INFO  epoch 19 training [time: 0.14s, train loss: 27.6409]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6478.39it/s]
15 Oct 14:37    INFO  epoch 19 evaluating [time: 0.09s, valid_score: 0.070200]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.0223    mrr@10 : 0.0702    ndcg@10 : 0.0304    hit@10 : 0.1909    precision@10 : 0.0257
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6708.27it/s]
15 Oct 14:37    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     3.20 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.72 G/30.64 G |
+-------------+----------------+
15 Oct 14:37    INFO  best valid : OrderedDict([('recall@10', 0.0223), ('mrr@10', 0.0702), ('ndcg@10', 0.0304), ('hit@10', 0.1909), ('precision@10', 0.0257)])
15 Oct 14:37    INFO  test result: OrderedDict([('recall@10', 0.0253), ('mrr@10', 0.0877), ('ndcg@10', 0.0369), ('hit@10', 0.211), ('precision@10', 0.03)])

[2/12] BPR: {'embedding_size': 16, 'learning_rate': 0.001}

15 Oct 14:37    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:37    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 16
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:37    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:37    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:37    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:37    INFO  BPR(
  (user_embedding): Embedding(944, 16)
  (item_embedding): Embedding(1683, 16)
  (loss): BPRLoss()
)
Trainable parameters: 42032
15 Oct 14:37    INFO  FLOPs: 32.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 37/40 [00:00<00:00, 368.73it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 337.85it/s]
15 Oct 14:37    INFO  epoch 0 training [time: 0.14s, train loss: 27.7250]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 415.09it/s]
15 Oct 14:37    INFO  epoch 1 training [time: 0.11s, train loss: 27.6977]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 388.51it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 349.25it/s]
15 Oct 14:37    INFO  epoch 2 training [time: 0.13s, train loss: 27.6002]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 384.80it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 347.89it/s]
15 Oct 14:37    INFO  epoch 3 training [time: 0.13s, train loss: 27.1737]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 327.81it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 303.05it/s]
15 Oct 14:37    INFO  epoch 4 training [time: 0.15s, train loss: 25.9339]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  88%|██████████████████████████████████████████▉      | 35/40 [00:00<00:00, 348.50it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 324.35it/s]
15 Oct 14:37    INFO  epoch 5 training [time: 0.14s, train loss: 23.6408]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 406.54it/s]
15 Oct 14:37    INFO  epoch 6 training [time: 0.12s, train loss: 20.8413]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 264.11it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 278.12it/s]
15 Oct 14:37    INFO  epoch 7 training [time: 0.16s, train loss: 18.4548]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 354.98it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 322.34it/s]
15 Oct 14:37    INFO  epoch 8 training [time: 0.14s, train loss: 16.7208]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 397.12it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 370.34it/s]
15 Oct 14:37    INFO  epoch 9 training [time: 0.12s, train loss: 15.5673]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6780.79it/s]
15 Oct 14:37    INFO  epoch 9 evaluating [time: 0.09s, valid_score: 0.254300]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.105    mrr@10 : 0.2543    ndcg@10 : 0.1286    hit@10 : 0.5228    precision@10 : 0.0962
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 397.98it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 368.05it/s]
15 Oct 14:37    INFO  epoch 10 training [time: 0.13s, train loss: 14.8540]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 369.52it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 341.84it/s]
15 Oct 14:37    INFO  epoch 11 training [time: 0.13s, train loss: 14.3312]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 400.08it/s]
15 Oct 14:37    INFO  epoch 12 training [time: 0.12s, train loss: 13.9199]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 333.65it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 310.24it/s]
15 Oct 14:37    INFO  epoch 13 training [time: 0.15s, train loss: 13.6501]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 266.04it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 271.16it/s]
15 Oct 14:37    INFO  epoch 14 training [time: 0.16s, train loss: 13.4718]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 319.53it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 300.50it/s]
15 Oct 14:37    INFO  epoch 15 training [time: 0.15s, train loss: 13.1917]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 383.59it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 354.02it/s]
15 Oct 14:37    INFO  epoch 16 training [time: 0.13s, train loss: 13.0501]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 357.12it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 324.10it/s]
15 Oct 14:37    INFO  epoch 17 training [time: 0.14s, train loss: 12.8588]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 314.95it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 301.80it/s]
15 Oct 14:37    INFO  epoch 18 training [time: 0.15s, train loss: 12.6525]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 37/40 [00:00<00:00, 368.87it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 335.16it/s]
15 Oct 14:37    INFO  epoch 19 training [time: 0.14s, train loss: 12.6483]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6680.77it/s]
15 Oct 14:37    INFO  epoch 19 evaluating [time: 0.09s, valid_score: 0.298000]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.135    mrr@10 : 0.298    ndcg@10 : 0.1569    hit@10 : 0.5928    precision@10 : 0.1069
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5840.05it/s]
15 Oct 14:37    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     3.40 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.72 G/30.64 G |
+-------------+----------------+
15 Oct 14:37    INFO  best valid : OrderedDict([('recall@10', 0.135), ('mrr@10', 0.298), ('ndcg@10', 0.1569), ('hit@10', 0.5928), ('precision@10', 0.1069)])
15 Oct 14:37    INFO  test result: OrderedDict([('recall@10', 0.1571), ('mrr@10', 0.3515), ('ndcg@10', 0.1916), ('hit@10', 0.6331), ('precision@10', 0.1284)])

[3/12] BPR: {'embedding_size': 16, 'learning_rate': 0.01}

15 Oct 14:37    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:37    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.01
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 16
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:37    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:37    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:37    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:37    INFO  BPR(
  (user_embedding): Embedding(944, 16)
  (item_embedding): Embedding(1683, 16)
  (loss): BPRLoss()
)
Trainable parameters: 42032
15 Oct 14:37    INFO  FLOPs: 32.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 379.94it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 351.91it/s]
15 Oct 14:37    INFO  epoch 0 training [time: 0.13s, train loss: 26.8043]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 381.06it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 354.93it/s]
15 Oct 14:37    INFO  epoch 1 training [time: 0.13s, train loss: 16.2752]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 373.48it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 347.05it/s]
15 Oct 14:37    INFO  epoch 2 training [time: 0.13s, train loss: 12.4941]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  72%|███████████████████████████████████▌             | 29/40 [00:00<00:00, 285.27it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 274.64it/s]
15 Oct 14:37    INFO  epoch 3 training [time: 0.16s, train loss: 10.7140]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 401.52it/s]
15 Oct 14:37    INFO  epoch 4 training [time: 0.12s, train loss: 9.7102]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 406.27it/s]
15 Oct 14:37    INFO  epoch 5 training [time: 0.12s, train loss: 8.8311]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 406.22it/s]
15 Oct 14:37    INFO  epoch 6 training [time: 0.11s, train loss: 8.3627]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 404.92it/s]
15 Oct 14:37    INFO  epoch 7 training [time: 0.12s, train loss: 8.0100]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  88%|██████████████████████████████████████████▉      | 35/40 [00:00<00:00, 342.86it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 323.82it/s]
15 Oct 14:37    INFO  epoch 8 training [time: 0.14s, train loss: 7.7022]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 395.86it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 369.48it/s]
15 Oct 14:37    INFO  epoch 9 training [time: 0.12s, train loss: 7.4519]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6940.58it/s]
15 Oct 14:37    INFO  epoch 9 evaluating [time: 0.09s, valid_score: 0.344700]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.1855    mrr@10 : 0.3447    ndcg@10 : 0.2022    hit@10 : 0.7041    precision@10 : 0.1428
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 338.37it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 305.03it/s]
15 Oct 14:37    INFO  epoch 10 training [time: 0.15s, train loss: 7.1695]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 263.19it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 250.25it/s]
15 Oct 14:37    INFO  epoch 11 training [time: 0.18s, train loss: 6.9813]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 298.03it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 284.26it/s]
15 Oct 14:37    INFO  epoch 12 training [time: 0.16s, train loss: 6.7863]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 389.67it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 356.27it/s]
15 Oct 14:37    INFO  epoch 13 training [time: 0.13s, train loss: 6.6051]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 395.40it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 364.65it/s]
15 Oct 14:37    INFO  epoch 14 training [time: 0.13s, train loss: 6.4968]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 386.01it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 354.96it/s]
15 Oct 14:37    INFO  epoch 15 training [time: 0.13s, train loss: 6.3467]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  72%|███████████████████████████████████▌             | 29/40 [00:00<00:00, 285.80it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 285.57it/s]
15 Oct 14:37    INFO  epoch 16 training [time: 0.16s, train loss: 6.2297]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 261.71it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 258.43it/s]
15 Oct 14:37    INFO  epoch 17 training [time: 0.17s, train loss: 6.0621]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 339.05it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 315.82it/s]
15 Oct 14:37    INFO  epoch 18 training [time: 0.14s, train loss: 5.9553]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 37/40 [00:00<00:00, 369.95it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 339.65it/s]
15 Oct 14:37    INFO  epoch 19 training [time: 0.14s, train loss: 5.9542]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6837.74it/s]
15 Oct 14:37    INFO  epoch 19 evaluating [time: 0.09s, valid_score: 0.351100]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.1992    mrr@10 : 0.3511    ndcg@10 : 0.2073    hit@10 : 0.7169    precision@10 : 0.1438
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6765.91it/s]
15 Oct 14:37    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     3.50 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.72 G/30.64 G |
+-------------+----------------+
15 Oct 14:37    INFO  best valid : OrderedDict([('recall@10', 0.1992), ('mrr@10', 0.3511), ('ndcg@10', 0.2073), ('hit@10', 0.7169), ('precision@10', 0.1438)])
15 Oct 14:37    INFO  test result: OrderedDict([('recall@10', 0.2137), ('mrr@10', 0.4401), ('ndcg@10', 0.2529), ('hit@10', 0.7487), ('precision@10', 0.1704)])

[4/12] BPR: {'embedding_size': 32, 'learning_rate': 0.0001}

15 Oct 14:37    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:37    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.0001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:37    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:37    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:37    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:37    INFO  BPR(
  (user_embedding): Embedding(944, 32)
  (item_embedding): Embedding(1683, 32)
  (loss): BPRLoss()
)
Trainable parameters: 84064
15 Oct 14:37    INFO  FLOPs: 64.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 387.30it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 352.20it/s]
15 Oct 14:37    INFO  epoch 0 training [time: 0.14s, train loss: 27.7271]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 359.09it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 324.75it/s]
15 Oct 14:37    INFO  epoch 1 training [time: 0.14s, train loss: 27.7228]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 381.28it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 354.19it/s]
15 Oct 14:37    INFO  epoch 2 training [time: 0.13s, train loss: 27.7209]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 377.76it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 348.79it/s]
15 Oct 14:37    INFO  epoch 3 training [time: 0.13s, train loss: 27.7180]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 375.89it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 346.55it/s]
15 Oct 14:37    INFO  epoch 4 training [time: 0.13s, train loss: 27.7156]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 37/40 [00:00<00:00, 362.14it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 335.10it/s]
15 Oct 14:37    INFO  epoch 5 training [time: 0.14s, train loss: 27.7119]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 369.84it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 323.16it/s]
15 Oct 14:37    INFO  epoch 6 training [time: 0.14s, train loss: 27.7093]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 332.67it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 305.71it/s]
15 Oct 14:37    INFO  epoch 7 training [time: 0.15s, train loss: 27.7046]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  88%|██████████████████████████████████████████▉      | 35/40 [00:00<00:00, 347.14it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 313.55it/s]
15 Oct 14:37    INFO  epoch 8 training [time: 0.14s, train loss: 27.7010]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 376.02it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 341.77it/s]
15 Oct 14:37    INFO  epoch 9 training [time: 0.13s, train loss: 27.6970]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6755.17it/s]
15 Oct 14:37    INFO  epoch 9 evaluating [time: 0.09s, valid_score: 0.022000]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.0071    mrr@10 : 0.022    ndcg@10 : 0.0087    hit@10 : 0.0689    precision@10 : 0.0074
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 279.67it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 251.11it/s]
15 Oct 14:37    INFO  epoch 10 training [time: 0.18s, train loss: 27.6922]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 319.23it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 291.97it/s]
15 Oct 14:37    INFO  epoch 11 training [time: 0.16s, train loss: 27.6880]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 37/40 [00:00<00:00, 369.28it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 337.28it/s]
15 Oct 14:37    INFO  epoch 12 training [time: 0.14s, train loss: 27.6821]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 259.57it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 264.03it/s]
15 Oct 14:37    INFO  epoch 13 training [time: 0.17s, train loss: 27.6733]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  88%|██████████████████████████████████████████▉      | 35/40 [00:00<00:00, 346.29it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 314.25it/s]
15 Oct 14:37    INFO  epoch 14 training [time: 0.15s, train loss: 27.6649]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 338.96it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 317.66it/s]
15 Oct 14:37    INFO  epoch 15 training [time: 0.14s, train loss: 27.6544]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 390.61it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 362.38it/s]
15 Oct 14:37    INFO  epoch 16 training [time: 0.13s, train loss: 27.6432]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 390.90it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 364.11it/s]
15 Oct 14:37    INFO  epoch 17 training [time: 0.13s, train loss: 27.6278]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 383.33it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 352.53it/s]
15 Oct 14:37    INFO  epoch 18 training [time: 0.13s, train loss: 27.6097]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 296.93it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 271.58it/s]
15 Oct 14:37    INFO  epoch 19 training [time: 0.17s, train loss: 27.5883]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5651.86it/s]
15 Oct 14:37    INFO  epoch 19 evaluating [time: 0.11s, valid_score: 0.065100]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.0208    mrr@10 : 0.0651    ndcg@10 : 0.0283    hit@10 : 0.1835    precision@10 : 0.024
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6330.80it/s]
15 Oct 14:37    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     3.70 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.72 G/30.64 G |
+-------------+----------------+
15 Oct 14:37    INFO  best valid : OrderedDict([('recall@10', 0.0208), ('mrr@10', 0.0651), ('ndcg@10', 0.0283), ('hit@10', 0.1835), ('precision@10', 0.024)])
15 Oct 14:37    INFO  test result: OrderedDict([('recall@10', 0.0222), ('mrr@10', 0.0784), ('ndcg@10', 0.0343), ('hit@10', 0.21), ('precision@10', 0.0288)])

[5/12] BPR: {'embedding_size': 32, 'learning_rate': 0.001}

15 Oct 14:37    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:37    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:37    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:37    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:37    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:37    INFO  BPR(
  (user_embedding): Embedding(944, 32)
  (item_embedding): Embedding(1683, 32)
  (loss): BPRLoss()
)
Trainable parameters: 84064
15 Oct 14:37    INFO  FLOPs: 64.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 405.07it/s]
15 Oct 14:37    INFO  epoch 0 training [time: 0.12s, train loss: 27.7251]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 376.25it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 342.62it/s]
15 Oct 14:37    INFO  epoch 1 training [time: 0.13s, train loss: 27.6782]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 298.85it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 288.58it/s]
15 Oct 14:37    INFO  epoch 2 training [time: 0.16s, train loss: 27.5329]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 264.38it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 266.05it/s]
15 Oct 14:37    INFO  epoch 3 training [time: 0.17s, train loss: 26.8899]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 322.39it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 308.32it/s]
15 Oct 14:37    INFO  epoch 4 training [time: 0.15s, train loss: 24.9752]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 37/40 [00:00<00:00, 369.28it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 341.70it/s]
15 Oct 14:37    INFO  epoch 5 training [time: 0.13s, train loss: 21.6269]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 37/40 [00:00<00:00, 364.89it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 339.56it/s]
15 Oct 14:37    INFO  epoch 6 training [time: 0.13s, train loss: 18.2601]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 387.55it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 356.45it/s]
15 Oct 14:37    INFO  epoch 7 training [time: 0.13s, train loss: 16.0649]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 385.55it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 350.00it/s]
15 Oct 14:37    INFO  epoch 8 training [time: 0.13s, train loss: 14.7539]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 259.38it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 254.16it/s]
15 Oct 14:37    INFO  epoch 9 training [time: 0.18s, train loss: 13.9258]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6230.48it/s]
15 Oct 14:37    INFO  epoch 9 evaluating [time: 0.10s, valid_score: 0.304700]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.1365    mrr@10 : 0.3047    ndcg@10 : 0.1612    hit@10 : 0.596    precision@10 : 0.1094
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 313.43it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 299.56it/s]
15 Oct 14:37    INFO  epoch 10 training [time: 0.15s, train loss: 13.3970]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 377.74it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 343.64it/s]
15 Oct 14:37    INFO  epoch 11 training [time: 0.13s, train loss: 12.9344]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 383.05it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 346.56it/s]
15 Oct 14:37    INFO  epoch 12 training [time: 0.13s, train loss: 12.5318]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 327.83it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 304.46it/s]
15 Oct 14:37    INFO  epoch 13 training [time: 0.15s, train loss: 12.1990]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 351.21it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 312.08it/s]
15 Oct 14:37    INFO  epoch 14 training [time: 0.15s, train loss: 11.9354]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 292.83it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 266.07it/s]
15 Oct 14:37    INFO  epoch 15 training [time: 0.17s, train loss: 11.6084]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 336.55it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 311.36it/s]
15 Oct 14:37    INFO  epoch 16 training [time: 0.15s, train loss: 11.3690]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 378.97it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 346.31it/s]
15 Oct 14:37    INFO  epoch 17 training [time: 0.13s, train loss: 11.1005]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 37/40 [00:00<00:00, 364.03it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 336.18it/s]
15 Oct 14:37    INFO  epoch 18 training [time: 0.14s, train loss: 10.8142]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 37/40 [00:00<00:00, 364.40it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 333.23it/s]
15 Oct 14:37    INFO  epoch 19 training [time: 0.14s, train loss: 10.7412]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6709.77it/s]
15 Oct 14:37    INFO  epoch 19 evaluating [time: 0.09s, valid_score: 0.319100]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.1695    mrr@10 : 0.3191    ndcg@10 : 0.1845    hit@10 : 0.6469    precision@10 : 0.1278
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6419.90it/s]
15 Oct 14:37    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     3.50 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.72 G/30.64 G |
+-------------+----------------+
15 Oct 14:37    INFO  best valid : OrderedDict([('recall@10', 0.1695), ('mrr@10', 0.3191), ('ndcg@10', 0.1845), ('hit@10', 0.6469), ('precision@10', 0.1278)])
15 Oct 14:37    INFO  test result: OrderedDict([('recall@10', 0.1961), ('mrr@10', 0.402), ('ndcg@10', 0.2307), ('hit@10', 0.6967), ('precision@10', 0.1539)])

[6/12] BPR: {'embedding_size': 32, 'learning_rate': 0.01}

15 Oct 14:37    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:37    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.01
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:37    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:37    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:37    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:37    INFO  BPR(
  (user_embedding): Embedding(944, 32)
  (item_embedding): Embedding(1683, 32)
  (loss): BPRLoss()
)
Trainable parameters: 84064
15 Oct 14:37    INFO  FLOPs: 64.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 381.60it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 346.64it/s]
15 Oct 14:37    INFO  epoch 0 training [time: 0.13s, train loss: 26.2657]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 339.01it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 317.02it/s]
15 Oct 14:37    INFO  epoch 1 training [time: 0.14s, train loss: 14.2902]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 378.19it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 347.39it/s]
15 Oct 14:37    INFO  epoch 2 training [time: 0.13s, train loss: 10.8524]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  72%|███████████████████████████████████▌             | 29/40 [00:00<00:00, 280.88it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 279.58it/s]
15 Oct 14:37    INFO  epoch 3 training [time: 0.16s, train loss: 9.1773]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 294.25it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 276.15it/s]
15 Oct 14:37    INFO  epoch 4 training [time: 0.16s, train loss: 8.4967]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 290.09it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 282.58it/s]
15 Oct 14:37    INFO  epoch 5 training [time: 0.16s, train loss: 7.6126]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 384.41it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 354.78it/s]
15 Oct 14:37    INFO  epoch 6 training [time: 0.13s, train loss: 7.1444]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 370.83it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 343.34it/s]
15 Oct 14:37    INFO  epoch 7 training [time: 0.13s, train loss: 6.7450]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 378.98it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 349.97it/s]
15 Oct 14:37    INFO  epoch 8 training [time: 0.13s, train loss: 6.2993]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 371.89it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 342.59it/s]
15 Oct 14:37    INFO  epoch 9 training [time: 0.13s, train loss: 5.9663]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6410.78it/s]
15 Oct 14:37    INFO  epoch 9 evaluating [time: 0.09s, valid_score: 0.342100]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.1843    mrr@10 : 0.3421    ndcg@10 : 0.201    hit@10 : 0.6946    precision@10 : 0.1439
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 37/40 [00:00<00:00, 365.93it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 317.91it/s]
15 Oct 14:37    INFO  epoch 10 training [time: 0.14s, train loss: 5.6627]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 37/40 [00:00<00:00, 367.12it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 335.94it/s]
15 Oct 14:37    INFO  epoch 11 training [time: 0.14s, train loss: 5.4090]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  78%|█████████████████████████████████████▉           | 31/40 [00:00<00:00, 304.85it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 287.80it/s]
15 Oct 14:37    INFO  epoch 12 training [time: 0.16s, train loss: 5.2104]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 358.44it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 331.51it/s]
15 Oct 14:37    INFO  epoch 13 training [time: 0.14s, train loss: 4.9575]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  60%|█████████████████████████████▍                   | 24/40 [00:00<00:00, 234.61it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 246.15it/s]
15 Oct 14:37    INFO  epoch 14 training [time: 0.18s, train loss: 4.7620]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 399.75it/s]
15 Oct 14:37    INFO  epoch 15 training [time: 0.12s, train loss: 4.6805]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 279.72it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 262.49it/s]
15 Oct 14:37    INFO  epoch 16 training [time: 0.17s, train loss: 4.5486]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  72%|███████████████████████████████████▌             | 29/40 [00:00<00:00, 280.89it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 263.16it/s]
15 Oct 14:37    INFO  epoch 17 training [time: 0.17s, train loss: 4.3706]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 315.65it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 290.60it/s]
15 Oct 14:37    INFO  epoch 18 training [time: 0.16s, train loss: 4.2669]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 389.68it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 361.31it/s]
15 Oct 14:37    INFO  epoch 19 training [time: 0.13s, train loss: 4.2303]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6738.94it/s]
15 Oct 14:37    INFO  epoch 19 evaluating [time: 0.09s, valid_score: 0.358100]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.1904    mrr@10 : 0.3581    ndcg@10 : 0.2038    hit@10 : 0.7169    precision@10 : 0.1393
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6717.17it/s]
15 Oct 14:37    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     4.10 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.73 G/30.64 G |
+-------------+----------------+
15 Oct 14:37    INFO  best valid : OrderedDict([('recall@10', 0.1904), ('mrr@10', 0.3581), ('ndcg@10', 0.2038), ('hit@10', 0.7169), ('precision@10', 0.1393)])
15 Oct 14:37    INFO  test result: OrderedDict([('recall@10', 0.2095), ('mrr@10', 0.3976), ('ndcg@10', 0.2354), ('hit@10', 0.7423), ('precision@10', 0.1629)])

[7/12] BPR: {'embedding_size': 64, 'learning_rate': 0.0001}

15 Oct 14:37    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:37    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.0001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:37    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:37    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:37    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:37    INFO  BPR(
  (user_embedding): Embedding(944, 64)
  (item_embedding): Embedding(1683, 64)
  (loss): BPRLoss()
)
Trainable parameters: 168128
15 Oct 14:37    INFO  FLOPs: 128.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 327.08it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 308.79it/s]
15 Oct 14:37    INFO  epoch 0 training [time: 0.15s, train loss: 27.7273]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  78%|█████████████████████████████████████▉           | 31/40 [00:00<00:00, 308.10it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 288.05it/s]
15 Oct 14:37    INFO  epoch 1 training [time: 0.16s, train loss: 27.7223]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 358.29it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 324.48it/s]
15 Oct 14:37    INFO  epoch 2 training [time: 0.14s, train loss: 27.7166]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 379.99it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 347.30it/s]
15 Oct 14:37    INFO  epoch 3 training [time: 0.14s, train loss: 27.7112]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 335.80it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 306.73it/s]
15 Oct 14:37    INFO  epoch 4 training [time: 0.15s, train loss: 27.7048]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 311.79it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 287.81it/s]
15 Oct 14:37    INFO  epoch 5 training [time: 0.16s, train loss: 27.6994]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 277.79it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 277.58it/s]
15 Oct 14:37    INFO  epoch 6 training [time: 0.17s, train loss: 27.6916]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  88%|██████████████████████████████████████████▉      | 35/40 [00:00<00:00, 345.20it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 321.32it/s]
15 Oct 14:37    INFO  epoch 7 training [time: 0.14s, train loss: 27.6857]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 329.42it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 310.88it/s]
15 Oct 14:37    INFO  epoch 8 training [time: 0.15s, train loss: 27.6798]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 353.48it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 321.40it/s]
15 Oct 14:37    INFO  epoch 9 training [time: 0.14s, train loss: 27.6707]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6456.86it/s]
15 Oct 14:37    INFO  epoch 9 evaluating [time: 0.10s, valid_score: 0.030500]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.0085    mrr@10 : 0.0305    ndcg@10 : 0.012    hit@10 : 0.088    precision@10 : 0.0097
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 376.77it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 345.75it/s]
15 Oct 14:37    INFO  epoch 10 training [time: 0.13s, train loss: 27.6601]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 37/40 [00:00<00:00, 366.31it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 331.95it/s]
15 Oct 14:37    INFO  epoch 11 training [time: 0.14s, train loss: 27.6482]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 277.70it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 263.70it/s]
15 Oct 14:37    INFO  epoch 12 training [time: 0.17s, train loss: 27.6375]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  78%|█████████████████████████████████████▉           | 31/40 [00:00<00:00, 309.74it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 294.32it/s]
15 Oct 14:37    INFO  epoch 13 training [time: 0.16s, train loss: 27.6218]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 324.67it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 298.60it/s]
15 Oct 14:37    INFO  epoch 14 training [time: 0.15s, train loss: 27.6039]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 352.60it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 322.56it/s]
15 Oct 14:37    INFO  epoch 15 training [time: 0.14s, train loss: 27.5833]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 351.95it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 325.29it/s]
15 Oct 14:37    INFO  epoch 16 training [time: 0.14s, train loss: 27.5554]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 372.14it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 338.97it/s]
15 Oct 14:37    INFO  epoch 17 training [time: 0.14s, train loss: 27.5270]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 358.06it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 315.03it/s]
15 Oct 14:37    INFO  epoch 18 training [time: 0.15s, train loss: 27.4915]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 298.82it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 277.53it/s]
15 Oct 14:37    INFO  epoch 19 training [time: 0.16s, train loss: 27.4488]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6467.57it/s]
15 Oct 14:37    INFO  epoch 19 evaluating [time: 0.09s, valid_score: 0.097700]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.031    mrr@10 : 0.0977    ndcg@10 : 0.0429    hit@10 : 0.2545    precision@10 : 0.0364
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6401.80it/s]
15 Oct 14:37    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     4.20 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.73 G/30.64 G |
+-------------+----------------+
15 Oct 14:37    INFO  best valid : OrderedDict([('recall@10', 0.031), ('mrr@10', 0.0977), ('ndcg@10', 0.0429), ('hit@10', 0.2545), ('precision@10', 0.0364)])
15 Oct 14:37    INFO  test result: OrderedDict([('recall@10', 0.0272), ('mrr@10', 0.0984), ('ndcg@10', 0.0429), ('hit@10', 0.2428), ('precision@10', 0.0365)])

[8/12] BPR: {'embedding_size': 64, 'learning_rate': 0.001}

15 Oct 14:37    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:37    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:37    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:37    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:37    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:37    INFO  BPR(
  (user_embedding): Embedding(944, 64)
  (item_embedding): Embedding(1683, 64)
  (loss): BPRLoss()
)
Trainable parameters: 168128
15 Oct 14:37    INFO  FLOPs: 128.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 373.43it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 324.92it/s]
15 Oct 14:37    INFO  epoch 0 training [time: 0.14s, train loss: 27.7240]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  78%|█████████████████████████████████████▉           | 31/40 [00:00<00:00, 303.91it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 280.02it/s]
15 Oct 14:37    INFO  epoch 1 training [time: 0.16s, train loss: 27.6345]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 327.48it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 310.07it/s]
15 Oct 14:37    INFO  epoch 2 training [time: 0.15s, train loss: 27.3318]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 326.31it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 300.14it/s]
15 Oct 14:37    INFO  epoch 3 training [time: 0.15s, train loss: 26.0469]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  88%|██████████████████████████████████████████▉      | 35/40 [00:00<00:00, 343.15it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 309.27it/s]
15 Oct 14:37    INFO  epoch 4 training [time: 0.15s, train loss: 22.7424]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 327.72it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 303.07it/s]
15 Oct 14:37    INFO  epoch 5 training [time: 0.15s, train loss: 18.4891]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 337.58it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 308.99it/s]
15 Oct 14:37    INFO  epoch 6 training [time: 0.15s, train loss: 15.6431]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 296.00it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 274.43it/s]
15 Oct 14:37    INFO  epoch 7 training [time: 0.17s, train loss: 14.2810]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  72%|███████████████████████████████████▌             | 29/40 [00:00<00:00, 287.40it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 272.97it/s]
15 Oct 14:37    INFO  epoch 8 training [time: 0.17s, train loss: 13.4723]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 337.92it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 309.67it/s]
15 Oct 14:37    INFO  epoch 9 training [time: 0.15s, train loss: 12.8887]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6344.05it/s]
15 Oct 14:37    INFO  epoch 9 evaluating [time: 0.10s, valid_score: 0.299100]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.1395    mrr@10 : 0.2991    ndcg@10 : 0.1601    hit@10 : 0.6119    precision@10 : 0.112
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  88%|██████████████████████████████████████████▉      | 35/40 [00:00<00:00, 342.16it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 310.04it/s]
15 Oct 14:37    INFO  epoch 10 training [time: 0.15s, train loss: 12.4353]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 355.19it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 324.76it/s]
15 Oct 14:37    INFO  epoch 11 training [time: 0.14s, train loss: 11.9655]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 354.21it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 322.67it/s]
15 Oct 14:37    INFO  epoch 12 training [time: 0.14s, train loss: 11.5190]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  78%|█████████████████████████████████████▉           | 31/40 [00:00<00:00, 308.04it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 281.38it/s]
15 Oct 14:37    INFO  epoch 13 training [time: 0.16s, train loss: 11.1336]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 294.13it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 263.21it/s]
15 Oct 14:37    INFO  epoch 14 training [time: 0.18s, train loss: 10.7970]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 327.36it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 297.56it/s]
15 Oct 14:37    INFO  epoch 15 training [time: 0.15s, train loss: 10.4318]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 310.32it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 284.94it/s]
15 Oct 14:37    INFO  epoch 16 training [time: 0.16s, train loss: 10.1359]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 352.83it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 321.52it/s]
15 Oct 14:37    INFO  epoch 17 training [time: 0.15s, train loss: 9.8093]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 37/40 [00:00<00:00, 363.68it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 329.58it/s]
15 Oct 14:37    INFO  epoch 18 training [time: 0.14s, train loss: 9.5000]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 370.97it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 337.22it/s]
15 Oct 14:37    INFO  epoch 19 training [time: 0.14s, train loss: 9.4030]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5937.96it/s]
15 Oct 14:37    INFO  epoch 19 evaluating [time: 0.10s, valid_score: 0.347400]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.181    mrr@10 : 0.3474    ndcg@10 : 0.1994    hit@10 : 0.6808    precision@10 : 0.1382
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6308.91it/s]
15 Oct 14:37    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     3.00 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.73 G/30.64 G |
+-------------+----------------+
15 Oct 14:37    INFO  best valid : OrderedDict([('recall@10', 0.181), ('mrr@10', 0.3474), ('ndcg@10', 0.1994), ('hit@10', 0.6808), ('precision@10', 0.1382)])
15 Oct 14:37    INFO  test result: OrderedDict([('recall@10', 0.2085), ('mrr@10', 0.4304), ('ndcg@10', 0.2494), ('hit@10', 0.7275), ('precision@10', 0.167)])

[9/12] BPR: {'embedding_size': 64, 'learning_rate': 0.01}

15 Oct 14:37    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:37    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.01
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:37    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:37    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:37    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:37    INFO  BPR(
  (user_embedding): Embedding(944, 64)
  (item_embedding): Embedding(1683, 64)
  (loss): BPRLoss()
)
Trainable parameters: 168128
15 Oct 14:37    INFO  FLOPs: 128.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 375.62it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 341.55it/s]
15 Oct 14:37    INFO  epoch 0 training [time: 0.14s, train loss: 25.2600]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 371.46it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 339.37it/s]
15 Oct 14:37    INFO  epoch 1 training [time: 0.14s, train loss: 13.0037]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 295.07it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 272.20it/s]
15 Oct 14:37    INFO  epoch 2 training [time: 0.17s, train loss: 9.8429]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  88%|██████████████████████████████████████████▉      | 35/40 [00:00<00:00, 348.15it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 323.58it/s]
15 Oct 14:37    INFO  epoch 3 training [time: 0.14s, train loss: 7.9576]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 376.26it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 340.14it/s]
15 Oct 14:37    INFO  epoch 4 training [time: 0.14s, train loss: 7.1204]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 374.24it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 339.61it/s]
15 Oct 14:37    INFO  epoch 5 training [time: 0.14s, train loss: 6.1491]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 371.26it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 338.20it/s]
15 Oct 14:37    INFO  epoch 6 training [time: 0.14s, train loss: 5.5717]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 374.07it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 342.00it/s]
15 Oct 14:37    INFO  epoch 7 training [time: 0.14s, train loss: 5.0738]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 377.72it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 343.48it/s]
15 Oct 14:37    INFO  epoch 8 training [time: 0.14s, train loss: 4.6037]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 277.16it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 273.76it/s]
15 Oct 14:37    INFO  epoch 9 training [time: 0.17s, train loss: 4.3014]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6598.95it/s]
15 Oct 14:37    INFO  epoch 9 evaluating [time: 0.09s, valid_score: 0.330500]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.1858    mrr@10 : 0.3305    ndcg@10 : 0.1956    hit@10 : 0.7041    precision@10 : 0.1392
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 351.49it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 319.21it/s]
15 Oct 14:37    INFO  epoch 10 training [time: 0.15s, train loss: 3.9565]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 375.46it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 341.68it/s]
15 Oct 14:37    INFO  epoch 11 training [time: 0.14s, train loss: 3.7091]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 377.52it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 342.56it/s]
15 Oct 14:37    INFO  epoch 12 training [time: 0.14s, train loss: 3.4709]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 356.92it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 329.01it/s]
15 Oct 14:37    INFO  epoch 13 training [time: 0.14s, train loss: 3.2957]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 255.59it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 249.37it/s]
15 Oct 14:37    INFO  epoch 14 training [time: 0.18s, train loss: 3.1316]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 272.59it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 261.12it/s]
15 Oct 14:37    INFO  epoch 15 training [time: 0.17s, train loss: 3.0091]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 298.08it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 282.04it/s]
15 Oct 14:37    INFO  epoch 16 training [time: 0.16s, train loss: 2.8710]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 358.80it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 330.94it/s]
15 Oct 14:37    INFO  epoch 17 training [time: 0.14s, train loss: 2.7255]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  92%|█████████████████████████████████████████████▎   | 37/40 [00:00<00:00, 361.16it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 329.85it/s]
15 Oct 14:37    INFO  epoch 18 training [time: 0.14s, train loss: 2.5715]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 373.52it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 334.80it/s]
15 Oct 14:37    INFO  epoch 19 training [time: 0.14s, train loss: 2.5139]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6477.18it/s]
15 Oct 14:37    INFO  epoch 19 evaluating [time: 0.09s, valid_score: 0.315800]
15 Oct 14:37    INFO  valid result:
recall@10 : 0.1784    mrr@10 : 0.3158    ndcg@10 : 0.1821    hit@10 : 0.684    precision@10 : 0.1262
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6619.76it/s]
15 Oct 14:37    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     3.90 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.73 G/30.64 G |
+-------------+----------------+
15 Oct 14:37    INFO  best valid : OrderedDict([('recall@10', 0.1858), ('mrr@10', 0.3305), ('ndcg@10', 0.1956), ('hit@10', 0.7041), ('precision@10', 0.1392)])
15 Oct 14:37    INFO  test result: OrderedDict([('recall@10', 0.1963), ('mrr@10', 0.3667), ('ndcg@10', 0.2147), ('hit@10', 0.72), ('precision@10', 0.1477)])

[10/12] BPR: {'embedding_size': 128, 'learning_rate': 0.0001}

15 Oct 14:37    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:37    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.0001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 128
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:37    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:37    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:37    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:37    INFO  BPR(
  (user_embedding): Embedding(944, 128)
  (item_embedding): Embedding(1683, 128)
  (loss): BPRLoss()
)
Trainable parameters: 336256
15 Oct 14:37    INFO  FLOPs: 256.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 265.21it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 250.55it/s]
15 Oct 14:38    INFO  epoch 0 training [time: 0.18s, train loss: 27.7254]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 268.77it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 261.12it/s]
15 Oct 14:38    INFO  epoch 1 training [time: 0.17s, train loss: 27.7143]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  72%|███████████████████████████████████▌             | 29/40 [00:00<00:00, 288.17it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 243.94it/s]
15 Oct 14:38    INFO  epoch 2 training [time: 0.18s, train loss: 27.7030]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  57%|████████████████████████████▏                    | 23/40 [00:00<00:00, 222.68it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 215.76it/s]
15 Oct 14:38    INFO  epoch 3 training [time: 0.21s, train loss: 27.6898]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 273.75it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 254.17it/s]
15 Oct 14:38    INFO  epoch 4 training [time: 0.18s, train loss: 27.6797]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  78%|█████████████████████████████████████▉           | 31/40 [00:00<00:00, 307.50it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 271.71it/s]
15 Oct 14:38    INFO  epoch 5 training [time: 0.17s, train loss: 27.6689]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 291.95it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 270.98it/s]
15 Oct 14:38    INFO  epoch 6 training [time: 0.17s, train loss: 27.6539]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 313.22it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 289.54it/s]
15 Oct 14:38    INFO  epoch 7 training [time: 0.16s, train loss: 27.6375]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 293.76it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 244.47it/s]
15 Oct 14:38    INFO  epoch 8 training [time: 0.19s, train loss: 27.6216]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 275.23it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 264.12it/s]
15 Oct 14:38    INFO  epoch 9 training [time: 0.17s, train loss: 27.6040]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6243.37it/s]
15 Oct 14:38    INFO  epoch 9 evaluating [time: 0.10s, valid_score: 0.029700]
15 Oct 14:38    INFO  valid result:
recall@10 : 0.0074    mrr@10 : 0.0297    ndcg@10 : 0.011    hit@10 : 0.0891    precision@10 : 0.0094
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 328.31it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 295.75it/s]
15 Oct 14:38    INFO  epoch 10 training [time: 0.16s, train loss: 27.5791]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 324.45it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 293.40it/s]
15 Oct 14:38    INFO  epoch 11 training [time: 0.16s, train loss: 27.5558]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 322.11it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 289.39it/s]
15 Oct 14:38    INFO  epoch 12 training [time: 0.16s, train loss: 27.5263]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 332.97it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 304.84it/s]
15 Oct 14:38    INFO  epoch 13 training [time: 0.15s, train loss: 27.4933]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  62%|██████████████████████████████▋                  | 25/40 [00:00<00:00, 249.05it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 235.59it/s]
15 Oct 14:38    INFO  epoch 14 training [time: 0.19s, train loss: 27.4496]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  60%|█████████████████████████████▍                   | 24/40 [00:00<00:00, 237.60it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 240.50it/s]
15 Oct 14:38    INFO  epoch 15 training [time: 0.19s, train loss: 27.3976]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 264.58it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 242.24it/s]
15 Oct 14:38    INFO  epoch 16 training [time: 0.19s, train loss: 27.3360]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 317.22it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 292.38it/s]
15 Oct 14:38    INFO  epoch 17 training [time: 0.16s, train loss: 27.2632]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  60%|█████████████████████████████▍                   | 24/40 [00:00<00:00, 236.91it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 243.40it/s]
15 Oct 14:38    INFO  epoch 18 training [time: 0.18s, train loss: 27.1744]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  72%|███████████████████████████████████▌             | 29/40 [00:00<00:00, 289.26it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 263.82it/s]
15 Oct 14:38    INFO  epoch 19 training [time: 0.18s, train loss: 27.0705]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5911.26it/s]
15 Oct 14:38    INFO  epoch 19 evaluating [time: 0.10s, valid_score: 0.127300]
15 Oct 14:38    INFO  valid result:
recall@10 : 0.0378    mrr@10 : 0.1273    ndcg@10 : 0.0589    hit@10 : 0.3097    precision@10 : 0.0515
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6284.88it/s]
15 Oct 14:38    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     3.70 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.73 G/30.64 G |
+-------------+----------------+
15 Oct 14:38    INFO  best valid : OrderedDict([('recall@10', 0.0378), ('mrr@10', 0.1273), ('ndcg@10', 0.0589), ('hit@10', 0.3097), ('precision@10', 0.0515)])
15 Oct 14:38    INFO  test result: OrderedDict([('recall@10', 0.0439), ('mrr@10', 0.159), ('ndcg@10', 0.072), ('hit@10', 0.3489), ('precision@10', 0.0606)])

[11/12] BPR: {'embedding_size': 128, 'learning_rate': 0.001}

15 Oct 14:38    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:38    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 128
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:38    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:38    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:38    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:38    INFO  BPR(
  (user_embedding): Embedding(944, 128)
  (item_embedding): Embedding(1683, 128)
  (loss): BPRLoss()
)
Trainable parameters: 336256
15 Oct 14:38    INFO  FLOPs: 256.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 321.51it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 283.25it/s]
15 Oct 14:38    INFO  epoch 0 training [time: 0.16s, train loss: 27.7167]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  62%|██████████████████████████████▋                  | 25/40 [00:00<00:00, 247.11it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 225.02it/s]
15 Oct 14:38    INFO  epoch 1 training [time: 0.20s, train loss: 27.5173]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  57%|████████████████████████████▏                    | 23/40 [00:00<00:00, 223.50it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 218.19it/s]
15 Oct 14:38    INFO  epoch 2 training [time: 0.21s, train loss: 26.8167]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  78%|█████████████████████████████████████▉           | 31/40 [00:00<00:00, 301.88it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 285.93it/s]
15 Oct 14:38    INFO  epoch 3 training [time: 0.16s, train loss: 24.2064]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 332.78it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 304.07it/s]
15 Oct 14:38    INFO  epoch 4 training [time: 0.15s, train loss: 19.4208]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 294.45it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 270.00it/s]
15 Oct 14:38    INFO  epoch 5 training [time: 0.17s, train loss: 15.5424]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  72%|███████████████████████████████████▌             | 29/40 [00:00<00:00, 288.72it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 272.33it/s]
15 Oct 14:38    INFO  epoch 6 training [time: 0.17s, train loss: 13.6943]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  55%|██████████████████████████▉                      | 22/40 [00:00<00:00, 217.33it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 207.89it/s]
15 Oct 14:38    INFO  epoch 7 training [time: 0.21s, train loss: 12.7211]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 318.21it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 294.28it/s]
15 Oct 14:38    INFO  epoch 8 training [time: 0.16s, train loss: 11.9612]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 325.67it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 285.96it/s]
15 Oct 14:38    INFO  epoch 9 training [time: 0.16s, train loss: 11.3082]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6498.55it/s]
15 Oct 14:38    INFO  epoch 9 evaluating [time: 0.10s, valid_score: 0.328300]
15 Oct 14:38    INFO  valid result:
recall@10 : 0.1754    mrr@10 : 0.3283    ndcg@10 : 0.1912    hit@10 : 0.6691    precision@10 : 0.1337
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 272.21it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 255.88it/s]
15 Oct 14:38    INFO  epoch 10 training [time: 0.18s, train loss: 10.7337]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 257.57it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 252.56it/s]
15 Oct 14:38    INFO  epoch 11 training [time: 0.18s, train loss: 10.2006]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 258.16it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 243.66it/s]
15 Oct 14:38    INFO  epoch 12 training [time: 0.19s, train loss: 9.7312]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 278.23it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 260.43it/s]
15 Oct 14:38    INFO  epoch 13 training [time: 0.18s, train loss: 9.3629]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  78%|█████████████████████████████████████▉           | 31/40 [00:00<00:00, 304.72it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 276.36it/s]
15 Oct 14:38    INFO  epoch 14 training [time: 0.16s, train loss: 9.0330]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 329.74it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 299.00it/s]
15 Oct 14:38    INFO  epoch 15 training [time: 0.15s, train loss: 8.7247]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 319.95it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 294.17it/s]
15 Oct 14:38    INFO  epoch 16 training [time: 0.16s, train loss: 8.4420]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  72%|███████████████████████████████████▌             | 29/40 [00:00<00:00, 284.18it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 270.44it/s]
15 Oct 14:38    INFO  epoch 17 training [time: 0.17s, train loss: 8.1667]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  52%|█████████████████████████▋                       | 21/40 [00:00<00:00, 206.01it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 214.17it/s]
15 Oct 14:38    INFO  epoch 18 training [time: 0.21s, train loss: 7.8821]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 268.57it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 260.79it/s]
15 Oct 14:38    INFO  epoch 19 training [time: 0.17s, train loss: 7.8021]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6332.81it/s]
15 Oct 14:38    INFO  epoch 19 evaluating [time: 0.10s, valid_score: 0.356500]
15 Oct 14:38    INFO  valid result:
recall@10 : 0.1943    mrr@10 : 0.3565    ndcg@10 : 0.2113    hit@10 : 0.7105    precision@10 : 0.1488
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6487.39it/s]
15 Oct 14:38    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     3.80 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.73 G/30.64 G |
+-------------+----------------+
15 Oct 14:38    INFO  best valid : OrderedDict([('recall@10', 0.1943), ('mrr@10', 0.3565), ('ndcg@10', 0.2113), ('hit@10', 0.7105), ('precision@10', 0.1488)])
15 Oct 14:38    INFO  test result: OrderedDict([('recall@10', 0.2258), ('mrr@10', 0.4587), ('ndcg@10', 0.2691), ('hit@10', 0.7529), ('precision@10', 0.1813)])

[12/12] BPR: {'embedding_size': 128, 'learning_rate': 0.01}

15 Oct 14:38    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:38    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.01
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 128
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:38    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:38    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:38    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:38    INFO  BPR(
  (user_embedding): Embedding(944, 128)
  (item_embedding): Embedding(1683, 128)
  (loss): BPRLoss()
)
Trainable parameters: 336256
15 Oct 14:38    INFO  FLOPs: 256.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  72%|███████████████████████████████████▌             | 29/40 [00:00<00:00, 281.68it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 267.47it/s]
15 Oct 14:38    INFO  epoch 0 training [time: 0.17s, train loss: 23.8633]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 331.93it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 299.42it/s]
15 Oct 14:38    INFO  epoch 1 training [time: 0.15s, train loss: 11.3476]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 334.08it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 309.31it/s]
15 Oct 14:38    INFO  epoch 2 training [time: 0.15s, train loss: 8.1615]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 255.17it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 250.47it/s]
15 Oct 14:38    INFO  epoch 3 training [time: 0.18s, train loss: 6.4449]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 278.07it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 253.92it/s]
15 Oct 14:38    INFO  epoch 4 training [time: 0.18s, train loss: 5.5213]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 270.39it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 244.17it/s]
15 Oct 14:38    INFO  epoch 5 training [time: 0.18s, train loss: 4.5565]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 254.72it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 256.11it/s]
15 Oct 14:38    INFO  epoch 6 training [time: 0.18s, train loss: 3.9648]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 329.74it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 304.64it/s]
15 Oct 14:38    INFO  epoch 7 training [time: 0.15s, train loss: 3.4699]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 328.14it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 297.42it/s]
15 Oct 14:38    INFO  epoch 8 training [time: 0.15s, train loss: 3.0429]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 329.30it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 303.85it/s]
15 Oct 14:38    INFO  epoch 9 training [time: 0.15s, train loss: 2.7160]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6280.51it/s]
15 Oct 14:38    INFO  epoch 9 evaluating [time: 0.10s, valid_score: 0.318200]
15 Oct 14:38    INFO  valid result:
recall@10 : 0.1753    mrr@10 : 0.3182    ndcg@10 : 0.1818    hit@10 : 0.6819    precision@10 : 0.1282
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 322.73it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 297.23it/s]
15 Oct 14:38    INFO  epoch 10 training [time: 0.16s, train loss: 2.5080]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 255.97it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 246.66it/s]
15 Oct 14:38    INFO  epoch 11 training [time: 0.18s, train loss: 2.2377]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  78%|█████████████████████████████████████▉           | 31/40 [00:00<00:00, 309.33it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 285.47it/s]
15 Oct 14:38    INFO  epoch 12 training [time: 0.16s, train loss: 2.0633]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 265.64it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 264.14it/s]
15 Oct 14:38    INFO  epoch 13 training [time: 0.17s, train loss: 1.9233]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 319.41it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 294.80it/s]
15 Oct 14:38    INFO  epoch 14 training [time: 0.16s, train loss: 1.7922]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 326.64it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 295.93it/s]
15 Oct 14:38    INFO  epoch 15 training [time: 0.16s, train loss: 1.6589]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 299.70it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 282.23it/s]
15 Oct 14:38    INFO  epoch 16 training [time: 0.16s, train loss: 1.5669]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 254.70it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 239.78it/s]
15 Oct 14:38    INFO  epoch 17 training [time: 0.19s, train loss: 1.4456]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 334.58it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 308.21it/s]
15 Oct 14:38    INFO  epoch 18 training [time: 0.15s, train loss: 1.3183]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 327.59it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 298.18it/s]
15 Oct 14:38    INFO  epoch 19 training [time: 0.15s, train loss: 1.3070]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6211.25it/s]
15 Oct 14:38    INFO  epoch 19 evaluating [time: 0.10s, valid_score: 0.303500]
15 Oct 14:38    INFO  valid result:
recall@10 : 0.1611    mrr@10 : 0.3035    ndcg@10 : 0.1657    hit@10 : 0.6479    precision@10 : 0.1117
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6097.63it/s]
15 Oct 14:38    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |     3.60 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.73 G/30.64 G |
+-------------+----------------+
15 Oct 14:38    INFO  best valid : OrderedDict([('recall@10', 0.1753), ('mrr@10', 0.3182), ('ndcg@10', 0.1818), ('hit@10', 0.6819), ('precision@10', 0.1282)])
15 Oct 14:38    INFO  test result: OrderedDict([('recall@10', 0.1824), ('mrr@10', 0.3419), ('ndcg@10', 0.1903), ('hit@10', 0.6988), ('precision@10', 0.1286)])

Saved to:
/home/kasparas/Desktop/MScCS/RecommenderSystems/RecBole_DSAIT4335_Group_18/tuning_results/BPR_tuning.csv

Best configuration:

,embedding_size,learning_rate,valid_score,recall@10,mrr@10,ndcg@10,hit@10,precision@10
0,32,0.01,0.3581,0.1904,0.3581,0.2038,0.7169,0.1393

In [17]:
slim_space = {
    "alpha": [0.0001, 0.001, 0.01, 0.1],
    "l1_ratio": [0.1, 0.5, 0.9]
}

slim_results = tune_model(
    name="SLIM",
    model="SLIMElastic",
    config_path=CONFIG_ROOT / "SLIMElastic" / "ml-100k.yaml",
    search_space=slim_space
)

Tuning SLIM
Number of experiments: 12
============================================================
[1/12] SLIM: {'alpha': 0.0001, 'l1_ratio': 0.1}

15 Oct 14:38    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:38    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[2/12] SLIM: {'alpha': 0.0001, 'l1_ratio': 0.5}

15 Oct 14:38    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:38    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[3/12] SLIM: {'alpha': 0.0001, 'l1_ratio': 0.9}

15 Oct 14:38    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:38    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[4/12] SLIM: {'alpha': 0.001, 'l1_ratio': 0.1}

15 Oct 14:38    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:38    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[5/12] SLIM: {'alpha': 0.001, 'l1_ratio': 0.5}

15 Oct 14:39    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:39    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[6/12] SLIM: {'alpha': 0.001, 'l1_ratio': 0.9}

15 Oct 14:39    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:39    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[7/12] SLIM: {'alpha': 0.01, 'l1_ratio': 0.1}

15 Oct 14:39    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:39    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[8/12] SLIM: {'alpha': 0.01, 'l1_ratio': 0.5}

15 Oct 14:39    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:39    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[9/12] SLIM: {'alpha': 0.01, 'l1_ratio': 0.9}

15 Oct 14:39    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:39    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[10/12] SLIM: {'alpha': 0.1, 'l1_ratio': 0.1}

15 Oct 14:39    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:39    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[11/12] SLIM: {'alpha': 0.1, 'l1_ratio': 0.5}

15 Oct 14:39    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:39    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[12/12] SLIM: {'alpha': 0.1, 'l1_ratio': 0.9}

15 Oct 14:40    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:40    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

Saved to:
/home/kasparas/Desktop/MScCS/RecommenderSystems/RecBole_DSAIT4335_Group_18/tuning_results/SLIM_tuning.csv

Best configuration:

,alpha,l1_ratio,valid_score,recall@10,mrr@10,ndcg@10,hit@10,precision@10
0,0.1,0.1,0.4165,0.2271,0.4165,0.2495,0.7625,0.1709

In [18]:
ease_space = {
    "reg_weight": [10, 50, 100, 200, 500, 1000]
}

ease_results = tune_model(
    name="EASE",
    model="EASE",
    config_path=CONFIG_ROOT / "EASE" / "ml-100k.yaml",
    search_space=ease_space
)

Tuning EASE
Number of experiments: 6
============================================================
[1/6] EASE: {'reg_weight': 10}

15 Oct 14:40    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:40    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[2/6] EASE: {'reg_weight': 50}

15 Oct 14:40    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:40    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[3/6] EASE: {'reg_weight': 100}

15 Oct 14:40    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:40    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[4/6] EASE: {'reg_weight': 200}

15 Oct 14:40    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:40    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[5/6] EASE: {'reg_weight': 500}

15 Oct 14:40    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:40    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[6/6] EASE: {'reg_weight': 1000}

15 Oct 14:40    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:40    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

Saved to:
/home/kasparas/Desktop/MScCS/RecommenderSystems/RecBole_DSAIT4335_Group_18/tuning_results/EASE_tuning.csv

Best configuration:

   reg_weight  valid_score  recall@10  mrr@10  ndcg@10  hit@10  precision@10
0         500       0.4189     0.2386  0.4189   0.2568  0.7815        0.1766

In [19]:
fism_space = {
    "embedding_size": [32, 64],
    "learning_rate": [0.001, 0.005],
    "alpha": [0.5],
    "reg_weights": [
        [0.0001, 0.0001],
        [0.001, 0.001],
    ],
}

fism_results = tune_model(
    name="FISM",
    model="FISM",
    config_path=CONFIG_ROOT / "FISM" / "ml-100k.yaml",
    search_space=fism_space,
)

Tuning FISM
Number of experiments: 8
============================================================
[1/8] FISM: {'embedding_size': 32, 'learning_rate': 0.001, 'alpha': 0.5, 'reg_weights': [0.0001, 0.0001]}

15 Oct 14:40    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:40    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
split_to = 0
reg_weights = [0.0001, 0.0001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:40    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:40    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:40    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:40    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
15 Oct 14:40    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
15 Oct 14:40    INFO  FISM(
  (item_src_embedding): Embedding(1683, 32, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 32, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 110339
15 Oct 14:40    INFO  FLOPs: 18944.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:05, 14.23it/s]:   5%|██▌                                                | 4/79 [00:00<00:05, 13.38it/s]:   8%|███▊                                               | 6/79 [00:00<00:05, 13.15it/s]:  10%|█████▏                                             | 8/79 [00:00<00:05, 12.45it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 12.46it/s]:  15%|███████▌                                          | 12/79 [00:00<00:05, 12.73it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 12.64it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 12.56it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:04, 12.45it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:04, 12.16it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 12.15it/s]:  30%|███████████████▏                                  | 24/79 [00:01<00:04, 12.37it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 12.67it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:03, 12.87it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:03, 12.92it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 12.83it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 12.83it/s]:  46%|██████████████████████▊                           | 36/79 [00:02<00:03, 12.86it/s]:  48%|████████████████████████                          | 38/79 [00:02<00:03, 12.74it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 12.54it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:02, 12.43it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 12.33it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 12.36it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:03<00:02, 12.21it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:03<00:02, 12.56it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 12.54it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:01, 12.55it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 12.60it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 12.30it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:04<00:01, 12.15it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:04<00:01, 12.48it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 12.59it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 12.78it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 12.72it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 12.67it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:05<00:00, 12.57it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:05<00:00, 12.56it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 12.86it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 13.06it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 12.64it/s]
15 Oct 14:40    INFO  epoch 0 training [time: 6.28s, train loss: 55.0431]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:05, 14.28it/s]:   5%|██▌                                                | 4/79 [00:00<00:05, 13.58it/s]:   8%|███▊                                               | 6/79 [00:00<00:05, 13.09it/s]:  10%|█████▏                                             | 8/79 [00:00<00:05, 13.23it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 13.30it/s]:  15%|███████▌                                          | 12/79 [00:00<00:05, 13.27it/s]:  18%|████████▊                                         | 14/79 [00:01<00:04, 13.15it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:04, 13.14it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:04, 13.16it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:04, 12.76it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 12.53it/s]:  30%|███████████████▏                                  | 24/79 [00:01<00:04, 12.62it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 12.49it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 12.70it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:03, 12.70it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 12.39it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 12.43it/s]:  46%|██████████████████████▊                           | 36/79 [00:02<00:03, 12.64it/s]:  48%|████████████████████████                          | 38/79 [00:02<00:03, 12.64it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 12.74it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:02, 12.59it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 12.18it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 11.79it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:03<00:02, 12.09it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:03<00:02, 12.28it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 12.44it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 12.48it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 12.52it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 12.39it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:04<00:01, 12.37it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:04<00:01, 12.30it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 12.59it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 12.71it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 12.96it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 12.39it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:05<00:00, 12.19it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:05<00:00, 12.21it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 12.38it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 12.51it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 12.59it/s]
15 Oct 14:40    INFO  epoch 1 training [time: 6.30s, train loss: 50.1013]
Train     2:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:05, 13.34it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 11.91it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 11.91it/s]:  10%|█████▏                                             | 8/79 [00:00<00:06, 11.83it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 12.17it/s]:  15%|███████▌                                          | 12/79 [00:00<00:05, 12.29it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 12.16it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 12.09it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 12.09it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:04, 12.33it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 12.50it/s]:  30%|███████████████▏                                  | 24/79 [00:01<00:04, 12.47it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 12.58it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 12.52it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:03, 12.51it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 12.77it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 12.76it/s]:  46%|██████████████████████▊                           | 36/79 [00:02<00:03, 12.83it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 12.91it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 12.95it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:02, 12.94it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 12.65it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 12.86it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:03<00:02, 13.13it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:03<00:02, 13.06it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 12.94it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:01, 13.06it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 12.44it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 12.22it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:04<00:01, 12.22it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:04<00:01, 12.18it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 12.21it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 12.17it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 12.11it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 12.04it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:05<00:00, 12.36it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:05<00:00, 12.47it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 12.45it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 12.35it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 12.44it/s]
15 Oct 14:40    INFO  epoch 2 training [time: 6.37s, train loss: 49.3642]
Train     3:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 12.79it/s]:   5%|██▌                                                | 4/79 [00:00<00:05, 12.63it/s]:   8%|███▊                                               | 6/79 [00:00<00:05, 12.54it/s]:  10%|█████▏                                             | 8/79 [00:00<00:05, 12.56it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 12.90it/s]:  15%|███████▌                                          | 12/79 [00:00<00:05, 13.08it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 12.24it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 12.53it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:04, 12.61it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:04, 12.51it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 12.53it/s]:  30%|███████████████▏                                  | 24/79 [00:01<00:04, 12.41it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 12.28it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 12.22it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 12.25it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 12.13it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 12.23it/s]:  46%|██████████████████████▊                           | 36/79 [00:02<00:03, 12.51it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 12.31it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 12.21it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 11.98it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 11.90it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 12.13it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:03<00:02, 12.29it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 12.40it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 12.15it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 12.24it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 12.14it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 11.92it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:04<00:01, 11.92it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 12.01it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.73it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.95it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 12.06it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 12.17it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:05<00:00, 12.29it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 12.26it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 12.06it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 12.18it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 12.25it/s]
15 Oct 14:40    INFO  epoch 3 training [time: 6.47s, train loss: 49.1869]

[2/8] FISM: {'embedding_size': 32, 'learning_rate': 0.001, 'alpha': 0.5, 'reg_weights': [0.001, 0.001]}

15 Oct 14:42    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:42    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
split_to = 0
reg_weights = [0.001, 0.001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:42    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:42    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:42    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:42    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
15 Oct 14:42    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
15 Oct 14:42    INFO  FISM(
  (item_src_embedding): Embedding(1683, 32, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 32, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 110339
15 Oct 14:42    INFO  FLOPs: 18944.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:05, 13.97it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 12.45it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 11.88it/s]:  10%|█████▏                                             | 8/79 [00:00<00:05, 12.09it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 12.46it/s]:  15%|███████▌                                          | 12/79 [00:00<00:05, 12.37it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 12.19it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 12.01it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 12.16it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:04, 12.38it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 12.26it/s]:  30%|███████████████▏                                  | 24/79 [00:01<00:04, 12.34it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 12.30it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 12.25it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 12.12it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 12.24it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 12.41it/s]:  46%|██████████████████████▊                           | 36/79 [00:02<00:03, 12.47it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 12.44it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 12.45it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 12.27it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 12.24it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 12.16it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:03<00:02, 12.48it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 12.48it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 12.65it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 12.44it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 12.42it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 12.33it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:04<00:01, 12.32it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 12.43it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 12.49it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 12.40it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 12.20it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 11.93it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:05<00:00, 11.87it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 12.02it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 12.24it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 12.26it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 12.29it/s]
15 Oct 14:42    INFO  epoch 0 training [time: 6.45s, train loss: 57.0669]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:05, 12.97it/s]:   5%|██▌                                                | 4/79 [00:00<00:05, 12.99it/s]:   8%|███▊                                               | 6/79 [00:00<00:05, 13.02it/s]:  10%|█████▏                                             | 8/79 [00:00<00:05, 12.57it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 12.26it/s]:  15%|███████▌                                          | 12/79 [00:00<00:05, 12.10it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 11.75it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 11.90it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 12.12it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:04, 12.12it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 11.92it/s]:  30%|███████████████▏                                  | 24/79 [00:01<00:04, 11.64it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.72it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.81it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.92it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 12.41it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 12.51it/s]:  46%|██████████████████████▊                           | 36/79 [00:02<00:03, 12.56it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 12.37it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 12.15it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 12.11it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 12.09it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 12.26it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:03<00:02, 12.36it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 12.30it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 12.07it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 11.99it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 11.94it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 12.06it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:04<00:01, 11.97it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.79it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.79it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 12.02it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 12.18it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 12.37it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:05<00:00, 12.01it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 11.61it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 11.47it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00,  9.90it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.80it/s]
15 Oct 14:42    INFO  epoch 1 training [time: 6.72s, train loss: 56.6402]
Train     2:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 11.00it/s]:   5%|██▌                                                | 4/79 [00:00<00:08,  8.83it/s]:   6%|███▏                                               | 5/79 [00:00<00:08,  8.26it/s]:   8%|███▊                                               | 6/79 [00:00<00:08,  8.25it/s]:   9%|████▌                                              | 7/79 [00:00<00:08,  8.45it/s]:  11%|█████▊                                             | 9/79 [00:00<00:07,  9.51it/s]:  14%|██████▉                                           | 11/79 [00:01<00:06, 10.24it/s]:  16%|████████▏                                         | 13/79 [00:01<00:06, 10.73it/s]:  19%|█████████▍                                        | 15/79 [00:01<00:05, 11.24it/s]:  22%|██████████▊                                       | 17/79 [00:01<00:05, 11.60it/s]:  24%|████████████                                      | 19/79 [00:01<00:04, 12.11it/s]:  27%|█████████████▎                                    | 21/79 [00:01<00:04, 12.09it/s]:  29%|██████████████▌                                   | 23/79 [00:02<00:04, 11.63it/s]:  32%|███████████████▊                                  | 25/79 [00:02<00:04, 11.61it/s]:  34%|█████████████████                                 | 27/79 [00:02<00:04, 11.54it/s]:  37%|██████████████████▎                               | 29/79 [00:02<00:04, 10.83it/s]:  39%|███████████████████▌                              | 31/79 [00:02<00:04, 10.82it/s]:  42%|████████████████████▉                             | 33/79 [00:03<00:04, 10.85it/s]:  44%|██████████████████████▏                           | 35/79 [00:03<00:04, 10.87it/s]:  47%|███████████████████████▍                          | 37/79 [00:03<00:03, 10.90it/s]:  49%|████████████████████████▋                         | 39/79 [00:03<00:03, 10.86it/s]:  52%|█████████████████████████▉                        | 41/79 [00:03<00:03, 10.90it/s]:  54%|███████████████████████████▏                      | 43/79 [00:03<00:03, 11.09it/s]:  57%|████████████████████████████▍                     | 45/79 [00:04<00:03, 11.21it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:04<00:02, 11.21it/s]:  62%|███████████████████████████████                   | 49/79 [00:04<00:02, 11.00it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:04<00:02, 10.91it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:04<00:02, 11.31it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:05<00:02, 11.18it/s]:  72%|████████████████████████████████████              | 57/79 [00:05<00:01, 11.37it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:05<00:01, 11.26it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:05<00:01, 11.18it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:05<00:01, 11.38it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:05<00:01, 11.41it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:06<00:01, 11.39it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:06<00:00, 11.51it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:06<00:00, 11.63it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:06<00:00, 11.38it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:06<00:00, 11.40it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:06<00:00, 11.32it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:07<00:00, 11.48it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:07<00:00, 11.01it/s]
15 Oct 14:42    INFO  epoch 2 training [time: 7.20s, train loss: 56.2779]
Train     3:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 12.53it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 11.52it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 11.16it/s]:  10%|█████▏                                             | 8/79 [00:00<00:06, 11.12it/s]:  13%|██████▎                                           | 10/79 [00:00<00:06, 10.96it/s]:  15%|███████▌                                          | 12/79 [00:01<00:06, 10.24it/s]:  18%|████████▊                                         | 14/79 [00:01<00:06, 10.24it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 10.53it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 10.86it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:05, 11.18it/s]:  28%|█████████████▉                                    | 22/79 [00:02<00:05, 11.30it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.48it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.44it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.58it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.57it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:04, 11.47it/s]:  43%|█████████████████████▌                            | 34/79 [00:03<00:03, 11.66it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 11.85it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 11.79it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 11.74it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 11.55it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:03, 11.41it/s]:  58%|█████████████████████████████                     | 46/79 [00:04<00:02, 11.11it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 10.97it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 11.21it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 11.42it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 11.56it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 11.68it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:05<00:01, 11.69it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.75it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.75it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.57it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.68it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 11.92it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:06<00:00, 12.02it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 11.80it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 11.99it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 11.97it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 11.90it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.48it/s]
15 Oct 14:42    INFO  epoch 3 training [time: 6.91s, train loss: 55.9284]

[3/8] FISM: {'embedding_size': 32, 'learning_rate': 0.005, 'alpha': 0.5, 'reg_weights': [0.0001, 0.0001]}

15 Oct 14:44    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:44    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.005
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
split_to = 0
reg_weights = [0.0001, 0.0001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:44    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:44    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:44    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:44    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
15 Oct 14:44    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
15 Oct 14:44    INFO  FISM(
  (item_src_embedding): Embedding(1683, 32, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 32, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 110339
15 Oct 14:44    INFO  FLOPs: 18944.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 12.60it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 12.08it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 11.87it/s]:  10%|█████▏                                             | 8/79 [00:00<00:05, 12.10it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 12.15it/s]:  15%|███████▌                                          | 12/79 [00:00<00:05, 12.05it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 11.76it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 11.83it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 12.08it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:05, 11.72it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 11.61it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.58it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.63it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.62it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.61it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:04, 11.59it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 11.76it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 11.80it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 11.90it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 11.88it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 11.79it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:03, 11.51it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 11.64it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 11.58it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 11.66it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 11.66it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 11.62it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:02, 11.49it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 11.45it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.40it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.26it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.37it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.28it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:01, 10.90it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:06<00:00, 11.16it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 11.06it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 11.14it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 11.24it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 11.48it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.60it/s]
15 Oct 14:45    INFO  epoch 0 training [time: 6.84s, train loss: 51.0733]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 12.40it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 12.30it/s]:   8%|███▊                                               | 6/79 [00:00<00:05, 12.41it/s]:  10%|█████▏                                             | 8/79 [00:00<00:05, 12.19it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 12.15it/s]:  15%|███████▌                                          | 12/79 [00:00<00:05, 12.14it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 12.10it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 12.11it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 12.13it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:04, 12.10it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 12.11it/s]:  30%|███████████████▏                                  | 24/79 [00:01<00:04, 12.08it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 12.06it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.97it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.88it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 11.92it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 12.02it/s]:  46%|██████████████████████▊                           | 36/79 [00:02<00:03, 11.85it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 12.01it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 11.87it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 11.95it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 11.89it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 12.01it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 11.73it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 11.71it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 11.70it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 11.70it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 11.60it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 11.50it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.26it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.54it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.62it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.76it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 11.82it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 11.76it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 11.66it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 11.85it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 11.86it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 11.73it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.87it/s]
15 Oct 14:45    INFO  epoch 1 training [time: 6.68s, train loss: 49.2472]
Train     2:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 12.79it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 11.74it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 11.41it/s]:  10%|█████▏                                             | 8/79 [00:00<00:06, 11.39it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 11.63it/s]:  15%|███████▌                                          | 12/79 [00:01<00:05, 11.72it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 11.80it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 11.96it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 11.81it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:04, 11.81it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 11.79it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.79it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.73it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.74it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.63it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:04, 11.65it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 11.72it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 11.74it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 11.40it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 11.45it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 11.40it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:03, 11.36it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 11.39it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 11.40it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 11.48it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 11.43it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 11.19it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:02, 11.43it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:05<00:01, 11.45it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.62it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.70it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.80it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.78it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 11.65it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:06<00:00, 11.76it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 11.80it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 11.60it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 11.61it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 11.83it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.64it/s]
15 Oct 14:45    INFO  epoch 2 training [time: 6.81s, train loss: 49.0508]
Train     3:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 12.81it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 12.21it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 11.77it/s]:  10%|█████▏                                             | 8/79 [00:00<00:05, 12.02it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 11.96it/s]:  15%|███████▌                                          | 12/79 [00:00<00:05, 11.96it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 11.77it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 11.78it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 11.70it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:05, 11.58it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 11.48it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.58it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.72it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.64it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.49it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:04, 11.66it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 11.68it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 11.49it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 11.62it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 11.59it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 11.51it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:03, 11.24it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 11.08it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 10.85it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 11.06it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 11.39it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 11.53it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 11.65it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:05<00:01, 11.59it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.66it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.77it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.85it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.60it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 11.54it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:06<00:00, 11.49it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 11.39it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 11.56it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 11.70it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 11.50it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.58it/s]
15 Oct 14:45    INFO  epoch 3 training [time: 6.85s, train loss: 48.6962]

[4/8] FISM: {'embedding_size': 32, 'learning_rate': 0.005, 'alpha': 0.5, 'reg_weights': [0.001, 0.001]}

15 Oct 14:47    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:47    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.005
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
split_to = 0
reg_weights = [0.001, 0.001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:47    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:47    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:47    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:47    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
15 Oct 14:47    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
15 Oct 14:47    INFO  FISM(
  (item_src_embedding): Embedding(1683, 32, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 32, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 110339
15 Oct 14:47    INFO  FLOPs: 18944.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 12.82it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 12.17it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 11.86it/s]:  10%|█████▏                                             | 8/79 [00:00<00:06, 11.55it/s]:  13%|██████▎                                           | 10/79 [00:00<00:06, 11.35it/s]:  15%|███████▌                                          | 12/79 [00:01<00:05, 11.58it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 11.84it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 11.58it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 11.56it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:05, 11.47it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 11.55it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.59it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.55it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.30it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.39it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:04, 11.29it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 11.34it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 11.47it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 11.38it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 11.43it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 11.49it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:03, 11.36it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 11.44it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 11.45it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 11.39it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 11.39it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 11.23it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:02, 11.12it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:05<00:01, 10.97it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.01it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 10.97it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 10.97it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 10.72it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:06<00:01, 10.69it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:06<00:00, 10.69it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 10.66it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 10.78it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 10.67it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 10.66it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:07<00:00, 11.22it/s]
15 Oct 14:47    INFO  epoch 0 training [time: 7.07s, train loss: 56.3302]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:08,  9.66it/s]:   4%|█▉                                                 | 3/79 [00:00<00:07, 10.48it/s]:   6%|███▏                                               | 5/79 [00:00<00:06, 10.96it/s]:   9%|████▌                                              | 7/79 [00:00<00:06, 11.12it/s]:  11%|█████▊                                             | 9/79 [00:00<00:06, 10.98it/s]:  14%|██████▉                                           | 11/79 [00:01<00:06, 11.11it/s]:  16%|████████▏                                         | 13/79 [00:01<00:06, 10.95it/s]:  19%|█████████▍                                        | 15/79 [00:01<00:05, 10.85it/s]:  22%|██████████▊                                       | 17/79 [00:01<00:05, 11.10it/s]:  24%|████████████                                      | 19/79 [00:01<00:05, 11.50it/s]:  27%|█████████████▎                                    | 21/79 [00:01<00:05, 11.30it/s]:  29%|██████████████▌                                   | 23/79 [00:02<00:04, 11.49it/s]:  32%|███████████████▊                                  | 25/79 [00:02<00:04, 11.47it/s]:  34%|█████████████████                                 | 27/79 [00:02<00:04, 11.39it/s]:  37%|██████████████████▎                               | 29/79 [00:02<00:04, 11.37it/s]:  39%|███████████████████▌                              | 31/79 [00:02<00:04, 11.00it/s]:  42%|████████████████████▉                             | 33/79 [00:02<00:04, 10.92it/s]:  44%|██████████████████████▏                           | 35/79 [00:03<00:03, 11.26it/s]:  47%|███████████████████████▍                          | 37/79 [00:03<00:03, 11.26it/s]:  49%|████████████████████████▋                         | 39/79 [00:03<00:03, 11.38it/s]:  52%|█████████████████████████▉                        | 41/79 [00:03<00:03, 11.58it/s]:  54%|███████████████████████████▏                      | 43/79 [00:03<00:03, 11.49it/s]:  57%|████████████████████████████▍                     | 45/79 [00:04<00:02, 11.40it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:04<00:02, 11.49it/s]:  62%|███████████████████████████████                   | 49/79 [00:04<00:02, 11.68it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:04<00:02, 11.63it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:04<00:02, 11.25it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:04<00:02, 11.28it/s]:  72%|████████████████████████████████████              | 57/79 [00:05<00:01, 11.34it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:05<00:01, 11.42it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:05<00:01, 11.43it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:05<00:01, 11.35it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:05<00:01, 11.10it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:05<00:01, 10.96it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:06<00:00, 11.27it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:06<00:00, 11.32it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:06<00:00, 11.37it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:06<00:00, 11.58it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:06<00:00, 11.82it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.88it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.32it/s]
15 Oct 14:47    INFO  epoch 1 training [time: 7.00s, train loss: 54.7613]
Train     2:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 12.62it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 11.61it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 11.68it/s]:  10%|█████▏                                             | 8/79 [00:00<00:06, 11.34it/s]:  13%|██████▎                                           | 10/79 [00:00<00:06, 11.14it/s]:  15%|███████▌                                          | 12/79 [00:01<00:06, 11.07it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 11.18it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 11.31it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 11.54it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:05, 11.51it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 11.50it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.53it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.64it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.82it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.75it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 11.82it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 11.63it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 11.47it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 11.76it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 11.79it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 11.69it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 11.73it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 11.73it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 11.80it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 11.83it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 11.75it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 11.74it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 11.74it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 11.70it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.68it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.66it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.81it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.77it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 11.74it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:06<00:00, 11.42it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 11.47it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 11.42it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 11.13it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 11.04it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.54it/s]
15 Oct 14:47    INFO  epoch 2 training [time: 6.87s, train loss: 53.6467]
Train     3:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 12.48it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 11.89it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 11.43it/s]:  10%|█████▏                                             | 8/79 [00:00<00:06, 11.32it/s]:  13%|██████▎                                           | 10/79 [00:00<00:06, 11.41it/s]:  15%|███████▌                                          | 12/79 [00:01<00:05, 11.36it/s]:  18%|████████▊                                         | 14/79 [00:01<00:06, 10.77it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 10.92it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 11.09it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:05, 10.96it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:05, 11.21it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.27it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.05it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.37it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.31it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:04, 11.27it/s]:  43%|█████████████████████▌                            | 34/79 [00:03<00:03, 11.42it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 11.45it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 11.64it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 11.55it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 11.56it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:03, 11.53it/s]:  58%|█████████████████████████████                     | 46/79 [00:04<00:02, 11.62it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 11.65it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 11.54it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 11.61it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 11.75it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 11.82it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:05<00:01, 11.89it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.87it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.20it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.26it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.41it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 11.62it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:06<00:00, 11.59it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 11.48it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 11.35it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 11.63it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 11.70it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.47it/s]
15 Oct 14:47    INFO  epoch 3 training [time: 6.91s, train loss: 52.8259]

[5/8] FISM: {'embedding_size': 64, 'learning_rate': 0.001, 'alpha': 0.5, 'reg_weights': [0.0001, 0.0001]}

15 Oct 14:49    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:49    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
split_to = 0
reg_weights = [0.0001, 0.0001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:49    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:49    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:49    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:49    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
15 Oct 14:49    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
15 Oct 14:49    INFO  FISM(
  (item_src_embedding): Embedding(1683, 64, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 64, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 218051
15 Oct 14:49    INFO  FLOPs: 37888.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:10,  7.30it/s]:   3%|█▎                                                 | 2/79 [00:00<00:11,  6.87it/s]:   4%|█▉                                                 | 3/79 [00:00<00:11,  6.84it/s]:   5%|██▌                                                | 4/79 [00:00<00:11,  6.76it/s]:   6%|███▏                                               | 5/79 [00:00<00:11,  6.72it/s]:   8%|███▊                                               | 6/79 [00:00<00:10,  6.81it/s]:   9%|████▌                                              | 7/79 [00:01<00:10,  6.56it/s]:  10%|█████▏                                             | 8/79 [00:01<00:10,  6.46it/s]:  11%|█████▊                                             | 9/79 [00:01<00:10,  6.47it/s]:  13%|██████▎                                           | 10/79 [00:01<00:10,  6.47it/s]:  14%|██████▉                                           | 11/79 [00:01<00:10,  6.43it/s]:  15%|███████▌                                          | 12/79 [00:01<00:10,  6.28it/s]:  16%|████████▏                                         | 13/79 [00:02<00:10,  6.23it/s]:  18%|████████▊                                         | 14/79 [00:02<00:10,  6.29it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:10,  6.29it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:10,  6.27it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:09,  6.39it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:09,  6.43it/s]:  24%|████████████                                      | 19/79 [00:02<00:09,  6.48it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:09,  6.52it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:08,  6.52it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:08,  6.48it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:08,  6.27it/s]:  30%|███████████████▏                                  | 24/79 [00:03<00:08,  6.14it/s]:  32%|███████████████▊                                  | 25/79 [00:03<00:08,  6.01it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:08,  5.94it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:08,  6.09it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:08,  6.15it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:08,  6.13it/s]:  38%|██████████████████▉                               | 30/79 [00:04<00:07,  6.15it/s]:  39%|███████████████████▌                              | 31/79 [00:04<00:07,  6.25it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:07,  6.32it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:07,  6.33it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:07,  6.40it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:06,  6.46it/s]:  46%|██████████████████████▊                           | 36/79 [00:05<00:06,  6.27it/s]:  47%|███████████████████████▍                          | 37/79 [00:05<00:06,  6.36it/s]:  48%|████████████████████████                          | 38/79 [00:05<00:06,  6.41it/s]:  49%|████████████████████████▋                         | 39/79 [00:06<00:06,  6.34it/s]:  51%|█████████████████████████▎                        | 40/79 [00:06<00:06,  6.25it/s]:  52%|█████████████████████████▉                        | 41/79 [00:06<00:06,  6.24it/s]:  53%|██████████████████████████▌                       | 42/79 [00:06<00:05,  6.28it/s]:  54%|███████████████████████████▏                      | 43/79 [00:06<00:05,  6.27it/s]:  56%|███████████████████████████▊                      | 44/79 [00:06<00:05,  6.29it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:05,  6.23it/s]:  58%|█████████████████████████████                     | 46/79 [00:07<00:05,  6.05it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:07<00:05,  6.12it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:07<00:05,  6.12it/s]:  62%|███████████████████████████████                   | 49/79 [00:07<00:04,  6.20it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:07<00:04,  6.31it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:08<00:04,  6.32it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:08<00:04,  6.36it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:08<00:04,  6.41it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:08<00:03,  6.40it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:08<00:03,  6.42it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:08<00:03,  6.34it/s]:  72%|████████████████████████████████████              | 57/79 [00:08<00:03,  6.30it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:09<00:03,  6.21it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:09<00:03,  6.14it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:09<00:03,  6.17it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:09<00:02,  6.12it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:09<00:02,  6.11it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:09<00:02,  5.97it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:10<00:02,  6.09it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:10<00:02,  5.96it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:10<00:02,  6.09it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:10<00:01,  6.10it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:10<00:01,  6.10it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:10<00:01,  6.06it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:11<00:01,  6.12it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:11<00:01,  6.19it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:11<00:01,  6.24it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:11<00:00,  6.29it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:11<00:00,  6.27it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:11<00:00,  6.28it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:12<00:00,  6.30it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:12<00:00,  6.26it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:12<00:00,  6.23it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:12<00:00,  6.35it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:12<00:00,  6.28it/s]
15 Oct 14:50    INFO  epoch 0 training [time: 12.60s, train loss: 54.1027]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:11,  6.60it/s]:   3%|█▎                                                 | 2/79 [00:00<00:12,  6.32it/s]:   4%|█▉                                                 | 3/79 [00:00<00:11,  6.36it/s]:   5%|██▌                                                | 4/79 [00:00<00:11,  6.41it/s]:   6%|███▏                                               | 5/79 [00:00<00:11,  6.39it/s]:   8%|███▊                                               | 6/79 [00:00<00:11,  6.40it/s]:   9%|████▌                                              | 7/79 [00:01<00:11,  6.39it/s]:  10%|█████▏                                             | 8/79 [00:01<00:11,  6.36it/s]:  11%|█████▊                                             | 9/79 [00:01<00:11,  6.32it/s]:  13%|██████▎                                           | 10/79 [00:01<00:10,  6.33it/s]:  14%|██████▉                                           | 11/79 [00:01<00:10,  6.31it/s]:  15%|███████▌                                          | 12/79 [00:01<00:10,  6.25it/s]:  16%|████████▏                                         | 13/79 [00:02<00:10,  6.31it/s]:  18%|████████▊                                         | 14/79 [00:02<00:10,  6.37it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:09,  6.44it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:09,  6.38it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:09,  6.23it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:09,  6.21it/s]:  24%|████████████                                      | 19/79 [00:03<00:09,  6.20it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:09,  6.06it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:09,  6.09it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:09,  6.19it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:08,  6.29it/s]:  30%|███████████████▏                                  | 24/79 [00:03<00:08,  6.31it/s]:  32%|███████████████▊                                  | 25/79 [00:03<00:08,  6.26it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:08,  6.18it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:08,  6.23it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:08,  6.20it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:08,  6.20it/s]:  38%|██████████████████▉                               | 30/79 [00:04<00:07,  6.16it/s]:  39%|███████████████████▌                              | 31/79 [00:04<00:07,  6.13it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:07,  6.02it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:07,  6.11it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:07,  6.08it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:07,  6.13it/s]:  46%|██████████████████████▊                           | 36/79 [00:05<00:06,  6.19it/s]:  47%|███████████████████████▍                          | 37/79 [00:05<00:06,  6.18it/s]:  48%|████████████████████████                          | 38/79 [00:06<00:06,  6.19it/s]:  49%|████████████████████████▋                         | 39/79 [00:06<00:06,  6.24it/s]:  51%|█████████████████████████▎                        | 40/79 [00:06<00:06,  6.26it/s]:  52%|█████████████████████████▉                        | 41/79 [00:06<00:06,  6.31it/s]:  53%|██████████████████████████▌                       | 42/79 [00:06<00:05,  6.33it/s]:  54%|███████████████████████████▏                      | 43/79 [00:06<00:05,  6.37it/s]:  56%|███████████████████████████▊                      | 44/79 [00:07<00:05,  6.26it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:05,  6.33it/s]:  58%|█████████████████████████████                     | 46/79 [00:07<00:05,  6.26it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:07<00:05,  6.36it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:07<00:04,  6.38it/s]:  62%|███████████████████████████████                   | 49/79 [00:07<00:04,  6.32it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:08<00:04,  6.03it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:08<00:04,  6.10it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:08<00:04,  6.00it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:08<00:04,  6.11it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:08<00:04,  6.15it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:08<00:03,  6.14it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:08<00:03,  6.08it/s]:  72%|████████████████████████████████████              | 57/79 [00:09<00:03,  6.02it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:09<00:03,  6.10it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:09<00:03,  6.20it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:09<00:03,  6.08it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:09<00:02,  6.16it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:09<00:02,  6.20it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:10<00:02,  6.16it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:10<00:02,  6.23it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:10<00:02,  6.22it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:10<00:02,  6.27it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:10<00:01,  6.29it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:10<00:01,  6.29it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:11<00:01,  6.15it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:11<00:01,  6.10it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:11<00:01,  5.87it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:11<00:01,  5.94it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:11<00:01,  5.92it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:11<00:00,  5.98it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:12<00:00,  6.07it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:12<00:00,  6.11it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:12<00:00,  6.14it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:12<00:00,  6.32it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:12<00:00,  6.43it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:12<00:00,  6.21it/s]
15 Oct 14:50    INFO  epoch 1 training [time: 12.75s, train loss: 49.6136]

[6/8] FISM: {'embedding_size': 64, 'learning_rate': 0.001, 'alpha': 0.5, 'reg_weights': [0.001, 0.001]}

15 Oct 14:54    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:54    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
split_to = 0
reg_weights = [0.001, 0.001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:54    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:54    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:54    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:54    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
15 Oct 14:54    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
15 Oct 14:54    INFO  FISM(
  (item_src_embedding): Embedding(1683, 64, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 64, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 218051
15 Oct 14:54    INFO  FLOPs: 37888.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:10,  7.65it/s]:   3%|█▎                                                 | 2/79 [00:00<00:10,  7.34it/s]:   4%|█▉                                                 | 3/79 [00:00<00:10,  7.05it/s]:   5%|██▌                                                | 4/79 [00:00<00:10,  6.83it/s]:   6%|███▏                                               | 5/79 [00:00<00:11,  6.62it/s]:   8%|███▊                                               | 6/79 [00:00<00:11,  6.60it/s]:   9%|████▌                                              | 7/79 [00:01<00:11,  6.33it/s]:  10%|█████▏                                             | 8/79 [00:01<00:11,  6.25it/s]:  11%|█████▊                                             | 9/79 [00:01<00:11,  6.27it/s]:  13%|██████▎                                           | 10/79 [00:01<00:10,  6.31it/s]:  14%|██████▉                                           | 11/79 [00:01<00:10,  6.30it/s]:  15%|███████▌                                          | 12/79 [00:01<00:10,  6.29it/s]:  16%|████████▏                                         | 13/79 [00:02<00:10,  6.19it/s]:  18%|████████▊                                         | 14/79 [00:02<00:10,  6.13it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:10,  6.06it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:10,  5.97it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:10,  6.05it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:09,  6.16it/s]:  24%|████████████                                      | 19/79 [00:03<00:09,  6.17it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:09,  6.16it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:09,  6.19it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:09,  6.20it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:09,  6.21it/s]:  30%|███████████████▏                                  | 24/79 [00:03<00:08,  6.24it/s]:  32%|███████████████▊                                  | 25/79 [00:03<00:08,  6.27it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:08,  6.28it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:08,  6.30it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:08,  6.37it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:07,  6.45it/s]:  38%|██████████████████▉                               | 30/79 [00:04<00:07,  6.36it/s]:  39%|███████████████████▌                              | 31/79 [00:04<00:07,  6.47it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:07,  6.48it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:07,  6.55it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:06,  6.52it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:06,  6.45it/s]:  46%|██████████████████████▊                           | 36/79 [00:05<00:06,  6.39it/s]:  47%|███████████████████████▍                          | 37/79 [00:05<00:06,  6.40it/s]:  48%|████████████████████████                          | 38/79 [00:05<00:06,  6.39it/s]:  49%|████████████████████████▋                         | 39/79 [00:06<00:06,  6.39it/s]:  51%|█████████████████████████▎                        | 40/79 [00:06<00:06,  6.33it/s]:  52%|█████████████████████████▉                        | 41/79 [00:06<00:06,  6.31it/s]:  53%|██████████████████████████▌                       | 42/79 [00:06<00:05,  6.22it/s]:  54%|███████████████████████████▏                      | 43/79 [00:06<00:05,  6.21it/s]:  56%|███████████████████████████▊                      | 44/79 [00:06<00:05,  6.23it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:05,  6.34it/s]:  58%|█████████████████████████████                     | 46/79 [00:07<00:05,  6.36it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:07<00:05,  6.36it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:07<00:04,  6.27it/s]:  62%|███████████████████████████████                   | 49/79 [00:07<00:04,  6.34it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:07<00:04,  6.40it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:08<00:04,  6.41it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:08<00:04,  6.24it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:08<00:04,  6.16it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:08<00:04,  6.22it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:08<00:03,  6.34it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:08<00:03,  6.35it/s]:  72%|████████████████████████████████████              | 57/79 [00:09<00:03,  6.35it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:09<00:03,  6.18it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:09<00:03,  6.33it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:09<00:02,  6.41it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:09<00:02,  6.37it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:09<00:02,  6.34it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:09<00:02,  6.33it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:10<00:02,  6.14it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:10<00:02,  6.13it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:10<00:02,  6.20it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:10<00:01,  6.22it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:10<00:01,  6.25it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:10<00:01,  6.27it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:11<00:01,  6.41it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:11<00:01,  6.38it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:11<00:01,  6.36it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:11<00:00,  6.33it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:11<00:00,  6.24it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:11<00:00,  6.31it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:12<00:00,  6.28it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:12<00:00,  6.21it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:12<00:00,  6.17it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:12<00:00,  6.30it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:12<00:00,  6.31it/s]
15 Oct 14:54    INFO  epoch 0 training [time: 12.55s, train loss: 57.0899]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:11,  6.84it/s]:   3%|█▎                                                 | 2/79 [00:00<00:11,  6.62it/s]:   4%|█▉                                                 | 3/79 [00:00<00:11,  6.50it/s]:   5%|██▌                                                | 4/79 [00:00<00:11,  6.34it/s]:   6%|███▏                                               | 5/79 [00:00<00:11,  6.31it/s]:   8%|███▊                                               | 6/79 [00:00<00:11,  6.32it/s]:   9%|████▌                                              | 7/79 [00:01<00:11,  6.26it/s]:  10%|█████▏                                             | 8/79 [00:01<00:11,  6.29it/s]:  11%|█████▊                                             | 9/79 [00:01<00:11,  6.27it/s]:  13%|██████▎                                           | 10/79 [00:01<00:11,  6.27it/s]:  14%|██████▉                                           | 11/79 [00:01<00:10,  6.24it/s]:  15%|███████▌                                          | 12/79 [00:01<00:10,  6.21it/s]:  16%|████████▏                                         | 13/79 [00:02<00:10,  6.17it/s]:  18%|████████▊                                         | 14/79 [00:02<00:10,  6.19it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:10,  6.19it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:10,  6.23it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:09,  6.25it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:09,  6.28it/s]:  24%|████████████                                      | 19/79 [00:03<00:09,  6.25it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:09,  6.31it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:09,  6.35it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:09,  6.31it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:08,  6.26it/s]:  30%|███████████████▏                                  | 24/79 [00:03<00:08,  6.27it/s]:  32%|███████████████▊                                  | 25/79 [00:03<00:08,  6.30it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:08,  6.30it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:08,  6.27it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:08,  6.28it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:07,  6.28it/s]:  38%|██████████████████▉                               | 30/79 [00:04<00:07,  6.34it/s]:  39%|███████████████████▌                              | 31/79 [00:04<00:07,  6.24it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:07,  6.22it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:07,  6.22it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:07,  6.07it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:07,  6.08it/s]:  46%|██████████████████████▊                           | 36/79 [00:05<00:07,  6.11it/s]:  47%|███████████████████████▍                          | 37/79 [00:05<00:06,  6.15it/s]:  48%|████████████████████████                          | 38/79 [00:06<00:06,  6.17it/s]:  49%|████████████████████████▋                         | 39/79 [00:06<00:06,  6.12it/s]:  51%|█████████████████████████▎                        | 40/79 [00:06<00:06,  6.13it/s]:  52%|█████████████████████████▉                        | 41/79 [00:06<00:06,  6.15it/s]:  53%|██████████████████████████▌                       | 42/79 [00:06<00:06,  6.13it/s]:  54%|███████████████████████████▏                      | 43/79 [00:06<00:05,  6.15it/s]:  56%|███████████████████████████▊                      | 44/79 [00:07<00:05,  6.12it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:05,  6.12it/s]:  58%|█████████████████████████████                     | 46/79 [00:07<00:05,  6.12it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:07<00:05,  6.09it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:07<00:05,  5.89it/s]:  62%|███████████████████████████████                   | 49/79 [00:07<00:05,  5.96it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:08<00:04,  5.88it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:08<00:04,  5.98it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:08<00:04,  6.03it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:08<00:04,  6.08it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:08<00:04,  6.14it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:08<00:03,  6.21it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:09<00:03,  6.16it/s]:  72%|████████████████████████████████████              | 57/79 [00:09<00:03,  6.00it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:09<00:03,  6.08it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:09<00:03,  6.14it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:09<00:03,  6.27it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:09<00:02,  6.25it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:10<00:02,  6.19it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:10<00:02,  6.28it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:10<00:02,  6.12it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:10<00:02,  6.18it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:10<00:02,  6.20it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:10<00:01,  6.17it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:10<00:01,  6.24it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:11<00:01,  6.26it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:11<00:01,  6.30it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:11<00:01,  6.23it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:11<00:01,  6.24it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:11<00:00,  6.25it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:11<00:00,  6.25it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:12<00:00,  6.07it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:12<00:00,  5.94it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:12<00:00,  6.00it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:12<00:00,  6.06it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:12<00:00,  6.24it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:12<00:00,  6.18it/s]
15 Oct 14:54    INFO  epoch 1 training [time: 12.80s, train loss: 56.6408]

[7/8] FISM: {'embedding_size': 64, 'learning_rate': 0.005, 'alpha': 0.5, 'reg_weights': [0.0001, 0.0001]}

15 Oct 14:59    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 14:59    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.005
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
split_to = 0
reg_weights = [0.0001, 0.0001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 14:59    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 14:59    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 14:59    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 14:59    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
15 Oct 14:59    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
15 Oct 14:59    INFO  FISM(
  (item_src_embedding): Embedding(1683, 64, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 64, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 218051
15 Oct 14:59    INFO  FLOPs: 37888.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:10,  7.53it/s]:   3%|█▎                                                 | 2/79 [00:00<00:10,  7.07it/s]:   4%|█▉                                                 | 3/79 [00:00<00:11,  6.71it/s]:   5%|██▌                                                | 4/79 [00:00<00:11,  6.52it/s]:   6%|███▏                                               | 5/79 [00:00<00:11,  6.43it/s]:   8%|███▊                                               | 6/79 [00:00<00:11,  6.36it/s]:   9%|████▌                                              | 7/79 [00:01<00:12,  5.99it/s]:  10%|█████▏                                             | 8/79 [00:01<00:11,  5.94it/s]:  11%|█████▊                                             | 9/79 [00:01<00:11,  5.98it/s]:  13%|██████▎                                           | 10/79 [00:01<00:11,  5.95it/s]:  14%|██████▉                                           | 11/79 [00:01<00:11,  5.92it/s]:  15%|███████▌                                          | 12/79 [00:01<00:11,  5.88it/s]:  16%|████████▏                                         | 13/79 [00:02<00:11,  5.84it/s]:  18%|████████▊                                         | 14/79 [00:02<00:11,  5.76it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:10,  5.83it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:10,  5.91it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:10,  5.96it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:10,  6.03it/s]:  24%|████████████                                      | 19/79 [00:03<00:10,  5.90it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:10,  5.90it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:09,  5.90it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:09,  5.92it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:09,  5.98it/s]:  30%|███████████████▏                                  | 24/79 [00:03<00:09,  5.95it/s]:  32%|███████████████▊                                  | 25/79 [00:04<00:08,  6.03it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:08,  6.07it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:08,  6.16it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:08,  6.23it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:08,  6.10it/s]:  38%|██████████████████▉                               | 30/79 [00:04<00:07,  6.14it/s]:  39%|███████████████████▌                              | 31/79 [00:05<00:07,  6.15it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:07,  6.16it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:07,  6.09it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:07,  6.02it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:07,  6.07it/s]:  46%|██████████████████████▊                           | 36/79 [00:05<00:07,  6.10it/s]:  47%|███████████████████████▍                          | 37/79 [00:06<00:06,  6.05it/s]:  48%|████████████████████████                          | 38/79 [00:06<00:06,  5.99it/s]:  49%|████████████████████████▋                         | 39/79 [00:06<00:06,  5.99it/s]:  51%|█████████████████████████▎                        | 40/79 [00:06<00:06,  6.00it/s]:  52%|█████████████████████████▉                        | 41/79 [00:06<00:06,  5.97it/s]:  53%|██████████████████████████▌                       | 42/79 [00:06<00:06,  5.81it/s]:  54%|███████████████████████████▏                      | 43/79 [00:07<00:06,  5.85it/s]:  56%|███████████████████████████▊                      | 44/79 [00:07<00:05,  5.86it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:05,  5.93it/s]:  58%|█████████████████████████████                     | 46/79 [00:07<00:05,  6.02it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:07<00:05,  6.16it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:07<00:05,  6.03it/s]:  62%|███████████████████████████████                   | 49/79 [00:08<00:05,  5.90it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:08<00:04,  5.97it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:08<00:04,  5.94it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:08<00:04,  5.76it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:08<00:04,  5.81it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:08<00:04,  5.91it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:09<00:04,  5.92it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:09<00:03,  5.94it/s]:  72%|████████████████████████████████████              | 57/79 [00:09<00:03,  5.84it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:09<00:03,  5.86it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:09<00:03,  5.91it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:09<00:03,  5.89it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:10<00:03,  5.85it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:10<00:02,  5.70it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:10<00:02,  5.72it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:10<00:02,  5.79it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:10<00:02,  5.93it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:11<00:02,  5.85it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:11<00:02,  5.99it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:11<00:01,  6.08it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:11<00:01,  6.12it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:11<00:01,  6.03it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:11<00:01,  6.07it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:12<00:01,  6.08it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:12<00:00,  6.02it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:12<00:00,  6.00it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:12<00:00,  5.98it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:12<00:00,  5.78it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:12<00:00,  5.78it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:13<00:00,  5.78it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  5.93it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  5.98it/s]
15 Oct 14:59    INFO  epoch 0 training [time: 13.25s, train loss: 50.7567]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:12,  6.10it/s]:   3%|█▎                                                 | 2/79 [00:00<00:12,  5.97it/s]:   4%|█▉                                                 | 3/79 [00:00<00:12,  6.17it/s]:   5%|██▌                                                | 4/79 [00:00<00:11,  6.26it/s]:   6%|███▏                                               | 5/79 [00:00<00:11,  6.32it/s]:   8%|███▊                                               | 6/79 [00:00<00:11,  6.28it/s]:   9%|████▌                                              | 7/79 [00:01<00:11,  6.12it/s]:  10%|█████▏                                             | 8/79 [00:01<00:11,  6.17it/s]:  11%|█████▊                                             | 9/79 [00:01<00:11,  6.07it/s]:  13%|██████▎                                           | 10/79 [00:01<00:11,  6.06it/s]:  14%|██████▉                                           | 11/79 [00:01<00:11,  6.00it/s]:  15%|███████▌                                          | 12/79 [00:01<00:11,  6.03it/s]:  16%|████████▏                                         | 13/79 [00:02<00:10,  6.02it/s]:  18%|████████▊                                         | 14/79 [00:02<00:10,  6.12it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:10,  6.08it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:10,  5.93it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:10,  5.98it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:10,  6.05it/s]:  24%|████████████                                      | 19/79 [00:03<00:09,  6.11it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:09,  6.17it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:09,  6.16it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:09,  6.11it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:09,  6.07it/s]:  30%|███████████████▏                                  | 24/79 [00:03<00:09,  6.10it/s]:  32%|███████████████▊                                  | 25/79 [00:04<00:08,  6.22it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:08,  6.17it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:08,  6.02it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:08,  6.00it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:08,  6.03it/s]:  38%|██████████████████▉                               | 30/79 [00:04<00:08,  6.01it/s]:  39%|███████████████████▌                              | 31/79 [00:05<00:07,  6.11it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:07,  6.18it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:07,  6.14it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:07,  6.09it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:07,  6.14it/s]:  46%|██████████████████████▊                           | 36/79 [00:05<00:06,  6.22it/s]:  47%|███████████████████████▍                          | 37/79 [00:06<00:06,  6.25it/s]:  48%|████████████████████████                          | 38/79 [00:06<00:06,  6.31it/s]:  49%|████████████████████████▋                         | 39/79 [00:06<00:06,  6.38it/s]:  51%|█████████████████████████▎                        | 40/79 [00:06<00:06,  6.25it/s]:  52%|█████████████████████████▉                        | 41/79 [00:06<00:06,  6.07it/s]:  53%|██████████████████████████▌                       | 42/79 [00:06<00:06,  5.95it/s]:  54%|███████████████████████████▏                      | 43/79 [00:07<00:06,  5.79it/s]:  56%|███████████████████████████▊                      | 44/79 [00:07<00:06,  5.81it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:05,  5.84it/s]:  58%|█████████████████████████████                     | 46/79 [00:07<00:05,  5.82it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:07<00:05,  5.85it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:07<00:05,  5.82it/s]:  62%|███████████████████████████████                   | 49/79 [00:08<00:05,  5.83it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:08<00:04,  5.88it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:08<00:04,  5.89it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:08<00:04,  5.96it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:08<00:04,  5.93it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:08<00:04,  6.02it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:09<00:03,  6.04it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:09<00:03,  6.12it/s]:  72%|████████████████████████████████████              | 57/79 [00:09<00:03,  6.14it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:09<00:03,  6.13it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:09<00:03,  6.10it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:09<00:03,  6.01it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:10<00:03,  5.99it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:10<00:02,  5.99it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:10<00:02,  6.17it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:10<00:02,  6.26it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:10<00:02,  6.12it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:10<00:02,  6.12it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:11<00:01,  6.15it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:11<00:01,  6.09it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:11<00:01,  6.09it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:11<00:01,  6.10it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:11<00:01,  6.02it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:11<00:01,  5.84it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:12<00:01,  5.76it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:12<00:00,  5.78it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:12<00:00,  5.98it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:12<00:00,  5.95it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:12<00:00,  6.02it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:12<00:00,  6.08it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  6.24it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  6.05it/s]
15 Oct 14:59    INFO  epoch 1 training [time: 13.08s, train loss: 49.1130]

[8/8] FISM: {'embedding_size': 64, 'learning_rate': 0.005, 'alpha': 0.5, 'reg_weights': [0.001, 0.001]}

15 Oct 15:03    INFO  ['/home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/run/user/1000/jupyter/runtime/kernel-v36cd5391c52be6575504c740c129b8ae9060d517b.json']
15 Oct 15:03    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /home/kasparas/miniconda3/envs/RecBole/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.005
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
split_to = 0
reg_weights = [0.001, 0.001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


15 Oct 15:04    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
15 Oct 15:04    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
15 Oct 15:04    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
15 Oct 15:04    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
15 Oct 15:04    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
15 Oct 15:04    INFO  FISM(
  (item_src_embedding): Embedding(1683, 64, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 64, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 218051
15 Oct 15:04    INFO  FLOPs: 37888.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:10,  7.12it/s]:   3%|█▎                                                 | 2/79 [00:00<00:12,  6.34it/s]:   4%|█▉                                                 | 3/79 [00:00<00:12,  6.06it/s]:   5%|██▌                                                | 4/79 [00:00<00:12,  5.96it/s]:   6%|███▏                                               | 5/79 [00:00<00:13,  5.66it/s]:   8%|███▊                                               | 6/79 [00:01<00:12,  5.76it/s]:   9%|████▌                                              | 7/79 [00:01<00:12,  5.84it/s]:  10%|█████▏                                             | 8/79 [00:01<00:11,  5.94it/s]:  11%|█████▊                                             | 9/79 [00:01<00:11,  6.00it/s]:  13%|██████▎                                           | 10/79 [00:01<00:11,  6.07it/s]:  14%|██████▉                                           | 11/79 [00:01<00:11,  6.04it/s]:  15%|███████▌                                          | 12/79 [00:02<00:11,  5.98it/s]:  16%|████████▏                                         | 13/79 [00:02<00:11,  5.91it/s]:  18%|████████▊                                         | 14/79 [00:02<00:11,  5.88it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:10,  5.89it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:10,  5.76it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:10,  5.64it/s]:  23%|███████████▍                                      | 18/79 [00:03<00:10,  5.67it/s]:  24%|████████████                                      | 19/79 [00:03<00:10,  5.76it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:10,  5.83it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:09,  5.88it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:09,  5.95it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:09,  5.98it/s]:  30%|███████████████▏                                  | 24/79 [00:04<00:09,  6.00it/s]:  32%|███████████████▊                                  | 25/79 [00:04<00:08,  6.11it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:08,  6.12it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:08,  6.12it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:08,  6.06it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:08,  6.04it/s]:  38%|██████████████████▉                               | 30/79 [00:05<00:08,  5.98it/s]:  39%|███████████████████▌                              | 31/79 [00:05<00:08,  5.91it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:07,  5.93it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:07,  5.91it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:07,  5.94it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:07,  6.00it/s]:  46%|██████████████████████▊                           | 36/79 [00:06<00:07,  5.92it/s]:  47%|███████████████████████▍                          | 37/79 [00:06<00:06,  6.01it/s]:  48%|████████████████████████                          | 38/79 [00:06<00:06,  6.05it/s]:  49%|████████████████████████▋                         | 39/79 [00:06<00:06,  5.99it/s]:  51%|█████████████████████████▎                        | 40/79 [00:06<00:06,  6.08it/s]:  52%|█████████████████████████▉                        | 41/79 [00:06<00:06,  6.11it/s]:  53%|██████████████████████████▌                       | 42/79 [00:07<00:06,  6.04it/s]:  54%|███████████████████████████▏                      | 43/79 [00:07<00:05,  6.12it/s]:  56%|███████████████████████████▊                      | 44/79 [00:07<00:05,  6.11it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:05,  6.16it/s]:  58%|█████████████████████████████                     | 46/79 [00:07<00:05,  5.84it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:07<00:05,  5.93it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:08<00:05,  5.69it/s]:  62%|███████████████████████████████                   | 49/79 [00:08<00:05,  5.69it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:08<00:05,  5.44it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:08<00:05,  5.56it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:08<00:04,  5.62it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:08<00:04,  5.69it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:09<00:04,  5.69it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:09<00:04,  5.73it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:09<00:03,  5.80it/s]:  72%|████████████████████████████████████              | 57/79 [00:09<00:03,  5.86it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:09<00:03,  5.88it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:09<00:03,  5.86it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:10<00:03,  5.82it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:10<00:03,  5.86it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:10<00:02,  5.94it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:10<00:02,  5.96it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:10<00:02,  5.89it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:11<00:02,  5.81it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:11<00:02,  5.79it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:11<00:02,  5.83it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:11<00:01,  5.87it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:11<00:01,  5.87it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:11<00:01,  5.88it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:12<00:01,  5.89it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:12<00:01,  5.88it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:12<00:01,  5.88it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:12<00:00,  5.91it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:12<00:00,  5.85it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:12<00:00,  5.82it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:13<00:00,  5.63it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:13<00:00,  5.70it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  5.93it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  5.89it/s]
15 Oct 15:04    INFO  epoch 0 training [time: 13.46s, train loss: 56.3470]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:12,  6.20it/s]:   3%|█▎                                                 | 2/79 [00:00<00:12,  6.20it/s]:   4%|█▉                                                 | 3/79 [00:00<00:12,  6.17it/s]:   5%|██▌                                                | 4/79 [00:00<00:12,  6.07it/s]:   6%|███▏                                               | 5/79 [00:00<00:12,  5.91it/s]:   8%|███▊                                               | 6/79 [00:00<00:12,  5.99it/s]:   9%|████▌                                              | 7/79 [00:01<00:12,  5.92it/s]:  10%|█████▏                                             | 8/79 [00:01<00:11,  5.96it/s]:  11%|█████▊                                             | 9/79 [00:01<00:11,  5.89it/s]:  13%|██████▎                                           | 10/79 [00:01<00:11,  5.82it/s]:  14%|██████▉                                           | 11/79 [00:01<00:11,  5.88it/s]:  15%|███████▌                                          | 12/79 [00:02<00:11,  5.84it/s]:  16%|████████▏                                         | 13/79 [00:02<00:11,  5.85it/s]:  18%|████████▊                                         | 14/79 [00:02<00:11,  5.86it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:10,  5.89it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:10,  5.97it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:10,  5.99it/s]:  23%|███████████▍                                      | 18/79 [00:03<00:10,  6.01it/s]:  24%|████████████                                      | 19/79 [00:03<00:09,  6.01it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:09,  6.06it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:09,  6.15it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:09,  6.15it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:09,  6.01it/s]:  30%|███████████████▏                                  | 24/79 [00:04<00:09,  5.83it/s]:  32%|███████████████▊                                  | 25/79 [00:04<00:09,  5.88it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:08,  5.93it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:08,  5.98it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:08,  6.03it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:08,  6.04it/s]:  38%|██████████████████▉                               | 30/79 [00:05<00:08,  6.00it/s]:  39%|███████████████████▌                              | 31/79 [00:05<00:07,  6.00it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:07,  6.05it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:07,  6.07it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:07,  6.08it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:07,  6.06it/s]:  46%|██████████████████████▊                           | 36/79 [00:06<00:07,  5.93it/s]:  47%|███████████████████████▍                          | 37/79 [00:06<00:07,  5.84it/s]:  48%|████████████████████████                          | 38/79 [00:06<00:07,  5.71it/s]:  49%|████████████████████████▋                         | 39/79 [00:06<00:06,  5.72it/s]:  51%|█████████████████████████▎                        | 40/79 [00:06<00:06,  5.74it/s]:  52%|█████████████████████████▉                        | 41/79 [00:06<00:06,  5.74it/s]:  53%|██████████████████████████▌                       | 42/79 [00:07<00:06,  5.67it/s]:  54%|███████████████████████████▏                      | 43/79 [00:07<00:06,  5.67it/s]:  56%|███████████████████████████▊                      | 44/79 [00:07<00:06,  5.68it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:05,  5.69it/s]:  58%|█████████████████████████████                     | 46/79 [00:07<00:05,  5.56it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:07<00:05,  5.53it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:08<00:05,  5.55it/s]:  62%|███████████████████████████████                   | 49/79 [00:08<00:05,  5.62it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:08<00:05,  5.71it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:08<00:04,  5.71it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:08<00:04,  5.71it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:09<00:04,  5.84it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:09<00:04,  5.94it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:09<00:04,  5.97it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:09<00:03,  5.80it/s]:  72%|████████████████████████████████████              | 57/79 [00:09<00:03,  5.82it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:09<00:03,  5.73it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:10<00:03,  5.73it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:10<00:03,  5.74it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:10<00:03,  5.82it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:10<00:02,  5.81it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:10<00:02,  5.86it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:10<00:02,  5.82it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:11<00:02,  5.74it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:11<00:02,  5.63it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:11<00:02,  5.72it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:11<00:01,  5.72it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:11<00:01,  5.83it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:11<00:01,  5.88it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:12<00:01,  5.95it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:12<00:01,  5.94it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:12<00:01,  5.89it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:12<00:00,  5.93it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:12<00:00,  5.95it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:12<00:00,  5.87it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:13<00:00,  5.81it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:13<00:00,  5.78it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  5.86it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:13<00:00,  5.86it/s]
15 Oct 15:04    INFO  epoch 1 training [time: 13.52s, train loss: 54.7640]

Saved to:
/home/kasparas/Desktop/MScCS/RecommenderSystems/RecBole_DSAIT4335_Group_18/tuning_results/FISM_tuning.csv

Best configuration:

,embedding_size,learning_rate,alpha,reg_weights,valid_score,recall@10,mrr@10,ndcg@10,hit@10,precision@10
0,64,0.005,0.5,"[0.0001, 0.0001]",0.3429,0.1821,0.3429,0.1976,0.7169,0.1417