In [1]:
from recbole.quick_start import run_recbole

from itertools import product
from pathlib import Path

import pandas as pd
import json

/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ray/_private/parameter.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [16]:
import os
from pathlib import Path

# Required only for loading checkpoints generated by a trusted local run.
os.environ.setdefault("TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD", "1")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

from recbole.quick_start import run_recbole
from recbole.config import Config
from recbole.data import create_dataset, data_preparation
from recbole.utils import get_model, get_trainer, init_seed


def find_project_root(start: Path) -> Path:
    for directory in (start, *start.parents):
        if (directory / "run_recbole.py").exists():
            return directory
    raise FileNotFoundError("Could not find project root (run_recbole.py)")


ROOT = find_project_root(Path.cwd().resolve())
DATASET = "ml-100k"
SEED = 2020
CONFIG_ROOT = ROOT / "recbole" / "config"
DATA_DIR = ROOT / "dataset"
CHECKPOINT_DIR = ROOT / "saved"
RESULTS_DIR = ROOT / "group_18" / "results" / "task_1_2"
RESULTS_FILE = RESULTS_DIR / "baseline_results.csv"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)

In [3]:
from recbole.config import Config
from recbole.data import create_dataset, data_preparation
from recbole.utils import get_model, get_trainer, init_seed


def evaluate_traditional_model(model_name, config_path, params):
    """Fit a traditional RecBole model and evaluate on validation data."""

    config = Config(
        model=model_name,
        dataset="ml-100k",
        config_file_list=[str(config_path)],
        config_dict={
            "seed": 2020,
            "reproducibility": True,
            "use_gpu": False,
            "data_path": str(DATA_DIR),
            **params,
        },
    )

    init_seed(config["seed"], config["reproducibility"])

    dataset = create_dataset(config)
    train_data, valid_data, _ = data_preparation(config, dataset)

    # EASE and SLIMElastic fit their parameters during initialization
    model = get_model(model_name)(
        config,
        train_data.dataset
    ).to(config["device"])

    trainer = get_trainer(
        config["MODEL_TYPE"],
        config["model"]
    )(config, model)

    valid_result = trainer.evaluate(
        valid_data,
        load_best_model=False
    )

    return {
        "best_valid_score": valid_result["mrr@10"],
        "best_valid_result": valid_result,
    }

In [4]:
def tune_model(
    name,
    model,
    config_path,
    search_space,
    fixed_params=None,
    save=True
):
    """
    Exhaustively tune a RecBole model.

    Parameters
    ----------
    name : str
        Name used for displaying/saving results.

    model : str
        RecBole model name.

    config_path : str or Path
        Path to the model's YAML configuration.

    search_space : dict
        Hyperparameters and values to test.

        Example:
        {
            "k": [20, 50, 100],
            "shrink": [0, 10, 50]
        }

    fixed_params : dict, optional
        Parameters that should remain fixed.
        Useful for things such as knn_method.

    save : bool
        Save tuning results to CSV.

    Returns
    -------
    DataFrame
        All tuning experiments.
    """

    if fixed_params is None:
        fixed_params = {}

    # Parameter names
    param_names = list(search_space.keys())

    # All combinations
    combinations = list(
        product(*search_space.values())
    )

    results = []

    print(f"Tuning {name}")
    print(f"Number of experiments: {len(combinations)}")
    print("=" * 60)

    for i, values in enumerate(combinations, start=1):

        params = dict(zip(param_names, values))

        config_dict = {
            "model": model,
            "dataset": "ml-100k",
            **fixed_params,
            **params,
        }

        print(
            f"[{i}/{len(combinations)}] "
            f"{name}: {params}"
        )

        if model in {"EASE", "SLIMElastic"}:
            result = evaluate_traditional_model(
                model_name=model,
                config_path=config_path,
                params={**fixed_params, **params},
            )
        else:
            result = run_recbole(
                model=model,
                dataset="ml-100k",
                config_dict=config_dict,
                config_file_list=[str(config_path)],
                saved=False,
            )

        valid = result["best_valid_result"]

        row = {
            **params,
            "valid_score": result["best_valid_score"],
            **valid,
        }

        results.append(row)
        
        valid = result["best_valid_result"]

    df = pd.DataFrame(results)

    # Best first
    df = df.sort_values(
        "valid_score",
        ascending=False
    ).reset_index(drop=True)

    if save:
        output_path = RESULTS_DIR / f"{name}_tuning.csv"
        df.to_csv(output_path, index=False)

        print(f"\nSaved to:")
        print(output_path)

    print("\nBest configuration:")
    display(df.head(1))

    return df

In [5]:
itemcf_space = {
    "k": [20, 50, 100, 200],
    "shrink": [0, 10, 50, 100]
}

In [6]:
itemcf_results = tune_model(
    name="ItemCF",
    model="ItemKNN",
    config_path=CONFIG_ROOT / "ItemKNN" / "ml-100k.yaml",
    search_space=itemcf_space,
    fixed_params={
        "knn_method": "item"
    }
)

Tuning ItemCF
Number of experiments: 16
============================================================
[1/16] ItemCF: {'k': 20, 'shrink': 0}

24 Oct 13:59    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 13:59    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 0
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 13:59    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 13:59    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 13:59    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 13:59    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 13:59    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  39%|███████████████████▏                             | 31/79 [00:00<00:00, 305.46it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 444.72it/s]
24 Oct 13:59    INFO  epoch 0 training [time: 0.20s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  71%|████████████████████████████████▌             | 334/472 [00:00<00:00, 3335.70it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 3388.62it/s]
24 Oct 13:59    INFO  epoch 0 evaluating [time: 0.15s, valid_score: 0.355300]
24 Oct 13:59    INFO  valid result:
recall@10 : 0.1884    mrr@10 : 0.3553    ndcg@10 : 0.2063    hit@10 : 0.7041    precision@10 : 0.1471
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  78%|███████████████████████████████████▊          | 367/472 [00:00<00:00, 3669.90it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 3653.53it/s]
24 Oct 13:59    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    23.50 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.51 G/16.00 G |
+-------------+----------------+
24 Oct 13:59    INFO  best valid : OrderedDict([('recall@10', 0.1884), ('mrr@10', 0.3553), ('ndcg@10', 0.2063), ('hit@10', 0.7041), ('precision@10', 0.1471)])
24 Oct 13:59    INFO  test result: OrderedDict([('recall@10', 0.2328), ('mrr@10', 0.4364), ('ndcg@10', 0.2637), ('hit@10', 0.7762), ('precision@10', 0.1852)])

[2/16] ItemCF: {'k': 20, 'shrink': 10}

24 Oct 13:59    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 13:59    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 10
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 13:59    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 13:59    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 13:59    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 13:59    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 13:59    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 899.35it/s]
24 Oct 13:59    INFO  epoch 0 training [time: 0.09s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  61%|████████████████████████████▏                 | 289/472 [00:00<00:00, 2880.84it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2933.44it/s]
24 Oct 13:59    INFO  epoch 0 evaluating [time: 0.17s, valid_score: 0.356500]
24 Oct 13:59    INFO  valid result:
recall@10 : 0.1925    mrr@10 : 0.3565    ndcg@10 : 0.2077    hit@10 : 0.7179    precision@10 : 0.1478
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  64%|█████████████████████████████▍                | 302/472 [00:00<00:00, 3014.57it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 3038.47it/s]
24 Oct 13:59    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    20.00 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.55 G/16.00 G |
+-------------+----------------+
24 Oct 13:59    INFO  best valid : OrderedDict([('recall@10', 0.1925), ('mrr@10', 0.3565), ('ndcg@10', 0.2077), ('hit@10', 0.7179), ('precision@10', 0.1478)])
24 Oct 13:59    INFO  test result: OrderedDict([('recall@10', 0.2339), ('mrr@10', 0.4326), ('ndcg@10', 0.2609), ('hit@10', 0.772), ('precision@10', 0.181)])

[3/16] ItemCF: {'k': 20, 'shrink': 50}

24 Oct 13:59    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 13:59    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 50
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 13:59    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 13:59    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 13:59    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 13:59    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 13:59    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  99%|████████████████████████████████████████████████▍| 78/79 [00:00<00:00, 776.25it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 738.01it/s]
24 Oct 13:59    INFO  epoch 0 training [time: 0.11s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  50%|██████████████████████▊                       | 234/472 [00:00<00:00, 2337.17it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2393.29it/s]
24 Oct 13:59    INFO  epoch 0 evaluating [time: 0.21s, valid_score: 0.348400]
24 Oct 13:59    INFO  valid result:
recall@10 : 0.1908    mrr@10 : 0.3484    ndcg@10 : 0.2051    hit@10 : 0.7073    precision@10 : 0.1459
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  53%|████████████████████████▎                     | 250/472 [00:00<00:00, 2494.51it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2521.19it/s]
24 Oct 13:59    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    25.90 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.59 G/16.00 G |
+-------------+----------------+
24 Oct 13:59    INFO  best valid : OrderedDict([('recall@10', 0.1908), ('mrr@10', 0.3484), ('ndcg@10', 0.2051), ('hit@10', 0.7073), ('precision@10', 0.1459)])
24 Oct 13:59    INFO  test result: OrderedDict([('recall@10', 0.2341), ('mrr@10', 0.4393), ('ndcg@10', 0.2627), ('hit@10', 0.7784), ('precision@10', 0.1803)])

[4/16] ItemCF: {'k': 20, 'shrink': 100}

24 Oct 13:59    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 13:59    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 100
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 13:59    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 13:59    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 13:59    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 13:59    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 13:59    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 895.25it/s]
24 Oct 13:59    INFO  epoch 0 training [time: 0.09s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  49%|██████████████████████▍                       | 230/472 [00:00<00:00, 2298.28it/s]: 100%|█████████████████████████████████████████████▊| 470/472 [00:00<00:00, 2356.00it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2314.19it/s]
24 Oct 13:59    INFO  epoch 0 evaluating [time: 0.21s, valid_score: 0.350100]
24 Oct 13:59    INFO  valid result:
recall@10 : 0.1965    mrr@10 : 0.3501    ndcg@10 : 0.2081    hit@10 : 0.7137    precision@10 : 0.1474
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  44%|████████████████████▎                         | 208/472 [00:00<00:00, 2074.70it/s]:  95%|███████████████████████████████████████████▊  | 449/472 [00:00<00:00, 2269.80it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2210.88it/s]
24 Oct 13:59    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    25.20 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.58 G/16.00 G |
+-------------+----------------+
24 Oct 13:59    INFO  best valid : OrderedDict([('recall@10', 0.1965), ('mrr@10', 0.3501), ('ndcg@10', 0.2081), ('hit@10', 0.7137), ('precision@10', 0.1474)])
24 Oct 13:59    INFO  test result: OrderedDict([('recall@10', 0.234), ('mrr@10', 0.4396), ('ndcg@10', 0.2633), ('hit@10', 0.7699), ('precision@10', 0.1811)])

[5/16] ItemCF: {'k': 50, 'shrink': 0}

24 Oct 13:59    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 13:59    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 0
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 13:59    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 13:59    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 13:59    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 13:59    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 13:59    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 891.12it/s]
24 Oct 13:59    INFO  epoch 0 training [time: 0.10s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  56%|█████████████████████████▉                    | 266/472 [00:00<00:00, 2650.14it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2793.38it/s]
24 Oct 13:59    INFO  epoch 0 evaluating [time: 0.18s, valid_score: 0.368000]
24 Oct 13:59    INFO  valid result:
recall@10 : 0.1992    mrr@10 : 0.368    ndcg@10 : 0.2163    hit@10 : 0.7296    precision@10 : 0.1531
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  63%|████████████████████████████▊                 | 296/472 [00:00<00:00, 2956.58it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2946.32it/s]
24 Oct 13:59    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    21.20 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.57 G/16.00 G |
+-------------+----------------+
24 Oct 13:59    INFO  best valid : OrderedDict([('recall@10', 0.1992), ('mrr@10', 0.368), ('ndcg@10', 0.2163), ('hit@10', 0.7296), ('precision@10', 0.1531)])
24 Oct 13:59    INFO  test result: OrderedDict([('recall@10', 0.2425), ('mrr@10', 0.4646), ('ndcg@10', 0.2794), ('hit@10', 0.79), ('precision@10', 0.1916)])

[6/16] ItemCF: {'k': 50, 'shrink': 10}

24 Oct 13:59    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 13:59    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 10
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 13:59    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 13:59    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 13:59    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 13:59    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 13:59    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 908.82it/s]
24 Oct 13:59    INFO  epoch 0 training [time: 0.09s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  49%|██████████████████████▌                       | 232/472 [00:00<00:00, 2318.47it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2370.13it/s]
24 Oct 13:59    INFO  epoch 0 evaluating [time: 0.21s, valid_score: 0.374300]
24 Oct 13:59    INFO  valid result:
recall@10 : 0.2017    mrr@10 : 0.3743    ndcg@10 : 0.2197    hit@10 : 0.7243    precision@10 : 0.1549
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  50%|███████████████████████                       | 237/472 [00:00<00:00, 2366.52it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2402.27it/s]
24 Oct 13:59    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    21.00 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.61 G/16.00 G |
+-------------+----------------+
24 Oct 13:59    INFO  best valid : OrderedDict([('recall@10', 0.2017), ('mrr@10', 0.3743), ('ndcg@10', 0.2197), ('hit@10', 0.7243), ('precision@10', 0.1549)])
24 Oct 13:59    INFO  test result: OrderedDict([('recall@10', 0.2406), ('mrr@10', 0.4623), ('ndcg@10', 0.2782), ('hit@10', 0.7858), ('precision@10', 0.1906)])

[7/16] ItemCF: {'k': 50, 'shrink': 50}

24 Oct 13:59    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 13:59    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 50
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 13:59    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 13:59    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 13:59    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 13:59    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 13:59    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 865.49it/s]
24 Oct 13:59    INFO  epoch 0 training [time: 0.10s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  45%|████████████████████▊                         | 213/472 [00:00<00:00, 2129.57it/s]:  91%|█████████████████████████████████████████▉    | 430/472 [00:00<00:00, 2153.22it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2105.65it/s]
24 Oct 13:59    INFO  epoch 0 evaluating [time: 0.23s, valid_score: 0.378500]
24 Oct 13:59    INFO  valid result:
recall@10 : 0.2019    mrr@10 : 0.3785    ndcg@10 : 0.2194    hit@10 : 0.7338    precision@10 : 0.1516
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  40%|██████████████████▎                           | 188/472 [00:00<00:00, 1878.43it/s]:  81%|█████████████████████████████████████▏        | 381/472 [00:00<00:00, 1908.14it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1804.44it/s]
24 Oct 13:59    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    21.30 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.63 G/16.00 G |
+-------------+----------------+
24 Oct 13:59    INFO  best valid : OrderedDict([('recall@10', 0.2019), ('mrr@10', 0.3785), ('ndcg@10', 0.2194), ('hit@10', 0.7338), ('precision@10', 0.1516)])
24 Oct 13:59    INFO  test result: OrderedDict([('recall@10', 0.2346), ('mrr@10', 0.4641), ('ndcg@10', 0.2767), ('hit@10', 0.7741), ('precision@10', 0.1872)])

[8/16] ItemCF: {'k': 50, 'shrink': 100}

24 Oct 13:59    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 13:59    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 100
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 13:59    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 13:59    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 13:59    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 13:59    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 873.96it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.10s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  42%|███████████████████▍                          | 199/472 [00:00<00:00, 1985.49it/s]:  85%|███████████████████████████████████████▎      | 403/472 [00:00<00:00, 2014.75it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1984.99it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.25s, valid_score: 0.374200]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.204    mrr@10 : 0.3742    ndcg@10 : 0.2194    hit@10 : 0.7285    precision@10 : 0.1532
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  44%|████████████████████▎                         | 208/472 [00:00<00:00, 2072.33it/s]:  88%|████████████████████████████████████████▌     | 416/472 [00:00<00:00, 2028.24it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1979.78it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    27.40 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.64 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.204), ('mrr@10', 0.3742), ('ndcg@10', 0.2194), ('hit@10', 0.7285), ('precision@10', 0.1532)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.233), ('mrr@10', 0.4669), ('ndcg@10', 0.2746), ('hit@10', 0.7709), ('precision@10', 0.1829)])

[9/16] ItemCF: {'k': 100, 'shrink': 0}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 0
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  90%|████████████████████████████████████████████     | 71/79 [00:00<00:00, 705.13it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 599.97it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.14s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  48%|██████████████████████                        | 227/472 [00:00<00:00, 2264.68it/s]:  99%|█████████████████████████████████████████████▋| 469/472 [00:00<00:00, 2352.90it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2293.08it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.22s, valid_score: 0.377900]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.2058    mrr@10 : 0.3779    ndcg@10 : 0.2213    hit@10 : 0.7328    precision@10 : 0.1554
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  50%|███████████████████████                       | 237/472 [00:00<00:00, 2364.44it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2414.09it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    21.80 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.58 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.2058), ('mrr@10', 0.3779), ('ndcg@10', 0.2213), ('hit@10', 0.7328), ('precision@10', 0.1554)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.247), ('mrr@10', 0.4623), ('ndcg@10', 0.2834), ('hit@10', 0.7847), ('precision@10', 0.1931)])

[10/16] ItemCF: {'k': 100, 'shrink': 10}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 10
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 864.55it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.10s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  43%|███████████████████▉                          | 204/472 [00:00<00:00, 2032.28it/s]:  88%|████████████████████████████████████████▍     | 415/472 [00:00<00:00, 2076.75it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2028.99it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.24s, valid_score: 0.378000]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.2027    mrr@10 : 0.378    ndcg@10 : 0.2215    hit@10 : 0.7296    precision@10 : 0.1555
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  44%|████████████████████▎                         | 208/472 [00:00<00:00, 2074.98it/s]:  88%|████████████████████████████████████████▌     | 416/472 [00:00<00:00, 2071.09it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2034.07it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    18.70 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.62 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.2027), ('mrr@10', 0.378), ('ndcg@10', 0.2215), ('hit@10', 0.7296), ('precision@10', 0.1555)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.244), ('mrr@10', 0.4705), ('ndcg@10', 0.2846), ('hit@10', 0.7805), ('precision@10', 0.1911)])

[11/16] ItemCF: {'k': 100, 'shrink': 50}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 50
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 886.20it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.10s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  40%|██████████████████▌                           | 191/472 [00:00<00:00, 1907.83it/s]:  82%|█████████████████████████████████████▌        | 385/472 [00:00<00:00, 1921.57it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1897.30it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.26s, valid_score: 0.381300]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.2044    mrr@10 : 0.3813    ndcg@10 : 0.2216    hit@10 : 0.7243    precision@10 : 0.1524
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  41%|██████████████████▉                           | 194/472 [00:00<00:00, 1938.58it/s]:  82%|█████████████████████████████████████▊        | 388/472 [00:00<00:00, 1927.30it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1900.74it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    26.10 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.64 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.2044), ('mrr@10', 0.3813), ('ndcg@10', 0.2216), ('hit@10', 0.7243), ('precision@10', 0.1524)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.2414), ('mrr@10', 0.4731), ('ndcg@10', 0.2816), ('hit@10', 0.7826), ('precision@10', 0.1859)])

[12/16] ItemCF: {'k': 100, 'shrink': 100}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 100
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 876.88it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.10s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  40%|██████████████████▎                           | 188/472 [00:00<00:00, 1877.82it/s]:  81%|█████████████████████████████████████         | 380/472 [00:00<00:00, 1898.46it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1880.68it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.26s, valid_score: 0.386900]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.2007    mrr@10 : 0.3869    ndcg@10 : 0.2216    hit@10 : 0.7264    precision@10 : 0.1496
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  39%|██████████████████                            | 185/472 [00:00<00:00, 1847.80it/s]:  79%|████████████████████████████████████▍         | 374/472 [00:00<00:00, 1867.94it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1853.84it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    29.30 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.59 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.2007), ('mrr@10', 0.3869), ('ndcg@10', 0.2216), ('hit@10', 0.7264), ('precision@10', 0.1496)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.2402), ('mrr@10', 0.4827), ('ndcg@10', 0.2819), ('hit@10', 0.7922), ('precision@10', 0.183)])

[13/16] ItemCF: {'k': 200, 'shrink': 0}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 0
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 871.83it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.10s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  41%|███████████████████                           | 195/472 [00:00<00:00, 1949.20it/s]:  84%|██████████████████████████████████████▋       | 397/472 [00:00<00:00, 1985.29it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1951.70it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.26s, valid_score: 0.370600]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.2073    mrr@10 : 0.3706    ndcg@10 : 0.223    hit@10 : 0.7328    precision@10 : 0.155
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  42%|███████████████████▎                          | 198/472 [00:00<00:00, 1974.55it/s]:  84%|██████████████████████████████████████▌       | 396/472 [00:00<00:00, 1966.75it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1885.32it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    24.70 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.61 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.2073), ('mrr@10', 0.3706), ('ndcg@10', 0.223), ('hit@10', 0.7328), ('precision@10', 0.155)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.2529), ('mrr@10', 0.4767), ('ndcg@10', 0.2894), ('hit@10', 0.7922), ('precision@10', 0.1935)])

[14/16] ItemCF: {'k': 200, 'shrink': 10}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 10
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 856.05it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.10s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  39%|█████████████████▋                            | 182/472 [00:00<00:00, 1815.97it/s]:  77%|███████████████████████████████████▌          | 365/472 [00:00<00:00, 1822.58it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1807.18it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.28s, valid_score: 0.370500]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.2064    mrr@10 : 0.3705    ndcg@10 : 0.2228    hit@10 : 0.7359    precision@10 : 0.1551
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  40%|██████████████████▏                           | 187/472 [00:00<00:00, 1865.43it/s]:  79%|████████████████████████████████████▍         | 374/472 [00:00<00:00, 1836.17it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1813.64it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    32.50 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.62 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.2064), ('mrr@10', 0.3705), ('ndcg@10', 0.2228), ('hit@10', 0.7359), ('precision@10', 0.1551)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.2526), ('mrr@10', 0.4791), ('ndcg@10', 0.29), ('hit@10', 0.79), ('precision@10', 0.1928)])

[15/16] ItemCF: {'k': 200, 'shrink': 50}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 50
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  86%|██████████████████████████████████████████▏      | 68/79 [00:00<00:00, 677.68it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 589.25it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.15s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  34%|███████████████▌                              | 160/472 [00:00<00:00, 1594.91it/s]:  69%|███████████████████████████████▉              | 328/472 [00:00<00:00, 1640.26it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1588.51it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.32s, valid_score: 0.374400]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.2045    mrr@10 : 0.3744    ndcg@10 : 0.2215    hit@10 : 0.7243    precision@10 : 0.1519
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  29%|█████████████▌                                | 139/472 [00:00<00:00, 1388.93it/s]:  60%|███████████████████████████▍                  | 282/472 [00:00<00:00, 1411.95it/s]:  97%|████████████████████████████████████████████▌ | 457/472 [00:00<00:00, 1563.58it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1485.29it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    42.80 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.63 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.2045), ('mrr@10', 0.3744), ('ndcg@10', 0.2215), ('hit@10', 0.7243), ('precision@10', 0.1519)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.2444), ('mrr@10', 0.4801), ('ndcg@10', 0.2861), ('hit@10', 0.7794), ('precision@10', 0.1864)])

[16/16] ItemCF: {'k': 200, 'shrink': 100}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 100
knn_method = item
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  91%|████████████████████████████████████████████▋    | 72/79 [00:00<00:00, 715.34it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 647.60it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.14s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  36%|████████████████▎                             | 168/472 [00:00<00:00, 1672.79it/s]:  72%|█████████████████████████████████             | 339/472 [00:00<00:00, 1690.80it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1691.26it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.30s, valid_score: 0.377900]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.1971    mrr@10 : 0.3779    ndcg@10 : 0.219    hit@10 : 0.719    precision@10 : 0.1486
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  38%|█████████████████▍                            | 179/472 [00:00<00:00, 1786.48it/s]:  76%|██████████████████████████████████▉           | 358/472 [00:00<00:00, 1726.49it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1708.99it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    21.90 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.62 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.1971), ('mrr@10', 0.3779), ('ndcg@10', 0.219), ('hit@10', 0.719), ('precision@10', 0.1486)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.2341), ('mrr@10', 0.4696), ('ndcg@10', 0.2765), ('hit@10', 0.7646), ('precision@10', 0.1801)])

Saved to:
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/group_18/results/task_1_2/ItemCF_tuning.csv

Best configuration:

     k  shrink  valid_score  recall@10  mrr@10  ndcg@10  hit@10  precision@10
0  100     100       0.3869     0.2007  0.3869   0.2216  0.7264        0.1496

In [7]:
usercf_results = tune_model(
    name="UserCF",
    model="ItemKNN",
    config_path=CONFIG_ROOT / "ItemKNN" / "ml-100k.yaml",
    search_space=itemcf_space,
    fixed_params={
        "knn_method": "user"
    }
)

Tuning UserCF
Number of experiments: 16
============================================================
[1/16] UserCF: {'k': 20, 'shrink': 0}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 0
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 770.30it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 728.74it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  65%|█████████████████████████████▉                | 307/472 [00:00<00:00, 3065.76it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 3060.38it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.17s, valid_score: 0.370300]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.2125    mrr@10 : 0.3703    ndcg@10 : 0.2216    hit@10 : 0.7359    precision@10 : 0.1505
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  72%|█████████████████████████████████▎            | 342/472 [00:00<00:00, 3415.60it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 3282.89it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    21.00 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.59 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.2125), ('mrr@10', 0.3703), ('ndcg@10', 0.2216), ('hit@10', 0.7359), ('precision@10', 0.1505)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.2429), ('mrr@10', 0.4381), ('ndcg@10', 0.2669), ('hit@10', 0.7773), ('precision@10', 0.1782)])

[2/16] UserCF: {'k': 20, 'shrink': 10}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 10
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 842.68it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.11s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  64%|█████████████████████████████▍                | 302/472 [00:00<00:00, 3009.56it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2988.44it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.17s, valid_score: 0.367800]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.2092    mrr@10 : 0.3678    ndcg@10 : 0.2177    hit@10 : 0.7359    precision@10 : 0.1471
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  66%|██████████████████████████████▌               | 313/472 [00:00<00:00, 3124.19it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 3052.51it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    21.20 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.59 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.2092), ('mrr@10', 0.3678), ('ndcg@10', 0.2177), ('hit@10', 0.7359), ('precision@10', 0.1471)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.2404), ('mrr@10', 0.4167), ('ndcg@10', 0.2585), ('hit@10', 0.7741), ('precision@10', 0.1751)])

[3/16] UserCF: {'k': 20, 'shrink': 50}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 50
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  92%|█████████████████████████████████████████████▎   | 73/79 [00:00<00:00, 718.40it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 639.93it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.14s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  50%|███████████████████████                       | 237/472 [00:00<00:00, 2365.86it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2378.24it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.22s, valid_score: 0.329700]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.186    mrr@10 : 0.3297    ndcg@10 : 0.1944    hit@10 : 0.6967    precision@10 : 0.134
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  53%|████████████████████████▎                     | 250/472 [00:00<00:00, 2499.02it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2351.68it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    27.80 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.60 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.186), ('mrr@10', 0.3297), ('ndcg@10', 0.1944), ('hit@10', 0.6967), ('precision@10', 0.134)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.2224), ('mrr@10', 0.3819), ('ndcg@10', 0.2352), ('hit@10', 0.7444), ('precision@10', 0.1618)])

[4/16] UserCF: {'k': 20, 'shrink': 100}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 20
shrink = 100
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  85%|█████████████████████████████████████████▌       | 67/79 [00:00<00:00, 666.99it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 598.36it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.15s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  47%|█████████████████████▊                        | 224/472 [00:00<00:00, 2235.51it/s]:  98%|█████████████████████████████████████████████ | 463/472 [00:00<00:00, 2323.64it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2221.20it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.23s, valid_score: 0.313500]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.1784    mrr@10 : 0.3135    ndcg@10 : 0.1852    hit@10 : 0.6713    precision@10 : 0.1268
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  50%|███████████████████████                       | 236/472 [00:00<00:00, 2353.29it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2276.47it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2212.24it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    27.60 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.58 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.1784), ('mrr@10', 0.3135), ('ndcg@10', 0.1852), ('hit@10', 0.6713), ('precision@10', 0.1268)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.2068), ('mrr@10', 0.3641), ('ndcg@10', 0.2195), ('hit@10', 0.7158), ('precision@10', 0.1507)])

[5/16] UserCF: {'k': 50, 'shrink': 0}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 0
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 847.44it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.11s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  56%|█████████████████████████▋                    | 263/472 [00:00<00:00, 2624.96it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2640.35it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.20s, valid_score: 0.401000]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.216    mrr@10 : 0.401    ndcg@10 : 0.2355    hit@10 : 0.755    precision@10 : 0.1562
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  57%|██████████████████████████▏                   | 269/472 [00:00<00:00, 2686.16it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2642.04it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    28.80 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.58 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.216), ('mrr@10', 0.401), ('ndcg@10', 0.2355), ('hit@10', 0.755), ('precision@10', 0.1562)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.2524), ('mrr@10', 0.477), ('ndcg@10', 0.2877), ('hit@10', 0.7932), ('precision@10', 0.1909)])

[6/16] UserCF: {'k': 50, 'shrink': 10}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 10
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 776.39it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 725.02it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.13s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  18%|████████▊                                       | 87/472 [00:00<00:00, 867.36it/s]:  58%|██████████████████████████▊                   | 275/472 [00:00<00:00, 1462.27it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1582.19it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.32s, valid_score: 0.380600]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.209    mrr@10 : 0.3806    ndcg@10 : 0.2266    hit@10 : 0.7359    precision@10 : 0.1526
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  46%|████████████████████▉                         | 215/472 [00:00<00:00, 2147.78it/s]:  92%|██████████████████████████████████████████▍   | 436/472 [00:00<00:00, 2183.06it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2049.64it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    32.30 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.58 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.209), ('mrr@10', 0.3806), ('ndcg@10', 0.2266), ('hit@10', 0.7359), ('precision@10', 0.1526)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.2456), ('mrr@10', 0.469), ('ndcg@10', 0.2816), ('hit@10', 0.7826), ('precision@10', 0.1853)])

[7/16] UserCF: {'k': 50, 'shrink': 50}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 50
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 773.85it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 722.58it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  37%|█████████████████▏                            | 176/472 [00:00<00:00, 1753.98it/s]:  83%|██████████████████████████████████████▍       | 394/472 [00:00<00:00, 2000.63it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1933.47it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.30s, valid_score: 0.361800]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.2018    mrr@10 : 0.3618    ndcg@10 : 0.2164    hit@10 : 0.7275    precision@10 : 0.1469
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  47%|█████████████████████▌                        | 221/472 [00:00<00:00, 2205.41it/s]:  94%|███████████████████████████████████████████   | 442/472 [00:00<00:00, 2158.45it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2064.11it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    22.80 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.58 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.2018), ('mrr@10', 0.3618), ('ndcg@10', 0.2164), ('hit@10', 0.7275), ('precision@10', 0.1469)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.2384), ('mrr@10', 0.445), ('ndcg@10', 0.2695), ('hit@10', 0.7561), ('precision@10', 0.1793)])

[8/16] UserCF: {'k': 50, 'shrink': 100}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 50
shrink = 100
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 811.60it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.11s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  42%|███████████████████                           | 196/472 [00:00<00:00, 1954.18it/s]:  85%|██████████████████████████████████████▉       | 399/472 [00:00<00:00, 1995.57it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1936.34it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.26s, valid_score: 0.350300]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.197    mrr@10 : 0.3503    ndcg@10 : 0.2086    hit@10 : 0.7179    precision@10 : 0.1434
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  42%|███████████████████▏                          | 197/472 [00:00<00:00, 1967.82it/s]:  84%|██████████████████████████████████████▋       | 397/472 [00:00<00:00, 1983.56it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1926.66it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    22.20 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.63 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.197), ('mrr@10', 0.3503), ('ndcg@10', 0.2086), ('hit@10', 0.7179), ('precision@10', 0.1434)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.2286), ('mrr@10', 0.4245), ('ndcg@10', 0.2565), ('hit@10', 0.7497), ('precision@10', 0.173)])

[9/16] UserCF: {'k': 100, 'shrink': 0}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 0
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 768.73it/s]: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 718.81it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.13s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  44%|████████████████████▎                         | 209/472 [00:00<00:00, 2081.73it/s]:  94%|███████████████████████████████████████████▎  | 444/472 [00:00<00:00, 2237.86it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2106.26it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.24s, valid_score: 0.399200]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.2102    mrr@10 : 0.3992    ndcg@10 : 0.2345    hit@10 : 0.7402    precision@10 : 0.1567
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  48%|██████████████████████                        | 227/472 [00:00<00:00, 2264.16it/s]:  97%|████████████████████████████████████████████▊ | 460/472 [00:00<00:00, 2299.77it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2190.49it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    19.50 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.62 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.2102), ('mrr@10', 0.3992), ('ndcg@10', 0.2345), ('hit@10', 0.7402), ('precision@10', 0.1567)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.2442), ('mrr@10', 0.4834), ('ndcg@10', 0.2873), ('hit@10', 0.7805), ('precision@10', 0.1885)])

[10/16] UserCF: {'k': 100, 'shrink': 10}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 10
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 830.20it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.11s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  43%|███████████████████▉                          | 205/472 [00:00<00:00, 2047.81it/s]:  87%|███████████████████████████████████████▉      | 410/472 [00:00<00:00, 1949.69it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1908.50it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.27s, valid_score: 0.388200]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.2094    mrr@10 : 0.3882    ndcg@10 : 0.2303    hit@10 : 0.7402    precision@10 : 0.1554
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  46%|████████████████████▉                         | 215/472 [00:00<00:00, 2142.16it/s]:  92%|██████████████████████████████████████████▎   | 434/472 [00:00<00:00, 2166.88it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 2056.22it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    18.10 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.64 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.2094), ('mrr@10', 0.3882), ('ndcg@10', 0.2303), ('hit@10', 0.7402), ('precision@10', 0.1554)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.2402), ('mrr@10', 0.4725), ('ndcg@10', 0.2817), ('hit@10', 0.7752), ('precision@10', 0.1853)])

[11/16] UserCF: {'k': 100, 'shrink': 50}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 50
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 826.15it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.11s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  40%|██████████████████▍                           | 189/472 [00:00<00:00, 1880.09it/s]:  80%|████████████████████████████████████▉         | 379/472 [00:00<00:00, 1891.09it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1833.88it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.28s, valid_score: 0.376900]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.2012    mrr@10 : 0.3769    ndcg@10 : 0.221    hit@10 : 0.7328    precision@10 : 0.1503
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  41%|██████████████████▉                           | 194/472 [00:00<00:00, 1936.69it/s]:  82%|█████████████████████████████████████▊        | 388/472 [00:00<00:00, 1915.01it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1871.53it/s]
24 Oct 14:00    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    18.70 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.64 G/16.00 G |
+-------------+----------------+
24 Oct 14:00    INFO  best valid : OrderedDict([('recall@10', 0.2012), ('mrr@10', 0.3769), ('ndcg@10', 0.221), ('hit@10', 0.7328), ('precision@10', 0.1503)])
24 Oct 14:00    INFO  test result: OrderedDict([('recall@10', 0.233), ('mrr@10', 0.4641), ('ndcg@10', 0.2745), ('hit@10', 0.7614), ('precision@10', 0.1803)])

[12/16] UserCF: {'k': 100, 'shrink': 100}

24 Oct 14:00    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:00    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 100
shrink = 100
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:00    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:00    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:00    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:00    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:00    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 797.28it/s]
24 Oct 14:00    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  38%|█████████████████▍                            | 179/472 [00:00<00:00, 1785.39it/s]:  76%|██████████████████████████████████▉           | 359/472 [00:00<00:00, 1790.84it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1764.73it/s]
24 Oct 14:00    INFO  epoch 0 evaluating [time: 0.29s, valid_score: 0.364700]
24 Oct 14:00    INFO  valid result:
recall@10 : 0.198    mrr@10 : 0.3647    ndcg@10 : 0.215    hit@10 : 0.7243    precision@10 : 0.1483
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  39%|██████████████████▏                           | 186/472 [00:00<00:00, 1852.81it/s]:  79%|████████████████████████████████████▎         | 372/472 [00:00<00:00, 1837.95it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1796.12it/s]
24 Oct 14:01    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    28.20 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.64 G/16.00 G |
+-------------+----------------+
24 Oct 14:01    INFO  best valid : OrderedDict([('recall@10', 0.198), ('mrr@10', 0.3647), ('ndcg@10', 0.215), ('hit@10', 0.7243), ('precision@10', 0.1483)])
24 Oct 14:01    INFO  test result: OrderedDict([('recall@10', 0.228), ('mrr@10', 0.4568), ('ndcg@10', 0.2683), ('hit@10', 0.755), ('precision@10', 0.1751)])

[13/16] UserCF: {'k': 200, 'shrink': 0}

24 Oct 14:01    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:01    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 0
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:01    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:01    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:01    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:01    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:01    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 804.28it/s]
24 Oct 14:01    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  39%|██████████████████▏                           | 186/472 [00:00<00:00, 1852.39it/s]:  80%|████████████████████████████████████▋         | 377/472 [00:00<00:00, 1884.43it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1842.28it/s]
24 Oct 14:01    INFO  epoch 0 evaluating [time: 0.28s, valid_score: 0.387400]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.1996    mrr@10 : 0.3874    ndcg@10 : 0.2241    hit@10 : 0.7232    precision@10 : 0.1494
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  41%|██████████████████▋                           | 192/472 [00:00<00:00, 1912.18it/s]:  81%|█████████████████████████████████████▍        | 384/472 [00:00<00:00, 1916.06it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1857.49it/s]
24 Oct 14:01    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    22.80 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.65 G/16.00 G |
+-------------+----------------+
24 Oct 14:01    INFO  best valid : OrderedDict([('recall@10', 0.1996), ('mrr@10', 0.3874), ('ndcg@10', 0.2241), ('hit@10', 0.7232), ('precision@10', 0.1494)])
24 Oct 14:01    INFO  test result: OrderedDict([('recall@10', 0.2325), ('mrr@10', 0.4684), ('ndcg@10', 0.2734), ('hit@10', 0.7656), ('precision@10', 0.1776)])

[14/16] UserCF: {'k': 200, 'shrink': 10}

24 Oct 14:01    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:01    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 10
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:01    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:01    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:01    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:01    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:01    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 797.75it/s]
24 Oct 14:01    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  38%|█████████████████▋                            | 181/472 [00:00<00:00, 1802.25it/s]:  77%|███████████████████████████████████▎          | 362/472 [00:00<00:00, 1594.15it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1542.75it/s]
24 Oct 14:01    INFO  epoch 0 evaluating [time: 0.33s, valid_score: 0.382300]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.1961    mrr@10 : 0.3823    ndcg@10 : 0.22    hit@10 : 0.7211    precision@10 : 0.1475
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  38%|█████████████████▎                            | 177/472 [00:00<00:00, 1764.86it/s]:  76%|███████████████████████████████████▏          | 361/472 [00:00<00:00, 1806.84it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1774.21it/s]
24 Oct 14:01    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    19.00 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.61 G/16.00 G |
+-------------+----------------+
24 Oct 14:01    INFO  best valid : OrderedDict([('recall@10', 0.1961), ('mrr@10', 0.3823), ('ndcg@10', 0.22), ('hit@10', 0.7211), ('precision@10', 0.1475)])
24 Oct 14:01    INFO  test result: OrderedDict([('recall@10', 0.2286), ('mrr@10', 0.4643), ('ndcg@10', 0.2702), ('hit@10', 0.7572), ('precision@10', 0.1752)])

[15/16] UserCF: {'k': 200, 'shrink': 50}

24 Oct 14:01    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:01    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 50
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:01    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:01    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:01    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:01    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:01    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 791.90it/s]
24 Oct 14:01    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  35%|████████████████▎                             | 167/472 [00:00<00:00, 1665.97it/s]:  72%|█████████████████████████████████             | 339/472 [00:00<00:00, 1694.13it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1675.56it/s]
24 Oct 14:01    INFO  epoch 0 evaluating [time: 0.30s, valid_score: 0.371800]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.1922    mrr@10 : 0.3718    ndcg@10 : 0.2143    hit@10 : 0.7031    precision@10 : 0.1448
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  36%|████████████████▊                             | 172/472 [00:00<00:00, 1712.29it/s]:  73%|█████████████████████████████████▋            | 346/472 [00:00<00:00, 1726.74it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1706.47it/s]
24 Oct 14:01    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    18.30 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.64 G/16.00 G |
+-------------+----------------+
24 Oct 14:01    INFO  best valid : OrderedDict([('recall@10', 0.1922), ('mrr@10', 0.3718), ('ndcg@10', 0.2143), ('hit@10', 0.7031), ('precision@10', 0.1448)])
24 Oct 14:01    INFO  test result: OrderedDict([('recall@10', 0.2276), ('mrr@10', 0.4523), ('ndcg@10', 0.2655), ('hit@10', 0.7497), ('precision@10', 0.173)])

[16/16] UserCF: {'k': 200, 'shrink': 100}

24 Oct 14:01    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:01    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 300
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
k = 200
shrink = 100
knn_method = user
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.TRADITIONAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:01    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:01    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:01    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:01    INFO  ItemKNN()
Trainable parameters: 1
24 Oct 14:01    INFO  FLOPs: 0.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 793.04it/s]
24 Oct 14:01    INFO  epoch 0 training [time: 0.12s, train loss: 0.0000]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  35%|███████████████▉                              | 164/472 [00:00<00:00, 1637.15it/s]:  71%|████████████████████████████████▌             | 334/472 [00:00<00:00, 1669.68it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1664.42it/s]
24 Oct 14:01    INFO  epoch 0 evaluating [time: 0.31s, valid_score: 0.368400]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.1889    mrr@10 : 0.3684    ndcg@10 : 0.2112    hit@10 : 0.701    precision@10 : 0.1431
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  35%|████████████████▏                             | 166/472 [00:00<00:00, 1658.59it/s]:  70%|████████████████████████████████▎             | 332/472 [00:00<00:00, 1642.49it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 1639.71it/s]
24 Oct 14:01    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    18.90 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.66 G/16.00 G |
+-------------+----------------+
24 Oct 14:01    INFO  best valid : OrderedDict([('recall@10', 0.1889), ('mrr@10', 0.3684), ('ndcg@10', 0.2112), ('hit@10', 0.701), ('precision@10', 0.1431)])
24 Oct 14:01    INFO  test result: OrderedDict([('recall@10', 0.2207), ('mrr@10', 0.4412), ('ndcg@10', 0.2579), ('hit@10', 0.7359), ('precision@10', 0.1678)])

Saved to:
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/group_18/results/task_1_2/UserCF_tuning.csv

Best configuration:

    k  shrink  valid_score  recall@10  mrr@10  ndcg@10  hit@10  precision@10
0  50       0        0.401      0.216   0.401   0.2355   0.755        0.1562

In [8]:
bpr_space = {
    "embedding_size": [16, 32, 64, 128],
    "learning_rate": [0.0001, 0.001, 0.01],
}

In [9]:
bpr_results = tune_model(
    name="BPR",
    model="BPR",
    config_path=CONFIG_ROOT / "BPR" / "ml-100k.yaml",
    search_space=bpr_space
)

Tuning BPR
Number of experiments: 12
============================================================
[1/12] BPR: {'embedding_size': 16, 'learning_rate': 0.0001}

24 Oct 14:01    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:01    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.0001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 16
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:01    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:01    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:01    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:01    INFO  BPR(
  (user_embedding): Embedding(944, 16)
  (item_embedding): Embedding(1683, 16)
  (loss): BPRLoss()
)
Trainable parameters: 42032
24 Oct 14:01    INFO  FLOPs: 32.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  52%|█████████████████████████▋                       | 21/40 [00:00<00:00, 202.53it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 210.31it/s]
24 Oct 14:01    INFO  epoch 0 training [time: 0.21s, train loss: 27.7264]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 297.77it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 274.73it/s]
24 Oct 14:01    INFO  epoch 1 training [time: 0.17s, train loss: 27.7244]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 311.30it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 280.42it/s]
24 Oct 14:01    INFO  epoch 2 training [time: 0.16s, train loss: 27.7230]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  78%|█████████████████████████████████████▉           | 31/40 [00:00<00:00, 307.13it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 271.34it/s]
24 Oct 14:01    INFO  epoch 3 training [time: 0.18s, train loss: 27.7213]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  78%|█████████████████████████████████████▉           | 31/40 [00:00<00:00, 304.35it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 281.08it/s]
24 Oct 14:01    INFO  epoch 4 training [time: 0.16s, train loss: 27.7196]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  78%|█████████████████████████████████████▉           | 31/40 [00:00<00:00, 304.91it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 279.67it/s]
24 Oct 14:01    INFO  epoch 5 training [time: 0.17s, train loss: 27.7181]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 259.52it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 255.18it/s]
24 Oct 14:01    INFO  epoch 6 training [time: 0.18s, train loss: 27.7166]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 269.28it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 261.25it/s]
24 Oct 14:01    INFO  epoch 7 training [time: 0.21s, train loss: 27.7146]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 291.91it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 270.52it/s]
24 Oct 14:01    INFO  epoch 8 training [time: 0.17s, train loss: 27.7128]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 299.22it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 275.57it/s]
24 Oct 14:01    INFO  epoch 9 training [time: 0.17s, train loss: 27.7095]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6448.15it/s]
24 Oct 14:01    INFO  epoch 9 evaluating [time: 0.10s, valid_score: 0.023600]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.008    mrr@10 : 0.0236    ndcg@10 : 0.0101    hit@10 : 0.0795    precision@10 : 0.009
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 257.36it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 245.04it/s]
24 Oct 14:01    INFO  epoch 10 training [time: 0.19s, train loss: 27.7070]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 254.59it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 237.44it/s]
24 Oct 14:01    INFO  epoch 11 training [time: 0.20s, train loss: 27.7041]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  62%|██████████████████████████████▋                  | 25/40 [00:00<00:00, 249.34it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 237.16it/s]
24 Oct 14:01    INFO  epoch 12 training [time: 0.20s, train loss: 27.6996]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  62%|██████████████████████████████▋                  | 25/40 [00:00<00:00, 249.99it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 234.76it/s]
24 Oct 14:01    INFO  epoch 13 training [time: 0.20s, train loss: 27.6958]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  62%|██████████████████████████████▋                  | 25/40 [00:00<00:00, 241.77it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 242.35it/s]
24 Oct 14:01    INFO  epoch 14 training [time: 0.20s, train loss: 27.6905]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 272.14it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 252.18it/s]
24 Oct 14:01    INFO  epoch 15 training [time: 0.19s, train loss: 27.6830]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  62%|██████████████████████████████▋                  | 25/40 [00:00<00:00, 243.89it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 236.27it/s]
24 Oct 14:01    INFO  epoch 16 training [time: 0.20s, train loss: 27.6751]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 254.48it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 250.54it/s]
24 Oct 14:01    INFO  epoch 17 training [time: 0.19s, train loss: 27.6659]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 262.47it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 244.55it/s]
24 Oct 14:01    INFO  epoch 18 training [time: 0.19s, train loss: 27.6538]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 266.72it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 254.68it/s]
24 Oct 14:01    INFO  epoch 19 training [time: 0.18s, train loss: 27.6409]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5743.21it/s]
24 Oct 14:01    INFO  epoch 19 evaluating [time: 0.11s, valid_score: 0.070200]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.0223    mrr@10 : 0.0702    ndcg@10 : 0.0304    hit@10 : 0.1909    precision@10 : 0.0257
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5331.95it/s]
24 Oct 14:01    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    35.60 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.60 G/16.00 G |
+-------------+----------------+
24 Oct 14:01    INFO  best valid : OrderedDict([('recall@10', 0.0223), ('mrr@10', 0.0702), ('ndcg@10', 0.0304), ('hit@10', 0.1909), ('precision@10', 0.0257)])
24 Oct 14:01    INFO  test result: OrderedDict([('recall@10', 0.0253), ('mrr@10', 0.0877), ('ndcg@10', 0.0369), ('hit@10', 0.211), ('precision@10', 0.03)])

[2/12] BPR: {'embedding_size': 16, 'learning_rate': 0.001}

24 Oct 14:01    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:01    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 16
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:01    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:01    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:01    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:01    INFO  BPR(
  (user_embedding): Embedding(944, 16)
  (item_embedding): Embedding(1683, 16)
  (loss): BPRLoss()
)
Trainable parameters: 42032
24 Oct 14:01    INFO  FLOPs: 32.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  55%|██████████████████████████▉                      | 22/40 [00:00<00:00, 213.32it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 206.11it/s]
24 Oct 14:01    INFO  epoch 0 training [time: 0.22s, train loss: 27.7250]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  62%|██████████████████████████████▋                  | 25/40 [00:00<00:00, 248.01it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 235.13it/s]
24 Oct 14:01    INFO  epoch 1 training [time: 0.19s, train loss: 27.6977]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 273.60it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 250.59it/s]
24 Oct 14:01    INFO  epoch 2 training [time: 0.18s, train loss: 27.6002]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 262.54it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 245.30it/s]
24 Oct 14:01    INFO  epoch 3 training [time: 0.19s, train loss: 27.1737]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  72%|███████████████████████████████████▌             | 29/40 [00:00<00:00, 286.84it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 266.53it/s]
24 Oct 14:01    INFO  epoch 4 training [time: 0.17s, train loss: 25.9339]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  62%|██████████████████████████████▋                  | 25/40 [00:00<00:00, 243.59it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 230.80it/s]
24 Oct 14:01    INFO  epoch 5 training [time: 0.20s, train loss: 23.6408]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 199.28it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 211.85it/s]
24 Oct 14:01    INFO  epoch 6 training [time: 0.22s, train loss: 20.8413]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  55%|██████████████████████████▉                      | 22/40 [00:00<00:00, 216.74it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 219.56it/s]
24 Oct 14:01    INFO  epoch 7 training [time: 0.21s, train loss: 18.4548]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 279.66it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 258.71it/s]
24 Oct 14:01    INFO  epoch 8 training [time: 0.18s, train loss: 16.7208]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  62%|██████████████████████████████▋                  | 25/40 [00:00<00:00, 249.11it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 237.48it/s]
24 Oct 14:01    INFO  epoch 9 training [time: 0.19s, train loss: 15.5673]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5914.12it/s]
24 Oct 14:01    INFO  epoch 9 evaluating [time: 0.11s, valid_score: 0.254300]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.105    mrr@10 : 0.2543    ndcg@10 : 0.1286    hit@10 : 0.5228    precision@10 : 0.0962
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 297.96it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 274.21it/s]
24 Oct 14:01    INFO  epoch 10 training [time: 0.17s, train loss: 14.8540]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  78%|█████████████████████████████████████▉           | 31/40 [00:00<00:00, 306.00it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 279.34it/s]
24 Oct 14:01    INFO  epoch 11 training [time: 0.17s, train loss: 14.3312]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  62%|██████████████████████████████▋                  | 25/40 [00:00<00:00, 244.71it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 223.65it/s]
24 Oct 14:01    INFO  epoch 12 training [time: 0.20s, train loss: 13.9199]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  72%|███████████████████████████████████▌             | 29/40 [00:00<00:00, 289.10it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 265.05it/s]
24 Oct 14:01    INFO  epoch 13 training [time: 0.17s, train loss: 13.6501]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  78%|█████████████████████████████████████▉           | 31/40 [00:00<00:00, 304.47it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 276.56it/s]
24 Oct 14:01    INFO  epoch 14 training [time: 0.17s, train loss: 13.4718]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 298.73it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 269.62it/s]
24 Oct 14:01    INFO  epoch 15 training [time: 0.18s, train loss: 13.1917]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  60%|█████████████████████████████▍                   | 24/40 [00:00<00:00, 239.83it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 230.82it/s]
24 Oct 14:01    INFO  epoch 16 training [time: 0.20s, train loss: 13.0501]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 257.75it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 243.08it/s]
24 Oct 14:01    INFO  epoch 17 training [time: 0.19s, train loss: 12.8588]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  60%|█████████████████████████████▍                   | 24/40 [00:00<00:00, 231.61it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 227.39it/s]
24 Oct 14:01    INFO  epoch 18 training [time: 0.20s, train loss: 12.6525]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  62%|██████████████████████████████▋                  | 25/40 [00:00<00:00, 247.59it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 237.69it/s]
24 Oct 14:01    INFO  epoch 19 training [time: 0.20s, train loss: 12.6483]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5929.71it/s]
24 Oct 14:01    INFO  epoch 19 evaluating [time: 0.11s, valid_score: 0.298000]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.135    mrr@10 : 0.298    ndcg@10 : 0.1569    hit@10 : 0.5928    precision@10 : 0.1069
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6032.32it/s]
24 Oct 14:01    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    27.60 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.57 G/16.00 G |
+-------------+----------------+
24 Oct 14:01    INFO  best valid : OrderedDict([('recall@10', 0.135), ('mrr@10', 0.298), ('ndcg@10', 0.1569), ('hit@10', 0.5928), ('precision@10', 0.1069)])
24 Oct 14:01    INFO  test result: OrderedDict([('recall@10', 0.1571), ('mrr@10', 0.3515), ('ndcg@10', 0.1916), ('hit@10', 0.6331), ('precision@10', 0.1284)])

[3/12] BPR: {'embedding_size': 16, 'learning_rate': 0.01}

24 Oct 14:01    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:01    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.01
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 16
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:01    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:01    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:01    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:01    INFO  BPR(
  (user_embedding): Embedding(944, 16)
  (item_embedding): Embedding(1683, 16)
  (loss): BPRLoss()
)
Trainable parameters: 42032
24 Oct 14:01    INFO  FLOPs: 32.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  55%|██████████████████████████▉                      | 22/40 [00:00<00:00, 214.31it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 200.20it/s]
24 Oct 14:01    INFO  epoch 0 training [time: 0.23s, train loss: 26.8043]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 259.62it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 238.80it/s]
24 Oct 14:01    INFO  epoch 1 training [time: 0.19s, train loss: 16.2752]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 258.67it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 248.53it/s]
24 Oct 14:01    INFO  epoch 2 training [time: 0.19s, train loss: 12.4941]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 255.65it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 236.68it/s]
24 Oct 14:01    INFO  epoch 3 training [time: 0.20s, train loss: 10.7140]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 254.14it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 243.90it/s]
24 Oct 14:01    INFO  epoch 4 training [time: 0.19s, train loss: 9.7102]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  62%|██████████████████████████████▋                  | 25/40 [00:00<00:00, 244.00it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 234.79it/s]
24 Oct 14:01    INFO  epoch 5 training [time: 0.20s, train loss: 8.8311]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 272.28it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 249.08it/s]
24 Oct 14:01    INFO  epoch 6 training [time: 0.19s, train loss: 8.3627]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  62%|██████████████████████████████▋                  | 25/40 [00:00<00:00, 246.59it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 233.62it/s]
24 Oct 14:01    INFO  epoch 7 training [time: 0.20s, train loss: 8.0100]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 272.38it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 249.04it/s]
24 Oct 14:01    INFO  epoch 8 training [time: 0.19s, train loss: 7.7022]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  62%|██████████████████████████████▋                  | 25/40 [00:00<00:00, 249.62it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 237.49it/s]
24 Oct 14:01    INFO  epoch 9 training [time: 0.20s, train loss: 7.4519]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6285.80it/s]
24 Oct 14:01    INFO  epoch 9 evaluating [time: 0.10s, valid_score: 0.344700]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.1855    mrr@10 : 0.3447    ndcg@10 : 0.2022    hit@10 : 0.7041    precision@10 : 0.1428
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 258.59it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 246.57it/s]
24 Oct 14:01    INFO  epoch 10 training [time: 0.19s, train loss: 7.1695]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  72%|███████████████████████████████████▌             | 29/40 [00:00<00:00, 281.37it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 251.76it/s]
24 Oct 14:01    INFO  epoch 11 training [time: 0.19s, train loss: 6.9813]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 252.78it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 246.90it/s]
24 Oct 14:01    INFO  epoch 12 training [time: 0.19s, train loss: 6.7863]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  60%|█████████████████████████████▍                   | 24/40 [00:00<00:00, 237.63it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 229.23it/s]
24 Oct 14:01    INFO  epoch 13 training [time: 0.20s, train loss: 6.6051]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 255.99it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 235.51it/s]
24 Oct 14:01    INFO  epoch 14 training [time: 0.20s, train loss: 6.4968]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 273.65it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 246.88it/s]
24 Oct 14:01    INFO  epoch 15 training [time: 0.19s, train loss: 6.3467]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 254.17it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 247.81it/s]
24 Oct 14:01    INFO  epoch 16 training [time: 0.19s, train loss: 6.2297]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 253.49it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 247.76it/s]
24 Oct 14:01    INFO  epoch 17 training [time: 0.19s, train loss: 6.0621]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  65%|███████████████████████████████▊                 | 26/40 [00:00<00:00, 258.72it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 242.46it/s]
24 Oct 14:01    INFO  epoch 18 training [time: 0.19s, train loss: 5.9553]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  62%|██████████████████████████████▋                  | 25/40 [00:00<00:00, 247.51it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 239.24it/s]
24 Oct 14:01    INFO  epoch 19 training [time: 0.19s, train loss: 5.9542]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5615.90it/s]
24 Oct 14:01    INFO  epoch 19 evaluating [time: 0.11s, valid_score: 0.351100]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.1992    mrr@10 : 0.3511    ndcg@10 : 0.2073    hit@10 : 0.7169    precision@10 : 0.1438
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5906.66it/s]
24 Oct 14:01    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    27.90 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.57 G/16.00 G |
+-------------+----------------+
24 Oct 14:01    INFO  best valid : OrderedDict([('recall@10', 0.1992), ('mrr@10', 0.3511), ('ndcg@10', 0.2073), ('hit@10', 0.7169), ('precision@10', 0.1438)])
24 Oct 14:01    INFO  test result: OrderedDict([('recall@10', 0.2137), ('mrr@10', 0.4401), ('ndcg@10', 0.2529), ('hit@10', 0.7487), ('precision@10', 0.1704)])

[4/12] BPR: {'embedding_size': 32, 'learning_rate': 0.0001}

24 Oct 14:01    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:01    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.0001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:01    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:01    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:01    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:01    INFO  BPR(
  (user_embedding): Embedding(944, 32)
  (item_embedding): Embedding(1683, 32)
  (loss): BPRLoss()
)
Trainable parameters: 84064
24 Oct 14:01    INFO  FLOPs: 64.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  30%|██████████████▋                                  | 12/40 [00:00<00:00, 117.17it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 132.73it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 131.78it/s]
24 Oct 14:01    INFO  epoch 0 training [time: 0.34s, train loss: 27.7271]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  45%|██████████████████████                           | 18/40 [00:00<00:00, 171.42it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 172.89it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 161.50it/s]
24 Oct 14:01    INFO  epoch 1 training [time: 0.28s, train loss: 27.7228]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 192.13it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 180.93it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 173.79it/s]
24 Oct 14:01    INFO  epoch 2 training [time: 0.26s, train loss: 27.7209]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  38%|██████████████████▍                              | 15/40 [00:00<00:00, 148.57it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 134.08it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 138.12it/s]
24 Oct 14:01    INFO  epoch 3 training [time: 0.32s, train loss: 27.7180]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 169.98it/s]:  88%|██████████████████████████████████████████▉      | 35/40 [00:00<00:00, 172.46it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 162.43it/s]
24 Oct 14:01    INFO  epoch 4 training [time: 0.28s, train loss: 27.7156]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 155.44it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 162.01it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 138.91it/s]
24 Oct 14:01    INFO  epoch 5 training [time: 0.33s, train loss: 27.7119]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  45%|██████████████████████                           | 18/40 [00:00<00:00, 177.66it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 171.05it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 162.16it/s]
24 Oct 14:01    INFO  epoch 6 training [time: 0.28s, train loss: 27.7093]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 181.49it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 176.56it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 164.66it/s]
24 Oct 14:01    INFO  epoch 7 training [time: 0.27s, train loss: 27.7046]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 183.22it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 179.00it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 167.34it/s]
24 Oct 14:01    INFO  epoch 8 training [time: 0.27s, train loss: 27.7010]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  45%|██████████████████████                           | 18/40 [00:00<00:00, 177.79it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 175.92it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 165.64it/s]
24 Oct 14:01    INFO  epoch 9 training [time: 0.27s, train loss: 27.6970]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  96%|████████████████████████████████████████████▏ | 454/472 [00:00<00:00, 4539.10it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 3852.05it/s]
24 Oct 14:01    INFO  epoch 9 evaluating [time: 0.16s, valid_score: 0.022000]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.0071    mrr@10 : 0.022    ndcg@10 : 0.0087    hit@10 : 0.0689    precision@10 : 0.0074
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 186.29it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 180.40it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 167.06it/s]
24 Oct 14:01    INFO  epoch 10 training [time: 0.27s, train loss: 27.6922]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 168.32it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 158.47it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 154.05it/s]
24 Oct 14:01    INFO  epoch 11 training [time: 0.29s, train loss: 27.6880]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 194.19it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 194.19it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 184.36it/s]
24 Oct 14:01    INFO  epoch 12 training [time: 0.24s, train loss: 27.6821]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  38%|██████████████████▍                              | 15/40 [00:00<00:00, 147.07it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 165.61it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 159.09it/s]
24 Oct 14:01    INFO  epoch 13 training [time: 0.28s, train loss: 27.6733]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 182.10it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 171.37it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 156.19it/s]
24 Oct 14:01    INFO  epoch 14 training [time: 0.28s, train loss: 27.6649]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 194.90it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 198.54it/s]
24 Oct 14:01    INFO  epoch 15 training [time: 0.23s, train loss: 27.6544]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 196.79it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 178.63it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 172.43it/s]
24 Oct 14:01    INFO  epoch 16 training [time: 0.26s, train loss: 27.6432]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  22%|███████████▍                                       | 9/40 [00:00<00:00, 86.23it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 154.58it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 151.33it/s]
24 Oct 14:01    INFO  epoch 17 training [time: 0.29s, train loss: 27.6278]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  55%|██████████████████████████▉                      | 22/40 [00:00<00:00, 214.76it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 210.35it/s]
24 Oct 14:01    INFO  epoch 18 training [time: 0.21s, train loss: 27.6097]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 194.02it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 180.35it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 172.26it/s]
24 Oct 14:01    INFO  epoch 19 training [time: 0.26s, train loss: 27.5883]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  91%|██████████████████████████████████████████    | 431/472 [00:00<00:00, 4305.01it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 3614.58it/s]
24 Oct 14:01    INFO  epoch 19 evaluating [time: 0.16s, valid_score: 0.065100]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.0208    mrr@10 : 0.0651    ndcg@10 : 0.0283    hit@10 : 0.1835    precision@10 : 0.024
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5163.88it/s]
24 Oct 14:01    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    27.90 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.48 G/16.00 G |
+-------------+----------------+
24 Oct 14:01    INFO  best valid : OrderedDict([('recall@10', 0.0208), ('mrr@10', 0.0651), ('ndcg@10', 0.0283), ('hit@10', 0.1835), ('precision@10', 0.024)])
24 Oct 14:01    INFO  test result: OrderedDict([('recall@10', 0.0222), ('mrr@10', 0.0784), ('ndcg@10', 0.0343), ('hit@10', 0.21), ('precision@10', 0.0288)])

[5/12] BPR: {'embedding_size': 32, 'learning_rate': 0.001}

24 Oct 14:01    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:01    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:01    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:01    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:01    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:01    INFO  BPR(
  (user_embedding): Embedding(944, 32)
  (item_embedding): Embedding(1683, 32)
  (loss): BPRLoss()
)
Trainable parameters: 84064
24 Oct 14:01    INFO  FLOPs: 64.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  35%|█████████████████▏                               | 14/40 [00:00<00:00, 130.53it/s]:  72%|███████████████████████████████████▌             | 29/40 [00:00<00:00, 138.25it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 143.17it/s]
24 Oct 14:01    INFO  epoch 0 training [time: 0.31s, train loss: 27.7251]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 198.50it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 203.51it/s]
24 Oct 14:01    INFO  epoch 1 training [time: 0.23s, train loss: 27.6782]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 186.39it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 181.30it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 170.92it/s]
24 Oct 14:01    INFO  epoch 2 training [time: 0.26s, train loss: 27.5329]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  52%|█████████████████████████▋                       | 21/40 [00:00<00:00, 203.80it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 201.88it/s]
24 Oct 14:01    INFO  epoch 3 training [time: 0.23s, train loss: 26.8899]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 184.32it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 181.74it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 171.80it/s]
24 Oct 14:01    INFO  epoch 4 training [time: 0.26s, train loss: 24.9752]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 198.57it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 189.93it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 180.42it/s]
24 Oct 14:01    INFO  epoch 5 training [time: 0.25s, train loss: 21.6269]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  30%|██████████████▋                                  | 12/40 [00:00<00:00, 114.94it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 134.79it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 140.74it/s]
24 Oct 14:01    INFO  epoch 6 training [time: 0.31s, train loss: 18.2601]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 156.43it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 161.39it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 159.22it/s]
24 Oct 14:01    INFO  epoch 7 training [time: 0.28s, train loss: 16.0649]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  52%|█████████████████████████▋                       | 21/40 [00:00<00:00, 209.10it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 191.40it/s]
24 Oct 14:01    INFO  epoch 8 training [time: 0.24s, train loss: 14.7539]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 163.30it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 175.89it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 166.10it/s]
24 Oct 14:01    INFO  epoch 9 training [time: 0.27s, train loss: 13.9258]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5713.04it/s]
24 Oct 14:01    INFO  epoch 9 evaluating [time: 0.11s, valid_score: 0.304700]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.1365    mrr@10 : 0.3047    ndcg@10 : 0.1612    hit@10 : 0.596    precision@10 : 0.1094
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  57%|████████████████████████████▏                    | 23/40 [00:00<00:00, 222.89it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 213.01it/s]
24 Oct 14:01    INFO  epoch 10 training [time: 0.22s, train loss: 13.3970]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  45%|██████████████████████                           | 18/40 [00:00<00:00, 174.43it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 185.83it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 175.14it/s]
24 Oct 14:01    INFO  epoch 11 training [time: 0.26s, train loss: 12.9344]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  52%|█████████████████████████▋                       | 21/40 [00:00<00:00, 208.92it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 207.89it/s]
24 Oct 14:01    INFO  epoch 12 training [time: 0.22s, train loss: 12.5318]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  57%|████████████████████████████▏                    | 23/40 [00:00<00:00, 229.00it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 219.47it/s]
24 Oct 14:01    INFO  epoch 13 training [time: 0.21s, train loss: 12.1990]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 184.31it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 194.26it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 183.61it/s]
24 Oct 14:01    INFO  epoch 14 training [time: 0.24s, train loss: 11.9354]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  57%|████████████████████████████▏                    | 23/40 [00:00<00:00, 223.74it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 212.14it/s]
24 Oct 14:01    INFO  epoch 15 training [time: 0.21s, train loss: 11.6084]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  57%|████████████████████████████▏                    | 23/40 [00:00<00:00, 226.39it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 208.05it/s]
24 Oct 14:01    INFO  epoch 16 training [time: 0.22s, train loss: 11.3690]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  57%|████████████████████████████▏                    | 23/40 [00:00<00:00, 223.23it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 220.47it/s]
24 Oct 14:01    INFO  epoch 17 training [time: 0.21s, train loss: 11.1005]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  60%|█████████████████████████████▍                   | 24/40 [00:00<00:00, 232.14it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 222.37it/s]
24 Oct 14:01    INFO  epoch 18 training [time: 0.21s, train loss: 10.8142]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  57%|████████████████████████████▏                    | 23/40 [00:00<00:00, 227.96it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 220.97it/s]
24 Oct 14:01    INFO  epoch 19 training [time: 0.21s, train loss: 10.7412]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6160.11it/s]
24 Oct 14:01    INFO  epoch 19 evaluating [time: 0.12s, valid_score: 0.319100]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.1695    mrr@10 : 0.3191    ndcg@10 : 0.1845    hit@10 : 0.6469    precision@10 : 0.1278
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 7120.24it/s]
24 Oct 14:01    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    17.90 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.47 G/16.00 G |
+-------------+----------------+
24 Oct 14:01    INFO  best valid : OrderedDict([('recall@10', 0.1695), ('mrr@10', 0.3191), ('ndcg@10', 0.1845), ('hit@10', 0.6469), ('precision@10', 0.1278)])
24 Oct 14:01    INFO  test result: OrderedDict([('recall@10', 0.1961), ('mrr@10', 0.402), ('ndcg@10', 0.2307), ('hit@10', 0.6967), ('precision@10', 0.1539)])

[6/12] BPR: {'embedding_size': 32, 'learning_rate': 0.01}

24 Oct 14:01    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:01    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.01
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:01    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:01    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:01    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:01    INFO  BPR(
  (user_embedding): Embedding(944, 32)
  (item_embedding): Embedding(1683, 32)
  (loss): BPRLoss()
)
Trainable parameters: 84064
24 Oct 14:01    INFO  FLOPs: 64.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 155.89it/s]:  88%|██████████████████████████████████████████▉      | 35/40 [00:00<00:00, 173.32it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 164.39it/s]
24 Oct 14:01    INFO  epoch 0 training [time: 0.27s, train loss: 26.2657]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  55%|██████████████████████████▉                      | 22/40 [00:00<00:00, 215.63it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 207.01it/s]
24 Oct 14:01    INFO  epoch 1 training [time: 0.22s, train loss: 14.2902]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  55%|██████████████████████████▉                      | 22/40 [00:00<00:00, 213.35it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 206.76it/s]
24 Oct 14:01    INFO  epoch 2 training [time: 0.22s, train loss: 10.8524]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 183.92it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 194.90it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 184.24it/s]
24 Oct 14:01    INFO  epoch 3 training [time: 0.24s, train loss: 9.1773]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  55%|██████████████████████████▉                      | 22/40 [00:00<00:00, 211.40it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 208.90it/s]
24 Oct 14:01    INFO  epoch 4 training [time: 0.22s, train loss: 8.4967]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  57%|████████████████████████████▏                    | 23/40 [00:00<00:00, 223.70it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 214.49it/s]
24 Oct 14:01    INFO  epoch 5 training [time: 0.21s, train loss: 7.6126]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  55%|██████████████████████████▉                      | 22/40 [00:00<00:00, 212.17it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 207.85it/s]
24 Oct 14:01    INFO  epoch 6 training [time: 0.22s, train loss: 7.1444]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  52%|█████████████████████████▋                       | 21/40 [00:00<00:00, 206.56it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 203.57it/s]
24 Oct 14:01    INFO  epoch 7 training [time: 0.22s, train loss: 6.7450]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  52%|█████████████████████████▋                       | 21/40 [00:00<00:00, 208.79it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 205.47it/s]
24 Oct 14:01    INFO  epoch 8 training [time: 0.22s, train loss: 6.2993]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  52%|█████████████████████████▋                       | 21/40 [00:00<00:00, 209.11it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 205.46it/s]
24 Oct 14:01    INFO  epoch 9 training [time: 0.22s, train loss: 5.9663]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6043.22it/s]
24 Oct 14:01    INFO  epoch 9 evaluating [time: 0.11s, valid_score: 0.342100]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.1843    mrr@10 : 0.3421    ndcg@10 : 0.201    hit@10 : 0.6946    precision@10 : 0.1439
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  55%|██████████████████████████▉                      | 22/40 [00:00<00:00, 211.08it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 203.40it/s]
24 Oct 14:01    INFO  epoch 10 training [time: 0.22s, train loss: 5.6627]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  55%|██████████████████████████▉                      | 22/40 [00:00<00:00, 214.18it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 207.53it/s]
24 Oct 14:01    INFO  epoch 11 training [time: 0.23s, train loss: 5.4090]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  52%|█████████████████████████▋                       | 21/40 [00:00<00:00, 209.03it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 205.31it/s]
24 Oct 14:01    INFO  epoch 12 training [time: 0.22s, train loss: 5.2104]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  55%|██████████████████████████▉                      | 22/40 [00:00<00:00, 214.29it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 206.87it/s]
24 Oct 14:01    INFO  epoch 13 training [time: 0.22s, train loss: 4.9575]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  55%|██████████████████████████▉                      | 22/40 [00:00<00:00, 213.75it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 208.43it/s]
24 Oct 14:01    INFO  epoch 14 training [time: 0.22s, train loss: 4.7620]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  57%|████████████████████████████▏                    | 23/40 [00:00<00:00, 226.71it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 216.59it/s]
24 Oct 14:01    INFO  epoch 15 training [time: 0.21s, train loss: 4.6805]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  57%|████████████████████████████▏                    | 23/40 [00:00<00:00, 227.47it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 215.51it/s]
24 Oct 14:01    INFO  epoch 16 training [time: 0.21s, train loss: 4.5486]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  52%|█████████████████████████▋                       | 21/40 [00:00<00:00, 209.89it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 208.71it/s]
24 Oct 14:01    INFO  epoch 17 training [time: 0.22s, train loss: 4.3706]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  55%|██████████████████████████▉                      | 22/40 [00:00<00:00, 218.36it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 204.05it/s]
24 Oct 14:01    INFO  epoch 18 training [time: 0.22s, train loss: 4.2669]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  55%|██████████████████████████▉                      | 22/40 [00:00<00:00, 213.57it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 208.10it/s]
24 Oct 14:01    INFO  epoch 19 training [time: 0.22s, train loss: 4.2303]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6285.10it/s]
24 Oct 14:01    INFO  epoch 19 evaluating [time: 0.11s, valid_score: 0.358100]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.1904    mrr@10 : 0.3581    ndcg@10 : 0.2038    hit@10 : 0.7169    precision@10 : 0.1393
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6076.05it/s]
24 Oct 14:01    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    19.90 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.49 G/16.00 G |
+-------------+----------------+
24 Oct 14:01    INFO  best valid : OrderedDict([('recall@10', 0.1904), ('mrr@10', 0.3581), ('ndcg@10', 0.2038), ('hit@10', 0.7169), ('precision@10', 0.1393)])
24 Oct 14:01    INFO  test result: OrderedDict([('recall@10', 0.2095), ('mrr@10', 0.3976), ('ndcg@10', 0.2354), ('hit@10', 0.7423), ('precision@10', 0.1629)])

[7/12] BPR: {'embedding_size': 64, 'learning_rate': 0.0001}

24 Oct 14:01    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:01    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.0001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:01    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:01    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:01    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:01    INFO  BPR(
  (user_embedding): Embedding(944, 64)
  (item_embedding): Embedding(1683, 64)
  (loss): BPRLoss()
)
Trainable parameters: 168128
24 Oct 14:01    INFO  FLOPs: 128.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  38%|██████████████████▍                              | 15/40 [00:00<00:00, 144.94it/s]:  82%|████████████████████████████████████████▍        | 33/40 [00:00<00:00, 163.47it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 157.60it/s]
24 Oct 14:01    INFO  epoch 0 training [time: 0.29s, train loss: 27.7273]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 194.58it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 189.66it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 181.38it/s]
24 Oct 14:01    INFO  epoch 1 training [time: 0.25s, train loss: 27.7223]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 154.14it/s]:  88%|██████████████████████████████████████████▉      | 35/40 [00:00<00:00, 172.92it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 163.47it/s]
24 Oct 14:01    INFO  epoch 2 training [time: 0.27s, train loss: 27.7166]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 187.90it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 185.51it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 173.67it/s]
24 Oct 14:01    INFO  epoch 3 training [time: 0.26s, train loss: 27.7112]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 184.29it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 185.05it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 173.79it/s]
24 Oct 14:01    INFO  epoch 4 training [time: 0.26s, train loss: 27.7048]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 193.00it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 188.38it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 180.45it/s]
24 Oct 14:01    INFO  epoch 5 training [time: 0.25s, train loss: 27.6994]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 184.65it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 184.09it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 172.95it/s]
24 Oct 14:01    INFO  epoch 6 training [time: 0.26s, train loss: 27.6916]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 195.14it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 190.58it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 182.35it/s]
24 Oct 14:01    INFO  epoch 7 training [time: 0.25s, train loss: 27.6857]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 188.13it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 193.42it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 180.48it/s]
24 Oct 14:01    INFO  epoch 8 training [time: 0.25s, train loss: 27.6798]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 187.29it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 184.61it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 173.72it/s]
24 Oct 14:01    INFO  epoch 9 training [time: 0.26s, train loss: 27.6707]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5365.60it/s]
24 Oct 14:01    INFO  epoch 9 evaluating [time: 0.13s, valid_score: 0.030500]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.0085    mrr@10 : 0.0305    ndcg@10 : 0.012    hit@10 : 0.088    precision@10 : 0.0097
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  52%|█████████████████████████▋                       | 21/40 [00:00<00:00, 203.72it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 197.54it/s]
24 Oct 14:01    INFO  epoch 10 training [time: 0.23s, train loss: 27.6601]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 193.21it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 186.26it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 178.66it/s]
24 Oct 14:01    INFO  epoch 11 training [time: 0.25s, train loss: 27.6482]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 187.57it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 187.39it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 175.70it/s]
24 Oct 14:01    INFO  epoch 12 training [time: 0.25s, train loss: 27.6375]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 194.03it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 191.12it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 182.65it/s]
24 Oct 14:01    INFO  epoch 13 training [time: 0.24s, train loss: 27.6218]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 184.82it/s]:  98%|███████████████████████████████████████████████▊ | 39/40 [00:00<00:00, 189.33it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 178.07it/s]
24 Oct 14:01    INFO  epoch 14 training [time: 0.30s, train loss: 27.6039]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 183.46it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 185.99it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 174.41it/s]
24 Oct 14:01    INFO  epoch 15 training [time: 0.26s, train loss: 27.5833]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 191.73it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 188.99it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 180.44it/s]
24 Oct 14:01    INFO  epoch 16 training [time: 0.25s, train loss: 27.5554]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 181.58it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 181.80it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 170.86it/s]
24 Oct 14:01    INFO  epoch 17 training [time: 0.26s, train loss: 27.5270]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 194.00it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 189.03it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 180.43it/s]
24 Oct 14:01    INFO  epoch 18 training [time: 0.25s, train loss: 27.4915]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 186.26it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 187.13it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 176.10it/s]
24 Oct 14:01    INFO  epoch 19 training [time: 0.25s, train loss: 27.4488]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5837.89it/s]
24 Oct 14:01    INFO  epoch 19 evaluating [time: 0.11s, valid_score: 0.097700]
24 Oct 14:01    INFO  valid result:
recall@10 : 0.031    mrr@10 : 0.0977    ndcg@10 : 0.0429    hit@10 : 0.2545    precision@10 : 0.0364
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5659.67it/s]
24 Oct 14:01    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    18.70 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.50 G/16.00 G |
+-------------+----------------+
24 Oct 14:01    INFO  best valid : OrderedDict([('recall@10', 0.031), ('mrr@10', 0.0977), ('ndcg@10', 0.0429), ('hit@10', 0.2545), ('precision@10', 0.0364)])
24 Oct 14:01    INFO  test result: OrderedDict([('recall@10', 0.0272), ('mrr@10', 0.0984), ('ndcg@10', 0.0429), ('hit@10', 0.2428), ('precision@10', 0.0365)])

[8/12] BPR: {'embedding_size': 64, 'learning_rate': 0.001}

24 Oct 14:01    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:01    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:01    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:01    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:01    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:01    INFO  BPR(
  (user_embedding): Embedding(944, 64)
  (item_embedding): Embedding(1683, 64)
  (loss): BPRLoss()
)
Trainable parameters: 168128
24 Oct 14:01    INFO  FLOPs: 128.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  35%|█████████████████▏                               | 14/40 [00:00<00:00, 137.83it/s]:  78%|█████████████████████████████████████▉           | 31/40 [00:00<00:00, 153.82it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 151.79it/s]
24 Oct 14:02    INFO  epoch 0 training [time: 0.29s, train loss: 27.7240]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 193.30it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 188.79it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 180.25it/s]
24 Oct 14:02    INFO  epoch 1 training [time: 0.25s, train loss: 27.6345]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 181.74it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 180.11it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 169.02it/s]
24 Oct 14:02    INFO  epoch 2 training [time: 0.27s, train loss: 27.3318]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 186.62it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 180.25it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 170.59it/s]
24 Oct 14:02    INFO  epoch 3 training [time: 0.26s, train loss: 26.0469]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  22%|███████████▍                                       | 9/40 [00:00<00:00, 88.61it/s]:  68%|█████████████████████████████████                | 27/40 [00:00<00:00, 141.40it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 143.25it/s]
24 Oct 14:02    INFO  epoch 4 training [time: 0.31s, train loss: 22.7424]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 186.86it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 183.56it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 172.48it/s]
24 Oct 14:02    INFO  epoch 5 training [time: 0.26s, train loss: 18.4891]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 184.46it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 179.13it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 167.53it/s]
24 Oct 14:02    INFO  epoch 6 training [time: 0.27s, train loss: 15.6431]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 188.23it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 185.46it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 174.72it/s]
24 Oct 14:02    INFO  epoch 7 training [time: 0.26s, train loss: 14.2810]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 188.01it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 184.49it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 174.22it/s]
24 Oct 14:02    INFO  epoch 8 training [time: 0.26s, train loss: 13.4723]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 192.57it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 187.36it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 178.97it/s]
24 Oct 14:02    INFO  epoch 9 training [time: 0.25s, train loss: 12.8887]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 4930.47it/s]
24 Oct 14:02    INFO  epoch 9 evaluating [time: 0.13s, valid_score: 0.299100]
24 Oct 14:02    INFO  valid result:
recall@10 : 0.1395    mrr@10 : 0.2991    ndcg@10 : 0.1601    hit@10 : 0.6119    precision@10 : 0.112
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 187.67it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 171.20it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 164.73it/s]
24 Oct 14:02    INFO  epoch 10 training [time: 0.27s, train loss: 12.4353]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 193.76it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 183.42it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 134.40it/s]
24 Oct 14:02    INFO  epoch 11 training [time: 0.34s, train loss: 11.9655]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  45%|██████████████████████                           | 18/40 [00:00<00:00, 179.87it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 177.56it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 168.76it/s]
24 Oct 14:02    INFO  epoch 12 training [time: 0.27s, train loss: 11.5190]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 197.23it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 190.02it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 181.66it/s]
24 Oct 14:02    INFO  epoch 13 training [time: 0.25s, train loss: 11.1336]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  45%|██████████████████████                           | 18/40 [00:00<00:00, 177.80it/s]:  92%|█████████████████████████████████████████████▎   | 37/40 [00:00<00:00, 182.66it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 171.35it/s]
24 Oct 14:02    INFO  epoch 14 training [time: 0.26s, train loss: 10.7970]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 189.97it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 185.97it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 175.10it/s]
24 Oct 14:02    INFO  epoch 15 training [time: 0.26s, train loss: 10.4318]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 184.51it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 181.87it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 171.31it/s]
24 Oct 14:02    INFO  epoch 16 training [time: 0.26s, train loss: 10.1359]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 192.97it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 189.48it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 181.02it/s]
24 Oct 14:02    INFO  epoch 17 training [time: 0.25s, train loss: 9.8093]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 153.60it/s]:  88%|██████████████████████████████████████████▉      | 35/40 [00:00<00:00, 170.00it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 160.63it/s]
24 Oct 14:02    INFO  epoch 18 training [time: 0.28s, train loss: 9.5000]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 192.51it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 189.11it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 180.43it/s]
24 Oct 14:02    INFO  epoch 19 training [time: 0.30s, train loss: 9.4030]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5035.46it/s]
24 Oct 14:02    INFO  epoch 19 evaluating [time: 0.12s, valid_score: 0.347400]
24 Oct 14:02    INFO  valid result:
recall@10 : 0.181    mrr@10 : 0.3474    ndcg@10 : 0.1994    hit@10 : 0.6808    precision@10 : 0.1382
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 6780.23it/s]
24 Oct 14:02    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    20.90 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.52 G/16.00 G |
+-------------+----------------+
24 Oct 14:02    INFO  best valid : OrderedDict([('recall@10', 0.181), ('mrr@10', 0.3474), ('ndcg@10', 0.1994), ('hit@10', 0.6808), ('precision@10', 0.1382)])
24 Oct 14:02    INFO  test result: OrderedDict([('recall@10', 0.2085), ('mrr@10', 0.4304), ('ndcg@10', 0.2494), ('hit@10', 0.7275), ('precision@10', 0.167)])

[9/12] BPR: {'embedding_size': 64, 'learning_rate': 0.01}

24 Oct 14:02    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:02    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.01
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:02    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:02    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:02    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:02    INFO  BPR(
  (user_embedding): Embedding(944, 64)
  (item_embedding): Embedding(1683, 64)
  (loss): BPRLoss()
)
Trainable parameters: 168128
24 Oct 14:02    INFO  FLOPs: 128.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  38%|██████████████████▍                              | 15/40 [00:00<00:00, 143.24it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 166.71it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 157.64it/s]
24 Oct 14:02    INFO  epoch 0 training [time: 0.29s, train loss: 25.2600]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 185.34it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 180.37it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 170.39it/s]
24 Oct 14:02    INFO  epoch 1 training [time: 0.26s, train loss: 13.0037]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 189.15it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 185.48it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 173.87it/s]
24 Oct 14:02    INFO  epoch 2 training [time: 0.26s, train loss: 9.8429]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 185.69it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 182.71it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 172.90it/s]
24 Oct 14:02    INFO  epoch 3 training [time: 0.26s, train loss: 7.9576]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 196.46it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 187.03it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 178.82it/s]
24 Oct 14:02    INFO  epoch 4 training [time: 0.25s, train loss: 7.1204]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  45%|██████████████████████                           | 18/40 [00:00<00:00, 176.23it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 176.33it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 167.55it/s]
24 Oct 14:02    INFO  epoch 5 training [time: 0.27s, train loss: 6.1491]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 186.51it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 182.19it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 172.25it/s]
24 Oct 14:02    INFO  epoch 6 training [time: 0.26s, train loss: 5.5717]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 192.48it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 189.43it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 180.38it/s]
24 Oct 14:02    INFO  epoch 7 training [time: 0.25s, train loss: 5.0738]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 180.91it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 182.32it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 171.21it/s]
24 Oct 14:02    INFO  epoch 8 training [time: 0.26s, train loss: 4.6037]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 187.52it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 184.76it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 172.99it/s]
24 Oct 14:02    INFO  epoch 9 training [time: 0.26s, train loss: 4.3014]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5884.92it/s]
24 Oct 14:02    INFO  epoch 9 evaluating [time: 0.12s, valid_score: 0.330500]
24 Oct 14:02    INFO  valid result:
recall@10 : 0.1858    mrr@10 : 0.3305    ndcg@10 : 0.1956    hit@10 : 0.7041    precision@10 : 0.1392
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 187.97it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 185.66it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 173.48it/s]
24 Oct 14:02    INFO  epoch 10 training [time: 0.26s, train loss: 3.9565]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 185.94it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 185.13it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 173.27it/s]
24 Oct 14:02    INFO  epoch 11 training [time: 0.31s, train loss: 3.7091]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 188.23it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 187.22it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 175.43it/s]
24 Oct 14:02    INFO  epoch 12 training [time: 0.25s, train loss: 3.4709]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  50%|████████████████████████▌                        | 20/40 [00:00<00:00, 192.26it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 187.26it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 177.15it/s]
24 Oct 14:02    INFO  epoch 13 training [time: 0.25s, train loss: 3.2957]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 185.56it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 182.04it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 171.91it/s]
24 Oct 14:02    INFO  epoch 14 training [time: 0.26s, train loss: 3.1316]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  45%|██████████████████████                           | 18/40 [00:00<00:00, 172.33it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 168.85it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 160.21it/s]
24 Oct 14:02    INFO  epoch 15 training [time: 0.28s, train loss: 3.0091]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  45%|██████████████████████                           | 18/40 [00:00<00:00, 179.10it/s]:  90%|████████████████████████████████████████████     | 36/40 [00:00<00:00, 177.14it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 167.87it/s]
24 Oct 14:02    INFO  epoch 16 training [time: 0.27s, train loss: 2.8710]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 165.14it/s]:  88%|██████████████████████████████████████████▉      | 35/40 [00:00<00:00, 172.62it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 163.02it/s]
24 Oct 14:02    INFO  epoch 17 training [time: 0.27s, train loss: 2.7255]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 184.83it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 183.70it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 173.14it/s]
24 Oct 14:02    INFO  epoch 18 training [time: 0.26s, train loss: 2.5715]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  48%|███████████████████████▎                         | 19/40 [00:00<00:00, 186.92it/s]:  95%|██████████████████████████████████████████████▌  | 38/40 [00:00<00:00, 181.05it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 169.29it/s]
24 Oct 14:02    INFO  epoch 19 training [time: 0.26s, train loss: 2.5139]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5454.44it/s]
24 Oct 14:02    INFO  epoch 19 evaluating [time: 0.12s, valid_score: 0.315800]
24 Oct 14:02    INFO  valid result:
recall@10 : 0.1784    mrr@10 : 0.3158    ndcg@10 : 0.1821    hit@10 : 0.684    precision@10 : 0.1262
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5492.91it/s]
24 Oct 14:02    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    27.30 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.52 G/16.00 G |
+-------------+----------------+
24 Oct 14:02    INFO  best valid : OrderedDict([('recall@10', 0.1858), ('mrr@10', 0.3305), ('ndcg@10', 0.1956), ('hit@10', 0.7041), ('precision@10', 0.1392)])
24 Oct 14:02    INFO  test result: OrderedDict([('recall@10', 0.1963), ('mrr@10', 0.3667), ('ndcg@10', 0.2147), ('hit@10', 0.72), ('precision@10', 0.1477)])

[10/12] BPR: {'embedding_size': 128, 'learning_rate': 0.0001}

24 Oct 14:02    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:02    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.0001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 128
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:02    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:02    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:02    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:02    INFO  BPR(
  (user_embedding): Embedding(944, 128)
  (item_embedding): Embedding(1683, 128)
  (loss): BPRLoss()
)
Trainable parameters: 336256
24 Oct 14:02    INFO  FLOPs: 256.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  32%|███████████████▉                                 | 13/40 [00:00<00:00, 126.43it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 136.01it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 137.17it/s]
24 Oct 14:02    INFO  epoch 0 training [time: 0.33s, train loss: 27.7254]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 157.35it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 150.91it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 148.21it/s]
24 Oct 14:02    INFO  epoch 1 training [time: 0.30s, train loss: 27.7143]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 159.52it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 153.54it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 147.55it/s]
24 Oct 14:02    INFO  epoch 2 training [time: 0.30s, train loss: 27.7030]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 161.18it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 159.08it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 152.43it/s]
24 Oct 14:02    INFO  epoch 3 training [time: 0.29s, train loss: 27.6898]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 157.92it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 152.34it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 148.78it/s]
24 Oct 14:02    INFO  epoch 4 training [time: 0.30s, train loss: 27.6797]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 159.55it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 155.57it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 150.36it/s]
24 Oct 14:02    INFO  epoch 5 training [time: 0.29s, train loss: 27.6689]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 165.17it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 159.25it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 153.36it/s]
24 Oct 14:02    INFO  epoch 6 training [time: 0.29s, train loss: 27.6539]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 163.06it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 159.37it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 151.96it/s]
24 Oct 14:02    INFO  epoch 7 training [time: 0.29s, train loss: 27.6375]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 155.08it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 152.00it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 145.54it/s]
24 Oct 14:02    INFO  epoch 8 training [time: 0.30s, train loss: 27.6216]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  35%|█████████████████▏                               | 14/40 [00:00<00:00, 138.88it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 146.75it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 143.69it/s]
24 Oct 14:02    INFO  epoch 9 training [time: 0.31s, train loss: 27.6040]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5597.05it/s]
24 Oct 14:02    INFO  epoch 9 evaluating [time: 0.12s, valid_score: 0.029700]
24 Oct 14:02    INFO  valid result:
recall@10 : 0.0074    mrr@10 : 0.0297    ndcg@10 : 0.011    hit@10 : 0.0891    precision@10 : 0.0094
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 162.86it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 159.53it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 152.73it/s]
24 Oct 14:02    INFO  epoch 10 training [time: 0.29s, train loss: 27.5791]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 163.78it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 159.40it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 152.32it/s]
24 Oct 14:02    INFO  epoch 11 training [time: 0.29s, train loss: 27.5558]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 156.07it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 153.15it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 148.57it/s]
24 Oct 14:02    INFO  epoch 12 training [time: 0.30s, train loss: 27.5263]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 161.61it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 156.11it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 150.09it/s]
24 Oct 14:02    INFO  epoch 13 training [time: 0.34s, train loss: 27.4933]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 163.97it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 158.17it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 152.06it/s]
24 Oct 14:02    INFO  epoch 14 training [time: 0.29s, train loss: 27.4496]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 161.35it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 157.59it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 152.14it/s]
24 Oct 14:02    INFO  epoch 15 training [time: 0.30s, train loss: 27.3976]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 159.77it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 154.79it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 149.90it/s]
24 Oct 14:02    INFO  epoch 16 training [time: 0.29s, train loss: 27.3360]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 162.93it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 159.41it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 153.03it/s]
24 Oct 14:02    INFO  epoch 17 training [time: 0.29s, train loss: 27.2632]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 165.75it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 159.05it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 153.95it/s]
24 Oct 14:02    INFO  epoch 18 training [time: 0.29s, train loss: 27.1744]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 164.18it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 156.41it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 149.71it/s]
24 Oct 14:02    INFO  epoch 19 training [time: 0.29s, train loss: 27.0705]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5444.50it/s]
24 Oct 14:02    INFO  epoch 19 evaluating [time: 0.12s, valid_score: 0.127300]
24 Oct 14:02    INFO  valid result:
recall@10 : 0.0378    mrr@10 : 0.1273    ndcg@10 : 0.0589    hit@10 : 0.3097    precision@10 : 0.0515
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5233.05it/s]
24 Oct 14:02    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    20.30 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.53 G/16.00 G |
+-------------+----------------+
24 Oct 14:02    INFO  best valid : OrderedDict([('recall@10', 0.0378), ('mrr@10', 0.1273), ('ndcg@10', 0.0589), ('hit@10', 0.3097), ('precision@10', 0.0515)])
24 Oct 14:02    INFO  test result: OrderedDict([('recall@10', 0.0439), ('mrr@10', 0.159), ('ndcg@10', 0.072), ('hit@10', 0.3489), ('precision@10', 0.0606)])

[11/12] BPR: {'embedding_size': 128, 'learning_rate': 0.001}

24 Oct 14:02    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:02    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 128
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:02    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:02    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:02    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:02    INFO  BPR(
  (user_embedding): Embedding(944, 128)
  (item_embedding): Embedding(1683, 128)
  (loss): BPRLoss()
)
Trainable parameters: 336256
24 Oct 14:02    INFO  FLOPs: 256.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  32%|███████████████▉                                 | 13/40 [00:00<00:00, 127.32it/s]:  72%|███████████████████████████████████▌             | 29/40 [00:00<00:00, 143.05it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 142.20it/s]
24 Oct 14:02    INFO  epoch 0 training [time: 0.31s, train loss: 27.7167]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 162.76it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 157.96it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 152.01it/s]
24 Oct 14:02    INFO  epoch 1 training [time: 0.29s, train loss: 27.5173]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 166.18it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 153.13it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 148.84it/s]
24 Oct 14:02    INFO  epoch 2 training [time: 0.30s, train loss: 26.8167]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 161.79it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 158.90it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 151.98it/s]
24 Oct 14:02    INFO  epoch 3 training [time: 0.29s, train loss: 24.2064]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 157.52it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 153.69it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 150.12it/s]
24 Oct 14:02    INFO  epoch 4 training [time: 0.29s, train loss: 19.4208]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 164.06it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 157.69it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 151.37it/s]
24 Oct 14:02    INFO  epoch 5 training [time: 0.29s, train loss: 15.5424]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 161.33it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 158.01it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 151.50it/s]
24 Oct 14:02    INFO  epoch 6 training [time: 0.29s, train loss: 13.6943]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 165.32it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 149.28it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 146.87it/s]
24 Oct 14:02    INFO  epoch 7 training [time: 0.30s, train loss: 12.7211]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 158.80it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 155.94it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 127.55it/s]
24 Oct 14:02    INFO  epoch 8 training [time: 0.34s, train loss: 11.9612]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 159.87it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 159.19it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 153.57it/s]
24 Oct 14:02    INFO  epoch 9 training [time: 0.29s, train loss: 11.3082]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  91%|█████████████████████████████████████████▉    | 430/472 [00:00<00:00, 4294.12it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 3748.74it/s]
24 Oct 14:02    INFO  epoch 9 evaluating [time: 0.16s, valid_score: 0.328300]
24 Oct 14:02    INFO  valid result:
recall@10 : 0.1754    mrr@10 : 0.3283    ndcg@10 : 0.1912    hit@10 : 0.6691    precision@10 : 0.1337
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 162.59it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 158.47it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 152.00it/s]
24 Oct 14:02    INFO  epoch 10 training [time: 0.29s, train loss: 10.7337]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 164.36it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 157.44it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 151.69it/s]
24 Oct 14:02    INFO  epoch 11 training [time: 0.29s, train loss: 10.2006]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 159.42it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 155.35it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 149.80it/s]
24 Oct 14:02    INFO  epoch 12 training [time: 0.29s, train loss: 9.7312]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 162.93it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 157.27it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 150.34it/s]
24 Oct 14:02    INFO  epoch 13 training [time: 0.29s, train loss: 9.3629]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 161.27it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 149.33it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 145.11it/s]
24 Oct 14:02    INFO  epoch 14 training [time: 0.30s, train loss: 9.0330]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 157.25it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 156.44it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 127.25it/s]
24 Oct 14:02    INFO  epoch 15 training [time: 0.34s, train loss: 8.7247]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 165.52it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 158.38it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 152.65it/s]
24 Oct 14:02    INFO  epoch 16 training [time: 0.29s, train loss: 8.4420]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 161.17it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 156.14it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 150.38it/s]
24 Oct 14:02    INFO  epoch 17 training [time: 0.29s, train loss: 8.1667]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 158.34it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 154.48it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 149.71it/s]
24 Oct 14:02    INFO  epoch 18 training [time: 0.30s, train loss: 7.8821]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 161.94it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 155.94it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 150.00it/s]
24 Oct 14:02    INFO  epoch 19 training [time: 0.29s, train loss: 7.8021]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]:  96%|████████████████████████████████████████████▏ | 454/472 [00:00<00:00, 4535.20it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 3855.14it/s]
24 Oct 14:02    INFO  epoch 19 evaluating [time: 0.15s, valid_score: 0.356500]
24 Oct 14:02    INFO  valid result:
recall@10 : 0.1943    mrr@10 : 0.3565    ndcg@10 : 0.2113    hit@10 : 0.7105    precision@10 : 0.1488
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 4876.03it/s]
24 Oct 14:02    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    19.10 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.53 G/16.00 G |
+-------------+----------------+
24 Oct 14:02    INFO  best valid : OrderedDict([('recall@10', 0.1943), ('mrr@10', 0.3565), ('ndcg@10', 0.2113), ('hit@10', 0.7105), ('precision@10', 0.1488)])
24 Oct 14:02    INFO  test result: OrderedDict([('recall@10', 0.2258), ('mrr@10', 0.4587), ('ndcg@10', 0.2691), ('hit@10', 0.7529), ('precision@10', 0.1813)])

[12/12] BPR: {'embedding_size': 128, 'learning_rate': 0.01}

24 Oct 14:02    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:02    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.01
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 128
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:02    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:02    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:02    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:02    INFO  BPR(
  (user_embedding): Embedding(944, 128)
  (item_embedding): Embedding(1683, 128)
  (loss): BPRLoss()
)
Trainable parameters: 336256
24 Oct 14:02    INFO  FLOPs: 256.0
Train     0:   0%|                                                           | 0/40 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:  32%|███████████████▉                                 | 13/40 [00:00<00:00, 126.16it/s]:  70%|██████████████████████████████████▎              | 28/40 [00:00<00:00, 138.91it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 138.83it/s]
24 Oct 14:02    INFO  epoch 0 training [time: 0.32s, train loss: 23.8633]
Train     1:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 160.52it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 155.80it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 150.65it/s]
24 Oct 14:02    INFO  epoch 1 training [time: 0.29s, train loss: 11.3476]
Train     2:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 158.85it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 157.22it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 151.12it/s]
24 Oct 14:02    INFO  epoch 2 training [time: 0.29s, train loss: 8.1615]
Train     3:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 154.93it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 153.49it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 148.94it/s]
24 Oct 14:02    INFO  epoch 3 training [time: 0.30s, train loss: 6.4449]
Train     4:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 157.12it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 150.89it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 147.86it/s]
24 Oct 14:02    INFO  epoch 4 training [time: 0.30s, train loss: 5.5213]
Train     5:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 162.76it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 158.52it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 151.61it/s]
24 Oct 14:02    INFO  epoch 5 training [time: 0.30s, train loss: 4.5565]
Train     6:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 159.74it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 154.76it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 150.15it/s]
24 Oct 14:02    INFO  epoch 6 training [time: 0.30s, train loss: 3.9648]
Train     7:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 159.48it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 156.32it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 151.72it/s]
24 Oct 14:02    INFO  epoch 7 training [time: 0.29s, train loss: 3.4699]
Train     8:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 163.84it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 160.60it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 153.86it/s]
24 Oct 14:02    INFO  epoch 8 training [time: 0.29s, train loss: 3.0429]
Train     9:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 164.17it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 157.96it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 151.17it/s]
24 Oct 14:02    INFO  epoch 9 training [time: 0.29s, train loss: 2.7160]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5097.96it/s]
24 Oct 14:02    INFO  epoch 9 evaluating [time: 0.13s, valid_score: 0.318200]
24 Oct 14:02    INFO  valid result:
recall@10 : 0.1753    mrr@10 : 0.3182    ndcg@10 : 0.1818    hit@10 : 0.6819    precision@10 : 0.1282
Train    10:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 162.87it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 155.19it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 149.08it/s]
24 Oct 14:02    INFO  epoch 10 training [time: 0.30s, train loss: 2.5080]
Train    11:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 162.27it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 158.53it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 151.58it/s]
24 Oct 14:02    INFO  epoch 11 training [time: 0.29s, train loss: 2.2377]
Train    12:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 160.86it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 157.18it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 150.55it/s]
24 Oct 14:02    INFO  epoch 12 training [time: 0.30s, train loss: 2.0633]
Train    13:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  38%|██████████████████▍                              | 15/40 [00:00<00:00, 143.25it/s]:  75%|████████████████████████████████████▊            | 30/40 [00:00<00:00, 146.70it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 143.94it/s]
24 Oct 14:02    INFO  epoch 13 training [time: 0.31s, train loss: 1.9233]
Train    14:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 158.27it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 153.15it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 148.34it/s]
24 Oct 14:02    INFO  epoch 14 training [time: 0.30s, train loss: 1.7922]
Train    15:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 159.16it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 155.35it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 151.00it/s]
24 Oct 14:02    INFO  epoch 15 training [time: 0.29s, train loss: 1.6589]
Train    16:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  35%|█████████████████▏                               | 14/40 [00:00<00:00, 135.62it/s]:  72%|███████████████████████████████████▌             | 29/40 [00:00<00:00, 141.44it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 140.59it/s]
24 Oct 14:02    INFO  epoch 16 training [time: 0.31s, train loss: 1.5669]
Train    17:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  42%|████████████████████▊                            | 17/40 [00:00<00:00, 164.46it/s]:  85%|█████████████████████████████████████████▋       | 34/40 [00:00<00:00, 158.95it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 153.50it/s]
24 Oct 14:02    INFO  epoch 17 training [time: 0.29s, train loss: 1.4456]
Train    18:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 157.04it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 149.92it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 146.37it/s]
24 Oct 14:02    INFO  epoch 18 training [time: 0.30s, train loss: 1.3183]
Train    19:   0%|                                                           | 0/40 [00:00<?, ?it/s]:  40%|███████████████████▌                             | 16/40 [00:00<00:00, 158.48it/s]:  80%|███████████████████████████████████████▏         | 32/40 [00:00<00:00, 153.82it/s]: 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 148.77it/s]
24 Oct 14:02    INFO  epoch 19 training [time: 0.30s, train loss: 1.3070]
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5292.74it/s]
24 Oct 14:02    INFO  epoch 19 evaluating [time: 0.14s, valid_score: 0.303500]
24 Oct 14:02    INFO  valid result:
recall@10 : 0.1611    mrr@10 : 0.3035    ndcg@10 : 0.1657    hit@10 : 0.6479    precision@10 : 0.1117
Evaluate   :   0%|                                                          | 0/472 [00:00<?, ?it/s]: 100%|██████████████████████████████████████████████| 472/472 [00:00<00:00, 5047.86it/s]
24 Oct 14:02    INFO  The running environment of this training is as follows:
+-------------+----------------+
| Environment |     Usage      |
+=============+================+
| CPU         |    18.70 %     |
+-------------+----------------+
| GPU         |   0.0 / 0.0    |
+-------------+----------------+
| Memory      | 0.54 G/16.00 G |
+-------------+----------------+
24 Oct 14:02    INFO  best valid : OrderedDict([('recall@10', 0.1753), ('mrr@10', 0.3182), ('ndcg@10', 0.1818), ('hit@10', 0.6819), ('precision@10', 0.1282)])
24 Oct 14:02    INFO  test result: OrderedDict([('recall@10', 0.1824), ('mrr@10', 0.3419), ('ndcg@10', 0.1903), ('hit@10', 0.6988), ('precision@10', 0.1286)])

Saved to:
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/group_18/results/task_1_2/BPR_tuning.csv

Best configuration:

,embedding_size,learning_rate,valid_score,recall@10,mrr@10,ndcg@10,hit@10,precision@10
0,32,0.01,0.3581,0.1904,0.3581,0.2038,0.7169,0.1393

In [10]:
slim_space = {
    "alpha": [0.0001, 0.001, 0.01, 0.1],
    "l1_ratio": [0.1, 0.5, 0.9]
}

slim_results = tune_model(
    name="SLIM",
    model="SLIMElastic",
    config_path=CONFIG_ROOT / "SLIMElastic" / "ml-100k.yaml",
    search_space=slim_space
)

Tuning SLIM
Number of experiments: 12
============================================================
[1/12] SLIM: {'alpha': 0.0001, 'l1_ratio': 0.1}

24 Oct 14:02    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:02    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[2/12] SLIM: {'alpha': 0.0001, 'l1_ratio': 0.5}

24 Oct 14:02    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:02    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[3/12] SLIM: {'alpha': 0.0001, 'l1_ratio': 0.9}

24 Oct 14:03    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:03    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[4/12] SLIM: {'alpha': 0.001, 'l1_ratio': 0.1}

24 Oct 14:03    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:03    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[5/12] SLIM: {'alpha': 0.001, 'l1_ratio': 0.5}

24 Oct 14:03    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:03    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[6/12] SLIM: {'alpha': 0.001, 'l1_ratio': 0.9}

24 Oct 14:03    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:03    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[7/12] SLIM: {'alpha': 0.01, 'l1_ratio': 0.1}

24 Oct 14:03    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:03    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[8/12] SLIM: {'alpha': 0.01, 'l1_ratio': 0.5}

24 Oct 14:04    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:04    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[9/12] SLIM: {'alpha': 0.01, 'l1_ratio': 0.9}

24 Oct 14:04    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:04    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[10/12] SLIM: {'alpha': 0.1, 'l1_ratio': 0.1}

24 Oct 14:04    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:04    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[11/12] SLIM: {'alpha': 0.1, 'l1_ratio': 0.5}

24 Oct 14:04    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:04    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[12/12] SLIM: {'alpha': 0.1, 'l1_ratio': 0.9}

24 Oct 14:04    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:04    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

Saved to:
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/group_18/results/task_1_2/SLIM_tuning.csv

Best configuration:

,alpha,l1_ratio,valid_score,recall@10,mrr@10,ndcg@10,hit@10,precision@10
0,0.1,0.1,0.4165,0.2271,0.4165,0.2495,0.7625,0.1709

In [11]:
ease_space = {
    "reg_weight": [10, 50, 100, 200, 500, 1000]
}

ease_results = tune_model(
    name="EASE",
    model="EASE",
    config_path=CONFIG_ROOT / "EASE" / "ml-100k.yaml",
    search_space=ease_space
)

Tuning EASE
Number of experiments: 6
============================================================
[1/6] EASE: {'reg_weight': 10}

24 Oct 14:04    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:04    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[2/6] EASE: {'reg_weight': 50}

24 Oct 14:04    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:04    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[3/6] EASE: {'reg_weight': 100}

24 Oct 14:04    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:04    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[4/6] EASE: {'reg_weight': 200}

24 Oct 14:04    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:04    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[5/6] EASE: {'reg_weight': 500}

24 Oct 14:04    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:04    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

[6/6] EASE: {'reg_weight': 1000}

24 Oct 14:04    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:04    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]

Saved to:
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/group_18/results/task_1_2/EASE_tuning.csv

Best configuration:

   reg_weight  valid_score  recall@10  mrr@10  ndcg@10  hit@10  precision@10
0         500       0.4189     0.2386  0.4189   0.2568  0.7815        0.1766

In [17]:
fism_space = {
    "embedding_size": [32, 64],
    "learning_rate": [0.001, 0.005],
    "alpha": [0.5],
    "reg_weights": [
        [0.0001, 0.0001],
        [0.001, 0.001],
    ],
}

fism_results = tune_model(
    name="FISM",
    model="FISM",
    config_path=CONFIG_ROOT / "FISM" / "ml-100k.yaml",
    search_space=fism_space,
)

Tuning FISM
Number of experiments: 8
============================================================
[1/8] FISM: {'embedding_size': 32, 'learning_rate': 0.001, 'alpha': 0.5, 'reg_weights': [0.0001, 0.0001]}

24 Oct 14:10    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:10    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
split_to = 0
reg_weights = [0.0001, 0.0001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:10    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:10    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:10    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:10    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
24 Oct 14:10    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
24 Oct 14:10    INFO  FISM(
  (item_src_embedding): Embedding(1683, 32, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 32, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 110339
24 Oct 14:10    INFO  FLOPs: 18944.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:   1%|▋                                                  | 1/79 [00:00<00:09,  7.94it/s]:   4%|█▉                                                 | 3/79 [00:00<00:07, 10.52it/s]:   6%|███▏                                               | 5/79 [00:00<00:06, 11.08it/s]:   9%|████▌                                              | 7/79 [00:00<00:06, 11.37it/s]:  11%|█████▊                                             | 9/79 [00:00<00:06, 11.61it/s]:  14%|██████▉                                           | 11/79 [00:00<00:05, 11.71it/s]:  16%|████████▏                                         | 13/79 [00:01<00:05, 11.75it/s]:  19%|█████████▍                                        | 15/79 [00:01<00:05, 11.83it/s]:  22%|██████████▊                                       | 17/79 [00:01<00:05, 11.77it/s]:  24%|████████████                                      | 19/79 [00:01<00:05, 11.84it/s]:  27%|█████████████▎                                    | 21/79 [00:01<00:04, 11.95it/s]:  29%|██████████████▌                                   | 23/79 [00:01<00:04, 12.00it/s]:  32%|███████████████▊                                  | 25/79 [00:02<00:04, 12.09it/s]:  34%|█████████████████                                 | 27/79 [00:02<00:04, 12.07it/s]:  37%|██████████████████▎                               | 29/79 [00:02<00:04, 12.08it/s]:  39%|███████████████████▌                              | 31/79 [00:02<00:03, 12.15it/s]:  42%|████████████████████▉                             | 33/79 [00:02<00:03, 12.12it/s]:  44%|██████████████████████▏                           | 35/79 [00:02<00:03, 12.13it/s]:  47%|███████████████████████▍                          | 37/79 [00:03<00:03, 12.13it/s]:  49%|████████████████████████▋                         | 39/79 [00:03<00:03, 12.16it/s]:  52%|█████████████████████████▉                        | 41/79 [00:03<00:03, 12.05it/s]:  54%|███████████████████████████▏                      | 43/79 [00:03<00:02, 12.08it/s]:  57%|████████████████████████████▍                     | 45/79 [00:03<00:02, 12.11it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:03<00:02, 12.03it/s]:  62%|███████████████████████████████                   | 49/79 [00:04<00:02, 12.06it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:04<00:02, 12.11it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:04<00:02, 12.02it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:04<00:01, 12.04it/s]:  72%|████████████████████████████████████              | 57/79 [00:04<00:01, 12.08it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:04<00:01, 12.08it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:05<00:01, 12.09it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:05<00:01, 12.10it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:05<00:01, 12.11it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:05<00:00, 12.09it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:05<00:00, 12.14it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:05<00:00, 12.16it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:06<00:00, 12.11it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:06<00:00, 12.09it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:06<00:00, 11.30it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.65it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.89it/s]
24 Oct 14:10    INFO  epoch 0 training [time: 6.68s, train loss: 55.0431]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:05, 13.07it/s]:   5%|██▌                                                | 4/79 [00:00<00:05, 12.51it/s]:   8%|███▊                                               | 6/79 [00:00<00:05, 12.31it/s]:  10%|█████▏                                             | 8/79 [00:00<00:05, 12.19it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 12.17it/s]:  15%|███████▌                                          | 12/79 [00:00<00:05, 12.17it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 12.14it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 12.14it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 12.16it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:04, 12.18it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 12.17it/s]:  30%|███████████████▏                                  | 24/79 [00:01<00:04, 12.20it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 12.21it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 12.21it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 12.21it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 12.19it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 12.15it/s]:  46%|██████████████████████▊                           | 36/79 [00:02<00:03, 12.14it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 12.15it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 12.18it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 12.16it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 12.17it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 12.16it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:03<00:02, 12.19it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 12.20it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 12.17it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 12.18it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 12.18it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 12.19it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:04<00:01, 12.18it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 12.17it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 12.14it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 12.15it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 12.16it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 12.12it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:05<00:00, 12.08it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 12.09it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 12.11it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 12.12it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 12.17it/s]
24 Oct 14:10    INFO  epoch 1 training [time: 6.52s, train loss: 50.1013]
Train     2:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:05, 12.93it/s]:   5%|██▌                                                | 4/79 [00:00<00:05, 12.58it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 10.96it/s]:  10%|█████▏                                             | 8/79 [00:00<00:06, 11.39it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 11.60it/s]:  15%|███████▌                                          | 12/79 [00:01<00:05, 11.77it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 11.77it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 11.83it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 11.91it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:04, 11.95it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 12.00it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.19it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.47it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.65it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.80it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 11.91it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 11.90it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 11.94it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 12.02it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 12.03it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 12.06it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 12.05it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 12.13it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 12.13it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 12.12it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 12.13it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 12.12it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 12.16it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 11.34it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.60it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.75it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.85it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.98it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 12.00it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 12.05it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 12.07it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 12.15it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 12.20it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 12.17it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.91it/s]
24 Oct 14:10    INFO  epoch 2 training [time: 6.66s, train loss: 49.3642]
Train     3:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:05, 12.93it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 12.46it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 11.01it/s]:  10%|█████▏                                             | 8/79 [00:00<00:06, 11.61it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 11.86it/s]:  15%|███████▌                                          | 12/79 [00:01<00:05, 12.07it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 12.12it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 12.23it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:04, 12.21it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:04, 12.18it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 11.90it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.23it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.50it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.72it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.79it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 11.80it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 11.87it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 12.00it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 12.03it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 12.08it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 12.10it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 12.14it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 12.16it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 12.06it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 12.04it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 12.11it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 12.09it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:02, 11.11it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 11.40it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.64it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.83it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.88it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.91it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 11.98it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 12.06it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 12.05it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 11.98it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 11.98it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 11.97it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.90it/s]
24 Oct 14:11    INFO  epoch 3 training [time: 6.67s, train loss: 49.1869]

[2/8] FISM: {'embedding_size': 32, 'learning_rate': 0.001, 'alpha': 0.5, 'reg_weights': [0.001, 0.001]}

24 Oct 14:13    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:13    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
split_to = 0
reg_weights = [0.001, 0.001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:13    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:13    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:13    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:13    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
24 Oct 14:13    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
24 Oct 14:13    INFO  FISM(
  (item_src_embedding): Embedding(1683, 32, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 32, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 110339
24 Oct 14:13    INFO  FLOPs: 18944.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:   1%|▋                                                  | 1/79 [00:00<00:08,  8.70it/s]:   4%|█▉                                                 | 3/79 [00:00<00:06, 10.88it/s]:   6%|███▏                                               | 5/79 [00:00<00:06, 11.42it/s]:   9%|████▌                                              | 7/79 [00:00<00:06, 11.72it/s]:  11%|█████▊                                             | 9/79 [00:00<00:05, 11.74it/s]:  14%|██████▉                                           | 11/79 [00:00<00:05, 11.41it/s]:  16%|████████▏                                         | 13/79 [00:01<00:05, 11.60it/s]:  19%|█████████▍                                        | 15/79 [00:01<00:05, 11.59it/s]:  22%|██████████▊                                       | 17/79 [00:01<00:05, 11.71it/s]:  24%|████████████                                      | 19/79 [00:01<00:06,  9.96it/s]:  27%|█████████████▎                                    | 21/79 [00:01<00:05, 10.44it/s]:  29%|██████████████▌                                   | 23/79 [00:02<00:05, 10.70it/s]:  32%|███████████████▊                                  | 25/79 [00:02<00:04, 11.10it/s]:  34%|█████████████████                                 | 27/79 [00:02<00:04, 11.35it/s]:  37%|██████████████████▎                               | 29/79 [00:02<00:04, 11.57it/s]:  39%|███████████████████▌                              | 31/79 [00:02<00:04, 11.65it/s]:  42%|████████████████████▉                             | 33/79 [00:02<00:03, 11.84it/s]:  44%|██████████████████████▏                           | 35/79 [00:03<00:03, 11.91it/s]:  47%|███████████████████████▍                          | 37/79 [00:03<00:03, 11.95it/s]:  49%|████████████████████████▋                         | 39/79 [00:03<00:03, 11.04it/s]:  52%|█████████████████████████▉                        | 41/79 [00:03<00:03, 11.32it/s]:  54%|███████████████████████████▏                      | 43/79 [00:03<00:03, 11.53it/s]:  57%|████████████████████████████▍                     | 45/79 [00:03<00:02, 11.64it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:04<00:02, 11.74it/s]:  62%|███████████████████████████████                   | 49/79 [00:04<00:02, 11.87it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:04<00:02, 11.99it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:04<00:02, 12.04it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:04<00:01, 12.08it/s]:  72%|████████████████████████████████████              | 57/79 [00:04<00:01, 12.10it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:05<00:01, 12.04it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:05<00:01, 12.08it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:05<00:01, 12.06it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:05<00:01, 12.02it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:05<00:00, 12.06it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:05<00:00, 12.07it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:06<00:00, 12.08it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:06<00:00, 12.11it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:06<00:00, 12.10it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:06<00:00, 12.08it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 12.17it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.65it/s]
24 Oct 14:13    INFO  epoch 0 training [time: 6.81s, train loss: 57.0669]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:05, 12.88it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 12.25it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 12.12it/s]:  10%|█████▏                                             | 8/79 [00:00<00:06, 10.93it/s]:  13%|██████▎                                           | 10/79 [00:00<00:06, 11.21it/s]:  15%|███████▌                                          | 12/79 [00:01<00:05, 11.45it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 11.59it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 11.74it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 11.81it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:04, 11.90it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 11.96it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.99it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 12.05it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 12.09it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 12.12it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 12.13it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 12.14it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 12.02it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 12.04it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 12.11it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 12.09it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 12.10it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 12.06it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 12.09it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 12.12it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 12.13it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 12.10it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:02, 11.14it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 11.42it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.62it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.76it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.89it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.96it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 11.83it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 11.92it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 11.18it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 11.44it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 11.61it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 11.76it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.83it/s]
24 Oct 14:13    INFO  epoch 1 training [time: 6.70s, train loss: 56.6402]
Train     2:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:05, 12.96it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 12.19it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 12.09it/s]:  10%|█████▏                                             | 8/79 [00:00<00:05, 12.12it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 12.12it/s]:  15%|███████▌                                          | 12/79 [00:00<00:05, 12.14it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 11.20it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 11.33it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 11.60it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:05, 11.74it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 11.84it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.91it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.96it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.99it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.96it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 11.97it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 12.01it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 11.96it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 11.19it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 11.45it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 11.65it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 11.80it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 11.85it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 11.88it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 11.96it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 12.02it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 12.07it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 12.09it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 12.14it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.23it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.48it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.62it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.77it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 11.82it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 11.91it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 12.01it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 12.04it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 11.17it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 11.43it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.78it/s]
24 Oct 14:13    INFO  epoch 2 training [time: 6.78s, train loss: 56.2779]
Train     3:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:05, 12.85it/s]:   5%|██▌                                                | 4/79 [00:00<00:05, 12.53it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 10.93it/s]:  10%|█████▏                                             | 8/79 [00:00<00:06, 11.37it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 11.66it/s]:  15%|███████▌                                          | 12/79 [00:01<00:05, 11.78it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 11.81it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 11.91it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 11.01it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:05, 11.34it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 11.58it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.75it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.78it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.92it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.94it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 11.96it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 12.00it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 12.05it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 12.06it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 12.03it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 10.75it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:03, 11.17it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 11.43it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 11.49it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 11.48it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 11.60it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 11.76it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 11.82it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 11.92it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.98it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 12.04it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.20it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.41it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 11.62it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 11.74it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 11.84it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 11.92it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 11.89it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 11.94it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.71it/s]
24 Oct 14:13    INFO  epoch 3 training [time: 6.78s, train loss: 55.9284]

[3/8] FISM: {'embedding_size': 32, 'learning_rate': 0.005, 'alpha': 0.5, 'reg_weights': [0.0001, 0.0001]}

24 Oct 14:15    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:15    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.005
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
split_to = 0
reg_weights = [0.0001, 0.0001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:15    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:15    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:15    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:15    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
24 Oct 14:15    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
24 Oct 14:15    INFO  FISM(
  (item_src_embedding): Embedding(1683, 32, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 32, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 110339
24 Oct 14:15    INFO  FLOPs: 18944.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:   1%|▋                                                  | 1/79 [00:00<00:08,  8.79it/s]:   4%|█▉                                                 | 3/79 [00:00<00:06, 11.05it/s]:   6%|███▏                                               | 5/79 [00:00<00:06, 11.61it/s]:   9%|████▌                                              | 7/79 [00:00<00:06, 11.86it/s]:  11%|█████▊                                             | 9/79 [00:00<00:05, 12.02it/s]:  14%|██████▉                                           | 11/79 [00:00<00:05, 12.07it/s]:  16%|████████▏                                         | 13/79 [00:01<00:05, 12.05it/s]:  19%|█████████▍                                        | 15/79 [00:01<00:05, 12.07it/s]:  22%|██████████▊                                       | 17/79 [00:01<00:05, 12.02it/s]:  24%|████████████                                      | 19/79 [00:01<00:04, 12.03it/s]:  27%|█████████████▎                                    | 21/79 [00:01<00:04, 12.01it/s]:  29%|██████████████▌                                   | 23/79 [00:01<00:04, 12.07it/s]:  32%|███████████████▊                                  | 25/79 [00:02<00:04, 12.05it/s]:  34%|█████████████████                                 | 27/79 [00:02<00:04, 12.09it/s]:  37%|██████████████████▎                               | 29/79 [00:02<00:04, 12.11it/s]:  39%|███████████████████▌                              | 31/79 [00:02<00:03, 12.14it/s]:  42%|████████████████████▉                             | 33/79 [00:02<00:03, 12.16it/s]:  44%|██████████████████████▏                           | 35/79 [00:02<00:03, 12.14it/s]:  47%|███████████████████████▍                          | 37/79 [00:03<00:03, 12.12it/s]:  49%|████████████████████████▋                         | 39/79 [00:03<00:03, 12.02it/s]:  52%|█████████████████████████▉                        | 41/79 [00:03<00:03, 12.04it/s]:  54%|███████████████████████████▏                      | 43/79 [00:03<00:03, 11.15it/s]:  57%|████████████████████████████▍                     | 45/79 [00:03<00:02, 11.37it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:03<00:02, 11.50it/s]:  62%|███████████████████████████████                   | 49/79 [00:04<00:02, 11.68it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:04<00:02, 11.83it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:04<00:02, 11.82it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:04<00:02, 11.96it/s]:  72%|████████████████████████████████████              | 57/79 [00:04<00:01, 12.03it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:04<00:01, 12.05it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:05<00:01, 12.09it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:05<00:01, 12.08it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:05<00:01, 12.03it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:05<00:01, 11.98it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:05<00:00, 11.85it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:05<00:00, 11.63it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:06<00:00, 11.52it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:06<00:00, 11.49it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:06<00:00, 11.60it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.63it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.83it/s]
24 Oct 14:15    INFO  epoch 0 training [time: 6.76s, train loss: 51.0733]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 12.78it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 12.13it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 12.04it/s]:  10%|█████▏                                             | 8/79 [00:00<00:07, 10.01it/s]:  13%|██████▎                                           | 10/79 [00:00<00:06, 10.56it/s]:  15%|███████▌                                          | 12/79 [00:01<00:06, 10.76it/s]:  18%|████████▊                                         | 14/79 [00:01<00:06, 10.69it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 10.78it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 10.75it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:05, 10.56it/s]:  28%|█████████████▉                                    | 22/79 [00:02<00:05, 10.78it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.09it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.38it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.60it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.79it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 11.91it/s]:  43%|█████████████████████▌                            | 34/79 [00:03<00:03, 11.98it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 12.03it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 12.07it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 12.14it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 12.04it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 12.04it/s]:  58%|█████████████████████████████                     | 46/79 [00:04<00:02, 12.15it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 12.12it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 12.13it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 12.16it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 12.08it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:02, 11.21it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:05<00:01, 11.51it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.63it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.82it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.85it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.91it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 11.76it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:06<00:00, 11.65it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 10.97it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 10.39it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00,  9.95it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00,  9.22it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:07<00:00,  9.06it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:07<00:00, 11.13it/s]
24 Oct 14:15    INFO  epoch 1 training [time: 7.13s, train loss: 49.2472]
Train     2:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 12.34it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 11.83it/s]:   8%|███▊                                               | 6/79 [00:00<00:07,  9.18it/s]:   9%|████▌                                              | 7/79 [00:00<00:08,  8.95it/s]:  10%|█████▏                                             | 8/79 [00:00<00:09,  7.84it/s]:  11%|█████▊                                             | 9/79 [00:01<00:09,  7.37it/s]:  13%|██████▎                                           | 10/79 [00:01<00:09,  7.03it/s]:  14%|██████▉                                           | 11/79 [00:01<00:09,  7.17it/s]:  15%|███████▌                                          | 12/79 [00:01<00:09,  7.19it/s]:  18%|████████▊                                         | 14/79 [00:01<00:07,  8.74it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:06,  9.74it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 10.47it/s]:  25%|████████████▋                                     | 20/79 [00:02<00:05, 10.86it/s]:  28%|█████████████▉                                    | 22/79 [00:02<00:05, 11.16it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.16it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 10.85it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 10.75it/s]:  38%|██████████████████▉                               | 30/79 [00:03<00:05,  8.34it/s]:  39%|███████████████████▌                              | 31/79 [00:03<00:06,  7.83it/s]:  41%|████████████████████▎                             | 32/79 [00:03<00:06,  7.62it/s]:  43%|█████████████████████▌                            | 34/79 [00:03<00:05,  8.84it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:04,  9.76it/s]:  48%|████████████████████████                          | 38/79 [00:04<00:03, 10.42it/s]:  51%|█████████████████████████▎                        | 40/79 [00:04<00:03, 10.95it/s]:  53%|██████████████████████████▌                       | 42/79 [00:04<00:03, 11.31it/s]:  56%|███████████████████████████▊                      | 44/79 [00:04<00:03, 11.58it/s]:  58%|█████████████████████████████                     | 46/79 [00:04<00:02, 11.74it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 11.87it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:05<00:02, 11.90it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:05<00:02, 11.99it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:05<00:02, 12.05it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:05<00:02, 11.07it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:05<00:01, 11.41it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.70it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:06<00:01, 11.83it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:06<00:01, 11.87it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:06<00:01, 11.98it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:06<00:00, 12.06it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:06<00:00, 12.11it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 12.15it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:07<00:00, 12.12it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:07<00:00, 11.28it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:07<00:00, 11.56it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:07<00:00, 10.50it/s]
24 Oct 14:15    INFO  epoch 2 training [time: 7.56s, train loss: 49.0508]
Train     3:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 12.37it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 12.04it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 12.07it/s]:  10%|█████▏                                             | 8/79 [00:00<00:05, 12.14it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 12.09it/s]:  15%|███████▌                                          | 12/79 [00:00<00:05, 12.11it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 11.42it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 11.61it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 11.46it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:05, 11.54it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 11.55it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.73it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.85it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.95it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.89it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 11.97it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 12.09it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 10.93it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 11.30it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 11.53it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 11.55it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 11.77it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 11.91it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 11.78it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 11.93it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 11.92it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 11.79it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:02, 11.29it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 11.55it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.54it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.75it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.81it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.90it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 12.00it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 12.01it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 11.93it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 12.04it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 11.03it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 11.34it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.70it/s]

[4/8] FISM: {'embedding_size': 32, 'learning_rate': 0.005, 'alpha': 0.5, 'reg_weights': [0.001, 0.001]}

24 Oct 14:18    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:18    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.005
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 32
split_to = 0
reg_weights = [0.001, 0.001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:18    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:18    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:18    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:18    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
24 Oct 14:18    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
24 Oct 14:18    INFO  FISM(
  (item_src_embedding): Embedding(1683, 32, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 32, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 110339
24 Oct 14:18    INFO  FLOPs: 18944.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:   1%|▋                                                  | 1/79 [00:00<00:09,  8.28it/s]:   4%|█▉                                                 | 3/79 [00:00<00:07, 10.72it/s]:   6%|███▏                                               | 5/79 [00:00<00:06, 11.22it/s]:   9%|████▌                                              | 7/79 [00:00<00:06, 11.69it/s]:  11%|█████▊                                             | 9/79 [00:00<00:05, 11.82it/s]:  14%|██████▉                                           | 11/79 [00:00<00:05, 11.95it/s]:  16%|████████▏                                         | 13/79 [00:01<00:05, 12.06it/s]:  19%|█████████▍                                        | 15/79 [00:01<00:05, 12.08it/s]:  22%|██████████▊                                       | 17/79 [00:01<00:05, 12.09it/s]:  24%|████████████                                      | 19/79 [00:01<00:05, 11.62it/s]:  27%|█████████████▎                                    | 21/79 [00:01<00:04, 11.73it/s]:  29%|██████████████▌                                   | 23/79 [00:01<00:04, 11.86it/s]:  32%|███████████████▊                                  | 25/79 [00:02<00:04, 11.91it/s]:  34%|█████████████████                                 | 27/79 [00:02<00:04, 11.99it/s]:  37%|██████████████████▎                               | 29/79 [00:02<00:04, 11.80it/s]:  39%|███████████████████▌                              | 31/79 [00:02<00:04, 11.86it/s]:  42%|████████████████████▉                             | 33/79 [00:02<00:03, 11.91it/s]:  44%|██████████████████████▏                           | 35/79 [00:02<00:03, 11.74it/s]:  47%|███████████████████████▍                          | 37/79 [00:03<00:03, 11.84it/s]:  49%|████████████████████████▋                         | 39/79 [00:03<00:03, 11.87it/s]:  52%|█████████████████████████▉                        | 41/79 [00:03<00:03, 11.90it/s]:  54%|███████████████████████████▏                      | 43/79 [00:03<00:03, 11.84it/s]:  57%|████████████████████████████▍                     | 45/79 [00:03<00:02, 11.76it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:03<00:02, 11.91it/s]:  62%|███████████████████████████████                   | 49/79 [00:04<00:02, 11.03it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:04<00:02, 11.11it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:04<00:02, 11.32it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:04<00:02, 11.45it/s]:  72%|████████████████████████████████████              | 57/79 [00:04<00:01, 11.39it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:05<00:01, 11.28it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:05<00:01, 11.45it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:05<00:01, 11.69it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:05<00:01, 11.83it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:05<00:01, 11.96it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:05<00:00, 12.03it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:06<00:00, 12.00it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:06<00:00, 12.10it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:06<00:00, 12.10it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:06<00:00, 12.11it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 12.25it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.75it/s]
24 Oct 14:18    INFO  epoch 0 training [time: 6.76s, train loss: 56.3302]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:05, 13.00it/s]:   5%|██▌                                                | 4/79 [00:00<00:05, 12.53it/s]:   8%|███▊                                               | 6/79 [00:00<00:05, 12.39it/s]:  10%|█████▏                                             | 8/79 [00:00<00:06, 11.33it/s]:  13%|██████▎                                           | 10/79 [00:00<00:05, 11.58it/s]:  15%|███████▌                                          | 12/79 [00:01<00:05, 11.79it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 11.50it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 11.20it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 11.43it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:05, 11.59it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 11.75it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.83it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.98it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 12.01it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.98it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 12.02it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 12.05it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 12.10it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 12.05it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 12.05it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 11.90it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 11.81it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 11.89it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 11.97it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 12.06it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 12.12it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 12.17it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 12.14it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 12.09it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.87it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.96it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.13it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.36it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 11.51it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 11.56it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 11.74it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 11.87it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 12.00it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 12.12it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.86it/s]
24 Oct 14:18    INFO  epoch 1 training [time: 6.69s, train loss: 54.7612]
Train     2:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:06, 12.68it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 12.39it/s]:   8%|███▊                                               | 6/79 [00:00<00:06, 10.93it/s]:  10%|█████▏                                             | 8/79 [00:00<00:06, 11.18it/s]:  13%|██████▎                                           | 10/79 [00:00<00:06, 11.46it/s]:  15%|███████▌                                          | 12/79 [00:01<00:05, 11.64it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 11.65it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 11.78it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 11.77it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:04, 11.90it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 11.98it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.80it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.64it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.12it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.43it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:04, 11.51it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 11.64it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 11.75it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 11.85it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 11.86it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 11.88it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:02, 11.94it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 11.89it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 11.93it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 11.98it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 10.85it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 11.23it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:02, 11.50it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 11.72it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.85it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.85it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.90it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.96it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 11.99it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 11.96it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 11.94it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 11.16it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 11.41it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 11.59it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.67it/s]
24 Oct 14:18    INFO  epoch 2 training [time: 6.80s, train loss: 53.6468]
Train     3:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   3%|█▎                                                 | 2/79 [00:00<00:05, 12.91it/s]:   5%|██▌                                                | 4/79 [00:00<00:06, 12.28it/s]:   8%|███▊                                               | 6/79 [00:00<00:05, 12.22it/s]:  10%|█████▏                                             | 8/79 [00:00<00:06, 11.05it/s]:  13%|██████▎                                           | 10/79 [00:00<00:06, 11.41it/s]:  15%|███████▌                                          | 12/79 [00:01<00:05, 11.66it/s]:  18%|████████▊                                         | 14/79 [00:01<00:05, 11.86it/s]:  20%|██████████▏                                       | 16/79 [00:01<00:05, 11.98it/s]:  23%|███████████▍                                      | 18/79 [00:01<00:05, 12.05it/s]:  25%|████████████▋                                     | 20/79 [00:01<00:04, 12.17it/s]:  28%|█████████████▉                                    | 22/79 [00:01<00:04, 12.23it/s]:  30%|███████████████▏                                  | 24/79 [00:02<00:04, 11.50it/s]:  33%|████████████████▍                                 | 26/79 [00:02<00:04, 11.64it/s]:  35%|█████████████████▋                                | 28/79 [00:02<00:04, 11.70it/s]:  38%|██████████████████▉                               | 30/79 [00:02<00:04, 11.77it/s]:  41%|████████████████████▎                             | 32/79 [00:02<00:03, 11.88it/s]:  43%|█████████████████████▌                            | 34/79 [00:02<00:03, 11.80it/s]:  46%|██████████████████████▊                           | 36/79 [00:03<00:03, 11.91it/s]:  48%|████████████████████████                          | 38/79 [00:03<00:03, 12.04it/s]:  51%|█████████████████████████▎                        | 40/79 [00:03<00:03, 12.06it/s]:  53%|██████████████████████████▌                       | 42/79 [00:03<00:03, 12.12it/s]:  56%|███████████████████████████▊                      | 44/79 [00:03<00:03, 11.18it/s]:  58%|█████████████████████████████                     | 46/79 [00:03<00:02, 11.47it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:04<00:02, 11.61it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:04<00:02, 11.79it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:04<00:02, 11.83it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:04<00:02, 11.89it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:04<00:01, 11.94it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:04<00:01, 12.02it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:05<00:01, 11.17it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:05<00:01, 11.47it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:05<00:01, 11.71it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:05<00:01, 11.46it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:05<00:00, 11.63it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:05<00:00, 11.76it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:06<00:00, 11.89it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:06<00:00, 11.63it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:06<00:00, 11.69it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:06<00:00, 11.82it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:06<00:00, 11.77it/s]
24 Oct 14:18    INFO  epoch 3 training [time: 6.79s, train loss: 52.8264]

[5/8] FISM: {'embedding_size': 64, 'learning_rate': 0.001, 'alpha': 0.5, 'reg_weights': [0.0001, 0.0001]}

24 Oct 14:20    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:20    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
split_to = 0
reg_weights = [0.0001, 0.0001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:20    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:20    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:20    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:20    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
24 Oct 14:20    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
24 Oct 14:20    INFO  FISM(
  (item_src_embedding): Embedding(1683, 64, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 64, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 218051
24 Oct 14:20    INFO  FLOPs: 37888.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:   1%|▋                                                  | 1/79 [00:00<00:20,  3.89it/s]:   3%|█▎                                                 | 2/79 [00:00<00:15,  4.96it/s]:   4%|█▉                                                 | 3/79 [00:00<00:14,  5.30it/s]:   5%|██▌                                                | 4/79 [00:00<00:12,  5.82it/s]:   6%|███▏                                               | 5/79 [00:00<00:12,  6.08it/s]:   8%|███▊                                               | 6/79 [00:01<00:11,  6.15it/s]:   9%|████▌                                              | 7/79 [00:01<00:11,  6.27it/s]:  10%|█████▏                                             | 8/79 [00:01<00:11,  6.38it/s]:  11%|█████▊                                             | 9/79 [00:01<00:10,  6.53it/s]:  13%|██████▎                                           | 10/79 [00:01<00:10,  6.61it/s]:  14%|██████▉                                           | 11/79 [00:01<00:10,  6.63it/s]:  15%|███████▌                                          | 12/79 [00:01<00:10,  6.53it/s]:  16%|████████▏                                         | 13/79 [00:02<00:09,  6.64it/s]:  18%|████████▊                                         | 14/79 [00:02<00:09,  6.61it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:09,  6.58it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:09,  6.66it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:09,  6.70it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:09,  6.57it/s]:  24%|████████████                                      | 19/79 [00:03<00:08,  6.70it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:08,  6.73it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:09,  6.03it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:09,  6.26it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:08,  6.33it/s]:  30%|███████████████▏                                  | 24/79 [00:03<00:08,  6.52it/s]:  32%|███████████████▊                                  | 25/79 [00:03<00:08,  6.57it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:08,  6.56it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:07,  6.68it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:07,  6.65it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:07,  6.59it/s]:  38%|██████████████████▉                               | 30/79 [00:04<00:07,  6.71it/s]:  39%|███████████████████▌                              | 31/79 [00:04<00:07,  6.74it/s]:  41%|████████████████████▎                             | 32/79 [00:04<00:06,  6.85it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:07,  6.39it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:07,  6.33it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:07,  6.18it/s]:  46%|██████████████████████▊                           | 36/79 [00:05<00:06,  6.39it/s]:  47%|███████████████████████▍                          | 37/79 [00:05<00:06,  6.51it/s]:  48%|████████████████████████                          | 38/79 [00:05<00:06,  6.47it/s]:  49%|████████████████████████▋                         | 39/79 [00:06<00:06,  6.39it/s]:  51%|█████████████████████████▎                        | 40/79 [00:06<00:06,  6.23it/s]:  52%|█████████████████████████▉                        | 41/79 [00:06<00:06,  6.33it/s]:  53%|██████████████████████████▌                       | 42/79 [00:06<00:05,  6.45it/s]:  54%|███████████████████████████▏                      | 43/79 [00:06<00:05,  6.53it/s]:  56%|███████████████████████████▊                      | 44/79 [00:06<00:05,  6.61it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:05,  6.53it/s]:  58%|█████████████████████████████                     | 46/79 [00:07<00:04,  6.61it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:07<00:04,  6.64it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:07<00:04,  6.53it/s]:  62%|███████████████████████████████                   | 49/79 [00:07<00:04,  6.64it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:07<00:04,  6.74it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:07<00:04,  6.71it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:08<00:04,  6.70it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:08<00:03,  6.70it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:08<00:03,  6.77it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:08<00:03,  6.67it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:08<00:03,  6.67it/s]:  72%|████████████████████████████████████              | 57/79 [00:08<00:03,  6.77it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:08<00:03,  6.59it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:09<00:03,  6.54it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:09<00:03,  6.32it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:09<00:02,  6.52it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:09<00:02,  6.40it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:09<00:02,  6.45it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:09<00:02,  6.49it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:10<00:02,  6.66it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:10<00:01,  6.73it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:10<00:01,  6.82it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:10<00:01,  6.60it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:10<00:01,  6.39it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:10<00:01,  6.15it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:10<00:01,  6.20it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:11<00:01,  6.09it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:11<00:01,  5.67it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:11<00:00,  5.88it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:11<00:00,  6.10it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:11<00:00,  6.33it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:11<00:00,  6.54it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:12<00:00,  6.62it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:12<00:00,  6.82it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:12<00:00,  6.44it/s]
24 Oct 14:21    INFO  epoch 0 training [time: 12.29s, train loss: 54.1027]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:10,  7.27it/s]:   3%|█▎                                                 | 2/79 [00:00<00:10,  7.07it/s]:   4%|█▉                                                 | 3/79 [00:00<00:11,  6.87it/s]:   5%|██▌                                                | 4/79 [00:00<00:10,  6.89it/s]:   6%|███▏                                               | 5/79 [00:00<00:11,  6.55it/s]:   8%|███▊                                               | 6/79 [00:00<00:10,  6.68it/s]:   9%|████▌                                              | 7/79 [00:01<00:10,  6.60it/s]:  10%|█████▏                                             | 8/79 [00:01<00:11,  6.39it/s]:  11%|█████▊                                             | 9/79 [00:01<00:11,  6.25it/s]:  13%|██████▎                                           | 10/79 [00:01<00:10,  6.42it/s]:  14%|██████▉                                           | 11/79 [00:01<00:10,  6.50it/s]:  15%|███████▌                                          | 12/79 [00:01<00:10,  6.60it/s]:  16%|████████▏                                         | 13/79 [00:01<00:10,  6.38it/s]:  18%|████████▊                                         | 14/79 [00:02<00:09,  6.54it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:09,  6.60it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:09,  6.76it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:09,  6.61it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:09,  6.61it/s]:  24%|████████████                                      | 19/79 [00:02<00:09,  6.64it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:08,  6.68it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:08,  6.58it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:08,  6.67it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:08,  6.64it/s]:  30%|███████████████▏                                  | 24/79 [00:03<00:08,  6.53it/s]:  32%|███████████████▊                                  | 25/79 [00:03<00:08,  6.51it/s]:  33%|████████████████▍                                 | 26/79 [00:03<00:08,  6.47it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:07,  6.52it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:07,  6.51it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:07,  6.43it/s]:  38%|██████████████████▉                               | 30/79 [00:04<00:07,  6.34it/s]:  39%|███████████████████▌                              | 31/79 [00:04<00:07,  6.49it/s]:  41%|████████████████████▎                             | 32/79 [00:04<00:07,  6.56it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:07,  6.51it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:06,  6.63it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:06,  6.67it/s]:  46%|██████████████████████▊                           | 36/79 [00:05<00:06,  6.67it/s]:  47%|███████████████████████▍                          | 37/79 [00:05<00:06,  6.56it/s]:  48%|████████████████████████                          | 38/79 [00:05<00:06,  6.63it/s]:  49%|████████████████████████▋                         | 39/79 [00:05<00:06,  6.63it/s]:  51%|█████████████████████████▎                        | 40/79 [00:06<00:07,  5.50it/s]:  52%|█████████████████████████▉                        | 41/79 [00:06<00:09,  4.21it/s]:  53%|██████████████████████████▌                       | 42/79 [00:06<00:08,  4.55it/s]:  54%|███████████████████████████▏                      | 43/79 [00:06<00:07,  4.89it/s]:  56%|███████████████████████████▊                      | 44/79 [00:07<00:06,  5.24it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:06,  5.59it/s]:  58%|█████████████████████████████                     | 46/79 [00:07<00:06,  5.44it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:07<00:05,  5.74it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:07<00:05,  5.70it/s]:  62%|███████████████████████████████                   | 49/79 [00:07<00:04,  6.01it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:08<00:04,  6.20it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:08<00:04,  6.36it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:08<00:04,  6.49it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:08<00:03,  6.60it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:08<00:03,  6.47it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:08<00:03,  6.59it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:08<00:03,  6.70it/s]:  72%|████████████████████████████████████              | 57/79 [00:09<00:03,  6.77it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:09<00:03,  6.83it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:09<00:02,  6.72it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:09<00:02,  6.80it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:09<00:02,  6.84it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:09<00:02,  6.54it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:09<00:02,  6.55it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:10<00:02,  6.60it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:10<00:02,  6.69it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:10<00:01,  6.75it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:10<00:01,  6.77it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:10<00:01,  6.82it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:10<00:01,  6.63it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:10<00:01,  6.74it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:11<00:01,  6.80it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:11<00:01,  6.80it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:11<00:01,  5.10it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:11<00:00,  5.12it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:11<00:00,  5.21it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:12<00:00,  4.94it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:12<00:00,  5.25it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:12<00:00,  5.63it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:12<00:00,  6.03it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:12<00:00,  6.24it/s]
24 Oct 14:21    INFO  epoch 1 training [time: 12.70s, train loss: 49.6136]

[6/8] FISM: {'embedding_size': 64, 'learning_rate': 0.001, 'alpha': 0.5, 'reg_weights': [0.001, 0.001]}

24 Oct 14:25    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:25    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
split_to = 0
reg_weights = [0.001, 0.001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:25    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:25    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:25    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:25    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
24 Oct 14:25    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
24 Oct 14:25    INFO  FISM(
  (item_src_embedding): Embedding(1683, 64, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 64, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 218051
24 Oct 14:25    INFO  FLOPs: 37888.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:   1%|▋                                                  | 1/79 [00:00<00:14,  5.43it/s]:   3%|█▎                                                 | 2/79 [00:00<00:12,  6.31it/s]:   4%|█▉                                                 | 3/79 [00:00<00:11,  6.65it/s]:   5%|██▌                                                | 4/79 [00:00<00:11,  6.71it/s]:   6%|███▏                                               | 5/79 [00:00<00:10,  6.85it/s]:   8%|███▊                                               | 6/79 [00:00<00:10,  6.92it/s]:   9%|████▌                                              | 7/79 [00:01<00:10,  6.98it/s]:  10%|█████▏                                             | 8/79 [00:01<00:10,  6.95it/s]:  11%|█████▊                                             | 9/79 [00:01<00:10,  6.99it/s]:  13%|██████▎                                           | 10/79 [00:01<00:09,  6.99it/s]:  14%|██████▉                                           | 11/79 [00:01<00:09,  7.02it/s]:  15%|███████▌                                          | 12/79 [00:01<00:09,  6.95it/s]:  16%|████████▏                                         | 13/79 [00:01<00:09,  7.00it/s]:  18%|████████▊                                         | 14/79 [00:02<00:09,  6.83it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:09,  6.77it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:09,  6.84it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:08,  6.91it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:08,  6.97it/s]:  24%|████████████                                      | 19/79 [00:02<00:08,  7.00it/s]:  25%|████████████▋                                     | 20/79 [00:02<00:08,  7.01it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:08,  7.00it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:08,  6.99it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:07,  7.01it/s]:  30%|███████████████▏                                  | 24/79 [00:03<00:07,  7.02it/s]:  32%|███████████████▊                                  | 25/79 [00:03<00:07,  7.03it/s]:  33%|████████████████▍                                 | 26/79 [00:03<00:07,  6.99it/s]:  34%|█████████████████                                 | 27/79 [00:03<00:07,  7.00it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:07,  7.04it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:07,  7.05it/s]:  38%|██████████████████▉                               | 30/79 [00:04<00:06,  7.05it/s]:  39%|███████████████████▌                              | 31/79 [00:04<00:06,  7.03it/s]:  41%|████████████████████▎                             | 32/79 [00:04<00:06,  7.02it/s]:  42%|████████████████████▉                             | 33/79 [00:04<00:06,  7.05it/s]:  43%|█████████████████████▌                            | 34/79 [00:04<00:06,  7.05it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:06,  7.05it/s]:  46%|██████████████████████▊                           | 36/79 [00:05<00:06,  7.03it/s]:  47%|███████████████████████▍                          | 37/79 [00:05<00:05,  7.01it/s]:  48%|████████████████████████                          | 38/79 [00:05<00:05,  7.01it/s]:  49%|████████████████████████▋                         | 39/79 [00:05<00:05,  7.03it/s]:  51%|█████████████████████████▎                        | 40/79 [00:05<00:05,  7.07it/s]:  52%|█████████████████████████▉                        | 41/79 [00:05<00:05,  7.06it/s]:  53%|██████████████████████████▌                       | 42/79 [00:06<00:05,  7.08it/s]:  54%|███████████████████████████▏                      | 43/79 [00:06<00:05,  7.07it/s]:  56%|███████████████████████████▊                      | 44/79 [00:06<00:04,  7.08it/s]:  57%|████████████████████████████▍                     | 45/79 [00:06<00:04,  7.07it/s]:  58%|█████████████████████████████                     | 46/79 [00:06<00:04,  7.06it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:06<00:04,  6.98it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:06<00:04,  7.02it/s]:  62%|███████████████████████████████                   | 49/79 [00:07<00:04,  7.02it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:07<00:04,  6.39it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:07<00:04,  6.59it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:07<00:04,  6.70it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:07<00:03,  6.83it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:07<00:03,  6.91it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:07<00:03,  6.96it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:08<00:03,  6.97it/s]:  72%|████████████████████████████████████              | 57/79 [00:08<00:03,  7.03it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:08<00:02,  7.03it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:08<00:02,  7.05it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:08<00:02,  7.07it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:08<00:02,  7.10it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:08<00:02,  7.05it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:09<00:02,  7.08it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:09<00:02,  7.08it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:09<00:01,  7.05it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:09<00:01,  7.07it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:09<00:01,  6.42it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:09<00:01,  6.63it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:09<00:01,  6.78it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:10<00:01,  6.88it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:10<00:01,  6.97it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:10<00:00,  7.02it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:10<00:00,  7.04it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:10<00:00,  7.06it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:10<00:00,  7.07it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:10<00:00,  7.08it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:11<00:00,  7.11it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:11<00:00,  7.12it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:11<00:00,  7.23it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:11<00:00,  6.96it/s]
24 Oct 14:25    INFO  epoch 0 training [time: 11.39s, train loss: 57.0899]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:10,  7.23it/s]:   3%|█▎                                                 | 2/79 [00:00<00:11,  6.55it/s]:   4%|█▉                                                 | 3/79 [00:00<00:11,  6.76it/s]:   5%|██▌                                                | 4/79 [00:00<00:10,  6.90it/s]:   6%|███▏                                               | 5/79 [00:00<00:10,  6.93it/s]:   8%|███▊                                               | 6/79 [00:00<00:10,  6.84it/s]:   9%|████▌                                              | 7/79 [00:01<00:10,  6.91it/s]:  10%|█████▏                                             | 8/79 [00:01<00:10,  6.93it/s]:  11%|█████▊                                             | 9/79 [00:01<00:10,  6.56it/s]:  13%|██████▎                                           | 10/79 [00:01<00:10,  6.39it/s]:  14%|██████▉                                           | 11/79 [00:01<00:11,  5.91it/s]:  15%|███████▌                                          | 12/79 [00:01<00:11,  5.99it/s]:  16%|████████▏                                         | 13/79 [00:01<00:10,  6.29it/s]:  18%|████████▊                                         | 14/79 [00:02<00:10,  6.48it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:09,  6.63it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:09,  6.77it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:09,  6.88it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:08,  6.95it/s]:  24%|████████████                                      | 19/79 [00:02<00:08,  6.99it/s]:  25%|████████████▋                                     | 20/79 [00:02<00:08,  6.99it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:08,  7.02it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:08,  7.03it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:07,  7.00it/s]:  30%|███████████████▏                                  | 24/79 [00:03<00:07,  6.98it/s]:  32%|███████████████▊                                  | 25/79 [00:03<00:07,  6.99it/s]:  33%|████████████████▍                                 | 26/79 [00:03<00:08,  6.40it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:07,  6.60it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:07,  6.70it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:07,  6.76it/s]:  38%|██████████████████▉                               | 30/79 [00:04<00:07,  6.84it/s]:  39%|███████████████████▌                              | 31/79 [00:04<00:06,  6.91it/s]:  41%|████████████████████▎                             | 32/79 [00:04<00:06,  6.99it/s]:  42%|████████████████████▉                             | 33/79 [00:04<00:06,  6.99it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:06,  7.00it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:06,  7.00it/s]:  46%|██████████████████████▊                           | 36/79 [00:05<00:06,  7.01it/s]:  47%|███████████████████████▍                          | 37/79 [00:05<00:05,  7.03it/s]:  48%|████████████████████████                          | 38/79 [00:05<00:05,  7.03it/s]:  49%|████████████████████████▋                         | 39/79 [00:05<00:05,  7.07it/s]:  51%|█████████████████████████▎                        | 40/79 [00:05<00:05,  7.03it/s]:  52%|█████████████████████████▉                        | 41/79 [00:06<00:05,  6.44it/s]:  53%|██████████████████████████▌                       | 42/79 [00:06<00:05,  6.63it/s]:  54%|███████████████████████████▏                      | 43/79 [00:06<00:05,  6.78it/s]:  56%|███████████████████████████▊                      | 44/79 [00:06<00:05,  6.55it/s]:  57%|████████████████████████████▍                     | 45/79 [00:06<00:05,  6.71it/s]:  58%|█████████████████████████████                     | 46/79 [00:06<00:04,  6.78it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:06<00:04,  6.87it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:07<00:04,  6.92it/s]:  62%|███████████████████████████████                   | 49/79 [00:07<00:04,  6.97it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:07<00:04,  7.00it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:07<00:03,  7.01it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:07<00:03,  7.00it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:07<00:03,  7.03it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:07<00:03,  7.04it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:08<00:03,  6.50it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:08<00:03,  6.66it/s]:  72%|████████████████████████████████████              | 57/79 [00:08<00:03,  6.78it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:08<00:03,  6.85it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:08<00:02,  6.87it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:08<00:02,  6.91it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:08<00:02,  6.96it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:09<00:02,  7.01it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:09<00:02,  7.08it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:09<00:02,  7.09it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:09<00:01,  7.04it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:09<00:01,  7.03it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:09<00:01,  7.04it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:09<00:01,  6.50it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:10<00:01,  6.64it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:10<00:01,  6.76it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:10<00:01,  6.81it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:10<00:01,  6.90it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:10<00:00,  6.97it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:10<00:00,  6.96it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:10<00:00,  6.98it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:11<00:00,  7.00it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:11<00:00,  7.03it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:11<00:00,  7.05it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:11<00:00,  7.15it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:11<00:00,  6.83it/s]
24 Oct 14:25    INFO  epoch 1 training [time: 11.67s, train loss: 56.6408]

[7/8] FISM: {'embedding_size': 64, 'learning_rate': 0.005, 'alpha': 0.5, 'reg_weights': [0.0001, 0.0001]}

24 Oct 14:29    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:29    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.005
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
split_to = 0
reg_weights = [0.0001, 0.0001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:29    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:29    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:29    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:29    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
24 Oct 14:29    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
24 Oct 14:29    INFO  FISM(
  (item_src_embedding): Embedding(1683, 64, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 64, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 218051
24 Oct 14:29    INFO  FLOPs: 37888.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:   1%|▋                                                  | 1/79 [00:00<00:14,  5.49it/s]:   3%|█▎                                                 | 2/79 [00:00<00:12,  6.33it/s]:   4%|█▉                                                 | 3/79 [00:00<00:11,  6.63it/s]:   5%|██▌                                                | 4/79 [00:00<00:11,  6.80it/s]:   6%|███▏                                               | 5/79 [00:00<00:10,  6.88it/s]:   8%|███▊                                               | 6/79 [00:00<00:10,  6.91it/s]:   9%|████▌                                              | 7/79 [00:01<00:10,  6.95it/s]:  10%|█████▏                                             | 8/79 [00:01<00:10,  6.96it/s]:  11%|█████▊                                             | 9/79 [00:01<00:09,  7.00it/s]:  13%|██████▎                                           | 10/79 [00:01<00:10,  6.89it/s]:  14%|██████▉                                           | 11/79 [00:01<00:09,  6.95it/s]:  15%|███████▌                                          | 12/79 [00:01<00:09,  6.93it/s]:  16%|████████▏                                         | 13/79 [00:01<00:09,  6.89it/s]:  18%|████████▊                                         | 14/79 [00:02<00:09,  6.93it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:09,  6.97it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:09,  6.99it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:08,  7.03it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:08,  7.05it/s]:  24%|████████████                                      | 19/79 [00:02<00:08,  7.04it/s]:  25%|████████████▋                                     | 20/79 [00:02<00:08,  7.00it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:08,  7.02it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:08,  6.34it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:08,  6.52it/s]:  30%|███████████████▏                                  | 24/79 [00:03<00:08,  6.68it/s]:  32%|███████████████▊                                  | 25/79 [00:03<00:07,  6.82it/s]:  33%|████████████████▍                                 | 26/79 [00:03<00:07,  6.84it/s]:  34%|█████████████████                                 | 27/79 [00:03<00:07,  6.88it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:07,  6.93it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:07,  6.94it/s]:  38%|██████████████████▉                               | 30/79 [00:04<00:07,  6.97it/s]:  39%|███████████████████▌                              | 31/79 [00:04<00:06,  6.98it/s]:  41%|████████████████████▎                             | 32/79 [00:04<00:06,  7.00it/s]:  42%|████████████████████▉                             | 33/79 [00:04<00:06,  6.98it/s]:  43%|█████████████████████▌                            | 34/79 [00:04<00:06,  6.99it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:06,  7.02it/s]:  46%|██████████████████████▊                           | 36/79 [00:05<00:06,  7.04it/s]:  47%|███████████████████████▍                          | 37/79 [00:05<00:05,  7.05it/s]:  48%|████████████████████████                          | 38/79 [00:05<00:05,  7.04it/s]:  49%|████████████████████████▋                         | 39/79 [00:05<00:05,  7.04it/s]:  51%|█████████████████████████▎                        | 40/79 [00:05<00:05,  7.03it/s]:  52%|█████████████████████████▉                        | 41/79 [00:05<00:05,  7.00it/s]:  53%|██████████████████████████▌                       | 42/79 [00:06<00:05,  7.00it/s]:  54%|███████████████████████████▏                      | 43/79 [00:06<00:05,  7.01it/s]:  56%|███████████████████████████▊                      | 44/79 [00:06<00:05,  6.99it/s]:  57%|████████████████████████████▍                     | 45/79 [00:06<00:04,  7.00it/s]:  58%|█████████████████████████████                     | 46/79 [00:06<00:04,  7.01it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:06<00:04,  7.01it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:06<00:04,  7.03it/s]:  62%|███████████████████████████████                   | 49/79 [00:07<00:04,  7.04it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:07<00:04,  7.06it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:07<00:03,  7.05it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:07<00:03,  7.05it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:07<00:03,  7.05it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:07<00:03,  7.07it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:07<00:03,  7.08it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:08<00:03,  7.05it/s]:  72%|████████████████████████████████████              | 57/79 [00:08<00:03,  7.07it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:08<00:02,  7.06it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:08<00:02,  7.08it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:08<00:02,  7.09it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:08<00:02,  7.09it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:08<00:02,  6.34it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:09<00:02,  6.24it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:09<00:02,  6.31it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:09<00:02,  6.35it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:09<00:02,  6.43it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:09<00:01,  6.58it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:09<00:01,  6.73it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:10<00:01,  6.83it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:10<00:01,  6.86it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:10<00:01,  6.94it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:10<00:01,  6.97it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:10<00:00,  6.99it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:10<00:00,  6.41it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:10<00:00,  6.58it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:11<00:00,  6.68it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:11<00:00,  6.80it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:11<00:00,  6.85it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:11<00:00,  6.99it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:11<00:00,  6.87it/s]
24 Oct 14:29    INFO  epoch 0 training [time: 11.53s, train loss: 50.7567]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:10,  7.63it/s]:   3%|█▎                                                 | 2/79 [00:00<00:10,  7.28it/s]:   4%|█▉                                                 | 3/79 [00:00<00:10,  7.18it/s]:   5%|██▌                                                | 4/79 [00:00<00:10,  7.12it/s]:   6%|███▏                                               | 5/79 [00:00<00:10,  7.04it/s]:   8%|███▊                                               | 6/79 [00:00<00:10,  7.03it/s]:   9%|████▌                                              | 7/79 [00:00<00:10,  7.04it/s]:  10%|█████▏                                             | 8/79 [00:01<00:10,  6.90it/s]:  11%|█████▊                                             | 9/79 [00:01<00:10,  6.97it/s]:  13%|██████▎                                           | 10/79 [00:01<00:10,  6.78it/s]:  14%|██████▉                                           | 11/79 [00:01<00:09,  6.85it/s]:  15%|███████▌                                          | 12/79 [00:01<00:09,  6.90it/s]:  16%|████████▏                                         | 13/79 [00:01<00:09,  6.92it/s]:  18%|████████▊                                         | 14/79 [00:02<00:09,  6.94it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:09,  6.97it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:09,  6.98it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:08,  7.00it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:08,  7.03it/s]:  24%|████████████                                      | 19/79 [00:02<00:08,  7.00it/s]:  25%|████████████▋                                     | 20/79 [00:02<00:08,  6.99it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:08,  6.99it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:08,  7.02it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:07,  7.04it/s]:  30%|███████████████▏                                  | 24/79 [00:03<00:07,  7.06it/s]:  32%|███████████████▊                                  | 25/79 [00:03<00:07,  7.07it/s]:  33%|████████████████▍                                 | 26/79 [00:03<00:07,  7.07it/s]:  34%|█████████████████                                 | 27/79 [00:03<00:07,  7.08it/s]:  35%|█████████████████▋                                | 28/79 [00:03<00:07,  7.01it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:07,  7.00it/s]:  38%|██████████████████▉                               | 30/79 [00:04<00:06,  7.02it/s]:  39%|███████████████████▌                              | 31/79 [00:04<00:06,  7.01it/s]:  41%|████████████████████▎                             | 32/79 [00:04<00:06,  7.04it/s]:  42%|████████████████████▉                             | 33/79 [00:04<00:06,  7.02it/s]:  43%|█████████████████████▌                            | 34/79 [00:04<00:07,  6.39it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:06,  6.60it/s]:  46%|██████████████████████▊                           | 36/79 [00:05<00:06,  6.72it/s]:  47%|███████████████████████▍                          | 37/79 [00:05<00:06,  6.79it/s]:  48%|████████████████████████                          | 38/79 [00:05<00:06,  6.79it/s]:  49%|████████████████████████▋                         | 39/79 [00:05<00:05,  6.85it/s]:  51%|█████████████████████████▎                        | 40/79 [00:05<00:05,  6.90it/s]:  52%|█████████████████████████▉                        | 41/79 [00:05<00:05,  6.92it/s]:  53%|██████████████████████████▌                       | 42/79 [00:06<00:05,  6.96it/s]:  54%|███████████████████████████▏                      | 43/79 [00:06<00:05,  7.00it/s]:  56%|███████████████████████████▊                      | 44/79 [00:06<00:04,  7.03it/s]:  57%|████████████████████████████▍                     | 45/79 [00:06<00:04,  7.03it/s]:  58%|█████████████████████████████                     | 46/79 [00:06<00:04,  7.04it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:06<00:04,  7.04it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:06<00:04,  7.06it/s]:  62%|███████████████████████████████                   | 49/79 [00:07<00:04,  7.05it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:07<00:04,  7.07it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:07<00:03,  7.08it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:07<00:03,  7.05it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:07<00:03,  7.01it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:07<00:03,  7.01it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:07<00:03,  7.02it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:08<00:03,  6.93it/s]:  72%|████████████████████████████████████              | 57/79 [00:08<00:03,  6.80it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:08<00:03,  6.87it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:08<00:02,  6.85it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:08<00:02,  6.89it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:08<00:02,  6.97it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:08<00:02,  7.01it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:09<00:02,  7.04it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:09<00:02,  7.04it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:09<00:01,  7.02it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:09<00:01,  7.01it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:09<00:01,  7.01it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:09<00:01,  7.03it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:09<00:01,  7.02it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:10<00:01,  7.05it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:10<00:01,  7.05it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:10<00:00,  7.03it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:10<00:00,  7.04it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:10<00:00,  7.07it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:10<00:00,  7.05it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:10<00:00,  6.46it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:11<00:00,  6.61it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:11<00:00,  6.73it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:11<00:00,  6.95it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:11<00:00,  6.95it/s]
24 Oct 14:29    INFO  epoch 1 training [time: 11.40s, train loss: 49.1130]

[8/8] FISM: {'embedding_size': 64, 'learning_rate': 0.005, 'alpha': 0.5, 'reg_weights': [0.001, 0.001]}

24 Oct 14:33    INFO  ['/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/ipykernel_launcher.py', '--f=/Users/randy/Library/Jupyter/runtime/kernel-v3c9b1d4a1e8ef3e34af002dd35dea90e2dc9ab7db.json']
24 Oct 14:33    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 20
train_batch_size = 2048
learner = adam
learning_rate = 0.005
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
split_to = 0
reg_weights = [0.001, 0.001]
alpha = 0.5
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


24 Oct 14:33    INFO  ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
24 Oct 14:33    INFO  [Training]: train_batch_size = [2048] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
24 Oct 14:33    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
24 Oct 14:33    WARNING  Max value of user's history interaction records has reached 35.115864527629235% of the total.
24 Oct 14:33    WARNING  Pay Attetion!! the `split_to` is set to 0. If you catch a OMM error in this case, you need to increase it
			until the error disappears. For example, you can append it in the command line such as `--split_to=5`
24 Oct 14:33    INFO  FISM(
  (item_src_embedding): Embedding(1683, 64, padding_idx=0)
  (item_dst_embedding): Embedding(1683, 64, padding_idx=0)
  (bceloss): BCEWithLogitsLoss()
)
Trainable parameters: 218051
24 Oct 14:33    INFO  FLOPs: 37888.0
Train     0:   0%|                                                           | 0/79 [00:00<?, ?it/s]/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/.venv/lib/python3.10/site-packages/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0:   1%|▋                                                  | 1/79 [00:00<00:23,  3.31it/s]:   3%|█▎                                                 | 2/79 [00:00<00:18,  4.13it/s]:   4%|█▉                                                 | 3/79 [00:00<00:16,  4.61it/s]:   5%|██▌                                                | 4/79 [00:00<00:15,  4.86it/s]:   6%|███▏                                               | 5/79 [00:01<00:14,  5.20it/s]:   8%|███▊                                               | 6/79 [00:01<00:13,  5.52it/s]:   9%|████▌                                              | 7/79 [00:01<00:12,  5.78it/s]:  10%|█████▏                                             | 8/79 [00:01<00:12,  5.77it/s]:  11%|█████▊                                             | 9/79 [00:01<00:11,  5.90it/s]:  13%|██████▎                                           | 10/79 [00:01<00:11,  6.01it/s]:  14%|██████▉                                           | 11/79 [00:02<00:11,  6.05it/s]:  15%|███████▌                                          | 12/79 [00:02<00:10,  6.16it/s]:  16%|████████▏                                         | 13/79 [00:02<00:10,  6.17it/s]:  18%|████████▊                                         | 14/79 [00:02<00:10,  6.25it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:10,  6.38it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:10,  6.30it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:09,  6.26it/s]:  23%|███████████▍                                      | 18/79 [00:03<00:09,  6.27it/s]:  24%|████████████                                      | 19/79 [00:03<00:09,  6.39it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:09,  6.39it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:09,  6.40it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:08,  6.36it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:09,  5.68it/s]:  30%|███████████████▏                                  | 24/79 [00:04<00:09,  5.78it/s]:  32%|███████████████▊                                  | 25/79 [00:04<00:09,  5.93it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:08,  6.11it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:08,  6.16it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:08,  6.24it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:08,  6.25it/s]:  38%|██████████████████▉                               | 30/79 [00:05<00:07,  6.22it/s]:  39%|███████████████████▌                              | 31/79 [00:05<00:07,  6.27it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:07,  6.39it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:07,  6.29it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:07,  6.27it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:06,  6.33it/s]:  46%|██████████████████████▊                           | 36/79 [00:06<00:06,  6.34it/s]:  47%|███████████████████████▍                          | 37/79 [00:06<00:06,  6.36it/s]:  48%|████████████████████████                          | 38/79 [00:06<00:06,  6.31it/s]:  49%|████████████████████████▋                         | 39/79 [00:06<00:06,  6.30it/s]:  51%|█████████████████████████▎                        | 40/79 [00:06<00:06,  6.38it/s]:  52%|█████████████████████████▉                        | 41/79 [00:06<00:05,  6.43it/s]:  53%|██████████████████████████▌                       | 42/79 [00:06<00:05,  6.35it/s]:  54%|███████████████████████████▏                      | 43/79 [00:07<00:05,  6.30it/s]:  56%|███████████████████████████▊                      | 44/79 [00:07<00:05,  6.40it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:05,  6.34it/s]:  58%|█████████████████████████████                     | 46/79 [00:07<00:05,  6.49it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:07<00:05,  6.39it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:07<00:04,  6.37it/s]:  62%|███████████████████████████████                   | 49/79 [00:08<00:04,  6.28it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:08<00:04,  6.28it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:08<00:04,  6.31it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:08<00:04,  6.25it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:08<00:04,  6.27it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:08<00:03,  6.37it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:09<00:03,  6.35it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:09<00:03,  6.29it/s]:  72%|████████████████████████████████████              | 57/79 [00:09<00:03,  6.43it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:09<00:03,  6.49it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:09<00:03,  6.43it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:09<00:03,  6.24it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:09<00:02,  6.31it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:10<00:02,  6.42it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:10<00:02,  6.40it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:10<00:02,  6.29it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:10<00:02,  6.26it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:10<00:02,  6.29it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:10<00:01,  6.45it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:11<00:01,  6.47it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:11<00:01,  6.50it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:11<00:01,  6.54it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:11<00:01,  5.89it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:11<00:01,  5.94it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:11<00:00,  6.08it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:12<00:00,  6.21it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:12<00:00,  6.25it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:12<00:00,  6.26it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:12<00:00,  6.27it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:12<00:00,  6.36it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:12<00:00,  6.35it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:12<00:00,  6.13it/s]
24 Oct 14:33    INFO  epoch 0 training [time: 12.93s, train loss: 56.3469]
Train     1:   0%|                                                           | 0/79 [00:00<?, ?it/s]:   1%|▋                                                  | 1/79 [00:00<00:11,  7.06it/s]:   3%|█▎                                                 | 2/79 [00:00<00:11,  6.63it/s]:   4%|█▉                                                 | 3/79 [00:00<00:11,  6.50it/s]:   5%|██▌                                                | 4/79 [00:00<00:11,  6.39it/s]:   6%|███▏                                               | 5/79 [00:00<00:13,  5.61it/s]:   8%|███▊                                               | 6/79 [00:00<00:12,  5.86it/s]:   9%|████▌                                              | 7/79 [00:01<00:12,  5.90it/s]:  10%|█████▏                                             | 8/79 [00:01<00:11,  6.05it/s]:  11%|█████▊                                             | 9/79 [00:01<00:11,  6.15it/s]:  13%|██████▎                                           | 10/79 [00:01<00:11,  6.12it/s]:  14%|██████▉                                           | 11/79 [00:01<00:10,  6.30it/s]:  15%|███████▌                                          | 12/79 [00:01<00:10,  6.34it/s]:  16%|████████▏                                         | 13/79 [00:02<00:10,  6.41it/s]:  18%|████████▊                                         | 14/79 [00:02<00:11,  5.87it/s]:  19%|█████████▍                                        | 15/79 [00:02<00:10,  6.06it/s]:  20%|██████████▏                                       | 16/79 [00:02<00:10,  6.14it/s]:  22%|██████████▊                                       | 17/79 [00:02<00:09,  6.23it/s]:  23%|███████████▍                                      | 18/79 [00:02<00:09,  6.27it/s]:  24%|████████████                                      | 19/79 [00:03<00:09,  6.34it/s]:  25%|████████████▋                                     | 20/79 [00:03<00:09,  6.36it/s]:  27%|█████████████▎                                    | 21/79 [00:03<00:09,  6.37it/s]:  28%|█████████████▉                                    | 22/79 [00:03<00:08,  6.39it/s]:  29%|██████████████▌                                   | 23/79 [00:03<00:08,  6.47it/s]:  30%|███████████████▏                                  | 24/79 [00:03<00:08,  6.55it/s]:  32%|███████████████▊                                  | 25/79 [00:04<00:09,  5.77it/s]:  33%|████████████████▍                                 | 26/79 [00:04<00:09,  5.87it/s]:  34%|█████████████████                                 | 27/79 [00:04<00:08,  6.08it/s]:  35%|█████████████████▋                                | 28/79 [00:04<00:08,  6.19it/s]:  37%|██████████████████▎                               | 29/79 [00:04<00:08,  6.24it/s]:  38%|██████████████████▉                               | 30/79 [00:04<00:07,  6.33it/s]:  39%|███████████████████▌                              | 31/79 [00:05<00:07,  6.27it/s]:  41%|████████████████████▎                             | 32/79 [00:05<00:07,  6.32it/s]:  42%|████████████████████▉                             | 33/79 [00:05<00:07,  6.40it/s]:  43%|█████████████████████▌                            | 34/79 [00:05<00:06,  6.45it/s]:  44%|██████████████████████▏                           | 35/79 [00:05<00:06,  6.48it/s]:  46%|██████████████████████▊                           | 36/79 [00:05<00:07,  5.78it/s]:  47%|███████████████████████▍                          | 37/79 [00:05<00:07,  5.94it/s]:  48%|████████████████████████                          | 38/79 [00:06<00:06,  6.06it/s]:  49%|████████████████████████▋                         | 39/79 [00:06<00:06,  6.18it/s]:  51%|█████████████████████████▎                        | 40/79 [00:06<00:06,  6.26it/s]:  52%|█████████████████████████▉                        | 41/79 [00:06<00:05,  6.34it/s]:  53%|██████████████████████████▌                       | 42/79 [00:06<00:05,  6.43it/s]:  54%|███████████████████████████▏                      | 43/79 [00:06<00:05,  6.50it/s]:  56%|███████████████████████████▊                      | 44/79 [00:07<00:05,  6.48it/s]:  57%|████████████████████████████▍                     | 45/79 [00:07<00:05,  6.44it/s]:  58%|█████████████████████████████                     | 46/79 [00:07<00:05,  5.85it/s]:  59%|█████████████████████████████▋                    | 47/79 [00:07<00:05,  5.93it/s]:  61%|██████████████████████████████▍                   | 48/79 [00:07<00:05,  6.05it/s]:  62%|███████████████████████████████                   | 49/79 [00:07<00:04,  6.16it/s]:  63%|███████████████████████████████▋                  | 50/79 [00:08<00:04,  5.91it/s]:  65%|████████████████████████████████▎                 | 51/79 [00:08<00:04,  5.61it/s]:  66%|████████████████████████████████▉                 | 52/79 [00:08<00:04,  5.75it/s]:  67%|█████████████████████████████████▌                | 53/79 [00:08<00:04,  5.96it/s]:  68%|██████████████████████████████████▏               | 54/79 [00:08<00:04,  5.91it/s]:  70%|██████████████████████████████████▊               | 55/79 [00:08<00:03,  6.01it/s]:  71%|███████████████████████████████████▍              | 56/79 [00:09<00:04,  5.54it/s]:  72%|████████████████████████████████████              | 57/79 [00:09<00:03,  5.83it/s]:  73%|████████████████████████████████████▋             | 58/79 [00:09<00:03,  6.00it/s]:  75%|█████████████████████████████████████▎            | 59/79 [00:09<00:03,  6.10it/s]:  76%|█████████████████████████████████████▉            | 60/79 [00:09<00:03,  6.10it/s]:  77%|██████████████████████████████████████▌           | 61/79 [00:09<00:02,  6.18it/s]:  78%|███████████████████████████████████████▏          | 62/79 [00:10<00:02,  6.24it/s]:  80%|███████████████████████████████████████▊          | 63/79 [00:10<00:02,  6.33it/s]:  81%|████████████████████████████████████████▌         | 64/79 [00:10<00:02,  6.33it/s]:  82%|█████████████████████████████████████████▏        | 65/79 [00:10<00:02,  6.36it/s]:  84%|█████████████████████████████████████████▊        | 66/79 [00:10<00:02,  5.76it/s]:  85%|██████████████████████████████████████████▍       | 67/79 [00:10<00:02,  5.89it/s]:  86%|███████████████████████████████████████████       | 68/79 [00:11<00:01,  5.92it/s]:  87%|███████████████████████████████████████████▋      | 69/79 [00:11<00:01,  6.07it/s]:  89%|████████████████████████████████████████████▎     | 70/79 [00:11<00:01,  6.19it/s]:  90%|████████████████████████████████████████████▉     | 71/79 [00:11<00:01,  6.30it/s]:  91%|█████████████████████████████████████████████▌    | 72/79 [00:11<00:01,  6.30it/s]:  92%|██████████████████████████████████████████████▏   | 73/79 [00:11<00:00,  6.38it/s]:  94%|██████████████████████████████████████████████▊   | 74/79 [00:12<00:00,  6.42it/s]:  95%|███████████████████████████████████████████████▍  | 75/79 [00:12<00:00,  6.42it/s]:  96%|████████████████████████████████████████████████  | 76/79 [00:12<00:00,  6.35it/s]:  97%|████████████████████████████████████████████████▋ | 77/79 [00:12<00:00,  5.78it/s]:  99%|█████████████████████████████████████████████████▎| 78/79 [00:12<00:00,  6.04it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:12<00:00,  6.28it/s]: 100%|██████████████████████████████████████████████████| 79/79 [00:12<00:00,  6.14it/s]
24 Oct 14:34    INFO  epoch 1 training [time: 12.91s, train loss: 54.7640]

Saved to:
/Users/randy/Desktop/Recommender Systems/New Final Project/RecBole_DSAIT4335_Group_18/group_18/results/task_1_2/FISM_tuning.csv

Best configuration:

,embedding_size,learning_rate,alpha,reg_weights,valid_score,recall@10,mrr@10,ndcg@10,hit@10,precision@10
0,64,0.005,0.5,"[0.0001, 0.0001]",0.3429,0.1821,0.3429,0.1976,0.7169,0.1417